# 02. Tratamento e Consolidação de Dados ETL (SmartQuestion)

Este notebook é responsável pelo processamento de dados dos relatórios do SmartQuestion e alimentação das tabelas do banco de dados.

In [1]:
# 1. Setup do Ambiente e Importações Centralizadas
from __future__ import annotations

import os
import sys
import glob
import time
import json
import yaml
import hashlib
import warnings
import calendar
import traceback
from datetime import datetime, date, timezone, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
from dotenv import load_dotenv
from supabase import create_client
from IPython.display import HTML, Markdown, display

try:
    from unidecode import unidecode
except ImportError:
    unidecode = lambda x: x

# Filtrar avisos de depreciação do Pandas (FutureWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

# Localizar a raiz do projeto dinamicamente
caminho_atual = Path.cwd().resolve()
for candidato in [caminho_atual, *caminho_atual.parents]:
    if (candidato / "SCRIPTS").is_dir() and (candidato / "DB").is_dir():
        raiz_projeto = candidato
        break
else:
    raise FileNotFoundError("Não foi possível localizar a raiz do projeto.")

for p in [raiz_projeto, raiz_projeto / "SCRIPTS", raiz_projeto / "SCRIPTS" / "FUNCTIONS"]:
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from FUNCTIONS.function import (
    aplicar_estilo_listrado_xlsx,
    aplicar_formatacao_excel,
    buscar_arquivo_mais_recente,
    carregar_config_referencia,
    carregar_env,
    consultar_tabela_supabase,
    converter_data_excel,
    converter_numero_br,
    detectar_raiz_projeto,
    dividir_seguro,
    exportar_varias_abas_xlsx,
    exportar_xlsx_formatado,
    extrair_data_nome_arquivo,
    garantir_colunas,
    ler_aba_excel_flex,
    normalizar_texto,
    obter_cliente_supabase,
    renomear_colunas_existentes,
)

# Carregar configurações do projeto (config.yaml)
config_ref = carregar_config_referencia(raiz_projeto)

caminho_config_yaml = raiz_projeto / "SCRIPTS" / "CONFIG" / "config.yaml"
if caminho_config_yaml.exists():
    with open(caminho_config_yaml, "r", encoding="utf-8") as f:
        config_yaml = yaml.safe_load(f)
else:
    raise FileNotFoundError(f"Arquivo de configuração não encontrado em: {caminho_config_yaml}")

# Leitura estrita de diretórios, tabelas e datas de referência (Lança KeyError se faltar chave)
DIR_BD_SQ = Path(config_yaml["caminhos"]["bd_smartquestion"])

TAB_VINCULOS_STAGING = config_yaml["supabase"]["tabelas"]["vinculos_staging"]
TAB_VISITAS_STAGING = config_yaml["supabase"]["tabelas"]["visitas_staging"]
TAB_VISITAS_FATO = config_yaml["supabase"]["tabelas"]["visitas_fato"]
TAB_INATIVACAO_PRODUTORES = config_yaml["supabase"]["tabelas"]["inativacao_produtores_staging"]
TAB_INATIVACAO_CONSULTORES = config_yaml["supabase"]["tabelas"]["inativacao_consultores_staging"]
TAB_CONSISTENCIA_FATO = config_yaml["supabase"]["tabelas"]["consistencia_fato"]
TAB_MOVIMENTACAO_FATO = config_yaml["supabase"]["tabelas"]["movimentacao_fato"]

# Datas de corte centralizadas
DATA_INICIAL_ANALISE = config_yaml["referencia"]["data_inicial_analise"]
DATA_INICIAL_ELABORE = config_yaml["referencia"]["data_inicial_elabore"]
DATA_INICIAL_FATO_VISITAS = config_yaml["referencia"]["data_inicial_fato_visitas"]
PERIODO_CHECAGEM_INICIO = config_yaml["referencia"]["periodo_checagem_inicio"]

DIRETORIO_ENV = str(raiz_projeto / "SCRIPTS")
NOTEBOOK_DIR = str(raiz_projeto / "SCRIPTS")

# Carregar variáveis de ambiente (.env)
caminho_env = raiz_projeto / "SCRIPTS" / "CONFIG" / ".env"
if caminho_env.exists():
    load_dotenv(caminho_env)
else:
    load_dotenv()

# Inicializar cliente Supabase globalmente
supabase_url = os.getenv("SUPABASE_URL")
supabase_key = os.getenv("SUPABASE_SERVICE_KEY")
if supabase_url and supabase_key:
    supabase = create_client(supabase_url, supabase_key)
else:
    supabase = None

print(f"Raiz do projeto: {raiz_projeto}")
print(f"Configuração carregada: {config_ref}")
print(f"Diretório BD_SMARTQUESTION: {DIR_BD_SQ}")
print(f"Datas de Corte: Análise={DATA_INICIAL_ANALISE} | Elabore={DATA_INICIAL_ELABORE} | Fato Visitas={DATA_INICIAL_FATO_VISITAS}")

Raiz do projeto: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\PY_SCRIPT
Configuração carregada: ConfigReferencia(mes_referencia=2026_08, extenso='agosto de 2026')
Diretório BD_SMARTQUESTION: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION
Datas de Corte: Análise=2025-01-01 | Elabore=2025-12-01 | Fato Visitas=2026-01-01

# 2. Inativação de Produtores

In [2]:
def etl_inativacao(diretorio=None, DIRETORIO_ENV=None):
    """
    Função completa para ETL diário de dados de inativação:
    1. Importa o arquivo Excel mais recente com _LISTA_INATIVACAO.xlsx
    2. Filtra registros novos
    3. Insere no Supabase

    Args:
        diretorio: Diretório onde procurar o arquivo Excel (opcional)

    Returns:
        bool: True se o processo foi concluído com sucesso, False caso contrário
    """

    try:
        print("=== ETL DIÁRIO DE INATIVAÇÃO ===")
        inicio_total = datetime.now()

        # ETAPA 1: IMPORTAR ARQUIVO EXCEL
        print("\n🔍 ETAPA 1: IMPORTANDO ARQUIVO EXCEL")

        # Salvar diretório atual

        # Mudar para o diretório especificado se fornecido

        # Buscar qualquer arquivo com o padrão _LISTA_INATIVACAO.xlsx
        diretorio_alvo = Path(diretorio) if diretorio else DIR_BD_SQ
        print(f"Diretório dos arquivos: {diretorio_alvo}")
        padrao = str(diretorio_alvo / "*_LISTA_INATIVACAO.xlsx")
        arquivos = glob.glob(padrao)

        if not arquivos:
            print(f"❌ Nenhum arquivo encontrado com o padrão {padrao}")
            # Voltar ao diretório original
            return False

        # Ordenar arquivos por data de modificação (mais recente primeiro)
        arquivos_ordenados = sorted(arquivos, key=os.path.getmtime, reverse=True)
        arquivo_mais_recente = arquivos_ordenados[0]

        print(f"✅ Arquivo mais recente encontrado: {arquivo_mais_recente}")

        try:
            # Definir colunas para importação
            colunas_inativacao = [
                'Número do atendimento:', 'Consultor(a):', 'Projeto',
                'Código do(a) produtor(a):', 'Produtor(a):', 'Propriedade:',
                'Grupo Ponto Atendimento', 'Data da solicitação:',
                'Data da inativação:', 'Motivo da inativação:',
                'Se outro, qual motivo?', 'Produtor(a) ativo(a)?'
            ]

            # Importar o arquivo Excel
            df_inativacao = pd.read_excel(arquivo_mais_recente, header=1, usecols=colunas_inativacao)

            # Mapear nomes de colunas
            inativacao_mapping = {
                'Número do atendimento:': 'id_atendimento',
                'Consultor(a):': 'nome_consultor',
                'Projeto': 'projeto',
                'Código do(a) produtor(a):': 'codigo_lr',
                'Produtor(a):': 'nome_produtor',
                'Propriedade:': 'nome_propriedade',
                'Grupo Ponto Atendimento': 'grupo_ponto_atendimento',
                'Data da solicitação:': 'data_solicitacao',
                'Data da inativação:': 'data_inativacao',
                'Motivo da inativação:': 'motivo_inativacao',
                'Se outro, qual motivo?': 'outro_motivo',
                'Produtor(a) ativo(a)?': 'produtor_ativo'
            }

            # Renomear colunas
            df_inativacao.rename(columns=inativacao_mapping, inplace=True)

            print(f"✅ Arquivo importado com sucesso: {arquivo_mais_recente} ({len(df_inativacao)} registros)")

        except Exception as e:
            print(f"❌ Erro ao importar {arquivo_mais_recente}: {str(e)}")
            # Voltar ao diretório original
            return False

        # Voltar ao diretório original

        if len(df_inativacao) == 0:
            print("❌ Nenhum dado encontrado no arquivo.")
            return False

        # ETAPA 2: BUSCAR REGISTROS NOVOS
        print("\n🔍 ETAPA 2: FILTRANDO REGISTROS NOVOS")
        
        # Carregar credenciais do Supabase
        key = os.getenv('SUPABASE_SERVICE_KEY')
        url = os.getenv('SUPABASE_URL')
        
        if not key or not url:
            print("❌ Credenciais não encontradas!")
            return False
        
        # Inicializar cliente Supabase
        supabase = create_client(url, key)
        
        # Buscar todos os id_atendimento já existentes no Supabase
        print("🔍 Buscando registros existentes no Supabase...")
        
        try:
            resultado = supabase.table(TAB_INATIVACAO_PRODUTORES) \
                .select("id_atendimento") \
                .execute()
        
            if resultado.data:
                ids_existentes = set(r['id_atendimento'] for r in resultado.data)
                print(f"✅ {len(ids_existentes)} registros já existem no Supabase")
            else:
                ids_existentes = set()
                print("⚠️ Nenhum registro encontrado no Supabase. Todos serão inseridos.")
        
        except Exception as e:
            print(f"⚠️ Erro ao buscar registros existentes: {str(e)}")
            ids_existentes = set()
        
        # Converter data_solicitacao para datetime
        df_inativacao['data_solicitacao'] = pd.to_datetime(df_inativacao['data_solicitacao'], errors='coerce')
        
        # Filtrar apenas registros cujo id_atendimento NÃO existe no Supabase
        df_novos = df_inativacao[~df_inativacao['id_atendimento'].isin(ids_existentes)].copy()
        
        if len(df_novos) == 0:
            print("✅ Nenhum registro novo encontrado.")
            return True
        
        print(f"✅ Encontrados {len(df_novos)} registros novos para inserir.")
        # ETAPA 3: PROCESSAR E INSERIR NO SUPABASE
        print("\n🔄 ETAPA 3: PROCESSANDO E INSERINDO DADOS")

        # Ajustar tipos de dados
        print("🔄 Ajustando tipos de dados...")

        # Converter colunas de data para datetime
        if 'data_inativacao' in df_novos.columns:
            df_novos['data_inativacao'] = pd.to_datetime(df_novos['data_inativacao'], errors='coerce')

        # Adicionar data_processamento atual
        df_novos['data_processamento'] = datetime.now()

        # Converter produtor_ativo para boolean se existir
        if 'produtor_ativo' in df_novos.columns:
            # Mapear valores para boolean
            df_novos['produtor_ativo'] = df_novos['produtor_ativo'].map({
                'Sim': True, 'sim': True, 'S': True, 's': True, True: True, 1: True, '1': True,
                'Não': False, 'não': False, 'N': False, 'n': False, False: False, 0: False, '0': False,
                None: None, np.nan: None
            })

        # Mostrar amostra dos dados
        print("\n📊 Amostra dos novos registros:")
        print(df_novos[['id_atendimento', 'nome_consultor', 'codigo_lr', 'data_solicitacao']].head())

        # Preparar para inserção
        df_prep = df_novos.copy()

        # Converter datas para formato ISO
        for col in ['data_solicitacao', 'data_inativacao', 'data_processamento']:
            if col in df_prep.columns and pd.api.types.is_datetime64_any_dtype(df_prep[col]):
                df_prep[col] = df_prep[col].dt.strftime('%Y-%m-%dT%H:%M:%S')

        # Converter NaN para None
        df_prep = df_prep.replace({np.nan: None})
        
        # Remover colunas que não existem no Supabase
        colunas_apenas_local = ['id_composto']
        df_prep = df_prep.drop(columns=[c for c in colunas_apenas_local if c in df_prep.columns])

        # Converter para lista de dicionários
        registros = df_prep.to_dict(orient='records')

        # Inserir no Supabase
        print("\n🔄 Inserindo registros no Supabase...")

        # Definir tamanho do lote
        lote = 100
        total = len(registros)
        total_lotes = (total + lote - 1) // lote

        # Contadores
        sucesso = 0
        erro = 0

        inicio = datetime.now()

        # Processar em lotes
        for i in range(0, total, lote):
            lote_atual = registros[i:i+lote]
            num_lote = i // lote + 1

            try:
                print(f"Processando lote {num_lote}/{total_lotes} ({len(lote_atual)} registros)...")

                # Realizar upsert
                resultado = supabase.table(TAB_INATIVACAO_PRODUTORES).upsert(lote_atual,on_conflict="id_atendimento").execute()
                
                # Verificar resultado
                if hasattr(resultado, 'error') and resultado.error:
                    print(f"❌ Erro no lote {num_lote}: {resultado.error}")
                    erro += len(lote_atual)
                else:
                    sucesso += len(lote_atual)
                    print(f"✅ Lote {num_lote} processado com sucesso.")

                # Pausa para não sobrecarregar a API
                if num_lote < total_lotes:
                    time.sleep(0.5)

            except Exception as e:
                print(f"❌ Erro no lote {num_lote}: {str(e)}")
                erro += len(lote_atual)

        # Mostrar resumo
        fim = datetime.now()
        duracao = (fim - inicio).total_seconds()
        duracao_total = (fim - inicio_total).total_seconds()

        print("\n=== RESUMO DO ETL ===")
        print(f"📄 Arquivo processado: {arquivo_mais_recente}")
        print(f"📊 Total de registros no arquivo: {len(df_inativacao)}")
        print(f"🔍 Registros novos identificados: {len(df_novos)}")
        print(f"✅ Registros inseridos com sucesso: {sucesso}")
        print(f"❌ Registros com erro: {erro}")
        print(f"⏱️ Tempo de inserção: {duracao:.2f} segundos")
        print(f"⏱️ Tempo total do ETL: {duracao_total:.2f} segundos")
        print(f"📅 Data/hora de conclusão: {fim.strftime('%Y-%m-%d %H:%M:%S')}")

        return True

    except Exception as e:
        print(f"❌ Erro durante a execução: {str(e)}")
        traceback.print_exc()
        return False

## Execução: Inativação de Produtores

In [3]:
# Executar ETL de Inativação de Produtores
resultado_inativacao = etl_inativacao(DIR_BD_SQ)

if resultado_inativacao:
    print('✅ ETL de inativação de produtores concluído com sucesso!')
else:
    print('❌ ETL de inativação de produtores falhou ou não identificou novos registros.')

=== ETL DIÁRIO DE INATIVAÇÃO ===

🔍 ETAPA 1: IMPORTANDO ARQUIVO EXCEL
Diretório dos arquivos: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION
✅ Arquivo mais recente encontrado: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION\260814_LISTA_INATIVACAO.xlsx
✅ Arquivo importado com sucesso: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION\260814_LISTA_INATIVACAO.xlsx (11 registros)

🔍 ETAPA 2: FILTRANDO REGISTROS NOVOS

🔍 Buscando registros existentes no Supabase...

✅ 883 registros já existem no Supabase
✅ Nenhum registro novo encontrado.
✅ ETL de inativação de produtores concluído com sucesso!

# 3. Inativação de Consultores

In [4]:
def etl_inativacao_consultor(diretorio=None, DIRETORIO_ENV=None):
    """
    ETL para identificar e registrar inativações de consultores no SmartQuestion.
    1. Lê o arquivo BD_STATUS_USUARIO_SQ.xlsx
    2. Identifica transições Sim → Não por consultor
    3. Faz upsert na tab_inativacao_consultor_sq_backup
    """
    try:
        print("=== ETL INATIVAÇÃO DE CONSULTOR ===")
        inicio_total = datetime.now()

        # ETAPA 1: IMPORTAR ARQUIVO
        print("\n🔍 ETAPA 1: IMPORTANDO ARQUIVO")

        diretorio_alvo = Path(diretorio) if diretorio else DIR_BD_SQ
        print(f"Diretório dos arquivos: {diretorio_alvo}")
        padrao = str(diretorio_alvo / "*BD_STATUS_USUARIO_SQ.xlsx")
        arquivos = glob.glob(padrao)

        if not arquivos:
            print(f"❌ Nenhum arquivo encontrado com o padrão {padrao}")
            return False

        arquivo = sorted(arquivos, key=os.path.getmtime, reverse=True)[0]
        print(f"✅ Arquivo encontrado: {arquivo}")

        df = pd.read_excel(arquivo)
        df["historyCreationDate"] = pd.to_datetime(df["historyCreationDate"])


        # ETAPA 2: IDENTIFICAR INATIVAÇÕES (Sim → Não)
        print("\n🔍 ETAPA 2: IDENTIFICANDO INATIVAÇÕES")

        df = df.sort_values(by=["Nome", "historyCreationDate"]).reset_index(drop=True)
        df["Ativo_anterior"] = df.groupby("Nome")["Ativo"].shift(1)

        df_inativacoes = df[
            (df["historyType"] == "UPDATED") &
            (df["Ativo"] == "Não") &
            (df["Ativo_anterior"] == "Sim")
        ][["historyCreationDate", "Nome"]].copy()

        df_inativacoes.rename(columns={
            "historyCreationDate": "data_inativacao",
            "Nome": "nome_consultor"
        }, inplace=True)

        print(f"✅ {len(df_inativacoes)} inativações identificadas")

        if len(df_inativacoes) == 0:
            print("⚠️ Nenhuma inativação encontrada no arquivo.")
            return True

        # ETAPA 3: GERAR HASH E PREPARAR DADOS
        print("\n🔄 ETAPA 3: PREPARANDO DADOS")

        def gerar_hash(nome, data):
            chave = f"{nome}_{data.date()}"
            return hashlib.md5(chave.encode()).hexdigest()

        df_inativacoes["id_inativacao_consultor"] = df_inativacoes.apply(
            lambda row: gerar_hash(row["nome_consultor"], row["data_inativacao"]),
            axis=1
        )

        df_inativacoes["data_inativacao"]   = df_inativacoes["data_inativacao"].dt.strftime('%Y-%m-%d')
        df_inativacoes["data_modificacao"]  = datetime.now(timezone.utc).isoformat()

        print(df_inativacoes[["nome_consultor", "data_inativacao", "id_inativacao_consultor"]].head())

        # ETAPA 4: UPSERT NO SUPABASE
        print("\n🔄 ETAPA 4: INSERINDO NO SUPABASE")

        url = os.getenv('SUPABASE_URL')
        key = os.getenv('SUPABASE_SERVICE_KEY')

        if not url or not key:
            print("❌ Credenciais não encontradas!")
            return False

        supabase = create_client(url, key)

        registros = df_inativacoes[[
            "id_inativacao_consultor",
            "nome_consultor",
            "data_inativacao",
            "data_modificacao"
        ]].to_dict(orient="records")

        lote       = 100
        total      = len(registros)
        total_lotes = (total + lote - 1) // lote
        sucesso = erro = 0

        for i in range(0, total, lote):
            lote_atual = registros[i:i+lote]
            num_lote   = i // lote + 1
            try:
                resultado = supabase.table(TAB_INATIVACAO_CONSULTORES).upsert(
                    lote_atual,
                    on_conflict="id_inativacao_consultor"
                ).execute()
                sucesso += len(lote_atual)
                print(f"✅ Lote {num_lote}/{total_lotes} inserido.")
            except Exception as e:
                print(f"❌ Erro no lote {num_lote}: {str(e)}")
                erro += len(lote_atual)

            if num_lote < total_lotes:
                time.sleep(0.5)

        # RESUMO
        fim = datetime.now()
        print("\n=== RESUMO ===")
        print(f"📄 Arquivo: {arquivo}")
        print(f"✅ Inseridos com sucesso: {sucesso}")
        print(f"❌ Com erro: {erro}")
        print(f"⏱️ Tempo total: {(fim - inicio_total).total_seconds():.2f}s")

        return True

    except Exception as e:
        print(f"❌ Erro: {str(e)}")
        traceback.print_exc()
        return False

## Execução: Inativação de Consultores

In [5]:
# Executar ETL de Inativação de Consultores
resultado_inativacao_consultor = etl_inativacao_consultor(DIR_BD_SQ)

if resultado_inativacao_consultor:
    print('✅ ETL de inativação de consultores concluído com sucesso!')
else:
    print('❌ ETL de inativação de consultores falhou!')

=== ETL INATIVAÇÃO DE CONSULTOR ===

🔍 ETAPA 1: IMPORTANDO ARQUIVO
Diretório dos arquivos: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION
✅ Arquivo encontrado: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION\BD_STATUS_USUARIO_SQ.xlsx

🔍 ETAPA 2: IDENTIFICANDO INATIVAÇÕES
✅ 31 inativações identificadas

🔄 ETAPA 3: PREPARANDO DADOS
                     nome_consultor data_inativacao  \
15                  AMANDA PINHEIRO      2026-03-10
40        ANGELO OLIVEIRA GONCALVES      2026-03-27
69  CARLOS EDUARDO AVILEZ BAHAMONDE      2026-03-10
86      DANIEL DOS SANTOS FERNANDES      2026-02-03
90         DANIELE DOS SANTOS SILVA      2026-03-10

             id_inativacao_consultor
15  4e65b179901747ad5d9376dc2b96b7bc
40  739cb0bf608dd32e2ab3769fdc73419c
69  e07bac2e12ba78e53fa0debcc063e74e
86  6d158906c0f844c989f13485d518d2a2
90  78a01a3963a973c0540515faf0760ade

🔄 ETAPA 4: INSERINDO NO SUPABASE

✅ Lote 1/1 inserido.

=== RESUMO ===
📄 Arquivo: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION\BD_STATUS_USUARIO_SQ.xlsx
✅ Inseridos com sucesso: 31
❌ Com erro: 0
⏱️ Tempo total: 0.61s
✅ ETL de inativação de consultores concluído com sucesso!

# 4. Vínculos de Atendimento

In [6]:
# Função melhorada para criar ID composto
def criar_id_composto(row):
    """
    Cria um ID composto usando MD5 hash de campos-chave com tratamento consistente
    """
    # Função auxiliar para tratar valores antes de concatenar
    def tratar_valor(valor):
        if pd.isna(valor) or valor is None:
            return ''
        # Converter para string, remover espaços extras e converter para minúsculas
        return str(valor).lower().strip()

    # Concatenar campos principais com tratamento consistente
    campos = [
        tratar_valor(row['codigo_lr']),
        # Tratar datas de forma especial para garantir formato consistente
        tratar_valor(pd.to_datetime(row['data_associacao']).strftime('%Y-%m-%d') if pd.notna(row['data_associacao']) else ''),
        tratar_valor(row['grupo_atendimento']),
        tratar_valor(row['projeto'])
    ]

    # Juntar campos e criar hash MD5
    texto_composto = '|'.join(campos)
    return hashlib.md5(texto_composto.encode('utf-8')).hexdigest()

# ✅ FUNÇÃO REUTILIZÁVEL DE TRIM
def aplicar_trim_colunas_texto(df, nome_df="DataFrame"):
    """
    Detecta automaticamente todas as colunas texto (object)
    e aplica TRIM, removendo espaços no início e fim.
    Retorna o DataFrame corrigido e um relatório das colunas tratadas.
    """
    # Identificar colunas texto automaticamente
    colunas_texto = df.select_dtypes(include=['object']).columns.tolist()

    print(f"🔄 Aplicando TRIM em {len(colunas_texto)} colunas texto de [{nome_df}]...")

    registros_corrigidos = 0

    for col in colunas_texto:
        # Contar quantos registros têm espaço antes/depois
        tem_espaco = df[col].apply(
            lambda x: isinstance(x, str) and x != x.strip()
        ).sum()

        if tem_espaco > 0:
            df[col] = df[col].apply(
                lambda x: x.strip() if isinstance(x, str) else x
            )
            print(f"  ✅ {col}: {tem_espaco} registro(s) corrigido(s)")
            registros_corrigidos += tem_espaco

    if registros_corrigidos == 0:
        print("  ✅ Nenhum espaço encontrado. Dados já estão limpos.")
    else:
        print(f"  📊 Total de correções: {registros_corrigidos}")

    return df
    
def etl_vinculos(diretorio=None, arquivo="BD_BI_VINCULOS_COMPLETO.xlsx", apenas_testar=False):
    """
    Função ETL para atualizar a tabela de vínculos no Supabase
    """
    try:
        print("=== ETL DE VÍNCULOS ===")
        inicio_total = datetime.now()

        # ETAPA 1: IMPORTAR ARQUIVOS EXCEL
        print("\n🔍 ETAPA 1: IMPORTANDO ARQUIVOS EXCEL")

        # Obter o diretório atual onde o notebook está sendo executado
        NOTEBOOK_DIR = DIR_BD_SQ

        # Definir o diretório
        diretorio_alvo = Path(diretorio) if diretorio else DIR_BD_SQ
        # os.chdir gerido no setup
        print(f"Diretório dos arquivos: {diretorio_alvo}")

        vinculo_arquivo_atual = diretorio_alvo / arquivo

        try:
            # Importar os arquivos Excel
            print("Importando arquivo de vínculos atuais...")
            df_vinculos = pd.read_excel(vinculo_arquivo_atual, engine='openpyxl')
            print(f"✅ Arquivo atual importado: {len(df_vinculos)} registros")


            # Mapear nomes de colunas
            vinculos_mapping = {
                'Código LR': 'codigo_lr',
                'Código agroindústria': 'codigo_agroindustria',
                'Código da fazenda': 'codigo_fazenda',
                'Produtor(a)': 'nome_produtor',  # Coluna D: Produtor(a)
                'Nome da propriedade': 'nome_propriedade',
                'Unidade de atendimento': 'unidade_atendimento',
                'Tipo de ponto atendimento': 'tipo_ponto_atendimento',
                'Cidade': 'cidade_produtor',
                'Estado': 'estado_produtor',
                'Ativo': 'vinculo_ativo',
                'Data de associação': 'data_associacao',
                'Grupo de atendimento': 'grupo_atendimento',  # Coluna L: Grupo de atendimento
                'Consultor(a) no grupo de atendimento': 'consultor_grupo_atendimento_raw',
                'PROJETO': 'projeto'  # Coluna N: PROJETO
            }

            # Renomear colunas
            df_vinculos.rename(columns=vinculos_mapping, inplace=True)
            
            # Função para extrair projeto da coluna consultor_grupo_atendimento usando lógica de fórmula Excel
            # CONSULTOR: Coluna L 'Grupo de atendimento'
            df_vinculos['consultor_grupo_atendimento'] = df_vinculos['grupo_atendimento']

            # PROJETO: Coluna N 'PROJETO', exceto valor igual a 'A'
            if 'projeto' in df_vinculos.columns:
                df_vinculos['projeto'] = df_vinculos['projeto'].astype(str).str.strip().str.upper()
                df_vinculos['projeto'] = df_vinculos['projeto'].replace({'A': None, 'NAN': None, 'NONE': None, '': None, '<NA>': None})

            # CONSULTOR: exceto MATEUS CARNIELLI (ALVOAR ECO)
            mask_teste_mateus = (
                df_vinculos['grupo_atendimento'].astype(str).str.upper().str.contains('MATEUS CARNIELLI', na=False) &
                df_vinculos['projeto'].astype(str).str.upper().str.contains('ALVOAR ECO', na=False)
            )
            df_vinculos = df_vinculos[~mask_teste_mateus].copy()

            # Verificar se todas as colunas necessárias existem
            colunas_necessarias = ['codigo_lr', 'nome_produtor', 'nome_propriedade', 
                                 'consultor_grupo_atendimento', 'data_associacao', 
                                 'grupo_atendimento', 'projeto']

            colunas_faltantes = [col for col in colunas_necessarias if col not in df_vinculos.columns]
            if colunas_faltantes:
                print(f"⚠️ Colunas faltantes: {', '.join(colunas_faltantes)}")
                # Criar colunas faltantes com valores nulos
                for col in colunas_faltantes:
                    df_vinculos[col] = None

            print(f"✅ Arquivo importado com sucesso: {len(df_vinculos)} registros")

        except Exception as e:
            print(f"❌ Erro ao importar arquivos: {str(e)}")
            # os.chdir gerido no setup
            return False

        # Voltar ao diretório de ambiente
        # os.chdir gerido no setup

        if len(df_vinculos) == 0:
            print("❌ Nenhum dado encontrado nos arquivos.")
            return False

        # ETAPA 2: VERIFICAÇÃO E TRATAMENTO DE DUPLICATAS
        print("\n🔍 ETAPA 2: VERIFICAÇÃO E TRATAMENTO DE DUPLICATAS")

        # Verificar valores nulos em colunas críticas
        colunas_criticas = ['codigo_lr', 'nome_produtor', 'nome_propriedade', 'consultor_grupo_atendimento', 'projeto']
        print("Verificando valores nulos em colunas críticas:")
        for col in colunas_criticas:
            nulos = df_vinculos[col].isna().sum()
            vazios = (df_vinculos[col] == '').sum() if df_vinculos[col].dtype == 'object' else 0
            print(f"  - Coluna {col}: {nulos} valores nulos, {vazios} strings vazias")


        # Se o id_composto deve ser sensível APENAS à data, use .dt.normalize()
        df_vinculos['data_associacao'] = pd.to_datetime(df_vinculos['data_associacao'], errors='coerce')
        # Preencher NaT com um valor padrão ou None para o hash
        df_vinculos['data_associacao'] = df_vinculos['data_associacao'].fillna(pd.NaT) # Usar NaT para representar nulo de data
        
        # Verificar duplicatas no DataFrame concatenado
        print("\nVerificando duplicatas no DataFrame...")
        duplicatas = df_vinculos[df_vinculos.duplicated(subset=['codigo_lr', 'consultor_grupo_atendimento', 'data_associacao'], keep=False)] # Pode ser que houve 2 vínculos para o produtor-consultor em datas diferentes.
        print(f"Encontradas {len(duplicatas)} linhas duplicadas (considerando código LR e consultor)")

        if not duplicatas.empty:
            # Mostrar algumas duplicatas para análise
            print("\nExemplo de duplicatas:")
            for codigo_lr in duplicatas['codigo_lr'].unique()[:3]:  # Mostrar até 3 exemplos
                registros_duplicados = df_vinculos[df_vinculos['codigo_lr'] == codigo_lr]
                print(f"\nCódigo LR: {codigo_lr}")
                print(registros_duplicados[['codigo_lr', 'nome_produtor', 'consultor_grupo_atendimento', 'projeto']].head())

            # Resolver duplicatas priorizando valores não nulos
            print("\n🔄 Resolvendo duplicatas...")

            # Função para mesclar valores, priorizando não nulos
            def mesclar_valores(serie):
                # Remover valores nulos
                valores_validos = [v for v in serie if pd.notna(v) and v != '']
                # Se todos são nulos, retornar None
                if not valores_validos:
                    return None
                # Caso contrário, retornar o primeiro valor não nulo
                return valores_validos[0]

            # Agrupar por código LR e consultor, mesclando valores
            colunas_agrupar = ['codigo_lr', 'consultor_grupo_atendimento', 'data_associacao']
            colunas_mesclar = df_vinculos.columns.difference(colunas_agrupar)

            df_vinculos = df_vinculos.groupby(colunas_agrupar)[colunas_mesclar].agg(mesclar_valores).reset_index()

            print(f"DataFrame após resolução de duplicatas: {len(df_vinculos)} registros")

            # Verificar se as duplicatas foram resolvidas
            duplicatas_restantes = df_vinculos[df_vinculos.duplicated(subset=['codigo_lr', 'consultor_grupo_atendimento', 'data_associacao'], keep=False)]
            print(f"Duplicatas restantes: {len(duplicatas_restantes)}")

        # ETAPA 3: TRATAMENTO DA COLUNA PROJETO
        print("\n🔍 ETAPA 3: TRATAMENTO DA COLUNA PROJETO")

        # Verificar valores nulos na coluna projeto ANTES do tratamento
        nulos_projeto_antes = df_vinculos['projeto'].isna().sum()
        vazios_projeto_antes = (df_vinculos['projeto'] == '').sum()
        print(f"Valores nulos na coluna projeto ANTES do tratamento: {nulos_projeto_antes}")
        print(f"Strings vazias na coluna projeto ANTES do tratamento: {vazios_projeto_antes}")

        # Verificar um caso específico para confirmar o tratamento
        codigo_lr_problema = 'LR03243'
        registro_problema = df_vinculos[df_vinculos['codigo_lr'] == codigo_lr_problema]
        if not registro_problema.empty:
            print(f"\nVerificação do registro problemático {codigo_lr_problema}:")
            print(registro_problema[['codigo_lr', 'nome_produtor', 'consultor_grupo_atendimento', 'projeto']].head())

        # ETAPA 4: PREPARAÇÃO DOS DADOS E CRIAÇÃO DO ID COMPOSTO
        print("\n🔄 ETAPA 4: PREPARAÇÃO DOS DADOS E CRIAÇÃO DO ID COMPOSTO")

        # Ajustar tipos de dados
        print("🔄 Ajustando tipos de dados...")

        # Converter data_associacao para datetime
        if 'data_associacao' in df_vinculos.columns:
            df_vinculos['data_associacao'] = pd.to_datetime(df_vinculos['data_associacao'], errors='coerce')

        # Converter vinculo_ativo para boolean
        if 'vinculo_ativo' in df_vinculos.columns:
            # Mapear valores para boolean
            df_vinculos['vinculo_ativo'] = df_vinculos['vinculo_ativo'].map({
                'Sim': True, 'sim': True, 'S': True, 's': True, 'Ativo': True, 'ativo': True, 
                'True': True, 'true': True, 'Verdadeiro': True, 'verdadeiro': True, 
                'V': True, 'v': True, '1': True, 1: True, True: True,

                'Não': False, 'não': False, 'N': False, 'n': False, 'Inativo': False, 'inativo': False, 
                'False': False, 'false': False, 'Falso': False, 'falso': False, 
                'F': False, 'f': False, '0': False, 0: False, False: False,

                None: None, np.nan: None
            })

        # ✅ TRIM AUTOMÁTICO: substitui todo o bloco manual anterior
        df_vinculos = aplicar_trim_colunas_texto(df_vinculos, nome_df="df_vinculos")
            
        # Criar coluna de ID composto
        print("🔄 Criando ID composto para cada registro...")
        df_vinculos['id_composto'] = df_vinculos.apply(criar_id_composto, axis=1)

        # Verificar se há duplicatas no ID composto
        duplicatas_id = df_vinculos[df_vinculos.duplicated(subset=['id_composto'], keep=False)]
        if not duplicatas_id.empty:
            print(f"⚠️ Encontradas {len(duplicatas_id)} duplicatas de ID composto!")
            # Manter apenas a primeira ocorrência de cada ID composto
            df_vinculos = df_vinculos.drop_duplicates(subset=['id_composto'], keep='first')
            print(f"✅ Duplicatas removidas. DataFrame final: {len(df_vinculos)} registros")

        # Adicionar data_processamento atual
        df_vinculos['data_processamento'] = datetime.now()

        # ETAPA 5: BUSCAR REGISTROS EXISTENTES NO SUPABASE
        print("\n🔍 ETAPA 5: BUSCANDO REGISTROS EXISTENTES NO SUPABASE")

        # Carregar credenciais do Supabase
        key = os.getenv('SUPABASE_SERVICE_KEY')
        url = os.getenv('SUPABASE_URL')

        if not key or not url:
            print("❌ Credenciais não encontradas!")
            return False

        # Inicializar cliente Supabase
        supabase = create_client(url, key)

        # Verificar se a coluna id_composto existe na tabela
        print("🔍 Verificando se a coluna id_composto existe...")

        try:
            # Tentar buscar um registro com a coluna id_composto
            supabase.table(TAB_VINCULOS_STAGING).select("id_composto").limit(1).execute()
            coluna_existe = True
            print("✅ Coluna id_composto encontrada na tabela.")
        except Exception as e:
            coluna_existe = False
            print("⚠️ Coluna id_composto não existe na tabela. Será criada durante o processo.")

        # Buscar dados existentes para comparação
        print("🔍 Buscando registros existentes...")

        try:
            # Buscar os campos necessários para criar o ID composto
            # Na etapa 5, modificar a consulta para selecionar todas as colunas
            resultado = (
                supabase
                .table(TAB_VINCULOS_STAGING) 
                .select("*")   # Selecionar todas as colunas
                .execute()
            )

            if resultado.data:
                # Criar DataFrame com os registros existentes
                df_existentes = pd.DataFrame(resultado.data)

                # Criar ID composto para os registros existentes usando a mesma função
                df_existentes['id_composto'] = df_existentes.apply(criar_id_composto, axis=1)

                # Obter conjunto de IDs existentes
                ids_existentes = set(df_existentes['id_composto'])

                print(f"✅ Encontrados {len(ids_existentes)} registros existentes no Supabase")

                # Verificar um caso específico para debug
                codigo_lr_problema = 'LR03243'
                registro_excel = df_vinculos[df_vinculos['codigo_lr'] == codigo_lr_problema]
                registro_supabase = df_existentes[df_existentes['codigo_lr'] == codigo_lr_problema]

                if not registro_excel.empty and not registro_supabase.empty:
                    print(f"\n🔍 VERIFICANDO REGISTRO ESPECÍFICO: {codigo_lr_problema}")
                    print("No Excel:")
                    print(registro_excel[['codigo_lr', 'nome_produtor', 'consultor_grupo_atendimento', 'projeto', 'id_composto', 'data_associacao']].iloc[0])
                    print("\nNo Supabase:")
                    print(registro_supabase[['codigo_lr', 'nome_produtor', 'consultor_grupo_atendimento', 'projeto', 'id_composto', 'data_associacao']].iloc[0])

                    # Verificar se os IDs compostos são iguais
                    id_excel = registro_excel['id_composto'].iloc[0]
                    id_supabase = registro_supabase['id_composto'].iloc[0]
                    if id_excel == id_supabase:
                        print(f"\n✅ IDs compostos correspondem: {id_excel}")
                    else:
                        print(f"\n❌ IDs compostos diferem:")
                        print(f"  Excel: {id_excel}")
                        print(f"  Supabase: {id_supabase}")

                        # Comparar os campos usados para gerar o ID
                        for campo in ['codigo_lr', 'nome_produtor', 'nome_propriedade', 'consultor_grupo_atendimento', 'grupo_atendimento', 'projeto']:
                            if campo in registro_excel and campo in registro_supabase:
                                valor_excel = registro_excel[campo].iloc[0]
                                valor_supabase = registro_supabase[campo].iloc[0]
                                if str(valor_excel).lower().strip() != str(valor_supabase).lower().strip():
                                    print(f"Diferença no campo '{campo}':")
                                    print(f"  Excel: '{valor_excel}' (tipo: {type(valor_excel)})")
                                    print(f"  Supabase: '{valor_supabase}' (tipo: {type(valor_supabase)})")
            else:
                ids_existentes = set()
                print("⚠️ Nenhum registro encontrado no Supabase.")
        except Exception as e:
            print(f"⚠️ Erro ao buscar registros existentes: {str(e)}")
            # Em caso de erro, assumir que não há registros
            ids_existentes = set()

        # ETAPA 6: IDENTIFICAR REGISTROS NOVOS OU ALTERADOS (CORRIGIDO PARA DATAS)
        print("\n🔍 ETAPA 6: IDENTIFICANDO REGISTROS NOVOS OU ALTERADOS")
        
        # Identificar registros novos ou alterados
        ids_atuais = set(df_vinculos['id_composto'])
        
        # Registros novos (não existem no Supabase)
        ids_novos = ids_atuais - ids_existentes
        df_novos = df_vinculos[df_vinculos['id_composto'].isin(ids_novos)]
        
        # Para os registros que existem em ambos, verificar se há diferenças
        ids_comuns = ids_atuais.intersection(ids_existentes)
        df_atualizar = pd.DataFrame()  # Iniciar com DataFrame vazio
        
        if ids_comuns and 'df_existentes' in locals() and not df_existentes.empty:
            print(f"Verificando diferenças em {len(ids_comuns)} registros comuns...")
        
            # Definir explicitamente as colunas a comparar (apenas colunas que existem em ambos os lugares)
            colunas_supabase = set(df_existentes.columns)
            colunas_excel = set(df_vinculos.columns)
            colunas_comuns = list(colunas_supabase.intersection(colunas_excel))
            colunas_comuns = [col for col in colunas_comuns if col not in ['id_composto', 'data_processamento']]
        
            print(f"Comparando apenas as {len(colunas_comuns)} colunas comuns: {', '.join(colunas_comuns)}")
        
            # Função melhorada para normalizar valores, com foco especial em datas
            def normalizar_valor(valor):
                """
                Normaliza valores para comparação consistente, com tratamento especial para datas
                """
                if pd.isna(valor) or valor is None:
                    return ''
                elif isinstance(valor, bool):
                    return 'true' if valor else 'false'
                elif isinstance(valor, (int, float)):
                    return str(float(valor))
                elif isinstance(valor, pd.Timestamp) or isinstance(valor, datetime):
                    # Para objetos de data/hora, retornar apenas a parte da data
                    return valor.strftime('%Y-%m-%d')
                elif isinstance(valor, str):
                    # Tratar strings que podem representar datas
                    valor_lower = valor.lower().strip()
        
                    # Verificar se a string parece uma data com hora (contém T ou t)
                    if 't' in valor_lower and len(valor_lower) > 10:
                        try:
                            # Extrair apenas a parte da data antes do T
                            data_parte = valor_lower.split('t')[0]
                            return data_parte
                        except:
                            return valor_lower
                    return valor_lower
                else:
                    return str(valor).lower().strip()
        
            # Converter df_existentes para dicionário para facilitar a busca
            dict_existentes = {}
            for _, row in df_existentes.iterrows():
                id_composto = row['id_composto']
                dict_existentes[id_composto] = row.to_dict()
        
            # Verificar diferenças para cada registro comum
            registros_diferentes = []
        
            for _, row in df_vinculos[df_vinculos['id_composto'].isin(ids_comuns)].iterrows():
                id_composto = row['id_composto']
        
                if id_composto in dict_existentes:
                    registro_existente = dict_existentes[id_composto]
        
                    # Verificar se há diferenças nas colunas de comparação
                    tem_diferenca = False
                    diferencas = []
        
                    for col in colunas_comuns:
                        # Tratamento especial para a coluna data_associacao
                        if col == 'data_associacao':
                            # Extrair apenas a data (YYYY-MM-DD) de ambos os valores
                            try:
                                # Para o valor atual
                                if pd.notna(row[col]):
                                    if isinstance(row[col], (pd.Timestamp, datetime)):
                                        valor_atual = row[col].strftime('%Y-%m-%d')
                                    else:
                                        valor_str = str(row[col]).lower()
                                        if 't' in valor_str:
                                            valor_atual = valor_str.split('t')[0]
                                        else:
                                            valor_atual = valor_str
                                else:
                                    valor_atual = ''
        
                                # Para o valor existente
                                if pd.notna(registro_existente[col]):
                                    if isinstance(registro_existente[col], (pd.Timestamp, datetime)):
                                        valor_existente = registro_existente[col].strftime('%Y-%m-%d')
                                    else:
                                        valor_str = str(registro_existente[col]).lower()
                                        if 't' in valor_str:
                                            valor_existente = valor_str.split('t')[0]
                                        else:
                                            valor_existente = valor_str
                                else:
                                    valor_existente = ''
                            except:
                                # Em caso de erro, usar a normalização padrão
                                valor_atual = normalizar_valor(row[col])
                                valor_existente = normalizar_valor(registro_existente[col])
                        else:
                            # Para outras colunas, usar a normalização padrão
                            valor_atual = normalizar_valor(row[col])
                            valor_existente = normalizar_valor(registro_existente[col])
        
                        # Comparar os valores normalizados
                        if valor_atual != valor_existente:
                            tem_diferenca = True
                            diferencas.append(f"{col}: '{valor_existente}' -> '{valor_atual}'")
        
                    if tem_diferenca:
                        # Adicionar informações de debug
                        print(f"Diferenças encontradas para ID {id_composto}:")
                        for diff in diferencas:
                            print(f"  - {diff}")
                        registros_diferentes.append(row)
        
            # Criar DataFrame com registros que realmente precisam ser atualizados
            if registros_diferentes:
                df_atualizar = pd.DataFrame(registros_diferentes)
                print(f"Encontrados {len(df_atualizar)} registros com diferenças reais que precisam ser atualizados.")
            else:
                print("✅ Nenhuma diferença encontrada nos registros comuns!")
        
        print(f"✅ Registros novos: {len(df_novos)}")
        print(f"✅ Registros a atualizar: {len(df_atualizar)}")
        print(f"✅ Total a processar: {len(df_novos) + len(df_atualizar)}")



        if apenas_testar:
            print("🧪 MODO TESTE (DRY-RUN) ATIVADO:")
            print("--------------------------------------------------")
            print(f"📊 Total de registros no Excel: {len(df_vinculos)}")
            print(f"🆕 Registros NOVOS identificados: {len(df_novos)}")
            print(f"🔄 Registros a ATUALIZAR identificados: {len(df_atualizar)}")
            if len(df_novos) > 0:
                print("🔍 Amostra dos 5 primeiros registros NOVOS:")
                cols_preview = [c for c in ['codigo_lr', 'nome_produtor', 'consultor_grupo_atendimento', 'projeto'] if c in df_novos.columns]
                print(df_novos[cols_preview].head())
            print("✅ Nenhuma alteração foi gravada no Supabase (Dry-run concluído com sucesso).")
            return True

        # ETAPA 7: INSERIR E ATUALIZAR NO SUPABASE
        print("\n🔄 ETAPA 7: PROCESSANDO REGISTROS NO SUPABASE")
        
        if len(df_novos) + len(df_atualizar) == 0:
            print("✅ Não há registros para processar.")
            return True
        
        # ── Função auxiliar de preparo
        def preparar_payload(df):
            df_prep = df.copy()
            for col in ['data_associacao', 'data_processamento']:
                if col in df_prep.columns and pd.api.types.is_datetime64_any_dtype(df_prep[col]):
                    df_prep[col] = df_prep[col].dt.strftime('%Y-%m-%dT%H:%M:%S')
            df_prep = df_prep.replace({np.nan: None})
            return df_prep.to_dict(orient='records')
        
        LOTE = 100
        sucesso = 0
        erro = 0
        inicio = datetime.now()
        
        # ── BLOCO 1: INSERT — apenas registros NOVOS
        if not df_novos.empty:
            print(f"\n📥 Inserindo {len(df_novos)} registros NOVOS...")
            registros_novos = preparar_payload(df_novos)
        
            for i in range(0, len(registros_novos), LOTE):
                lote_atual = registros_novos[i:i+LOTE]
                num_lote = i // LOTE + 1
                total_lotes = (len(registros_novos) + LOTE - 1) // LOTE
                try:
                    supabase.table(TAB_VINCULOS_STAGING).insert(lote_atual).execute()
                    # ↑ INSERT puro: só para registros que não existem
                    sucesso += len(lote_atual)
                    print(f"  ✅ Lote {num_lote}/{total_lotes} inserido.")
                except Exception as e:
                    erro += len(lote_atual)
                    print(f"  ❌ Erro no lote {num_lote}: {e}")
                time.sleep(0.3)
        
        # ── BLOCO 2: UPDATE — apenas registros EXISTENTES com diferença
        if not df_atualizar.empty:
            print(f"\n🔄 Atualizando {len(df_atualizar)} registros EXISTENTES...")
            registros_atualizar = preparar_payload(df_atualizar)
        
            for registro in registros_atualizar:
                id_composto = registro.get('id_composto')
                try:
                    (
                        supabase
                        .table(TAB_VINCULOS_STAGING)
                        .update(registro)
                        .eq("id_composto", id_composto)
                        # ↑ UPDATE filtrado pelo id_composto: nunca gera conflito de constraint
                        .execute()
                    )
                    sucesso += 1
                except Exception as e:
                    erro += 1
                    print(f"  ❌ Erro ao atualizar {id_composto}: {e}")

        # ETAPA 8: RESUMO E FINALIZAÇÃO
        fim = datetime.now()
        duracao = (fim - inicio).total_seconds()
        duracao_total = (fim - inicio_total).total_seconds()

        print("\n=== RESUMO DO ETL DE VÍNCULOS ===")
        print(f"📄 Arquivos processados: {vinculo_arquivo_atual}")
        print(f"📊 Total de registros: {len(df_vinculos)}")
        print(f"🆕 Registros novos: {len(df_novos)}")
        print(f"🔄 Registros atualizados: {len(df_atualizar)}")
        print(f"✅ Registros processados com sucesso: {sucesso}")
        print(f"❌ Registros com erro: {erro}")
        print(f"⏱️ Tempo de inserção: {duracao:.2f} segundos")
        print(f"⏱️ Tempo total do ETL: {duracao_total:.2f} segundos")
        print(f"📅 Data/hora de conclusão: {fim.strftime('%Y-%m-%d %H:%M:%S')}")

        return True

    except Exception as e:
        print(f"❌ Erro durante a execução: {str(e)}")
        traceback.print_exc()
        return False

## Execução: Vínculos de Atendimento (Modo Teste)

In [7]:
# Executar ETL de Vínculos em Modo Teste (apenas_testar=True)
resultado_vinculos = etl_vinculos(DIR_BD_SQ, apenas_testar=False)

if resultado_vinculos:
    print('✅ Teste de ETL de vínculos concluído com sucesso!')
else:
    print('❌ Teste de ETL de vínculos falhou!')

=== ETL DE VÍNCULOS ===

🔍 ETAPA 1: IMPORTANDO ARQUIVOS EXCEL
Diretório dos arquivos: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION
Importando arquivo de vínculos atuais...

✅ Arquivo atual importado: 6198 registros
✅ Arquivo importado com sucesso: 6142 registros

🔍 ETAPA 2: VERIFICAÇÃO E TRATAMENTO DE DUPLICATAS
Verificando valores nulos em colunas críticas:
  - Coluna codigo_lr: 0 valores nulos, 0 strings vazias
  - Coluna nome_produtor: 0 valores nulos, 0 strings vazias
  - Coluna nome_propriedade: 1022 valores nulos, 0 strings vazias
  - Coluna consultor_grupo_atendimento: 0 valores nulos, 0 strings vazias
  - Coluna projeto: 103 valores nulos, 0 strings vazias

Verificando duplicatas no DataFrame...
Encontradas 0 linhas duplicadas (considerando código LR e consultor)

🔍 ETAPA 3: TRATAMENTO DA COLUNA PROJETO
Valores nulos na coluna projeto ANTES do tratamento: 103
Strings vazias na coluna projeto ANTES do tratamento: 0

Verificação do registro problemático LR03243:
     codigo_lr            nome_produtor  \
3177   LR03243  ANTONIO DOMINGOS MORAIS
4368   LR03243  ANTONIO DOMINGOS MORAIS

                    consultor_grupo_atendimento          projeto
3177  JOAO PEDRO SILLOS DAMITTO TINOCO (SEMEAR)           SEMEAR
4368         MATEUS CARNIELLI (CFT DANONE 2026)  CFT DANONE 2026

🔄 ETAPA 4: PREPARAÇÃO DOS DADOS E CRIAÇÃO DO ID COMPOSTO
🔄 Ajustando tipos de dados...
🔄 Aplicando TRIM em 14 colunas texto de [df_vinculos]...
  ✅ codigo_agroindustria: 16 registro(s) corrigido(s)
  ✅ nome_produtor: 10 registro(s) corrigido(s)
  ✅ nome_propriedade: 50 registro(s) corrigido(s)
  📊 Total de correções: 76
🔄 Criando ID composto para cada registro...

🔍 ETAPA 5: BUSCANDO REGISTROS EXISTENTES NO SUPABASE

🔍 Verificando se a coluna id_composto existe...

✅ Coluna id_composto encontrada na tabela.
🔍 Buscando registros existentes...

✅ Encontrados 8681 registros existentes no Supabase

🔍 VERIFICANDO REGISTRO ESPECÍFICO: LR03243
No Excel:
codigo_lr                                                        LR03243
nome_produtor                                    ANTONIO DOMINGOS MORAIS
consultor_grupo_atendimento    JOAO PEDRO SILLOS DAMITTO TINOCO (SEMEAR)
projeto                                                           SEMEAR
id_composto                             eac2c54d49916a031a1227c95e6f487e
data_associacao                                      2024-06-28 00:00:00
Name: 3177, dtype: object

No Supabase:
codigo_lr                                                                LR03243
nome_produtor                                            ANTONIO DOMINGOS MORAIS
consultor_grupo_atendimento    FRANCISCO NETO / JOAO PEDRO SILLOS DAMITTO TINOCO
projeto                                                                   SEMEAR
id_composto                                     eac2c54d49916a031a1227c95e6f487e
data_associacao                                              2024-06-28T00:00:00
Name: 2191, dtype: object

✅ IDs compostos correspondem: eac2c54d49916a031a1227c95e6f487e

🔍 ETAPA 6: IDENTIFICANDO REGISTROS NOVOS OU ALTERADOS
Verificando diferenças em 6141 registros comuns...
Comparando apenas as 14 colunas comuns: vinculo_ativo, grupo_atendimento, cidade_produtor, nome_propriedade, unidade_atendimento, projeto, consultor_grupo_atendimento, nome_produtor, codigo_agroindustria, codigo_lr, codigo_fazenda, tipo_ponto_atendimento, estado_produtor, data_associacao

Diferenças encontradas para ID 2de9fa4b8b30d710e97ea5607a660fc1:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID af781b7931278205c2523d272feb75f8:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 60d5d489be6716325eb8f3d933bea2c4:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID c53a515650306daab22a0167eb562887:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID b5541af3d387442b8bd386e53b321fb2:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 7f0d3ad970938cf1018d7e82f1ab0e70:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 4fb5bc3fdc777a9a1271d6d2687c5de8:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 5a90e723745d1fac1089969a5bcd66ea:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID c2d15c54be5f7bfb5b1ea055947b7520:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID c20369716594bef0a86456a1761ade3a:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID a7abe0b12bb11f56ac1f48b999e38460:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 871e4831108770c77332ea298b438145:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 8807fc3ea4f8ca85f728fa6b1c9f8e0c:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 0aa6092f558f7ecd73047cb36a03450b:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID a4ff40817c0db5f99b34ebb987c97f5f:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 6b0ad027aa937ca33015561f3f9029ef:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 6a66bfb0d705512639f22d670c5b0059:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID fbb9483dbd012cf76d74b95a9a578f09:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 2c3ec6bb80eaa50fbabba2ea36761b5a:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 8bbf369ee90b4b830ec497597ddb570b:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 2ac500a56ea6f8ae39fe8dbae6a85040:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 7b0cdd05442aa726de8107901afa89ea:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 77bcbeccf5fba8051dce8f81fafc0186:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 49d8a732e010d9a4664bca64ceab2bcf:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID ab67ab400dec1584a6c7ddf8614e0827:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 7d5a8c0220de45d53e29bb9ab6cc1a6f:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID ebf0038ed2bd07e86a36ac3acbfe35a6:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 10eb1d8d5d09d1b4321a6aa3d8af7fdb:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 83deaeeb641313c825e1e14c8a127eb9:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 37d31505f8bbf098b204cbadd1ff9a93:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID acccd7f369e955058ceffb1e2d19181d:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 481ffa988ee973ff7e048ee63cb5842b:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 110ec14b22630673a3b6507c6ef09936:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 1dea0e12b9679f668ae89b76634655e4:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID bdf16758f85df7974dc00c25bdff52d0:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 32b97f45895f999c24628f3b6688d754:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 886c7d807dfa58904d2cec82cb270d1d:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID f59074eec84ea7e4e7fd7f5ec55a6979:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 52a83c104eea30e7c27ac58e48ab031a:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID ff32bc0e8e2018ddde47b5fcef46a50b:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 844c5e8718fb42853b34a36f63888a34:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 31f8c78134c7521fd6cdc92988c0fa71:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID bf0998a85d5d2262258414ffbca78ded:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID bdca1c6ba34912e6c40568dd10698f52:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID d2899205d5afbf2023a8ec8b977f24ce:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID dc0912315c268c002a9d3a7e5a706b23:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 2f0bdc1d18d42fee2a2ae0ef38d78960:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID be3921bdca56198912d004c4fc91ca10:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 3e343182b662057bbdb01d8570810daa:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID b86b740f3117cb80e66166796aaf7222:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 2a7bc6525eb1c1d96ae37ed206825e06:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 6f71dcb71369790c93a5153d95badcb6:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 780c7347b97f7d2ce9afd035135179a4:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID d355163323818f4fd83468657a92ad50:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 47ef3f0898fbca4819120908d8d92817:
  - consultor_grupo_atendimento: 'adenis alves ferreira / alan henrique ferreira chaves / iago parmanhani pin' -> 'adenis alves ferreira (cafe & ges'
Diferenças encontradas para ID 038e673de8184f492d9cc54b3018b4d3:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID b0ea8d1fbc4aba3b038e3e01a87f6e47:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 3f60477c57e8066618d547887877dd16:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID f45cedb5121b78e46f87b3c08950895f:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 0be5d6985a377d4f14affee0e914ee33:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 415828fe75fe5645e0b3053b6d16a717:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 5056702551f36296120325584ea86e28:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID c668687d1403da4a871c33ce53ebd5b9:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID d105e17ebf4a17c621bebdc1e440146e:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID a55a76bcc29c3ea1e92c5cfcee51bb15:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 71ff7ccd52ef98983d039da2459dc1a1:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 35e013fbf84d08f8cce4d4c7f3ec5921:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID c7915d5c917ab3478c47670ab5d4647b:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 155d925cf4e30d3c659e57cc359d7909:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 5be61ba622e9d6bbbea766513583ff60:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID df118a3e19cf63c83211b399e9d34279:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 72ea47ba39eff0308567985f64cfa7a5:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 69c79630641450206bbfe5cdef8019ce:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 406e0e5c545278db5096846e7ce3e8fa:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 31244a0b99189129be8a77daf283e188:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 54d62742e0ac8c7071a3b413eff40a5a:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 743fae1d5e790c9940048bb9969bc608:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID a660f95ba2db11c3405e9d8e2bb6dce4:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 2858ac98f9109f3dfe68babade967d08:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 7d56d7f62903e42f114441603d6372ff:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 63be2c904caa79118fd5572ba66be4ad:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID d976f7b4f56d79eb17a6d137e69c38f5:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 77449e28fb5725e736fec3233520e182:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID e3901cbc0850fb62e40760a454e59f7f:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID d7f152a2aa48be11598495dd6e921d94:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 9dd9663545374525812bf52e948d9f8a:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID aed1b00d3d70b37931e58c3a150ececa:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID f05cb63ec44e34f571eabdaf5a4df780:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID e0f62e5003040ad8c1d67b39d409fe04:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 01bcde5e97eb42201f84d2dc2a25a174:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 77b206c7cc6fa5f20ad80bda95cbf371:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 18f34e072fe2fda1a9f539810d018f13:
  - consultor_grupo_atendimento: 'adenis alves ferreira' -> 'adenis alves ferreira (m&e cafe)'
Diferenças encontradas para ID 2832daed0d6a5cd1ad98e3ba59426a40:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 1f8958fc52abd61c286e8811b28fd079:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 06139cd12052eddb306ca65f7b0f5bb9:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID c9c5632b876ff2ba1049415e2ae23ac7:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID f432389183c7671fef8071a8249e68c5:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 428fb65e73112aeeaa48f8682b1ee790:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 5db144a9f04bc3f4c8b6ca4617d26b7c:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 4e4536652247d7fb5e4ffe913838d8de:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID fbfe45cab975991784f2492e10403511:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 1c6624845ce2481eadc43f7612c9adc9:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 8486fc91739294073dd0f5751e7f0b9f:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 18ae61aa8a2959858324a788ddc9c4b3:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 27bfa7249b83c7f71e6bbdadaffa30c6:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID 8ce9362c063757d0b225a05c9565cc76:
  - consultor_grupo_atendimento: 'alan henrique ferreira chaves' -> 'alan henrique (ncp)'
Diferenças encontradas para ID e9809d990bcb900ab777388dfe1996e0:

Diferenças encontradas para ID cdc05652ad692b348e016a7e496c563a:
  - consultor_grupo_atendimento: 'herick lucca cos' -> 'herick '
Diferenças encontradas para ID d6d87f9dbc0e485966c2e70e80930fc2:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 525079eff766816540617dea580680f4:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 1b4d082f3134aef56529cfaa140d6feb:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID d0fef2787ab855fa9b07ac65f98a49b8:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 9b6f59b11a14d9b6fb8bf1afc8ee178f:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID b572e862f6b3f6cbec5a94eeb293d82c:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID a02ee4636357a89254cfcd499f6588e9:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 897214c3c9abcc1bd6bbd51eb6ff93f7:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 4aa9fdc26512f8e82e731af9bcb993fb:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 0d9cae4e3f492be0663ceace97eb0a32:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 8bc9ec259e7c0a05e276fc64530c81c0:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 5f3763af10849778e2ff0b4f72a36b47:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 657d4d517e20b2317e3c57442b60f229:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 35a29e664eba107c24373fbc6f3f52ec:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 569263f0649c6d7cd6771444a3cdd3d8:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 4b93028fe90715bdf63f2a6d2cce0e6f:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 8c7b3191df8a66d5785769c2ef059513:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID a1e16e73a500f127a711becc83d7113a:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID c00ef856accd35ea6a40211b3f72c383:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 7737884f24beaa697abd22f9505deaa4:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 8f1b771427504d1156b0558517fa6922:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 36783af256cbe621bf4291d067046068:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 608ff11c6353df87e94c776e8964f777:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID e9b44bdda8f8a24c8c4e8120834674a9:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 2d64c2f64c832913947445881bb1def9:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 82c363202870722f474d84b78557c4a3:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID e63931882118959c4360119218ea2f70:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID df68d7ec7f24ef09a804af0cf11aa6dd:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID 03b227efc2489e1b939dbeb71708067b:
  - consultor_grupo_atendimento: 'francisco ne' -> 'igor miranda zane'
Diferenças encontradas para ID dfd73d0b54f36d4bf85fdf2554a62154:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 7fab274331d6b0672ea00249903e5aa6:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 400558ad9f693ef2e21fe8cc5c483d0e:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 9db2cfabc4ac009a98f6bd2cb5459740:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID a8f853de8bfe648c7991e53b379e8105:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 3b34430718c7b531eccc9b918c62515a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID bd8eb8d9df8212f0e7f9a5b9de89a2bb:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 1a56ba92c53e4c5e0d1f993af53232da:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 23503985bbc38e57f06cdff083c307d6:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 0ceacbeefc80836c09e11e029c9b9408:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 94025f4ef9f180813a3cfec4898c5f04:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 8859b6af683350fd57fa9a136c76c714:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 6f9045488a4daf92739bfce1ce08e717:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID f362657c2c1a6b0414e5de743445b0c2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID b2f5377c631df6e00afbb23ea015372d:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID b22cbbfbd1f4d28568246e2f773c9db1:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 62b78545f235c6fc1477f466a670a843:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 5d5b34865a2a628b1225f5758eb91eef:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 6342d577be430e9fd1c1567ca980d82f:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 48d113eafaa6e3a2a431fcf89fda76e0:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID c1f582a862c379c952aacbdb27f2620e:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 1eaca689a18c3214ae1f400e0083d6eb:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 1a0584b10af0fb2068a2f032ec1a4bc3:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 5924448f38550af83e731778b5614db2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 5749032bad5510bceb18dd29482e1973:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 70250132e4fe1b879acd00703f896951:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 2fe5dd67480da99905888f0b8d4f7385:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 4011f3eb6b3886b187d49aba59e16a4f:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID c9d447602c396493ecbbd78a107fed6c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID cde2d18dfe3c211ccb3c0f855d7acc8f:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 81284d4665fa4f4da884ac087805d11a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 39e1e7d7cb6b27a80e85d3ac3b21e4a4:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 46497fe6da87e782faaa0b6f35ac64b1:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID b497502f8d1c0a44ecff06e03c563793:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 8c46419c5dffe589aceaf93bf5872283:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 2256cf581b13b079900350996dad2c97:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 11ad328fc8406864b6193296371e9e80:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID d7c8b09331ac666cc6c05ef14923810c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 9fb941c67e0106435cd799b7db432ef3:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID b742d4562b3b7e029990f71ee63c95e0:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID bf4764c75f61e154e7223ab1316031fa:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 4bb64a0de63c0124263f7f699e863dcf:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID e65c898afe6b05590285983853067b05:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID f4376e0c9c1ef2904f78edcf9b398029:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID a2a04cd37a1ccbc398603c12fa8a9d03:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID f65956c02c4c82380b882ceb5351fd90:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID ff12f6818f4c5b14ee68cf4eece04a0b:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID c27ca9d1ee7a65ee8cad1ddbfad78505:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID a9271b299907b5a30f65ead64eebedc2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID e5982c1bb135b3c7cb4405eacaefcdeb:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 33cd75f53a88929433c671e51e7c09a2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 0930c00a3a459554105b918453c17e05:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 191621cf35a2901d4314d22d5eb14b19:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 8f16c5ef28057480b6390c45b5b25b4b:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID 0049908cf928197a5d3bd720ddc22e4c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (ncp)'
Diferenças encontradas para ID f79323f22d69057a4bf2ee5020931237:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 5e37d91fda637ce643cf6fc7dd513e5f:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 01af96ee82a887065a8cf8ddb078ca53:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID f53b676ecd4b26b3094e482dfc1b542c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 8dfafd09c43aeff94a58348a9bc559b2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 717fd499d90e0970eaa133631c41bb42:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 75f4742d26e55e3502270bf56de57f57:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 3a35dae721ece7568df45f019b0e554a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID bbe574096d5b9550047e0b64bff7ef1a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID d5460587b6b83e4c63ab985d96d39396:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID bfc678a2b6a515cc2583b53ff39d30be:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID f7ea6d7dbf3afa9852e14f7c900a52f4:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 582c5517920ad92238ca631c3ea9df58:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 82450b799cf4b2755c92b927408597e2:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 4b0e4c8a1e84134e66f4128877bcfb63:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 14d905b031c61c5339942cc2d3616977:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID f6ae85fe0b3ed10fcbfb9dce2d1b6543:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID d066083db21fb0d71fb9d56e9aececc8:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 2b83484f5e364e6a965ff8e346940db9:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 57fea846daa0c6e30cb2be4398ba9ecb:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 78b58bd946294e7900cea3775bbff70a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 9261d650836f447f5a5fd621eca368cd:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID a2939d38414d25926e53246587bd0c36:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID d5ca91ea0201997ff927a45c2136e9db:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 9a568dad7a6bda6368625e53379e3d6c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 1bc690f802cfefc39d7852a8b1d7d3e5:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 52590064527559b4519078da6f8cd4fb:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 1738ffd735c7a0c9c6f4dca5ecb17955:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID cd39faec9a67ef5ea7b41d876cf20851:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 4a37da95958d712f16444774edf9a10d:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID b96d96453b9192ff83418340ded7cab7:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 5e1ce892a6161518e3179bc7ff7d5a89:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 98d99c794022e20423f79fb2a5afdbc4:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 0cf6ad5ff0d56119f800742938f103d6:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID a6351f4a9493afda5b7cd365b04547ee:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID afe12e7640c8bc8e64b9da9a9eaa2882:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 73fb0470c5365ed63b8b9870d5d79514:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 196f8527a5064c26a21f391d289d8b5c:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 8d5b62d23e2b47c3aab05ea15cca9fa5:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID bd9d77dd72183d164643e48f73ca1c07:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID e0b7b89bc0063a304457467358b19ff5:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 1bb309d6adf6bb573a5c7ae9305aa0a3:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 434cffc8eac34fea013f4f95234efc69:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 2ec51259f426438cb286f25e42d7ef2a:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID c3c90c600f2a86ef08f2e1eeadbb4d70:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 1c2ac82059d1bcf0801cdfb93817c6ae:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID c91cd4ddf181692da6645a794e580700:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 705fe92ee103ceed23943591e74f5ba6:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID ce7207c92cb0986ab9c80d66cea733ed:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 0aae7985f60d8144d39c5451030c2783:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 23e2dfa8fd3ef34656f818d7b4a6593f:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID bfbd9ee9cd787aaf8706a2ae9010baa6:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID f007e08a9d31ab4199b2d463a8c9e8d0:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 6c0c86fcfeaa956c8ff49ed1a3a9f650:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 63728a4dc5062987bb10464f560d7c09:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID a93f8ac8689f80f4dc24dcd6909d5a69:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID 6cb8555184cb457124ab43512f8c2669:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'
Diferenças encontradas para ID eaecaf0c0d068f7b8cb0d15e1958dbe0:
  - consultor_grupo_atendimento: 'israell melo' -> 'israell melo (pv cargill)'

Diferenças encontradas para ID 3ab5253df60121c6d49bea605b4861ef:
  - consultor_grupo_atendimento: 'paolla mara dellabrida de andrade faria' -> 'paolla mara dellabrida de andrade faria (regenera)'
Diferenças encontradas para ID c9a492e11deed091f0ae258f8b20e379:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 6a043f8ad74315cb5b2086dc5e2f84f7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID aa5d3d884ba8520faad519fa84dcccef:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 57930e3d2592c4d9ce6063e28f5f6448:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID a954e800735b30d5ebbaf55cc42ec4ec:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 7f3009104588206ba2e61ecf7337da75:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID a8c54f43ada0be61675043ecfcc2051e:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 9db933363ab40bf7c6767f248beac916:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 40ecd68b1c5fc421ba1b4b4696176b11:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 744cc4dd1bdb8a29bd671ff4ab94a18d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d16373ffc673563f7655b563240f3f33:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID e88a573bf750c278ea57f87cd9eb920d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 87bf205274a9fcd5138b0c7944c1723c:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 23d44895eff6e38b7e9acba3f6b8e361:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID c5636d0f04b7213df039a6448746afd7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 41ca5c07eb95b590effc7358264ea384:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 1971bee3f8798eafb3803985f628f23e:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 142bb44c4c9149a73c912ce4494462bf:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID c4d39c861acb903c4d920f0edb721fb4:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 0ef3e5f6e3b14a8f3d536dc77be187cc:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID fd2650b1d922724aa0b16d3a4a97d548:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 185191c865e4482d0a8d9aadf819d655:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID e0fcbb739663c049f894949c2779a9a7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 0a0b2466d1107bfb51cfaefca0279be2:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID ba983e6c393282a624a1d79fdc2e7eaf:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 8f6771f1db48a76a872ba95013619b4d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 5458c6128c3ee0138407bb2cfd903275:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d9f0fd68873b06a6206df70b17edcef6:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 41f0d296a354c08fb3b545803ea2f0a7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4f8efc5f2fa0ea38ba70690d62009bf1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 5bad2f9bb8d2b12b2f2210214f613ed6:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 23984754fcec3a8daee6ae691f77d909:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 0fbaa1e0d83700fd19e261b0777dede2:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 19955446a1f67facb95891d1a564ad56:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 97523a9428e5195828f6bde6155efca7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 457a2f686e759232dbe0de1f47570ec4:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f1831635fe5e792f2773871d9b8b08c5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID ff0b4b1b35f8c250b85d7d2b89598c7c:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID eec8bd2358b5f3296bebe71abedfca0b:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 2efc4036fb6967e924722efe6a811829:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 78e10c191fb1ad33947bd934b86bddd9:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 84f14a73dfcc3ed7f8df538311da84b5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 23aaea89256a8a4e405f3a875205cfcc:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 846dcbab8e931627e7ce0575bbce86ba:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4c05e38459cbc040e103c34bb0a1018e:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 391e5c76118631d2ac0109f2f51b3015:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 3eb584bb446cfa520dd122f6899c7b1a:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 019eafbf4caec28472b8f85539981191:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID eac61e2292dc09704fb2545c2bcc7195:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f308eddfc04b028f11d70afa17c53a3a:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID b70ddd9195b090c679c24bf2a56a9a11:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 2f42ce93bd1dcab5722c1aa0361419a5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID bfc872305762ffc446e702fc18dfbba2:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID b7d1be00b4e20877e2cfd4d20b78f8cc:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 5e8b870a507dbc4ddb26eeab7cd6afa7:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d2287bacab6d9fb2430484d4fd2c8d3f:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID ceefd5012b310e96561d91cbc22d3e7d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID b84ada97e72ab0ff5eb2bfc9b6ce26a1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID dc4bc63e66047dc9631eaecab34c4040:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 6ae1c7ed8d4db6aa7577d23a97ff45eb:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4ca753fcd68e4c53cd4973eac6d14d28:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 3ac43726836cdf3ffa49fe5949105407:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 3ef3283670e15fa072cfcc9cc4277e70:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID e2453f2fb836f564b333745c592afe6b:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID eb0a9df7f9faa05d63973bd0f78fe4df:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 25b359da94c09738d98ac443e2b68d5d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID a4b693e0d9a8a7b403088ab6b947f334:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 60d51faf56e91a17639f6a7e2bd6d533:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 36f3fcb6791174bf9b65138cf7990326:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 195851b1750ea1a1c03a6b6d7c25a3c1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 09b30ba411c2fcf237ecbc4fb4de160a:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 669f389f6ffea71c40097055fa640b94:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 622698df629423ac331ed08de6c1acbc:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 729e52cacb64c5b4a005d4ad77e57cf0:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 1abc4fb531be3acdeec8505fc0328d69:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 20d9af38e6073856b0dbabdd66f63479:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 479e6ad06fc57d7477266bb328577d31:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 73777c8e6cb3bc4a0281de9edc63ffa5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 6b333a341f60f5fcd852967db9a38ddb:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID ec60eeaf6645bf8cd9bc7722c1e28309:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID c6f20b112276c6f71bd487c6f59ce29e:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID ae4638ac109f136b541b0e10fd232e30:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d551a28e6795bad4d8881f83dc778bf5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 7206db1e167e9ead00e5ba61e806cfce:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 487d62e93eee626ce514c825a3f2a7eb:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f2e2eca4fbd9fa03daad7eaad4b193e1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 092e88dc33ec5d65cea5093df0b5ad8c:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 01ea26bce1e842b5d58e66b389611d5f:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 1ebb889fd8bb3bb8018fcf5d8ae916ba:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f3e1713c2d75aac572c134aa2ee0d47b:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4e6a157b158390c23d8bffc1fc885d56:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 7c7d8ca37f3edac7b52c8a3f5f552eb1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID b740f4801fbcdf8e8559708f48354d5a:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 8f2b7fd62942ac93bd94915dff8787d8:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 0b8dc2e8652161c0a09f4474e52d73db:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID c2054da332682f231d089115f10c4e6d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f410b652aa862dff6017d0a84bb85bc6:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 17a4a4242e93d47bafcfe97c5daa45ee:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 0f5dc6e4d69a0c7fd45f3ffb024608a9:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID da1579a82d5bf194351010a59989933d:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d5de563c2cfef607c2f5437489a18906:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4e280024fec5bbad75aafccbd867c630:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID e30d62d1f5bca80151a9dab04d76df17:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d80e95fa0c0aa3fb5813aa81b0443dee:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 8d8f212c3850777cff92389c69f5e141:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 092fc76498ad3715cdedb06f0b9ae6a3:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID dc8b40584b41c9e352dd9250d2970cb2:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 97c6b9c51af9d17711e765aeae1d7edc:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 01fe16166a24c3b774081a8390d155ce:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f905272fdf7ae795b41d9a8271a33400:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4211681127dc9ce2f533693b18f3a6d1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 39e2de26e03d7a5fc9df4d817eec1859:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 6b21856394a84e95078603eed8c3e91b:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 4714a894e4b349340d870d47e06d4ea1:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f062f19344810c69cce3e38367247a11:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID aedcae59c294b291d196381b8970cfb4:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 5631e124b77efbd6fdcd6162dba6db53:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 7d2cbd922c749aec18d0078bee210ee0:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID cc5bc12b010f1dadba87335f18a38794:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 68048505a1c757dd3e300af15e5ba127:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID a9d404a7a7748a1b3469dfc91773b359:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID a740991bf516d57e3865b189cb5c7e65:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 2fa692a035aff704d0ff1850d3e444e5:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID c39521e5d617550c7bddd7cc76f445fd:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 1db511e384f7ff19a4bd556fe6658235:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID d6b306d62c32fd40d6c65b02957c7eaa:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 8fc7264acf80049b7335196886721272:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 753a00e422f1b049003b0d1eb352e6ac:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 35a7c5844e1bc79d0c5ab96c1c528329:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 9c8bb9a6b7e80aaff1e0f5a9a74f3c79:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 01515f70aea8a3a71fb716b8272082bf:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 678e458c221a27964694ffd292acee73:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID cfb4c14faa9125860d43f44b2e4eb277:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID f62e1b4542b05e5581ad916df6466dac:
  - consultor_grupo_atendimento: '' -> 'paulo andre miranda moreira (pv cargill)'
Diferenças encontradas para ID 59c5249fc384b40c43dd82c9c8ca3d28:

  ❌ Erro no lote 1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

🔄 Atualizando 3693 registros EXISTENTES...
  ❌ Erro ao atualizar 2de9fa4b8b30d710e97ea5607a660fc1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af781b7931278205c2523d272feb75f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60d5d489be6716325eb8f3d933bea2c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c53a515650306daab22a0167eb562887: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b5541af3d387442b8bd386e53b321fb2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f0d3ad970938cf1018d7e82f1ab0e70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4fb5bc3fdc777a9a1271d6d2687c5de8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a90e723745d1fac1089969a5bcd66ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2d15c54be5f7bfb5b1ea055947b7520: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c20369716594bef0a86456a1761ade3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7abe0b12bb11f56ac1f48b999e38460: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 871e4831108770c77332ea298b438145: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8807fc3ea4f8ca85f728fa6b1c9f8e0c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0aa6092f558f7ecd73047cb36a03450b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4ff40817c0db5f99b34ebb987c97f5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6b0ad027aa937ca33015561f3f9029ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a66bfb0d705512639f22d670c5b0059: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbb9483dbd012cf76d74b95a9a578f09: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2c3ec6bb80eaa50fbabba2ea36761b5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bbf369ee90b4b830ec497597ddb570b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2ac500a56ea6f8ae39fe8dbae6a85040: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b0cdd05442aa726de8107901afa89ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77bcbeccf5fba8051dce8f81fafc0186: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49d8a732e010d9a4664bca64ceab2bcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ab67ab400dec1584a6c7ddf8614e0827: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d5a8c0220de45d53e29bb9ab6cc1a6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ebf0038ed2bd07e86a36ac3acbfe35a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 10eb1d8d5d09d1b4321a6aa3d8af7fdb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83deaeeb641313c825e1e14c8a127eb9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37d31505f8bbf098b204cbadd1ff9a93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar acccd7f369e955058ceffb1e2d19181d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 481ffa988ee973ff7e048ee63cb5842b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 110ec14b22630673a3b6507c6ef09936: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1dea0e12b9679f668ae89b76634655e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdf16758f85df7974dc00c25bdff52d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32b97f45895f999c24628f3b6688d754: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 886c7d807dfa58904d2cec82cb270d1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f59074eec84ea7e4e7fd7f5ec55a6979: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52a83c104eea30e7c27ac58e48ab031a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ff32bc0e8e2018ddde47b5fcef46a50b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 844c5e8718fb42853b34a36f63888a34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31f8c78134c7521fd6cdc92988c0fa71: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf0998a85d5d2262258414ffbca78ded: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdca1c6ba34912e6c40568dd10698f52: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2899205d5afbf2023a8ec8b977f24ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dc0912315c268c002a9d3a7e5a706b23: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f0bdc1d18d42fee2a2ae0ef38d78960: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar be3921bdca56198912d004c4fc91ca10: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e343182b662057bbdb01d8570810daa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b86b740f3117cb80e66166796aaf7222: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a7bc6525eb1c1d96ae37ed206825e06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6f71dcb71369790c93a5153d95badcb6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 780c7347b97f7d2ce9afd035135179a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d355163323818f4fd83468657a92ad50: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 47ef3f0898fbca4819120908d8d92817: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 038e673de8184f492d9cc54b3018b4d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0ea8d1fbc4aba3b038e3e01a87f6e47: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f60477c57e8066618d547887877dd16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f45cedb5121b78e46f87b3c08950895f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0be5d6985a377d4f14affee0e914ee33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 415828fe75fe5645e0b3053b6d16a717: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5056702551f36296120325584ea86e28: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c668687d1403da4a871c33ce53ebd5b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d105e17ebf4a17c621bebdc1e440146e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a55a76bcc29c3ea1e92c5cfcee51bb15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 71ff7ccd52ef98983d039da2459dc1a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35e013fbf84d08f8cce4d4c7f3ec5921: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7915d5c917ab3478c47670ab5d4647b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 155d925cf4e30d3c659e57cc359d7909: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5be61ba622e9d6bbbea766513583ff60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar df118a3e19cf63c83211b399e9d34279: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 72ea47ba39eff0308567985f64cfa7a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69c79630641450206bbfe5cdef8019ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 406e0e5c545278db5096846e7ce3e8fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31244a0b99189129be8a77daf283e188: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54d62742e0ac8c7071a3b413eff40a5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 743fae1d5e790c9940048bb9969bc608: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a660f95ba2db11c3405e9d8e2bb6dce4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2858ac98f9109f3dfe68babade967d08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d56d7f62903e42f114441603d6372ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 63be2c904caa79118fd5572ba66be4ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d976f7b4f56d79eb17a6d137e69c38f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77449e28fb5725e736fec3233520e182: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3901cbc0850fb62e40760a454e59f7f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7f152a2aa48be11598495dd6e921d94: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9dd9663545374525812bf52e948d9f8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aed1b00d3d70b37931e58c3a150ececa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f05cb63ec44e34f571eabdaf5a4df780: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0f62e5003040ad8c1d67b39d409fe04: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 01bcde5e97eb42201f84d2dc2a25a174: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77b206c7cc6fa5f20ad80bda95cbf371: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18f34e072fe2fda1a9f539810d018f13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2832daed0d6a5cd1ad98e3ba59426a40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f8958fc52abd61c286e8811b28fd079: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06139cd12052eddb306ca65f7b0f5bb9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c9c5632b876ff2ba1049415e2ae23ac7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f432389183c7671fef8071a8249e68c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 428fb65e73112aeeaa48f8682b1ee790: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5db144a9f04bc3f4c8b6ca4617d26b7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e4536652247d7fb5e4ffe913838d8de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbfe45cab975991784f2492e10403511: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c6624845ce2481eadc43f7612c9adc9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8486fc91739294073dd0f5751e7f0b9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18ae61aa8a2959858324a788ddc9c4b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 27bfa7249b83c7f71e6bbdadaffa30c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ce9362c063757d0b225a05c9565cc76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9809d990bcb900ab777388dfe1996e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb12620608ce1ef4b267b8935f37a6f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c1472e965513137bef8f7ee5279ad7f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar be4101165706659d651e2ca11f8c7ba8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ead90e3ecee22fb3965d6ce92b0af327: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b68bd34d416e4be40df05e7d5eed9700: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f62f5f6c82008b86407a8e109cc5782: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0384a2812bd774b74d4224d5730550a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ca50f2f434dc16f377fa8b87be36e6f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 59bcc931cd1212b050c40cb18c46f232: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c16a1a198226dacd948d7dccde04654: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80b24c7e48eac453154a1a0b1e137ddc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf9df977a5496454954cd093df7c6fdb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb611c7288d90455ae3bafaa755739a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a42f0c9b640bd3a57f9b84aa10e1c038: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 933b525008d7b29982f73ce0d5f99fc7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77110782ca329691c5afe46e5befcf43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 30441f819446aaea9fe1c0def44fd2cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f4399f1d5d8fb5e725ee197f4207ef2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 46ebbef7daf237186d85fcf967b5717b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5f90a615a093375de263f4f41ed75ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 790f3e3debd0457ae13c06783c5a0850: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9162ef222739c5fea158e0454536dcae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c640f1849dec94254ede276be2a3e37b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0fd0b2112268802233df9baec374c7bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d7f92ee40c19ef098a94b8345ace88b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b134af7829aa7ec421e091981eebba30: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6794909a8457edc50f0d4db42d035921: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b8979cb20ff75fe33217acc6f6fbce5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2cbc1739cd0f0790faa1c71a4ba75595: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59ef3bc03458e529819d48210e158787: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3d704b35495b53bb9c0093b06056e9c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fb05dcac54c106c902c00fd4c75c30aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 236a95d99a69707f54f49599cab3e5cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dfb4dd75cf7103127e276d28ac1fc7b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e15c0de63be92b542b32c9c132fee0f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53fe718d486596233b85defac35e378b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 409fd475098058b07a8056433376eddd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ae4a0c356b0ea96a19a922939b06b8d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4213ce4ea675a1b885da5404127d8f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 33f404dc31b8544709c43bc42835fa22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53ffe5888bf1cbc4bd65aa445779592a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 742cfb06e62874ab4afad266fb63da25: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6abf649e670b2a0601b7f6b4790c5b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1c7de9107fb424944432d53e51fd572: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7df82f38ce64dfe12799872276e8256: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 37721fb132a536c2397328d250a5bcbe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36d1d796e6e6827e14dd2313ed00ac65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bbe80674dececbf2b836e3e2358d0f13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dab4995793839f887556a841866980ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd820c28216d13b78893d6efa215bc95: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ec2fea8bbbc44ec27aafc73f22629fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5e4eb1125775546b1510d3f66c696189: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b8a1f3558d53f01849de770e6da8cf3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 111882cd07d89680e0f676cf591502e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 955b9f7c5e2fd9dc5131d97b606405b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d62bf32fbf92bee2f72e21008517e26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 432f8f3831f356dd927ff0d54754c44a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89b23634a30ec7c1e771662f7cfe2053: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e00e9dbb5d3981ec185cc52c118fbec5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a745b4c2be6a700ebf591454d73d256e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d697f8641b708e805e47397cdfa331a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6019e0831a80ef4ccfe9abbe569883a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3067c414f49f3d5942d0e311624af558: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7fac63f95f37d1487d26e2231fe8f36f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2aa2cdfee050c7badae44f1d3b2519b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f71fa1d7d4fb8cca131af59c47b4b4c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e57bdadc66b8341a29055beb5bfa194e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92bff4f4021d841839aef21f724c523d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76e71f22ff60b3133e6488c177255c4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 944162db344b5317d3d5597245c65150: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ec618aa850263ced0751c20121a604bd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1d4d2fac15da6f6a77474bc9d28cf277: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0855c2ad4cda8c6e9350f3ac88c39a32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b49e37f50f717781c9016922a3746ba7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 193d76335a6a049f601a686dc4187861: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bdf8eee060c39a2091423bcf6fdfca1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c938d69806d5eb8365cf1efd7aaee487: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a552c23f7eb4a9544100976e22abf37d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60e621071505cccd79905f264a342462: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc9368d0bfc75974e2bd85986ee860d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0b40b7f2782652efcb9d9d408d122a6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a42090fb9509cf86f4bcce8df5b3f75c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2ab6841520194a224042395a39c27293: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 604948e9c7e72ce3f460099ee5b560de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce4e452814fb5c576addc6aee7fbd0de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb5b20623e22c4028a1501005f98bbf9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e5f2875cd0974276d32d8e167a01f08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cab896ec70ae427f65d57fbd8d753989: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9ae5a4a61158443c7236dbae745c66a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b69b59428eadfb7013025ec0828b22a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 445d1c0d80167b84c28110e139803bb5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 46c72dc91910bfef643caba1c8c16a24: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 56f64129e15bb538963fa47f669fd2b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e7a0c872179576fd817d04df7cbb4202: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b19b08bb06bc989e9e5609eb20ad98db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a53a6f019e280021e7187d6b37119c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 030e594305923d7b07a54cb88b3b1b77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 45d9a45cf391986e7e13cd8989dba594: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9042907dbb01f5a44976f83c58cbe06d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 583f458f007f96b9212bd0c8b9b1d0a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0d650777d247d22b705891112e008afa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8304d793c709e8ea737e537bbea3cecb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50dd7381a6ec5dedad8afa7a38a14abf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 097ccfddc9b42a7f29d571177ee84b79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1f53de82dbf59cf61f229932fe4c1c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cec6eca4ca45dfd567fcec99f749f5d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 411e993a560e4f2d909325bdddd4b1b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c2f56f889f23d5a2cae6f5ac5de98caf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 24d2811aee8d23498dac2f0e0404b9a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81db0127b9c6cf56ceb4a3e84686122a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bab14e6d91fd7b1f331077b6ffac2bbb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1ab72b275524bc840b7b1fc0320b134: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b7220fb380149d88c3499a7ef8d8182: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f7268b317cad4391e77189eb55782a08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f81e9fd6451617d93d09d6ac01c1e496: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ce36a112225ec153b367f3bb1557601: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7fc74aa0b9a3d257ed1506876e67c1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb8a14b16334c8ed777dd4b82185dd9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ef14b7e3b3d68f61d12f69310c1de04: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6c54624db494cb7a985c348343f5237: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c33775c95e05cfde3e9ce5057fdb2717: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84e3da8954a3675cdb89f29abefd3ffc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89e0527d8c4aba590b78e28a32ab04de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6dda86cbcd6ac3d6dfbb43253386bd9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e54e855712edc17f18175580942caeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3280688bf7e7d86f47bff1593a81c819: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3fa5cc05605ce45e7064fb7ea3d1787c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f34bd41484ecb065d155ecd4eb784079: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7d373dc702f549c2066c102d3bf4f68e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09206737cccf0ad7125e1f6375bf01dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bedd9bfabdfc401072a88a91fd798d91: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 502964029cb25c0dbfb5f22ae17da3fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d69ff856c69b78879bb5cffdc7433a7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a54c3ba6e6a3dda0b6aca8b28d723b16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fe10182b5ab0deb911268fbeb4c903d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21c96c7b65bdb173c07a8b1b11957e4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4df4beb6a9634113105dd2b1c0e2993d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8158ec60fdfcbead4121b086aca7c2b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e05a9891df3174b3dd6d023a4a85ee4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 439ad9cca520a050d43172f4d7a2e1f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 33e3be727b9fbbab5922eee563b48b6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9c4ab99b17c98f04ebe49e5289a84217: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar efa029e716ea48d2910c1807282b0ec0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c63030727d0fcca2caff6f13638cdd6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f010c73f6c999604323c8bee1ea1e0c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a3b92b91c37365641498234802062125: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar adb738e0a4abca972423fbd4910b8b3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 73ed2061d686f27ee09d1f0b55f2c590: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da6290cec4528873a0ad76196f1150ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2feec8c38f9d95226e24e574cf4a889c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e600d3dd44c000d2507f205e37c82869: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4742dba25c735f6d99dfb837d0acd93e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ba43060060fc2b70cfba74a080fe04ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5775b76c764a1fab9e58c75d140ec919: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b547683ac391c72eaf8f56c16407da43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a47bad8dd4afa00ae2c6cd42cc02572: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53ce65da7a6e045990fbe43dd18050f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 133ce400b0c632f9ba8ddc384702e6a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bcda23193a792d78dd3b1930dea5368c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ab163bbf9041d2341b270bf7f454f3b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac7609e1ae23132c405c66eab46413ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8421ec174a9ba41d240ca54088b2986d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1451518dd162d7e3d57d90c9ac98316: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 11202722f0f7938803de512a646c687e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4fa09df7cd3ba379f1e750e1cc8c7c35: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e2cb1aeae68b1e3c29cbcce3e5819de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0bd2910b0f11561231e6453ad1c74b9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 346a960c58c56aa37cb1b581a2b38538: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ad83844ca007948218648b20d356ae88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43e40aebfaa0eab0b5c8876d34a428b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25a348b4f3d140fd8d8cfa46a337e6f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7bf6915d96540b78f4cc14cea915e7c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 431e132f220925ccff58986aae3429b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c70829ee9e53ce5b8f5672c62a3d651: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fc3b3739185199f4b2bd0e32251b4e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8a8e48497c3e041256405ecbe73d646: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e97f6440fadfec85ac9d1b3b8fe90f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0134cf167706627384588e9cc82307e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 722ce4c55bcfdcb321c9c8d3f5d0163a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5b45778c41112ea627cb1a372e12be83: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25df2346eb98dd887d8c8607b0514447: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b561b5cc7b9a744a386982840e1c9182: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa0f0ce13eeadeacf766d1ac97f1d0c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c088cfc3d8312abb2ac17039ec055e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a365ab1de0d7d2e5dcda0e68dbf9ade: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ad1631fd06b259c35c6650306ffbe304: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 14c77da895f2de35af79eda3b04bfb43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dbfc896ce4b0b8dc29fc7f0f8de393ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 004a1ab2bd004e0bedc932e861c7c837: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 56ff9ec455ff1dd27cdab828ca1a54f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 88e6579ef27db3eaece994aca72254d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f9d1cb09751444351e25a830a5260a20: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f9c77b499c3d8837d30612e77242a84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b8f17ebf55b6fc6b69db4e78f61beffc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ebba264e3f6a75c99a5a4162dd4bf4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d2d511fcd6db444c809a53808975084: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32a034c5df8a68429c8f060e4e250000: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b03b857488c89cafcbb640723b54c28c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c248971a3fc0994f30d995907049eabd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 378a660990c37b94e355cd59cb0cfebb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4cd13caf0819a9363c2f1769e05464e7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b114c3a1363d1646ef659f8908966c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cad713b881eb82fbb44538c74dfbe59: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a0a2c33e4f9d05045c1b4d781017cda: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f1ffdffa17d4d33a29c10b39f3033ad2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d44690aeca12d926a69b8bddfc339b4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 109fd6ded0ea40e1916096ca46db142b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f025d0923ece518712bb323393de3b40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec2b4fa1177278dad701f419ed955c3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ac7041aa41c27bed0bdf14a017d20f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4199d7b4bba3e0cf5af54bfc36371db6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a80ccce11f424ccdbac0cc049305dfe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a6ebd5c0be1b05c96ca65a9aed07f887: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39fdb97fdeb10b851d689f4ec0f3d0d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar de726ab14c46e19156938c0a5727e941: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 16ab738e2741c0fcf7a4adf84c69ebac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17b31a9cc1abca9fd7ca7ad5795e2cd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b69010f58192a29e1f7fe9a841a3275a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5cdd2d9e53eb93d7d3ccc7392d1ed366: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b46d21f2d0485dce80e282f86181a1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3cddf8787e9abaf0b92d89202ce7607: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0bc0bd23a02df7b36f86c48073cb386b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b248bdfbe2c9aa2126e2f3430ba017c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aeb70207ba6217a8854b13de66904a34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b3a0e5eee85b6f68dbd4a3c374ab606f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f63e2fe015a2d880c70d9dfb4744d79a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 075ea1dad6face7ea059f0c84926bf16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 52b43dfaad27988d974e50c658fc7412: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c302fb6fd8c88d8c5ec527ecf3b23a6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc42500ef31eb7051b4e9b60b8c93805: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 053ca9315483a2b4e197762a4a9f342b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ddf1f02d4855baa01be737ed575dfd1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d3773ce4bed7aaf8d4d537ae4e388c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5586c79d8bf9860e4fe33fc82ee83e59: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 87691ffa0d24ab59f666cb778ef60ce8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ad3df3cfa4ab6e756c15f16c9e79d4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f1b0ab51a1959b0c889c45e086c2dc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d97cee800ddde409d6b5861be639f14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 621e58df729c4a3650e02552cfbd065a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cb279d4cdeb25062ec4ef8d34aed74e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 609336df7bc558bda3d8d37c0a4b2d08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 321b94014e88ecde3f44983d8ed9d192: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf0d6f805d68b7ca63c8bfc2b1a2b2d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cbf46dfbfd3aa8785d4d4c78246d7106: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4f9f70bdba3ec352270e23f1fda0dfcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0fae70232e498670f42971940c5a8826: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d08c81f1928b2754434296958b0fe4a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 072ca0ea3808992df8abf8af20e83273: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6a1a0e2d4e6a76f7fc4f34eb8f0c55f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d30cecee718db2cfbc56227cafd33b5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 372724596ee0ae44f4dd30413d47b892: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d6bd8bf69c0664715579d7cb22ffe96: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1013674acd68451643d953d0d951135b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d69601b9cf4cb732a48c1e32975f75b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5307e355a63a9587011a6a50d492ac8b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a4089284424436a3e5e84db0f8890ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e5c94be86a0c39e026d040481897ea68: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98290a0111b8b7ac677c90d1d1ba8f05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dde9bbf216412bd1b26b3f1a2191b6df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c7e4f33c8c4e760b648cc0d065f48c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1dd327f931bba8b5bb3dd408e40447a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e101bd74e1b1446cc4b7a5dadab357ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 369d2c746ab30ec915dc6a57e6269eae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 909f36c4fbf37fdec562c660e9c7ae9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e57efa7895f683100932542030db243f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a70c915b4a5c7ac44bf387b4e0b32f70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ce57c01796ce188e2bf593d74e154f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7334c50750fcd89edf40052670ae083b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 780986a9733691c07325f6cd2ebb83bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 320eb8cf61ef76eb1738a473513de228: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3bfa13718a0c6329753e5eb87176e0fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc4ebbefef8c36b260f9c33cc8b7bed9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cdf2510c3b3c909cfa70ae2069742494: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4af34879c21dc164f65c46f71846eab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 247b293e97bafaefcea471a0863af2c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e523cebf199947cb38073b3e34dd8f60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2077e67a4b2c34772f41f15e675677b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2e8aab51e92c57c6d137bf066e8ad0e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0df248fc7410498fabbbb7c185ba05fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7eb9b2e1648f22bf7d1f2a5bc328d3d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e91fc3aa746b781354c4e6ba42255db0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fc3966b356e1a9b8dd5821a9d738a0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00daff209eeb1a5811fd6da911269bcb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cce99c4ea8a242427e2d39b41483fb39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar daa32c8a4500d17fd6b74019270f79b5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35d04292fbad6e78663ed16d6cd26482: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7cc101da92dc70bf55af5215baefaa48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e3bf49c7875c7246af68be9a0f10c60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0bebbbc3dac979997bee90d94bb5d5ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38e0dc5a613beba5ea7d8e35637c6ae1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c87ab5f762a73de2633e6808155782e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c7fc9500eede4ff2e4a5cf2ac20539e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3548e5962b5b2863225f804ef2db7e33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7821f6ea9248248669e73ba5652ea98b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d20ccfe8083c7f075752a4d1c2b6c636: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3d569f92a5a6220e21aa67fdaa6b05ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 953bad8ebe94159f5b87b063c9574b43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf5d46c5c728d3e0400ef74f370c4bf6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0a36d59a7100ff5ec50185ce45cf36ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9c19a67a3439756a4686127fc50073f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a788c2b7f5828b867d887985b9d8dd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f0e4c746065487658e86d780dd5b10d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 751a28d6803b019ea2eb6942b93a368d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b310fea12c1ead64d4f76bccc8062be7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7dc400a3d5b61683803d18539d1b86f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 04c66959bd33a517f917f2fd6088df9c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68621b7480b0b1d827811d27dfe0d7f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48dd04afae3dde83a799c08000268528: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c96f1f01e5b99c52b356ff88c658ead8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 296877ddc2d2c4765284b592084539f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a64eff0a03b721612973d76d16220dc7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1b40e4de50600c102fff38e1297ab223: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aec20847e134123e88987984b4690582: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0a287e9b424eb8a3b0726e0755b5b0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 51656312b428739b522bfd581bb69658: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b28ce423510ad7683425f28457d4113: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc70a2244e400a947355a7e05a15e440: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81fe49cf76d3a1f6843973497ad448df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8a83b724c96d0ae17b09d57ab0b2518: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bae30faab11f9632535bfbfd5efc1395: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 719d586dc02e789a71a681f17d69c131: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8b10b33b5dd5f2a0125b48b63a5cfeaa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7daee229115c882efb01579b0a52b339: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e323a4bf1ade275b3649b68698b34a07: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc4dd5d3f7c30e0859b212b40cedacaa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23b39fe1e77f57294acb1dfd5421f46b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d5786f522b0cbc52e48d63b0226f4e1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef0bceb0a3a271a716729ab3a46b19ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 690ec5859062379a69f8471b435e2e46: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10c29c60fa072637156fe124cdead3ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a3c60586c27c47243259cd548fb6897f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43c09adb3e04e7e52856eac3aec65be3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 13a39c2f2214c64177e62289ab007c5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b75ba5d03a86a043009b4618efb5a2b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar de4ce110c34abc862cb970e44e4595a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc1ebe8c9f59d521521e5568131efdab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51f4f74459662a736cb863044013b2db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11c02f01cde0f8b01099105f4d8f98ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b8179fb53672fe27647b84e41abe062d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68e1b21ddb884c1b05e2143a82b5c616: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 95044c6f929292ef8e2897b8b6aadf8c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5290a0db0dd267fc66049dd80606352e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 29e1be02b7dfe60e79186a2ee67ae17d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70a47cf07dc95f767312c58bd5d6776f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1d690b512524bf3c350fa7a00b58d034: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 47d149a1406f292e722ffba7f7561374: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f64a34d11baf790877d2df625f0b55c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a6dede6ef44f55f88df82e1ee08b510: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0e40d67e8d5e216dbb9308bbd518372: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1764af7b005fb97b510b714edee338d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8d9c21e9b74013b8ee7d8043d93ac8c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9c372a944e1537aaeec469dd74173d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ca7799f0f03d5f306966aeb9e1b024d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2bbd029d5213e9f1f4e79d2352100d93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 29164eb54cc3d1b0ccee6229fe81d54a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ca9bda5dd61b3242de15085681c4201: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4044775ecaf24bad50de8b094fad1684: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f7e49a945bfaac99a9d251d102dc4bd9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5eb31b317f99a754c394d577a6b486fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aea1e117a80f0b7c18c339372bb2acc1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3124ec5aefe933800b14a1e6caeb3c07: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f3cc6c455f158d4b63faba9c0fda156: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 585ce4b3104e89e4ae909471fd5136ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1b96d2e1f7a641e05614faa54cc9890: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23fe711eaeca339f63b0495724b20144: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0fdcbe027b68a6b68a255d459594b2c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35cd597c7ac160ccf83a735d656dd2eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52fea1c603bced45f9b4e263fc8f3ac4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 08a339fd1e6da3ee76df5255718a8041: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2c4fa87d21e94bc98d08fc0509c28636: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 096453864740efe64e671afa390b74ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf4b61cceb1e66c72ff8bc1c7e0686b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 72e237e91f1e64f99e019d292cce75c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8db2639ce98ac3d63226440effd0daf7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b2ce9ae1f7f058f12b0839c466e31428: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6d704d5b3233238ad0669b5f74fdbbd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d3b505ae1f7c9c4e4860c4e612ba18fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 66521b9c4a006057c432c09671575678: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 822cd28371fc1e6f982e457edfeb313b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a2557b28a8fe8617be64d7a93bc6d58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ec1694b5b225d5dad97f8aa224aee3fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 94d56a283517332a393c735040114026: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 08485debb82bee15ed7c635f96da062a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 819575351f583820405b658d07e38944: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0699a03de96ffb073374c8956582724: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51dfb5a295d1b0e6654dc056e05fc36b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7eebd8dceb768ad74e1ac8a4717dc424: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b485136536b8980efb2276c968b7eaf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fedefc7545add854033872176e954981: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e00109b8895310e193a506421f88fe8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa3c73cf6f208c0d989098268bce0904: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ae58fb1894ca6dde21bf82430b0cbd6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32e6c4b55568a869c9e01f731f67dbc5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07a47a107030ebeae821498af50c68f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57accf22548b959cbb3440e25bc6a612: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a422eaa35a9b590ed9ff7dec271424b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4625c0db9799b181fdefdccceddf1e45: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 11a077b49b09191eb168871ba4b17e41: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6d170c3d404d506b4aa292ba093a9ee3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89fbbd1fa42f43c8c306964e81cb8497: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7aa8254195347663f23245c7e9340aa2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c26f893836191aa207c1cf93aa68ae34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1ee41d152d6cc55b879bccbbf9441cac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0da11f0da71d0c3c6fe5530b17082313: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b290763d04640a8033a53de12204f21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e913d084d38e869134efbb50a6e5f9b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d54e5b80db853abc7c3e50441631493: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d200d474eab37c90fad256b577d61060: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c8b0ee61309dcf15984234c782c60746: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82adb6e48afef604282ba43a71e5e281: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41e67fe934e76812b88019a36a067730: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f0a89f8855e1deb3dfe6855f28d0fb0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19607fa0f64385947959e32146d35775: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 29b46eb6590874dad277def5ee6f0055: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc20f307a7bccf664ff2e6eed250768d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d98b12898762611e5d5dd6f1439ed44a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 118785ffd31395e17a41bd0f16846589: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 336d5dcd5f16b082ec8a71c7a2dbabc8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64f8dec26f41ecb02e87191dcf6e8722: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4ba05e609ab14ef73d872c6a48575199: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e1af9a6162c408460c76cfd7f4ce991c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2d99e36f62f935375ada4dfe5ae8665: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78a6a0f908b54972716fe1a2566b420a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6fa327236fc40c39615db0f72b45f84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9198c646edbec53dfbe05e33d46bd5b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0183f8bff6a9f545b4c331e6b90b469d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 370ef04cd83cfb716fed8da7b70c344c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4423f459c87434ccf65cd6c1238c011: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 254c0654cb1200ed3a67fb91b56f2cc1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2c5efb969f038f44b7987e53c8f8c7d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 328aba46be22658801c5ece8c649c1dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 00d3df942790c576c67b4b8f21dcf7ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25c3b1ce8fb7477019429abc2ff54de3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 069c8685660ab7a57dffc9408970c5a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 61a2b79db6b111eb655c6e11b724909d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64956792ebddd2d7ea618a33e016dded: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4322a44ef35fafaf358ee5720b34ecc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ab180b380fb3bd0ab265a9a9728d8c6e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5209a30b8a899bdb482f3995364af800: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2904a772da1adf6d9949aafcfe45132: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b38a6142c30989ea0fc570ebc8d1dd2d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d385dd21a6cc7013ab4553a695d8a7cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 61ead95584a3a3972764d8db5d4eabd8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4bc43dc10e54c4c738ef65c85fad964b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 973f2fa1bbebe4b14277275b26c27ada: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 313894d300b85934cb73664949ae9155: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 400f0d3c5fa9f37ea1c5d71207d35eb5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c468ec0d893704cb83f14a742f92a848: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4eec16acd672f85b07821a78f0f60ee8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2e69673bb01deb9a3e4dc67d20eaf9b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ba2aa1b4d5d6f5457a7ad895fe8ecf9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a703205ecb492f4ca3b0861b33911f3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c26f0ebf78dc1956c0d3e7ddec72f36: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0045423df4f6d9e9c80050bcdb57c26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec47a10f531269c70b4a8b1aaeffcca5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 79cc07b40a639d0f8895e9ede30393ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bd7ed5f7be267daf6ad73d88b072a40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae39d32126dd4303c8d5987140091724: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 74c405221ae215bc81bdc11f078ab7ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d70fc77b185698cd974b4ef8173208fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc4ea8cb82c434fffa95a29cce89d4f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fe8b02a11c52ca34742aa7a70ca51ebf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d0f842aa160fb95384cf5df2d4f5f51: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a9ecadd0ac7b89eadb43c9e67c00d61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 641fd064891c5ed9045ffeff6df566ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae93f5ba42f9926a65ddca5dd8da0dc0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1450a661531b6a02333e8b02de25a3ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 060fbe2f02b6344a0e107a5253dcf5b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0a42b0c9ce56ab32e2e28f471f2d79a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eca085765da7afc0cb81ae2573a481c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4bda75fb330f8b7f670f40d203e0a38: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d7535227bfe8ee4824a32119e826b7e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cd45fa21ff73d2ffa6f79443f18d596f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 893e7596e6b94e834e24978d69d602cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67aed4f2c96eb389c328d144499f367c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e5ec8ca9acd904951edc1bc19588d80: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa6eeafcf09ce0b6058f5e72ba9ddbf3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f8693f14a61be9894c78c8cd49770949: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f89da96bf1563afb2b66259e8ff9d92: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7017f63169e1a6270a71071fa2a78574: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6cf20fbed08844e36e568231aad2b5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96e03aef13378470f4ad4901953b9b55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ccdeb6271dfdc75e249c7c70f2b8a16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 29359cae9e87ef471193091ff328474c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f7e13582ecdd90066c24154b1419e28: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ea09c005c61964075bf4074cc3ece5d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0713753f23606bef0f578a184da2da9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d862cf7c5714bd16ab9e8aac2ad7a999: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 780f49b7d90211ed2e548e9f69cbe3f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2818ef173c9d05274b4533a78b31be1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar be843d47fcb6aa755846c503a8f1b2c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c427d46a8b19628c9035935421a12b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2430515c7e5242579bc8650a79467929: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 905de12732b8f8ec3f14b2f62e8b58c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ab4906915d5c4c0cd4849b0e898f36d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cd0da5aadb36b445443db7e28bb515ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0a64a5db06b03b52a4c3f4e10edb34a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c77e1173621ada0ab35b586fd2fd68f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac9f9299ffbfbcdaa2fe302197cd2eb9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f6dd424d01458b6a6c217b8893861ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 62c82e26bf95b6ba8780a896e537d058: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4f4f4e01224ea3a4d987d2b229b32358: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2741506192d2a72c1f7230e0fdddd93a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 55787143230e4db27ab5a55f62addff7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar abc9091cd29408ba35b8fc8eaa5fe400: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 392ebe25ed9a89f90c8f552e6cf1014d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93867fe0492363bc85ca52fdf8621e9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d002dff3b05ef03d9d5b4f2b3c096cbd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 71802a4d16005ef21744c98fb8692737: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f31576e8788736cc9cea753a99d0c73e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af102bbd824cc73caac5ac33c449c407: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ba8925030d9ad6250e977c8426791e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81dd73f1cf172875c16cfa8267e05281: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8a030969af3ec242a899252d4e18dd0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc898feb8b42854f95f46bae694d3937: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dabef3726bd8730ed876ad05c21564ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 666121e3323b896a08d4fdb7ed3e51df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0a10864b2cdb01ce423a52ed65c21a87: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dab1e003bf3185b0652a367860cd52a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7d287e19c4534cbfa58433db52618c4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86d378542ff8173d90c31e74c08bf795: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33c5dd318cc450329ebb7da4e0cef667: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00f6ab2c28abc00635638de237bcc762: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78be761c57c1ba9056fa70a84cead66a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 68ef7f7f3f3886c0358592d90da55340: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 898a718e019402d899d694048f0e95e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33f3f11d3077a5e5e89129783f13fcd7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84f42d220e57ecd4febfb0d376f3b1c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c98e97529252c3a8e461e0589f41d65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2d150d6cc734475a6efe5fcd27e29d84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23539dd352605903805194edc33946a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 879809d6c2182d99bcee2a8bd3153177: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ceac8bc99f65f4fcd74b485f3797d56: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 34df66979a418f12ecd4da5f68cb0629: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98b40f6f4f58038953aaa8bf64c9e2f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cb531578746e49fc04e01bf4d56ab303: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 256d45dff91a78e1e92765d6fa7a9d52: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 378c19e28ac68435c71277a7c8e5c247: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ae5186697f81c890bf2c7972c6ae473: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b3b28016f8719cdcb783d06c985a6b59: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58be183ebfc9d396261ca93954448a48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5c69a46ed83e7bf582d112ed9258ed0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67cce4e4593088dfa7798a1af2af01f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e311faf275d82b421412bd92fa4dc1f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51a789543fe80164c51f4f184ca967e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b66704d07c8b5122f91658934fc8ce5e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 030dd023076f17983fa5f3dc4c3edd90: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0a30edbebc5a0eace0bb753d3ec0ed2d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b6d04d5c299336a09810ba435caca908: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e217f1f6c6d18100016d82b744f7ad49: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64844eff79bcd953e908f53df3c4bfb7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 42ea982884b0ba1aabc608199081fe08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1cb47aa5415a499caf257d0b11feecf0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9ff34e1b5a96c360236a3eb8e544e0b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ded5def73a311dac0db588c5c331e26e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar afe2811d63fa294b267a94caac3b1c3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b27e17e842aebe2712ad6a0ce1714a90: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b93f4aa4b40ca1a6585ffbeac30fd90c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f4b1bdac87b01cb585ab9398d4a7da4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d0d3e6332e60765167d35bc2e559a5ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 259dcb90d69e804ed7c9ae434a7f9451: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 054b4a547c9489456d76aad26c1b01f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9be1ae05f20e4187e42e807ff8d4ff3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ab33609271bd34b6cfa78eba129d875: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11c26c5e79385c69a804bb52bf8d1c16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5c6c0aba97896e4d3f14fc431db92370: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52e02e88e20bbe86816683141ef885fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c32cf9ecfde2ef156394202bd2c0e620: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc3a2c3fe005cf225105ac7408eb025d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0abb263b6797addc4c99dde72519c40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 26f880c7d0bd0c69ec2c7667297f524c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07db7ab2e9c8b0931f8de9e7bb11fa9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 688db7886f6dbc8b3897cc1b9af2ce37: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfaf842685392e76d170bdc0dae94023: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cec2eb898d48528677ec66ff461d7414: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3943f39787cb1835ccc3bde8d95c1b33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 517505d9d5484642764688866e95b12b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1441b72e418c3737963c70d976e49426: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83fcba3b5dd1590ae7e3e08b0de694f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 659643547c876d43390e2fd42acaf608: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1cbee7a5807f75d4cd46c6f54af29a4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 671cc2115860756ad00c06c8d9b80599: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68a5e7526eaee6bf1a18233a188a4428: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f681c7ccbfe5c330ebe3daf140bf5507: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 42c5f0cc4dd4a6e64727ed1e45ab2af7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d2f3afcffe8d77ad49af183e63330891: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01c89200d8aaebd7981ef66131654725: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e12813dfefd6a3f811fcfc66b1e6a3ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6d77cd5141945a1d8b4b7ef34482bbe0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a8f12bd038dc047d1e264ae9ade8509b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6e62b4129328aa9ead655e42a4dd4498: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 81fafe909629db985b3b425de6a1d986: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc479c41b7b2247088eca9ad120bc573: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0bf3a070103141c9587e4db359744c65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a37ba2009dbdde7091d19641b96b8e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb3afca4baf8cd1fb6d76ff6c95e8d2d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 446b41986f6490903ffdbc8bc7153a5e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5bd413cefdfe4911365d170a1517fdad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 624959f9914b7edfda592d8f6dfe6d08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4d0c2e6dcfe16177e5ee8f94cee8680: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cf994ec50eb798d0f6055788da958881: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6205f51187efcd0d7129e0826effb996: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d1716f5e8cbb2e13b5153b2ab1c5e479: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 13db8d9336b380a877591e18f5f6f132: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f8b3dbec5a2ae5cebd8b7f2f68e6e35: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0186974b0e0400013ae7dcd21f9e0b7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f9fe9cb556b4caa3b34a56c442c6c885: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4629c39690edd50253f9c3ca26b26f4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f0c28c71a09695086827cd398beb915: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e37c6e634aca711db7e6dfbe4fc3580b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37e544b65501c10d2fbdffb8a7483f9a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7fa71f538acbab7bc6df77bf7bfd9a73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51b806b3a4fa068951614d3251c8c28a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 666f588942deb45c9695a84cc869c8e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53bfd3acd9891071a811f6524052792a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a74a08f42d4537837cce25139c2777c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f02f01338c98a3b9d0edb466a49bf21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36c7eba34a59c3017424b65444efeca4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5703cdd4a781eda149ba0bc910974b42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd339f579227dbdb8892b63ebc0079b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6a7eb8200395fb75b0ec9b83b16a4d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e8ecf8fa468be9b866cbe7f67b8494e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06bbfe02bd40abf7f97e566979c94414: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2d0c27e63075047c2ced824f151d9cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4351899da1be0d4e3aa6422b80b5a0bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dff9ca5056018ee677590c3d9ff8d0ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3099b1d9572aa19107598fd6c7442de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ded63c2bc540022f3e334b007a4a7f6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 30762e2b60a42d0b745fcca9edd06238: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0459282f0e6c8a0ee9a4ef78f158ba88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 62ecb36c6f297d912ce5b2daf8b87858: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc649e0869a9e6053b8acce801c26438: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6406a5d50c768c293232f1d8b989d4e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9a8d70df4c142313f59d999c9919dd3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fe0d388a4cc21997e943247efbaf6c02: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6ce27739615af1297357a14a2d08606: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86ba840d3996af04ad775b7e74ae3210: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dde0c748472160ccb509382172402ada: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 708ef4851d664c283ed3d36a83d6c270: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9e2d05c50e4c00a42c5c53cad7137afd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b74248502f445a311eb96afa02c5aecf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cce549fb805bb7f1b42323881d12fe32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05527b7efba87059cd2c9018641de06d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68f6cbbb8c7fdfff52feff519a6326b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d53d94ece462ab18705b20b1e4975d1b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 61a7a4231f2ce93e8ab0b4d9780510ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53569247f4304b0467b9e78ebbc90fab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4f998767870f60d0c29756822a132db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20a3a6bbfd6f1e9f69be608dc5fe2cbc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ad6f8c8967908c9c20672622ceee89c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 518d720058afbdf5c3e15967bfd7fff3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4b79e0fdaa1a559c0481f816dd3def69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 823a7bf90bc4991ea69224475c4fc455: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a643b105c7aff290f147d0c89d6c53da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49cf07fe5dbabb7c4f19fe8195eb11f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 495eeef5e3e1520d02d3059937b86921: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53379dff7decaacd55a6a184fde3eb56: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0e473d1936161081fb4c391b72ffa887: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7d83810afb66a3070b9f55d41be61de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a4a787112bceb7f88e73d7bb9736951: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8a51098ed5f67a06cc00f3f31932102: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfef6cddf6ee3f5347231dc602901bdc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81b228a775c6ff09b7e3e487affb6de7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e27b45123afd734775b171b125680686: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d34686925d51e6de7b17a362adbb82b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 883fa78a7056c9b3cf4dc101fd19e111: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ad77d3b4813c2589e444b12e75c6cc1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7ff621614435074050418271fa3e786: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b02cb2e226e5a7b0bbfa59bf22528c23: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4d0d4c89f35b69898d2d6129789eceb2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dff1b5a03d116f4ba55ab6eddb6b058b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8787f293657d19df0b67702a068f99a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6652b4c8a5b2d46f625c9493c6af8d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fa8045aa29778ef1a0d64149b0f8215: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef89d619bad78514bd26f2d04e3b2975: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a1d07ae833f918fa6fd60f3fbd463052: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 30b2d006a48f9a3df62eee81e614edc8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37425b01726d1faff5cc14e90a7e2ca0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 79a925b2c76769157b09fefcd6a67066: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 91ef89157f5debd1b8552efe360d9c39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9be5beac2f4ffd652d3d3b67be69bada: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c009cc31299024fffa2cdaac71c83c6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09bf9bb038831d10620b00f4e252c703: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0e85f4caecbb7faf41245bdeeeb6b56b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 002f9a5b144239abc71c9a5d55a11258: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bfc6384dceb1f00815584de43cda193: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7a79862d5593cf36ba13bec762a906e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 020a7a082c7e73b767c241b363174551: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a79d817d3c3aadfeb791495a54789235: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35b7d7f95615031bd5cd1c0aea483060: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 849d1a65f723df3cb502503b00d30dce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f68fd9a8d0a5cf8d4675518dc522c42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f983b7f141e2ff6fed43a8513c48fd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 18b6ab886c792e9f4ee0789afd5a8767: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cf51368989f4dfc86730a16968e0300: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6d3e1a1cc210e7c8c9d50d62fb293f8d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1d9759f3fb8b63b7f1ada2e3fdd031e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cd802e93253e242c52e29817c7dad208: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c8ef116329c5f7a31f1f9edbb1b47562: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 55f56158c97ec9a76e7eb96eb36856c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d654d7b50376e095c0ee8929f1a57d22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a25847f04638bfe280a2fc933f1b104f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f4899d2ffbdf0da9e7ccc7150732f14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0082b021a60562f9afaafa98fb9154cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b8abeb72bb55a72612e9e59a9a864b14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e03fce6a7a974038bb0698f6d58970a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c93523efd0c419aba0fcb63ba5d122dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 067a58ab275c6828dcf98bd03a366d3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a76da4e88ba06554ecdb9b4649f014f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb91a978b20c8767b946ac96ac7c28dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ae4135b68f61980ee62e424885ec47fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ab8dff155c3577832fe89f87babe97f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f956ebfc509d9c14b8fb7657119b605a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc1d5e4f4a560e9c6e03553f02b3e4b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ba1ad0932c85335f71057f3feea0817: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fef6925df2f72a34a7659d75fc0a64d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0b76882822ae440da4bc2999d48d6512: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2330b498137c3fd510afaa0c631e518a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 33383e2b977a1d4c1f2fb4105fb41377: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4455bf1c79fae8ba208ab9287e51e515: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 051a59e45c2b0a4651db39af9bb8f7ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fc5991a5d65aae1f9a86dd3e05e161e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d59750d11155b0446c1a0fe9229bc44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 90dcffa6ea4c1ae58bcb2457152619e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 494c5d17462887492225e4816b015b11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0bb15fc3968c5aceab946a812ee2cb77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 201abfa38812eef1b0297147a4fc394a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9846dd527048c104cbe9ba03a6101b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6443a5473141e1f8a7c15fff4e5108ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2b34eb3118a1862467eed1fa02d89971: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ebbff5f95420da721f43bdf30c0629d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4bf20ae385c11793e446dd17b9b7f81: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9cb9dce42194bbedf60080937dad0e52: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 860a17dfe8ff1cf6b8591c5d723033a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 977664fb787bc54aaf7564990fb952ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d0df9d6d129d90ceb94b9d3013650cd1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 61355da3c4e444d0f5d29b483c63920f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e61a49f61971be0c53e4b461c0abeae2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fffa53d268d41964ee215e85517acb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1e12a74bd291168c9c73525cc667183: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a52d0d08814922a4c230838c0f46dd1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3e32be68bf1433c66a492d5cf1b9cefa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00fbf5934424248ac9dd04b44538ef77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3df3806803ba41327e5092e66bc517fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d983007b1d797c47b3a79c2458c46b3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar deefd3616dbdd571db64bc82375dc06e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0fc1ed15f2cf5a1226a3a5cd7af19b2c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6649266ad86fc1d11f8a35c581a1078d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96e972c5bc91340a113d77f75cfb0179: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f5a3f0c62aa4bea30e116be9d3ac3d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ef83d6263f12a1c5067a9a026349201: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9281d648afa0382d521c7fa84068e298: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b46aa09ea13eab3dc5d2ff10794adc88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d30d864cda09602089b77b9b2ea9d880: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37a28d00a5f5bfa45d9dd61f49125cb5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b550a6992f76d0ca6a03699507a4101: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed96ac81f1030ce0e6bd5938fb3d30f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6e2734ee06ad9662dc62011ed65b2f8e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e36795f7deb60f81ca7e726c7acc340a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1e9ae3f8346ac88929f7e40ae979ce8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 29a4a640c298f4ed03929b72a67ccd37: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd20af43a9f50f1c8995a318be9b2eb9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dcf0225589b9aa269a8e00f1a906780a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a612653d65576320fb9109fe578b74f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c957bebbf38c5df7ea262a57f38fdb7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4031e6484be7c4be0fff24d0578da456: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83eee7fdfe995eca1977cb9db6a33baf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3739a0cd3c5cde9268a01eb66c50ee1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c34f791d583bfdbb23c72bf238aa7613: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ccfb12771482f99a0c1d8320ba5fdbaa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b218f5a4ae80da6234d5968c3dc281cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02ff651b74737e21f5ee8638d7e77347: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86f78857bb2a72ddebe001b486ce505c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3935f21dffed1ae070604275f53f5d62: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 202d4e9ea5e1fbb80bd25d34ec2e717f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20a6ae0e84ce1e0d94845dcb0ae04365: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4617b14b6d09eda3f9154a0d1125276a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 72197bb96bb5dbb45ce4e37731d26712: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb64c73034894ea83dc2197126d38208: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa7b575ac8aacca5ab75dbf61b5c57fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 61339e767d0674862e90b15790e9f383: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1a8bd423d33b671a505d69163f6da1b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39888d694824c6e6da4ef687173f78af: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b85211a1e047a02c4076ca03ea5b3daf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ca0efbe7cc35ab5e0a151124c9e75dfc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ffe7af9bf8abbf751b01bcd8be1ef963: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 957a9521549e5c63688a4c92a1edeffe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84e16fbb4426635905606288b8878213: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 75e4ca0aaec0e245627f7da9a52a8dee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a51e8f61e2002803f488d0e41b05a680: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 90be4ae25268a94d939e582bb6d9a5ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ad85a910384a19090366c9d340b7d73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 62ac8b7a8c4e4809c2fbda363d4db167: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a3031703c61530355722d953b6c13f7a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5dd83232c9a9c18f5f7207e8c81a6bd7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fda0f4df5c24cb43f1870dd9036be25a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36b3fb4465a94b19b85e84adb53c8fcb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31c69624f0e955fa849237257409e399: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 919c0458bb74e50b60baef8670df9dad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2a83c6c19d9e5c8b5237d67a4a6486e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76c3c77a59da827e6de68aae3143911e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d5fefbf3b45fc49314bab93e63238ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c292af3d34bb6b8d0568fba529ae8b94: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed72b98436b8dcc712a693b12a76a9f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc5051823dbaae211489220bd610fc9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b3ecf2054724a98209a26d1fa8fe7096: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc0a7ef932cf2a20b751954592df6796: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e99ae9eda640cfe6b1a74e7aaff0a539: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ad599a9f520c0ba3efd188312259029: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c6dbaf634709fd3a042f3d365cc93f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ad9f9ecb3426437aae9c649b6a216867: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 90429e95f17567efa4b7c38f273639f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 931b1e25d3df944751023005b0a8d166: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c755678340acfe36d3f4f8a768eb806: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9935f2954e1bd82a300942448eb3e7ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9bcc5afb5e4ce0c0b3a9d4397d691d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 14e8b43ca9d8208d9fdac224b05c942d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3b90b88e286324fff3d9b53c4ddd1be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e6d68c3d8a0bebf661bc7f4ba9f77b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b97e925a964fc51536c28bcec11ac16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ba6d2eb24634ffaaf82f7ecb9d1f958: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f7327c087b0cfafe80f367234ad0fb0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2efcadf65d3e5b6ced719313fa2f2202: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f09acccb0ed8172c56eaabfd8392684: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a67d2c788223a6da8bac6550a0c2ef63: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83a31c447ae1a285307708f1c6d36565: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e36759170ff8fb8bb091f62242fafc21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0e92de6f2ec6fd4e42fb7a9f625d7fbf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f51cb8e6ac0137dc0832304608b845ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 361b97a3e26d2c329ef30174b87a88c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a5ceb315bdb7a1f9063db1d3eef4b84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bbd0e67cf13542acd92d1d9d3021990a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cb35f65b4e0d6c5994684bd33ee6e37a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0681dd83a2edaaf7e7725defe63f631: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96c736774e42c7cc2738df724507c950: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c004935e6cba5258908b03a54aa5502: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7755e619269ed897b7969bceae4ec74: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar df0986742740af9c78484fa48c1ef896: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1e0ba676bcd131e662d651b3296e51e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 858e277ca1046146be552a8431d182e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6573cd4f612ec9ba8536b41f98b4ab00: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1554e9fd26a5f1eda3f0d3d651b9ad26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e547bf7313aed80dcb3e1ef3cb2a374: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc3ae9ad3aa7d4bb540c5413aa5671c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b6272eceeeb30ddfd9c509df08cd6a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 203abffddd805cb6a6771fe974b1afe9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 179967f959539b5a05e38bc0ecb10472: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a527b27da5c221407cbcdef0c3a3598: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cdc05652ad692b348e016a7e496c563a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6d87f9dbc0e485966c2e70e80930fc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 525079eff766816540617dea580680f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1b4d082f3134aef56529cfaa140d6feb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d0fef2787ab855fa9b07ac65f98a49b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b6f59b11a14d9b6fb8bf1afc8ee178f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b572e862f6b3f6cbec5a94eeb293d82c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a02ee4636357a89254cfcd499f6588e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 897214c3c9abcc1bd6bbd51eb6ff93f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4aa9fdc26512f8e82e731af9bcb993fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0d9cae4e3f492be0663ceace97eb0a32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bc9ec259e7c0a05e276fc64530c81c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f3763af10849778e2ff0b4f72a36b47: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 657d4d517e20b2317e3c57442b60f229: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35a29e664eba107c24373fbc6f3f52ec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 569263f0649c6d7cd6771444a3cdd3d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4b93028fe90715bdf63f2a6d2cce0e6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c7b3191df8a66d5785769c2ef059513: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1e16e73a500f127a711becc83d7113a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c00ef856accd35ea6a40211b3f72c383: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7737884f24beaa697abd22f9505deaa4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f1b771427504d1156b0558517fa6922: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 36783af256cbe621bf4291d067046068: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 608ff11c6353df87e94c776e8964f777: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9b44bdda8f8a24c8c4e8120834674a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d64c2f64c832913947445881bb1def9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82c363202870722f474d84b78557c4a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e63931882118959c4360119218ea2f70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar df68d7ec7f24ef09a804af0cf11aa6dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 03b227efc2489e1b939dbeb71708067b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfd73d0b54f36d4bf85fdf2554a62154: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7fab274331d6b0672ea00249903e5aa6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 400558ad9f693ef2e21fe8cc5c483d0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9db2cfabc4ac009a98f6bd2cb5459740: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a8f853de8bfe648c7991e53b379e8105: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b34430718c7b531eccc9b918c62515a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd8eb8d9df8212f0e7f9a5b9de89a2bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a56ba92c53e4c5e0d1f993af53232da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23503985bbc38e57f06cdff083c307d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ceacbeefc80836c09e11e029c9b9408: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 94025f4ef9f180813a3cfec4898c5f04: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8859b6af683350fd57fa9a136c76c714: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f9045488a4daf92739bfce1ce08e717: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f362657c2c1a6b0414e5de743445b0c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b2f5377c631df6e00afbb23ea015372d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b22cbbfbd1f4d28568246e2f773c9db1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 62b78545f235c6fc1477f466a670a843: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d5b34865a2a628b1225f5758eb91eef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6342d577be430e9fd1c1567ca980d82f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48d113eafaa6e3a2a431fcf89fda76e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1f582a862c379c952aacbdb27f2620e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1eaca689a18c3214ae1f400e0083d6eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1a0584b10af0fb2068a2f032ec1a4bc3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5924448f38550af83e731778b5614db2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5749032bad5510bceb18dd29482e1973: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70250132e4fe1b879acd00703f896951: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2fe5dd67480da99905888f0b8d4f7385: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4011f3eb6b3886b187d49aba59e16a4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c9d447602c396493ecbbd78a107fed6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cde2d18dfe3c211ccb3c0f855d7acc8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81284d4665fa4f4da884ac087805d11a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39e1e7d7cb6b27a80e85d3ac3b21e4a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 46497fe6da87e782faaa0b6f35ac64b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b497502f8d1c0a44ecff06e03c563793: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c46419c5dffe589aceaf93bf5872283: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2256cf581b13b079900350996dad2c97: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11ad328fc8406864b6193296371e9e80: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7c8b09331ac666cc6c05ef14923810c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9fb941c67e0106435cd799b7db432ef3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b742d4562b3b7e029990f71ee63c95e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf4764c75f61e154e7223ab1316031fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4bb64a0de63c0124263f7f699e863dcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e65c898afe6b05590285983853067b05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4376e0c9c1ef2904f78edcf9b398029: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2a04cd37a1ccbc398603c12fa8a9d03: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f65956c02c4c82380b882ceb5351fd90: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff12f6818f4c5b14ee68cf4eece04a0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c27ca9d1ee7a65ee8cad1ddbfad78505: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9271b299907b5a30f65ead64eebedc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e5982c1bb135b3c7cb4405eacaefcdeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33cd75f53a88929433c671e51e7c09a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0930c00a3a459554105b918453c17e05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 191621cf35a2901d4314d22d5eb14b19: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8f16c5ef28057480b6390c45b5b25b4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0049908cf928197a5d3bd720ddc22e4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f79323f22d69057a4bf2ee5020931237: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e37d91fda637ce643cf6fc7dd513e5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01af96ee82a887065a8cf8ddb078ca53: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f53b676ecd4b26b3094e482dfc1b542c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8dfafd09c43aeff94a58348a9bc559b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 717fd499d90e0970eaa133631c41bb42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 75f4742d26e55e3502270bf56de57f57: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3a35dae721ece7568df45f019b0e554a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bbe574096d5b9550047e0b64bff7ef1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5460587b6b83e4c63ab985d96d39396: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bfc678a2b6a515cc2583b53ff39d30be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7ea6d7dbf3afa9852e14f7c900a52f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 582c5517920ad92238ca631c3ea9df58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82450b799cf4b2755c92b927408597e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b0e4c8a1e84134e66f4128877bcfb63: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 14d905b031c61c5339942cc2d3616977: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f6ae85fe0b3ed10fcbfb9dce2d1b6543: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d066083db21fb0d71fb9d56e9aececc8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b83484f5e364e6a965ff8e346940db9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57fea846daa0c6e30cb2be4398ba9ecb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78b58bd946294e7900cea3775bbff70a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9261d650836f447f5a5fd621eca368cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a2939d38414d25926e53246587bd0c36: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5ca91ea0201997ff927a45c2136e9db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a568dad7a6bda6368625e53379e3d6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1bc690f802cfefc39d7852a8b1d7d3e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52590064527559b4519078da6f8cd4fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1738ffd735c7a0c9c6f4dca5ecb17955: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cd39faec9a67ef5ea7b41d876cf20851: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a37da95958d712f16444774edf9a10d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b96d96453b9192ff83418340ded7cab7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e1ce892a6161518e3179bc7ff7d5a89: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98d99c794022e20423f79fb2a5afdbc4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cf6ad5ff0d56119f800742938f103d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a6351f4a9493afda5b7cd365b04547ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar afe12e7640c8bc8e64b9da9a9eaa2882: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 73fb0470c5365ed63b8b9870d5d79514: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 196f8527a5064c26a21f391d289d8b5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d5b62d23e2b47c3aab05ea15cca9fa5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd9d77dd72183d164643e48f73ca1c07: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e0b7b89bc0063a304457467358b19ff5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1bb309d6adf6bb573a5c7ae9305aa0a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 434cffc8eac34fea013f4f95234efc69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ec51259f426438cb286f25e42d7ef2a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3c90c600f2a86ef08f2e1eeadbb4d70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c2ac82059d1bcf0801cdfb93817c6ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c91cd4ddf181692da6645a794e580700: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 705fe92ee103ceed23943591e74f5ba6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce7207c92cb0986ab9c80d66cea733ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0aae7985f60d8144d39c5451030c2783: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23e2dfa8fd3ef34656f818d7b4a6593f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfbd9ee9cd787aaf8706a2ae9010baa6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f007e08a9d31ab4199b2d463a8c9e8d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c0c86fcfeaa956c8ff49ed1a3a9f650: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 63728a4dc5062987bb10464f560d7c09: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a93f8ac8689f80f4dc24dcd6909d5a69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6cb8555184cb457124ab43512f8c2669: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eaecaf0c0d068f7b8cb0d15e1958dbe0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 66a15578822fcc175e6e2abb5f053690: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed6414926ad96a8510cb9d9cd649c326: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e1616596a880133ad5fc3d443553eb81: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 680895db539f5d77e2496ac794c275e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d1863de7c2ab8d2f41dfdc8ac3739ab8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e099e2124309bb1a37e84d398434c32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar beddbcebea52ec730fa0e19667585757: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3a76c49ecf1ca0545f64f679768df67b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c5b56014ab72202446360104cc10793: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3019ef859f6a0032eb362a3ee2621f4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9cae1bcbc20964c9d6dc86d8e77b8853: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 857cb9e8f8eeb720716b8f2d5793afd2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60aa26083f7ef11319a06ef652b433e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0a822c3313ee025a2fd70881dceeed32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f0505c0a6c3a13f713570e27a749025: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4bb70311c55aed4240d973c5441e9005: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e58cc532cff747ff29b4961114649c81: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8029e1061578c01e81b68dc6c8a507c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 201e79b0a1393eb027be783a5f09d7e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e56fdfe7bef121eb55d7b7b26b0cb824: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6490d466ad8842ce514848a8a66aed3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 406daea8fd56c2c960e315c5f9a65033: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 62f0b6b34a4ad31d896a27c9c79a261f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 792285d775ecd3c45da2ba9d42ddc324: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20f9bc844b6c7c9ee2c717be6847c5d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8cf92fa0a6369b39269e807b1aa7c5fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e49537a0dd5be73decc70eccf41039cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21dfec9d2c216d96253cb1918b5518a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e8bffc235664b7bb933e0f9a945416f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b4544b9208246f01b9a5b2604ea1e4a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 95849cc68036c2c97cb27af942b6c87f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 55258c8dec93bc2eedd4ab762f5cb955: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9fb125a9dc54636e1b6a11516092afd5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 408187ba5dce70760bb59b3eb23abc46: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8d5926120289f2cc2457950a5e136646: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98538cf1ac84ab2189dbfb1a044daeb9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c848d1eae79372230d378f1edcee401: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e22f789a04488feb651ddd08df70df5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 329006f55370962d0797111099e052e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8557bc188f71c97968a71f6f755a9a51: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3593ae80b34c1d9f3c71729114af341f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 611b7dc80d59c908c9f9fe4626b7c594: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7630e774f07d8381571329becee035aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7255120fac5d6e880c0c1c06f89f66f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3fdc73eca649ee7cb7f892138a6e530d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dd1f65b855827d3184ba228cb0cef83e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 08cad8cf11b2c6afd9be16b6ef61192a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 331c8db4ed332334594442a11f6d3515: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5af67e270c151ebcdd25c65775f884ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar be98d316af53a0fe9d4f5f7062d32aad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51bfd48a29c64761c4eeeadfd5f316c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3cfc89115ee35ee5831aa3755361dc1e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8410933a7619eb2d58a0a47ccaa1c8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e73125b2a4cc033f6d36a8f8a6e64b21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1bde36a030916bd8a99d641df0b3e22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07bc20d9090c0f8d100a5320d3234900: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e2b86755f97e7ee721b36cfa89956172: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e324aba62795a246a7d154516eb2652a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc259b2669765f31674905202e587adc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d24cf0bee62a047e88a72fd9635eb76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8314079231167f2f836f635ea64e2299: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6d432e46cddf31fafcf241645b597e0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6318a69bb7de780a0c2ab2f0073d1087: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d6959a9347902f602f5f8566a1b7157f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8b9d93c42a35c8b7ec03d4bd83391a06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 881b0a9845d4452e58452eea53e5061a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f65465c805a4bf7b0197255b22150fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cd70bd9be7877dad4cbd3ae10d7d580a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28753510e0926fd9df48b9ef7272509b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4ca20b61336bc760d2c347556629717b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d36cf14f1229a1dff9531fb1a61dea47: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7fd0389ba2d962eac9e8e0d7924200a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8b773e2f42a236033cc91e015c247365: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cbe04368961d039c49ac64df4dc5d52d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2644e1bde57ec87170d825a91092e7e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15726c9cd010c99b90de69dc4093024e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c388f36fdf1da656d2ba359054740d92: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0e983d0e74686fac1964e553be62ce67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8106b4717f25ea14ebc7b095cce435f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ffeeabae7cc3800ce60b418fbbb36e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5eea0deb298c34925f377d93f92181c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7411ab6fe127aefecee6e374d8b788b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21530c37d5172b71c976dd6b8abba03d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a50dcde1e6fcc9f7e197c67599b06928: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d47f25297729f2f1add1300bc74154a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd3a6fb6de779144da5ea03b01d08890: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 40c791f212b31a9e0182deb7ca38f4f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 498aa64efe05b083ece2aeacf032991a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c3d222ffdb19db6084cffb6b06dd135: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7acc3407e5bc67a1cbca8ba19bfcb7ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b50c95131ee654e23b4409bfa0ae5411: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 322005f9cd82e54f3293759bbcc31163: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ba4746b9b30f8fa359fefed8a1bbe0ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7e8a27a36bb4af6add4c6c7a7abee99: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a8a7682140005b7909617cf01a017638: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2fa648cf5204751e8e6d54f1a76b9dec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89d983c5676a78cc0638c1cfbed7bc98: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6912eb8ab89adc73241f194a09c98bd2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 27359e6945544a3c0f643556cf970d72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e69eb21ac6cfd28f4e1dda3944982c2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cbec70f1feb61eb76c3d103881d8410: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b2f6ad2620c18594060a9b45a824218: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d75e58c97177235e8be95e2d2e89eb8c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar febea9592edf4a280e12a3c4f8ec65c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00590b5801f8269ebd17f28cc02fc7d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64f170a7d6dee41c914630ea65aeefe4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84a23948d1d530e00eb10bad9ccaa179: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar aa0257d6490049402d6ba0d5be789d11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7372e7f8d3abb3f559479760c9b1dc72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e70e1016e9ed6ceac6c8b072358f0cf4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 610c7e1fa212de86fc52ca4b284545f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 45600f62df6ce0ad7ed7432fa9d8755a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0c2a938567a964817c93185ac0dcc38: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b63c8e757931fc672861b8d64071f6dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a5577bc13e5d98aa658b7ce54bee01b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 714d64c8e685c039da70be981fe94b5d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f227e23dad7453a15999956bca3b41ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f97115981f16b19d2f4c68a5ac85de20: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ed9e4ff08e20ad535a858de3d5c52e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 35d8170c5c4c9de260ef8485cb3f3aa1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52af9b41019bc7f6f49d83bfa49edcc9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a28b10443232654c1bf66aec2435ad2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 886acd93a2a16fa4d10569028470148f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1256baa581dc037be864893c1d9048e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60c6a7818eb2690a3c6c2293bc1d1b3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5a64c648bca1bb53185b9251e20546bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93453d090881d4ed6a5f351715a2131f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2823baa37657e3bc83a316a1ff8d0706: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb743ffde07c46a790eba8c7ce00f9c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53c888c42e2e76fb42c345a8b7ebebfd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fd25a71176d8bd526ed1cc56fa74a8cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4748c3dfab98b6edf881b877f958f59d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 75a389d653c55890af10b670868b01a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0622a589d4240a42e68f516c65921f91: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69fdd0630ed48d9468ed854792939288: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9bdce5997f7e39fe38f19a79ed1e0adf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 894e5c9376e5fc0b216316d5d0920c66: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f15282e09e70090acb016e78f376cc9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a4752e2b7d9034f9eae63517fab3997: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25eca83203150d9dcfb076ed6c61d451: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ff4429ebfa569569737d330484b040d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 321f68a2195df0a3590024c25bbde315: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fadf31ecb29e7ab1ed388922d3666ab0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 08a90040fc0a77cd0e831d64de00fba3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 72f4256ce68a8512bd5de6ec9b688a8b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc03fd9326475a3a964b61d3f8d5712f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f6ef07b8d7ea53ba5aec41dd4f12c7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f01364686e3f05bac255cab5bb4f8530: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5a640ca17fc006227c3d31ca0cd9bbfd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8df7d4aac4dd22cc2c490914c9c587ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 819629f4aafa323b370355ea74ee353a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e7fdf20e2b9ee33efb5229260b939336: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9507636ed434a76584e76c40c037170c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d232b02fc7128e217ab98fbe49deeed5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 14c869a08c406793620b9e1f152fa4f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0aebf24ffabcf17bd857d74d8937d8cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 734964f3ffc9550f2adf9252faf7de9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a1ac6b8e77acd8cfb793de5c425ac58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c2689bbcb426361663f105fe498e410: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d3a042ebe3bf167208a1c0ddb63ce6a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aba17359a6a2fce80b54caa2188792b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 035ad6bf2f55ad555c218b254ef310be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65331c2dbfe821604626787615eaa9f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 34c646aeff15ac74fff52f7b7ed964b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 873a84810bc659a37aecc8e1f4ee375d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar de7bdfbb97d6f5c3af2532832764f08c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11f6a6a8e065e5887694afca1fbb657b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cf55f889e28069f9cf2dc63c774940a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d38f1fab0b7899e5577ece215d56227: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b3fc10636b86031c21e8431b5872fba1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7d4ceca7cfdbfcd40910e15be702f23: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5c3ff5bee76c61f5beb3d86ba038e7bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 009388876c76c56a74a34be24c6bf23e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8aeab4b37b701a0196c49c4d896199b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 22ca75b3f8a72da96e3a2d84159ae599: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9869f309b71a9aa2a05a103698f95dfb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a36aa2a47fefad58bcd34e8ca3ae4dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c872a389b24ad4c6fcd2e55713ffab16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28f4d698ca4eb9e0b21987e557208c0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84357658b93ed28f0248f0953fde3dcc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5decc2616bc80dd987365835bf064f88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c17c64c3de0d4bee0b1717885e6187b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15686961b0623a7ab2e06f1eb7104f76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f8f6bda9ea3a108529a138f543200a61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8750d22c89067dcc732d6c318c44de05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cbacb494ee684340c788dbbf18ac344: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b4e56526b8c51ef316d48a8680e36340: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82217f6e8ffd0b24a633da0e566301d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b306fd6c1869fe5100d0d30ab5ea9270: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e45306b753e014eba41b183c99de65e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 662332ce92aaaaaa453842a0138104b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39b6993e874d16af343a73fe452a73c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10be1ac700b45a7c12a033eae230ac65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ab56d1ee93137803bde067db9f4c0a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2018fdbd3793aa6a0e38ed15e8ad5997: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82b166572ae1bae842dd0bf5436bed64: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c23138cefad9bd167773240842b1b2a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4712b4039e01bfdd3b53ccd79f59caf6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07279960202d00d869e00ac2fb55c3cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 485c89b258f878819ff46dd0c4cf4a4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f3741b5f0f480bd3029f25c507304ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2e944c20cdf0429ef31671f6135f6a74: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc83ad3e2ea749026084636e9f82907a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4bc7e16a4e14978b979642edda1c266: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10f8a4ac20fdea83193656f6de2ba597: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 51091e3d0a6c3b47902022167fd50f5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28ca83271ba892f5aa869dc8dc6defeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7881df14497275ede2a4ea4951b6e48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa834a036f6fe1e0a87010c1fa5e56e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4122d9c7e7dbc2a0683c610cb3ee015a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3651c1ace6a99be1d0b62ec4e7e9cf8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar eac2c54d49916a031a1227c95e6f487e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ab182d941587d41dcb38f4e015c93bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d16a57431c0bb5dcd49d840e45a2d8bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b7ec03bb464592a54e289088fdc2a6ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c5456218dcafc7fc2ffc94b670fc067c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b504f83fbed6a48c665d1810f91ecc35: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9cdb10f231a959f6a9e44f5945cea8c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3989061156d6580082ecaae9d9032ec3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 66644abfd45a47ae7656ec0a41cf65db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 09dbd590a100604db3a8290da69dcb22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59ab47ece73afd12e96cf7a86cb97b3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4659162c52354c18aaa1bb97eabf6a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28607cecdc23d0fa9c6ad9064bfbc7e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f113853affd91102fd84f9d68d3e067c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e316989313ea45245251550b48033492: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8a4eebe9c0da0d82da28ae5d542d70a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84f7a8485ef49c2c723a46a7049110db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5677cb1e54abf76de4b03c80150e0b77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a8c29b3a77eb986fe78508e4e7f0605: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1c0bd647bc66e8e56cc45572be2c37b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aeefb34f87c760ec25cf59f0ed8996d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 54065b7326c02a19a35a1acb59b4e04e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82fe120759628f15033d05255865fbbf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e1846548b197ecc5cadc98b53809cd59: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cd529db186cd9454c3512bc08cef0f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3eda14bb0b60bf7f5b9544de7c513a79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9af3a8b2bfe60d6480a1c2b288d29da8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9eeed72027fbe129c849205ff05645c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f77f6ec2e0d17931d1e1aeabd585609b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a30926f0582db3cff14efa1aa662f1f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57891f5eea7f74cee1e7b284cacf6403: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ebd60a400a0eaeb67437cf1524e7b17: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 726e8c307272ba46c59731a32c364a57: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 34773713b7cc8b220e2fe659ca121da5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ccd8217175ff44399036ffb30b38843: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15f2b94a5fda382fcf3f14e0c46137b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31e0e2772ddbb5d6c36d0deb170c74ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f25cf799615fee7ba12ecbb83f1e84a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c910baead73cb65a5d1edb028af066a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7b9008ec6c01a6c80d6ab74a478b882d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d6fd0541a65a2b5b742ae7c4801f40a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d08950c003a8f89ec4c32e34196a9992: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f56a3eb628b563fcd17c9d249fee617: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3699642214a35dacc99e66d78395d8dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f3b6e62b971e2eb8603512760547b91: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7863741dc347d24b5c2b3dca4420024b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 321169e23b4991f9b4b0429b564697f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3214d81e6b49f9877217a14b530a646: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e88e342272d4ff9413103638077cc64f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4cd61010bbf23be07e4c0b3440c7a963: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9caf4faf6b6694533fbb059372e8129d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 18bc9a9249bec637f990099d5259ce63: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6625f46b6c9f73d7d91ff1ab657b89b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2a6fc18457613119b1230b65d838c05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54e0fd68d7a7041ab506f32f7f194746: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4916faa544b28da3b9ae13973a9b4545: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83cc3d0fca4df1ebf944dae5459b6024: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d27c6d4c75ff15b4ec7ec8d1eae4d988: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7420c0bd4d1bf045ac4a537d8d828984: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b3e64c8a7152f952731f2742b933dc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d09b30cf923c5cac6d2c8437b87367f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86ba30bedf0f84960b229338eeeba1e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4506655f37821c8049e3f4c36eca63ec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6b44aa5fd3bb52d3cfa8f792769f1d8c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e509622f6b40d079905e1fd02d24092f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60de933c4f03bb12eee67d0c76af15c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80691e9819976b431afb35983ffa74f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ea8e1b44791bd8a141b3c78b2978fc7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 88f72b570f03e59ac87ac5cff6645b34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 865d51940ac61500796bcf04ee5a4814: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01354be34d1c09294bdb1a39c75f3d8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 974caf223cae9362e6520c8ffa5c0a18: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b76bf42394d28cb53a5a7bcca3d8dc0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ddda2d7bb0acf3fd45a17d4a43cbc83: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 556c4e7bba9f50d9fe7bd2034828e940: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59718dca8405401f4d3e95c5651e8fc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4def44d4f03357e217873b9fd457516: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 806133529858bd87821a9ffcd99ffb5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 623a6496878da6134661786acf91b1ca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6dc44b8e24bea126a6c1b31dd0ca4acb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e659d78da53650d1644e46142144c809: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ff667bfce1405a540d01bc39390116a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 062bf7746c86fa7f28a3884bf716b2d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 154f7e55ca1b2dd9df102db7018aa702: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21335dce77750561592f1326c670ae76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7f3aa8071e3f8532a7e7a5eee926af2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a108549ab08bfa921e5085842aa82eb2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b8f89ee695dc84b8f4de698de92490f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 537575cd3b05b07a709a0aa47f516582: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eebe1b5c4574a8f078ad76f23556862b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 895eda91d7ece750fd329b5bb5f54582: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6495d9e7d1d2f76b2a4edd40c92c1c77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4de1c721bb742c4c2578e234108df528: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f8adc609f7a83be20085b87e5dc2c80: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e592a46d3ce64e11c813ec4ae6c224df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43b2253d08f4068f4645cf304af98713: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f1f5a50ee3bf95a2e77756c7a286921: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a6179dc49384dab1da2f8e374242155: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0b9f6c210623d5103e9c6bce54f1404: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 89137c29f31e541dfcfd1e216227526e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fd392e8beb4840d858b030275ec0e46b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35719fe9bf997dd73f256466459791bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dae1748d15e7296fe3632a938ae1edec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e49e73680bd1113806e4f17ca807be7e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69f75ccc042a0f5a7a3af3c88db84152: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e6b2f99ffeaf7115727fb81d8b1490a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d38ea3c9ef039b4d4f4417a1f55c4665: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 99dc67e774258d9ad47a3075ea3fe0b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a965a319d1858a15f6932c428af25544: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01641dad0fea98275021616e109a3ff1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec77980f35417ec1ff97c6f6d8b84f0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1fd14b2f1fc8f15525f3285481baac06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9913bd946897777a56e7d9cc286fdcb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 773ab3e13363b4f485cd39b90700b1cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9b8069fd63acb2cad926aba4b9762ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 217bc7c7a7c2a823ad97018155addd5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6837734d3f575a5e1bce98ad4534c8d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e012a841554ead234442d459fc53985f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0415125ba2dd7b334207dedb7aeb6463: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 233eb672abc161d26e108e78f04524a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3f3caa78d3e94a14d11ad8105ae5cd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da899cf1d89391bf1dabb090ec486fb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7a51fb0e96224693ee3bf2cb23a2e9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bec2bf49c017509f802f87ec9eeedf1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar db60c4e9012c1f6f6891278091d38c73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69450de4f102019643c724ca4d67b2ec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f810b8e1984de26cc1431600b544699: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b9a0c95899ed633321d294df0111064: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 362010c90d1c659bd0ede72d6124b8be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 371b035d5f5582fd13f95d402c525357: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 262d10163b51387b04b33d00c9d2e36d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6cfe0f185c410b16232aeb668fbbec7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02ebfc498a19ee87e34e76d58c43d219: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 593832392eebb89e11d5a9388cfa511c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37bda97537c2bbc536f0b567934450c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e0de99417e30b9f32120d2461ec750e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 91300f39dd5c4f39f29be82673dccdeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b4d7308b09f2cda434362d708222e9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec1389042ccfb0d91cbb7de7646582d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f27cf5c4516cd784b88b485d07b2071: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f721e65049a3830558d644fa03de7149: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5310c3e22133861438b1aa2da109ba88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d9d0c7ff1cc4f1c71b9666e142ba10f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ccce673be0194f418a543e8d09e4e157: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d32a68450215a4f24321ed05e294f79c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e139b0ed5c064f0cb430e274328ea2fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5f28b6e0f11de3c0253f914598c2b73d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af525b41b5093b1c7b407094bb1a95b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5edc3598c9ce47cc21432b0395fc1af0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0aa374a7636259e3efca3146b14f5dbc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4f1c9f2bcb1378e98052343ac416948: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6202174ffc2f413c736b1cbb301888db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b09e9e4dfcbc01dfe45729e5300e9990: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d169ff1cf17d807f26505b6d260d2eb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e4432d3915940c97e919ab1b137d9702: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fd2fa225fd4f502ed54a5820486af13b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e5462548f17752d228d85ca9f413ce3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 413b5cd4be77a92ecdff2c0716b094d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d75fdea4af76c30b6013070cd7de0b8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac35be028e0d91e74c57cbc4d8bd252d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2b7d7344083818d848d300796c1203c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26a0b7eedaaa60fd07550c7040d8e882: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d1bb85c9d8867a162ff07afec03f38c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 822f1eb2386db5e773c8c9340bcc6e90: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 93be13da3ddde20b33a5dc2014e13dca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bcc43f8341257a1674ed9f8c53b25112: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7bc003130a84cb3961171214eb10e5cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c3fb9baa583f51d96f0c2617aefbab5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9eedcb58de5957f716df47118835d4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57d7d7369b16297e4765003c9af980b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6f0b86b1ba08e2dc12f93462e23f6507: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1fbab0108e44de1ed47569b178dc3b2c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8cb105a06cc4a66b7c004cab2e7845fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 16a62834d7db4805f962d9a3af06ee77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d8414e37a330f83e12b2ccd48dfca14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 86e1baa104d45546e3c1a49015d5f383: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5438d37c46a3eed2b7ab0b4b1fe33721: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ea4a9f8293a0da9659144eb833e5ce15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d5d1f5cfeb0e45a666866e08ccf2392: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 03dcfe9fc09da16f8b7c68eb563ca6fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0b565bee2903a069021b1ccbd9a2bbb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b624a1a38556156a66cb21998b8fea8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3777555a9561f5a2d3a190f05547d144: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 74deb0b9b037cb170292c4a346964acd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5db91e78a20ca8d6f9c9ffbc2604efaf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a3cbbab76ed6748d16a1d046a7783e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 536e8c550ef4cfdfa86fcc5ffc63efa1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0df8b19c11c4c81111d4538bca1ac0ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2491661777db297d90f47bcc21976644: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e3e9322745613a789ad55e77d015711: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4063d597de3e21ff99f2daa516847a9b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6b9bccab04319bdf68282768436507b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0b9dad95bc3aec2fda05477dd64126e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4be39202a352d9fdfd02e33f2a61caee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e380707150074697ef705e7cc52ac7d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d0f6d763f4bce617d50d9b9ed0266d39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64dc7bf4bd1aeb6cf1f5b035df0105a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d0bf118a69d2e18884ded7b5894afe5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b4ed531e526436b4ea3375985f60ab86: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b441c1832d3db0c6c4c677ffe54cc54f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3948cf96bcf26839e29423286e676548: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d288600a44b1fc6a6d9eb75ba050dd45: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8757d20cdf024c8c80832d9911e2d53c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ca7037402de321b81fd063cef295f2c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7343d47336dfb52d88b6eda9d63c3ef5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 75c4da8bf4f5069e313a9495f1c19faf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 695093fa679e5e899c01b908701cd56b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e5374c3446076c6f171dc7aa205e139: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a44d36ccfb939bf754ae49e42c8187a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25c9937dd28c965e12028a5c2ade6945: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d3f4d1394e9a7837889f8eb941f386d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ef75a24dc0c537760a74c1beb36b72a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e76b28fd0340060353a28078ae9c3da3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b69142047017f96df3c3763e522baeb5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc99a763d6175140d8dede07ee884728: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 159d50fef457a678d3612538d88efd4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67151bcaffc4239b09cdaaf4f0d8dfcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 139b520fb5b076f60e0615132acee200: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e1bdd4e40795f0007f3ddfede9d599b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e516fbb62aac6a420e97b7952857dc14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54767044f9172c46a617fb1ea5141cd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0797012a98ad03226d752a06e843fb99: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c16f27f4829c4bada4403f70065bf59c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 427a60662f0ff9dca849a1f8f03481e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 417bdb531ddca7d7a5f7f88e72617137: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8848a42baac374fb1ebe6b4b138ef1fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9958c39289810c60408cf4a285c4e7b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 974da636bc43307a2fe9e69a44e3b6a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3effd3f9df75fb4b085b30c98867f145: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c0a1acf991d5542a15c505d8c5d2187: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 521c1699f57da0f211b4f675b7614f76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3426489a1e178cfe14eaea92d68306c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 803687a05e6ea65fc0a4daa34320c789: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar de27ff71785941837c9aabb6b6f7751d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b23360b1a9a91ac12d717916f2bf29f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce66bd325be30654b94287354fea14b5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5de88a326e9a98736b65b3686df3a282: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0b85bffd0221d91fa4b092b684baa35: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d2b7c5b93a1f09000b169f17861a2f8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1879bf97a3b4dff6dde0a80329eb74a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a365e63657cf5bd6856fa4d2b459e865: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 580fff77f6cbb3db9bcccb9dd9d473b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c490eaef8a4cffc7e9cf803b643cc82b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4964c59e91b163674fdbdcb90982dcb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 092c1df36e44f63707be00fdb02cf917: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35efbf7603ea726477878bde316f6ab7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar daa66807e20d5ef5c51fc279c258bada: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fad89576903737d6f3878d2e8c62cb5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 400f1207adc2d19b5112aab5229b0937: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc6f7762622e62ed98d55c102e2bcd62: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 58de2ef687389894c7e009299dcd9233: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aaf161adc93ce23801913404ecdb71bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f801462de7c8ab6090534580504e77da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 941efa0c01f6c9d19978b6b8261f2810: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce7e6157f70dad5a48524fe6b63e59e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e74dc460423869905c4cfa43b2c7a68: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0c24386cf0b4eb689f8d97023dc21ef6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19920978caaf664397d7099a22e4f10a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05e85b26459e997c750bb2dbec42776b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e18fc0831411a77fa9ef1252d96f748b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ebb7d987139a8021d2c1e5977e23d273: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6489bef629d80b4522b752621469d32e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7e2eee35e74f56cfd945181ce2d4895b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6390921c2ab00c9c539dc6947b4d45d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0fdb8ad5b5992f39e62b2743387a57b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6090fce28fdaa763fb2fa66707b6eaad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ef3d4304869ed6faf10687fe8b8e303: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3b2819606719a5a955ecde4c2e3b6220: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f2c8131c9d4d6ffdff91b882756897c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 45195473058b3e4c7feabd4a31065e3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 707286441e02eb50d74979c3090c8585: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c37d5aa3478ba0125500ff890081fe8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar eb587d67915f2756f3f221d451e5a7d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c0f0c67c891f2f9250a73a8ce2526021: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 127b25511d5b5f0436542501f5ea10b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20536deba3bd9d29df5a0cd454dcc425: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 786be9ead17aabc4a4593366ee1c77d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 21929b78bc5481b58afe54eaf8407d3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0086bb72eb770b3f8ae62075d5187716: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 03ea7cc43a7fd537c02ab6b5a5cf08a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e37cd29b2d9d100ff35beed5f7820c42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6daed41fb7c70cd7deb06b045b5052f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0f1992fc7a478d9acbea875d28c1ce16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c767f5096f14edc2a08b0c04a816698: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c957526239da53af88a0a8146f8f53e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd7ff235315ebef68cd48b7ecaaa4fed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar daa352a7e7c06c3cdf51a55daa665607: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b3cdc129bc5e05049ec6b14fbbf9184a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac5b8b5ada68d3efe4fb5a25455ac5c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07bce4a9f3476813e654ad2322bcfde6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0a46cccd40aa8f8b52e6f448b107684: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e722ed41d1dfd31d28d45a8e78d23d13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51d3fdaf44457ccb9ae22e07c7f32723: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 163f44db49c0e030e8f24b4705421429: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5d41b53c61bbc8f5c80a80ff6fa30caf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar efbdb88bde5340fbaf0004ab75640a80: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e0aa2947ca85c47ac922344a3f37df3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b9a1562fd972693d6def8d1c8a033e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5afbbb183dce81e587780f309aa4aa42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 30df8fbeece5e8a7c4e0180843140c5d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ad8a54197913fe8820903c1507a7614e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35aa2dbd20044d1a71bc153ccf6ccca9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d31574c196c5c1ec6f8a7845aded38c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5169c08cf73b492a38175f42a9e261e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c0c9398b4fe4692b51094ea925046283: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a1e80957c8991c50037e855193e38b88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 565136d8858508fe8fc2a96c51d3f58b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a13d02545b0e015d85ab89f1d6e822d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e6b9c0fe311b958c15f7215202f6f27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d9dd0de704804c6ccf865478935ff73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2206345d79c2efedf0e40f2cba17472e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2639a00e0fb747908348211cf3ae2306: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 602763d9e50a70e7ff38917c20f8abd7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39e0f29af5ad6f5d63f4a57a6e237c77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 785e65ce0cd2fc2901ad55339dab0881: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 97ceb1a66bd7b951090ad1a5d35b2233: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25ead8e27398d9f80dc9859877e2c22c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b3134e2de13b435a7708e95a6688b61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfe2ced6d75ed0833cd7fe474c0655a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a9e8cad882c09ed4a32535733d9462c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 297287fab9c82fc48eca3b334fa0aa1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fcba20af5bc8978eb6d5d2a29abeb422: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82aecfc2a119755041e49e8380a68bd1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 88de7573642df2421aafcf860e626cf3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae2fa348075588f420b2f067fc7d9720: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdb1a346387985e095bc7782b242a1c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 71e9c2e7dc2dd17be0edc7d5b1874e03: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64fa52e5160aed5df33a6b6a50126b48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 378d5df3e96167ca8f3aafad4a66103a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f53a9a577d0c17568564fbfc8366f8d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ccf85ba5b8239b6e531d543dbde00783: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d7fbd83ab7e0d521939daeb2a4e937da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cfc2d7bad70461c31889acaefbae4aba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc69cb6ed87f9e2283da337b407353af: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fb24143b2c071dffa944e8b6f62804b5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b3d8c67077ca8f1847eaa1ad408d8146: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 23d504fe6e00aa70a06e35ef8b833e49: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a87da3931892cb8a78682f771d87aa6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8cefdbfacdce24be0f52bbe2d94856bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2c0cd350db41d1bc63f1b2bba672dacb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e4d3fc57be2f0e330d4c42c165a07060: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e68797c2c4fd466f1e7a6164bc8d35ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 057dd0d26875f4a6f9ed913ff1ee82a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 62e37a193dbb861d93e61ebf44db0f62: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bce1ebc270c1e08f5038f145f37f341a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar feabdb40e03bdbe0bf9dd1ff5313f1c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4b3c6af30c58a60f9b352bf800b4031: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3d8d1f1cfd6a811c570de9cff4f746bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c388beb7f8b9f3db562f4757c5c663a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98a6c6ec9af5a9f28163dfde8f59a941: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5149310b262da4b9e374443e6fe69255: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78104e3c8e7a2c6af737f09cfc395174: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2db2eabaa1cafd50ddc645f839956a51: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4718a2a82635a73efaeb67db7d4d6052: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17bbfd771c6d00aa76b2b866756f42aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9374bd22875bd08daecc0f46f02d2374: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83965a063ca37f194db322eeda6c8119: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb150b5b7c27386613229a7517a08d92: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 689fa323449eeee41c0f64c43eeceb2c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e7091476c20ed44e9ec446e1336c5df9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9c86da3c3b0b2836b4a6d529e1f5295c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 311ec41b5d6554a4c48552e7a295e655: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc3bb172276af66137287ab9170b3f1f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2d550a9e53482f6b348bfca15c1fac6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0b3731ddffae3ed939980c8ef14f426: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e8615a91d1bc9fa345e5babcf9c793f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cb5de0bb5cf6530a100953fbed2a3caf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 14766d5152e421fca4e733723863f2cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ff39769fe99441369534bbbfedb9946: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ccdd4a3b962ab0c10f848d2c35ac38b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar abe0ee5c04a79871e8479e7254ae22b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fcbe38326c8b7e67fa3e92a21afb2722: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a673e09e57bc6e2bc49180f4bcad9da9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78988585313d5f623cfcd1f65ac8a1a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc62d44925818b80c865bfd89711e41a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2d791417f59e8977fdf60edac714c18: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38d5b37a715f753c261016e0e094b6e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8f44269a65efe7a80e1f0551763c3f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5c511d7dc04ffd8d2b3f2a5a5b3966c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09e0b535dc98603f0ca1efd936335c40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1008644db4d558cfa2fc49292a2b4618: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec8f799c1f12748ee74d85a5d044e1e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2481e3623122ccdb7ffdffdedf92e5b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0f3c016e6a5a6f22c6d6ef8f317d6667: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ed3c923e5f3fff48545f5b533f0fa3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e843b6318889333ce78531932739cee4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02a3fae912238dc4036964bffaa19095: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9bc47983795e7e2b5664742ed734f9f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 78b677289efc7bb51334451f273a147c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6eca1ea8cb3fd064e8b6ae52e42a2acb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b6915faead1f9f74cc1e2e818c6a379: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f05562297bc7c0ac77caa3dc5c216be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10cf46f78ac77b6e584d281db8532d8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41439913f93458e7fbb97ac90a5d1065: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2e4bc5077b55c641399c790a36b0b431: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d539aca22947393ffe22c548fe20441: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9140e380a63cd3b0424725aaae8bb852: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c71c1096dbfea9b51a9f6a6ee5505b16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 541b3bb00acf2b439b74677e2c4bddbe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57f0a3521de4675e9730cefe7d65e462: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d44aa632b962ea714ec354a534d4e06c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c5749e4b71b9e2604b04e732fe6d0f4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83683869e0ea156eea2460fb86e4d3f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 44f41a6641a37df1392ba841dc02b8b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ed6df6b79229c40c90819267eb398cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9d2437cf1ab30ac4433ba243ea926daa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67ff78cf8e50ddfff2471851d7e19182: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4b5a29139ba38241541c1e4de15dbd5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb54f27f29ad81b7f0251f98a0c2395f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11d9f162d8a0f43e7ab8638d20e76f4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0670e175902c2c51a731ef42ce634815: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 71a6f224232371144aaa95b6d01577a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21e683f967a4c0584672655edbb43769: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b6433046329ab808a703439504eb5d9c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8bf39b1281684392ba0e954f2dc6a87: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 82ecd815212362b6b7e4989b6197ed29: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bcd606b1d01c18121de90718896e8ef7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38288e87013cbddd4d260a8fae2fce01: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8c607d45cb447cd119e38303f659eaf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 741dcf5e1ef6bea292ca78a399115b84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9d283627b5b264c100fdb463513786e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b05b571e31fe690734c35e047d1b5acf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdd43d38a734cb73c42c5149b1c3e38e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ebeb291edca81cef46f87e99d384348: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 97e76e660af80086e97560f6275d0949: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 80aa4a4bb31be24364dd6a0256d89a8e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51f7ac3285506372fff3accf674a04c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 66a28b30e059839a3e95a4bc42ca0e1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2c82a898ffe81aa7cd0ab6c242944da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00f0e6d08aec2b134f841898e62e2659: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c9416c4b78d6882a6414cc452f32aa5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4e3e97e1daa9bd8129386dae9691ba2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f23e89478c2771ce053cbf062bcc517c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ac370b4e7a5a0386665471705d3c42f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da7ca86bf310d976817fd712820eeb0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cef9da4628535924175a44261299883: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 950ce0d9a0690108835a606e7dc04954: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 89542a5848c01020d13fe30b8a7b65d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 14dc501b58ae0f8cd4fad4c5fe4538ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f97fec70382d7f7fa1881a9e56ad6944: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 841465723357cfb7db2cec1c100dc77a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 164b298d68f1e636b87597a475828ef9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 757aaa045a7ade3462a8f84feb4e63db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar eff9731558b68cdfdf366a1409363257: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 27928d77b2c9da3f4e5c0e7547e9d5c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0e1c05653411756d99f3d6c26f957fde: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18e6df9e230a5c02f47f09cf0b8aaf40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d0a7a83db501bb970e962ba421fe73f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3d0d24c7cc3b4ff108b7a98b895b68a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 326369b793b65d02d8022c8595aaf4d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e9aa0ee30e15f3f22d6dd3f19fd189a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a30da43b901756058975ea0cbd30cf44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5819b496282d30eee91b87e6cf4fca05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b4dae2cba3684bcdb496e8dec1eab57: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f2dff1d87c8c67c541d551913bfe23d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9eded8557e9c98ba623ae79eae09308a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54524335d99db1906a75be4cccb40f81: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c72310a234e77d792058f867a4e885f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28602a4153b4004927cebc73a01af807: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b32a03b636d8affcb8ac636f1936676: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar efc32c498ae298bcda816f1105243ad4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7922646f282f49a7394e4f7f7a71ecab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 866aad755431d8fadba80f7e817550c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd2085e5cb9452eea413b58bfd60e337: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 474cc181859a269665352103a004b602: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68d8ee26578f4cf0ff5861e6d0d346e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0490fe727f746df0616a617b886fa957: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 56a5eb3905c5b58a004394e01d4966c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc739425affc0d472ede9e6c6ff9f55b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7ec8fbdb5586c3014946bdeaf4f0f02: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ea955969425c77d43b741b994caface: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 55a85bd9039b141970d3624971519fba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec24ceb713a23405738edb97db1f06d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fa423734b7f9801cb31dc32d9cce97ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 611cf19e1b1c6c2b83f1ef24cda2121d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4f3f7a4fae62345c2199d2f4e2fc4c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 718b5608e74c9f5218fb80f08a120649: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 141699ba983ddb732806560f9939868c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3fd2aed2e5977543138dc9b80584c83d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9f74de2979e65d863798c3e30e888305: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e044e75219cd56ba50151f97234bfd42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17b789197dac832cbaa0ebc45a40e0d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f646e01286e613051faa73b76067d2a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fddbf80837c394ad70b4cbf9f49b6db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 63e878105665bd0cbf3bb17e0a8b72da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ed92be67162fa269fa791b30604fd71f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dab063861930b5ed52ca2b162fc3f1b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98bdb96d875fadb24362b337d69c3d80: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cdae2c0e30bd8a3fa39b610590c6a949: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b477e46f0f852c7c02a5b7bee8bdafc4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 88730c66c658515ac84705f3afe1c2cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 871b14f90631f051c02d359e07535dca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 581c0937d66ab497fe307b1b8b488789: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7daed385375ef90ef278d1e2d318bf5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar deb9094ccc711231534f8bab34f00d8b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00700dcbb826e952c9342ef6da220acc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5dd9176da5805062469903759f247638: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1e9f284de9516a34316ef0943b5cd806: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 566ee56efc0c1d8aa3a40cf188f4613e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b074e2cb58222606445da527e4370bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b25ed90e86b5d3bcaee3f8fb636cb90d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e26f8dc2084702680c8c44fdace231d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6288bf778f81fa26acf83297f748b2c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9405e5cc490dd81669ac6a1238a4e884: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 68a6821291b09f7cde516e14286ac627: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80927449d0e4cf152b4fe5443ba5e34d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4e0db27561a11fe54dec1a01e75d591: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar adcadb5faaeb89a9feea9b96eff2151c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1683e917b802f777669b65373b90564a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ca984fca1d6148148c9ad7f9deda940: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3eed691a3db23b30e08781d6dc5be062: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80869e353a9e2a71f930782e40401b58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce1e6102dd7d30907cb907838b615fce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa6b3d0b6375db0e78abf99bae553837: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfc85f89c1c10837381e7f67856ace67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3067a49d33a03710479646aa18062414: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 14c2d030203c7b146c6edf55b0c03c9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5b65845dc74e1b17f25624cefa23bd82: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9597aecc45ab39d55c5c88628137d87a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 034c5a009690b44db0d4c478b0a42844: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6078deb4d41736905fb0ac021f660018: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5d4c3997afe372fffff3a91f658e17c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2bb68b23e9f3682bfb93a7a6b1fb5f60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5f272238b11aed90ad926df7dde2906: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b5d6e0a80a109e8ce015600d0cbfcb7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1667d856be5320a9116c3b468deb81e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ee5b3533fb78efff543dd2892d519cb3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar be6a1c0bc7ab613aff1a869bc3ec6a72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67a6a1544979a928288b68299c0727f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5fa2e73062d318e0a564bb261c3ce523: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b121263f5a85b3bbef7159160e031250: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92a975c943f55cde62f313ce98ec8ea1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a39064a807c564bb6a5964cfdbfa281: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d96fd20b8ef31b12c2b05058dd5c3417: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c9b010d39d65d1157f65df27bb1b164: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 390607c59dd2a1606859fed7f5abf30d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2adeeb6f0cdde7cf27e80f52124793d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6000528574bd250becb85b5f4d2fb27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e394353b17eded20b024cefa36bfbefd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c64b43e7cda5ae4df9aeb78ae367d32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e4f691c5b5aac3c87caf022557e3a55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cd660011195277084dfeeee529e9798: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3f00abb6098de8be0e5168e951ef38c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60eed539076e2353f8bf444b8b40082a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e06a3914da17a0be6b0c69836a4610b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6597549ae7c33cb12967d5f73aa761c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b4f81ceb78a1360c30824479fc301f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48dab1df7fba778cad31c480975bdf4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6598aae3fecd174d343035abe2d609a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 29cd240b8f709acb75181032e19fcf58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ab3c7db3673bc29bef1b097cc9d60084: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdf132b0fff9820e16b85d3d7a035cae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5456054c0d418ef9605d0de6832f0093: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f3b512763ae1d7c9ee6c936b76bb53f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77b22ae9615744a19709fac4cbb73e3f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3b38feb3ad38662be180d871612c0537: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e6b4985f12c1d7574c318a61817a75d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa018211bcc832c1fda9e0514ce6f26f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 238da6e5b2b618fe581089703b79bcab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15b32ed5fbdb22e4ef3094b41116407b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eea571046661b8c9e4f47c05e0bd0f5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8742cbd8ed4eac3af8f3570da50d949: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a2550fbb856300a23035ab5bd968e58a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c807b2ae3bd95da2b26e33534e5bd00b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6bcea14294ec332dbcb58a59662b94ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc21164781bff0a401d1c67b36f72b8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e32c0a525e1939f4a252f86cb6e76c61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1343e8e9fb3f01e344434c173a783dd4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1698d25d92bac31385fb0e077ecfd98f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b35ac5a8c9077649e84172258b7b8ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 99a8e571a5fd6c735dddf7d5ce3554e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33b113f0cd0222d82de8dc5c7435acb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c76add6ed62ebaa15af1bf93e0ce4018: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 13839d5271a8c3393d6be4e3bbf8b8a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fd3108d9cbf604632c5339757e447fc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52414606f2cddb2834051f7bdcb4e9ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2fbb001eb3b50a8cf7d25d0f3d3c7aaa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81ad647a81ddf91545bd6767ef8b33af: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e86f179b02deb782cab156220b93029e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f12dd9854c6a66516647e93a5a80e84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 316c8e1a0c64e6ebf09a52671e03fd3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7e065e3e256e10da84357b7811df007: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3055dd86b22af5f51b72ea09306f7911: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f1ecc2352bb42b1bd3f8d47c8307535: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32190a6f5e1a871e8c02cdd6ac7a86c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d05746759822a599b87d4449384ed65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 36f4c24d7c13c4c42d3ff9cd9d21b3fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e303cc1e2fa2cdf1f85f353e4bac3f1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f9e5a20c23c64e3dae6674e2fbd90aeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25be7984b38727ca16d76e1efe9cb0fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c588380cdd16a3329f778c108b7bf87: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f98dc5958726ed668268138ca0147315: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar baf8bfa747397055839e2487642532d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1fdf2d31d72f38346b584ab2595fd5fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2334e778b1d25cd8eab5a5f4a37f31c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc253443e3aaca89246f8eeaa46a3160: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7e0937ed0322444942252fb101c483c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f3ceb37feb332731b432bbbbfcf6e4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9a801e22078fd9c6c2e9d3e5087fedd4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7246339ec6f71fcc93b7a48bf093356a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ff1e07bb9141a14b8d34887510f99bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ac32cdc678c0333b7c0ee04287fe7ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6e93d26415cacda60a6e44a978ae5458: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 690196a38d1d6aca089368b3704044d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 277af93c0000c87e65243ba26267243a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef963a50473b8ce334db89fc559e2d14: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e4f58a06def657feef0ad78ac6e50cc6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fe69ee391dd89887117ef7898d1657be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa34a4df833f0b913b15876e03e76e15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 985c86e600da3c617d657cfb20b52521: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d197b7d80d6dd8461ccd293782e4c45c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b73bc7d78845d147f96c48d8d1fdb0b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31445eda7e05d04b7bfd7a608538df23: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59c979f822d07afedce9ddc6b351b448: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef7ef5ed0e60b125a420985c4635b44e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 335d75a5cf4d3415d7dc1e9d1e9611d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5edcf136a3798aef125a99ce6997abc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f77d674a9f79505bd76dbe108e84f8a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a8474126c4992630d01f50fed52ef18: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 118076589e95c3ca348d4be7402df26d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5091f83e5f436458bfdfc3f73c4780dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6c60c3882c0d1a23d8da5796e02c2702: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92d75311593faed05a3819a3e2feee13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 792c4880790d0205b3796c894eb396c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c602195208ce05645674c9d69aea7142: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4416f6920e0b33125c30b5b27fac737c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26dfab6587c8f8c5ace223e8ecb10a61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4682f592e86e1887e57df1a28d6ddf32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar df530ac11c3ded360a2da13053aba50b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4020bc44e687c15af5a19b8e380aa3c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4c2ff088afd72a25012f5b63ba0e5a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 47e1482da8883437236e6437e48c28e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 51ec465bfe2ab8fcd120b204e7da849a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b59d642b3348ac01104e9001e46b944e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 638684b558cf3aace8757518d72c48eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fa1527db4164d173d198d9f69c182191: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c14883f972d33f728904deec2a814e7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b32952ea68a0cd43fd5b929d67c76704: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a7f5c66568dfa5479b9982f0340c5a0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfe9ff2334394f044b714aca5a34cad9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 119fade728a12353d30c5723421130e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92a435cb89fa91c39fb4a235ce2f3d5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a174906418c53a4ada078dc464c73122: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ff38dc4b91eec03cd83484624f86b1e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ff21c246fa3b4358b76a7361249f9261: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38c7176584a41ddc936cfd904ca33f5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8260095844636a13566956fea4329b34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a1f21935c18ffe62d4fdd6aa5beeb5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc141c5c7f38916320defba630c55ab6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b6c4171df1a070c3e4da4e05303f81c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f74dc819d917e6c16d618d260879add0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8e3e1d698ed2ff6f5fb0f8dd8505ded2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ead52a1227b3944b3b897d8325d11bf9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93d39c0a1ef967a94d284b7036b10872: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76357c9641dbd47530f88d4b84b09ee2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 96f2a9cd25c23a7975a4e23691bc08f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 842dcb8ee38ec33339125315b1016db0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c5dce378f1484293cb7ca1066ab3b217: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f486d778e1d57fb63237c46b9231beb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c075ba96af57acabf55d14113f8d85c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 542f9b056e1ef306746a88b7cef0a3b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d400776bd40d0f8418517bc5d94df559: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1122db687ed8f386d5feae4c0fad1159: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6671f57a09d75b73367bad444f780f30: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ac9a7d0df0608f16e7f62a681dc1604: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1be782805e05468aa9bdf5e6cf694a6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb032770b8328dd314e567206a184281: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3b13d4ac7fa149859ad228a66fb8c302: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f75092e6cbfa9f1b8e229492ef6c7c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 75d95e35da60668562bd06c18b3dce99: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd5cae026d01073f9cad61aaa02d9c3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a8482d08ca4b8d84b1b9853c43e393c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e97a223b423afeae7f4541fc0e16a7c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 09911182deab0c342d5c1807a2b027c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3392d7fdf1d2b38a27dd802535706823: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7d10a0c803d77601c7d5e17b40c1603: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d3487a3ab36e91c601fd3db7a218b950: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdad45a1b22aa4b2a380eacaddb3396c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cba87f45fdb1c9f0595d69dbcd545e6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar baed22a11a5dfb4b51388cef8423ed6e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 572e25814e3eec29a5a67f09b1786a48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0d01b133cab260c870355c72a92dc01c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a3ac80569a4e5a9e37a3574222e4735d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed7703ad2b86a33effff1da704452d1e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 46317fdd37ad98c685f4980ba7bf5fbe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a20212e477f2b0ad8ff8cc0de1154f1f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 48db0a250afa4c91c42932b4461e37f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20941ef428679f5542d0d875b9f1248f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfbc54cfdea379e6444ac08323099fbc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 289d088f269579d9224111ce8e9ea8b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7698caa7746642e97869b3a311877f13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18b936660d80338543e776a07a4b6dbb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cd045b21df6095dce9995d57057c8b0f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 904ce7eb67c36c5cb4e27cf4809ecfcb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 46f9fa7dda92af4bf318e0fee0173f27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8e093231897512b6a180a33b08f31df5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da254be88615f03b56cb4d349d872d16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8e647d6fa7f526609bbec28621c42e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1ced2719fefc7d5ae4b4dbfc591120a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar faa5ef81621f12d54db108199e4b6273: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5584c4de8147effe79fd1e26b55b3dac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2995146fe3244eabe41ae56c02490f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00325737e7ed13e641279ce80326b79a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d94abebb3829400b1c1a2e2c4c0cf0e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3292dfb001480666998fb9eaae7c1006: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7ecfe066f503b09310a37c1d965afef9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4abc12a5ee2c0a2f8c0041cff08e127: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af86e6b8ee36a5c93ea74b9b71e11ca0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4022284e1a158378e5e46bf5344ed3e0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e7c5d9bad99120c1f18a8401a524902: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 60613296839a970bd8ba20f577722509: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eaea7096645c830fb22bb08e354a3a72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52bfae047981d732c57cf4157b913b72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2fdbdb4e1e8598e556048704ac34935: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 379e676c2ba8baa9188e5d96a0e650e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7af211eaf9a65e1200d2ff90679aa29f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 56bdb50caa51dc25a540a6a048dc1c88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 572aec453c5ecd22078446efe617566e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0612866769bd84604e4f23af9a3aed9c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 471674c525fd08fb7e67d91a88d2a48d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 971d16b30cf271f9420e6c56cae3db51: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 83e2b9991bdc4e11f560b24ed74b2486: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 629f9e8696a320d62948399f27fe60c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 141c3c57b5f528b86bd17f68f20bc4fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52bd0ef3b0892f453be57ef5fae85692: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 12a5bc2188c3e268735d50796a342a64: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68d4fd9b6a11df1a307956c55ab93cbb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84bdecf830ef0144507f0534b1d3b1ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 58b847d760907765bc9147920a01fbc0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 44ed6935e0f7c491df71cf8a4aa04e6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d619327d6b8ecdabc37914be6047dcda: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c3632de8981306c43cec9cba40e5c06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f2b98181f1adb18f6f0f9eb3723e2e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f65c7f5239d54ddadfe361d79b42fde: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2c431cf0a330d96a8fb16365c9c1fc4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bbd8565d37dfbc557e5106eabbce870f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 362199358ab4ba7837636a2d0dfd3f27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93488f8d0c4347daccbcc916c391075a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b53318b35f6dd9c498fead46af059f79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c1c17dca233df5bddca0deb5f2e4148: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0c4f3548f02e246b48566da14811fd31: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ffe4548a62f7b82aae0c1443c969a433: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69660c6662250c25fee23f65dcb6f407: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36d13092b59083a0d20a0fa7166ac027: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e1f1c48b9e69c265f8a704e71db0c278: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar adc0abaf0234899aabbfb54b8057671a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0664187396ba506c8c11a56af93ed266: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 411be49791a76e96a2b4e056c0324910: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84a7e3f2397f8ad27f5314a055fa88cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 674ed51ef7fd2ae336973ded1343f805: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02315f1eb76c5ca2d28f55195944bd09: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c9fbb342da42c98142225ca2c52fbfa1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2a63a3796e36e1f1545103a8dd279b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 99a2bcf93997fc324de843e60f7fbc3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7bee443e9d7472a16f410b4fe8a44228: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dbf4f165bb565a98d2a1907c6aba8491: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c25ed42b95fefa5d77d1bdc6fc6c79a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b7fb4bea79c24c1aab1c720f1d6d4244: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b82cf2a063dbf9ef0d5a5f5cb700beb6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7d3f277c3eb9fab9a58bf2cf439f725: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dbe20ee72b7485e18cfba1082f562720: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c703afcbb1c848b5da1e69d720758691: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23722004609b0433a18364a06bab3be0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c8cf126a1b66bf8dc772f3b4b043f95a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65365ca8dab37faf92809a0a29a61c44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ee67ab9365dea6f4873f82135498f73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a63703db879fc362c47790d1a867eac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 803b3e7b7c92d8ab0d3f5473d684450c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6b83531d4fe3953198479117fd17047: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2f83838215038adf08757b82af9c513c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 22f3a737caada1bd6cdc6661f7e592fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 453d1e33b07ccae786728dbcd07c845c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96de28413cff9ee595e19e7dbb1d34fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5be7d7be2bfc2f1f9057bb2710b48276: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2142fbad126a6813f1766b8c2fe4dbe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2845d12f4fc3d01f4d7436552ce40d47: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6331800917faef35c5eb4c366ee220dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cc7d5fbc897349e14f02d04ef8dc39c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3c14b8940b2ac96260ada812da0387a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 953523f28d352e4642b5b380890dba44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a20d01fbc868b132af757f2e38c43f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar af04c8b79b4fa4f97850159cce573ce2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 577634893432c4d147a145a0856897d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb3b766e1bcefcf14f143ab630060800: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0dbc315a2ae3b08d63c799abc38cb5cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 789d602d9f772402dcbcbf3474ba39f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 35070d67379e6188db6f335c4bd20532: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2b7ead7adc97af7264d1a9e7e2f745a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c5eac08c9505841ec71fb7c0035e632: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e57de79cf383fbbe3b90aa84738fd59f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4614f4788528362e99d72d0204489021: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57525fc2ac2d8b7df927be0994dc7667: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f33359a8a8a3ae977a27093d1f41802a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ae04564c88946fdb31f2ee3892bc38b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c9ff6ae1c4eed30287f1109884c3e58e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58e5927d3677308e911b28322911eae2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc33a7ebd166b6ff8997e74acd235ee1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a8dbe62149f3448fba42b86ca544daa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 27acd53aa931c67f59202999b4025df6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1c9cc8de832f3477ad76fd4ba4ec32f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bad389f93e900c721d055b6579f190f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70af666e6f3b3003fc0ed2b02f5fab6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d903cc05f52983eafb1a532852c36353: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0930e37cfe2fe0e34a774a9038384e28: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7a6f8648ccb44ce9bad193efcaa9c206: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3dbdba6dd963405bb3079851a8f2eb7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1c227fedac00e77cb67ee46bfafc994: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0576ce11c5d0cd1598a1457fd9d3c714: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33af5e8caea682f8c96fa0af6503b922: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d68f9206f9f24f80d1229e968aa92f16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8775296864367e510ded9dabf6d3438c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbbfa368a574f2b9e3660946b65079a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26067ed82ef8f9fa30628222908c89f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 001efebdab6e856f8adb1b68550bda48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e4fbd3fd5b40f995f8fb27184851514c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ea025290b3078e3d58cbb8834fcd26d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 88214440bdca23736cfec2d20b6be1f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23eef0a6d948eb9b3e322dfccb37db58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7583c0c36d47f6d1be4af42a0528f1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4b9664e5bdea721dc4c715b93b2d28d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6711d3b2764bb18d549d179cbddce6a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1b47a67ff931ae4b96c880f8d31f2d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3060d09845133aaaa6790d08a220a063: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b790e7b7511ae4842e99052f894822fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 51f4ec99c170d7da5ba2b2315d5c9ff9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2eaf62b0be567bd30c222c9410539ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7623da164387a316286afb0bcab7bc79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49894c6f5a8816145b66442c418888f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bbb964d55706d454825124aa35db0f13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd23c4429d6f167e7ca8f4e31b718e5e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f3b4b6b193c393cb935bf0376f7ca00: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 169d8e4d4dfcd92a748f6ecc195b0855: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 967afd14a2b92df921722791d18735c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 35d497528453fae196256614ad58d7ca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a583eb23efa5b8ae80b104896a2f0bea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc8c9eb008a17754bac0b4a4a59f0405: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2795b204864a89faf6e721aff19441de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8cfc50de4688b1f8464e8a4b729bc6a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5938bbaaec18830af2ef47d8f86ec896: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d896344c93ba43286cd7edf8dfce062a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 95f7f6d9dc241ad999f57a99f7dcdd39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ae392a1571cb274b4b1d4e4a69ec41d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a65ce61c442b2162393fe923d86e9a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3a67a3adf7d8debb48ea887b4b045baa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82cd58a44c457654fd581572507bb6d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a9b202cca9c9fd506413f66427f7e6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15477fa2291fa9ba0ddd8e39a20623fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10ac56a2238deedb2da8cf2f45435889: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e08f35a88d995edebcb9ee5ba3948756: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f97e1f8ef262a1cb1260656867a95a0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25da362256c9fff885e8291359661e42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3155492e8e55293c3128e7b46edf8613: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f8b75bb1ad561758ef334daab47cc42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4a06042659d25e3246fae9b395684535: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ead96c5d67a9d6c6f7f66a355be8218: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f905feca50f966da9cc5f0d35c36fe3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1df04aa9620b593604d941589deebc7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ee5e684b051fac1b4578459648a9fe7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3d4990f796c9a0a181a9ec9866a4af2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11b23d6007bfb5bb6d0ff59a80c6f7c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26f2425316189bf3cb51fe7e6f8711cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b6e69843e106cd04acd4c12602454ef9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 413e94c5237df4065e411933f39f4c2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 69194c592955825383d66b897b552338: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1d797272a0ceba871ca6d999d7eebe42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c3016a73d614d3c7931eab75952e1159: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b9dbbb8c1cd51f7d3e1677b6cc4cbc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a3d25fba8df13c2c1aedbcfe23f4299: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0d3bb812a4c474c8817d22ba5a0f1934: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5237be089ec619e02b55ee956554a633: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 47747240d411adfddf133723cb1a22cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1491813b8b2a676db9e475df0ab548de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4281b03be6a1e1df6e2fe0e09aee71c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48ee50dd4b68f12a9f46209e4922131b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c11ddf4e55216c09adf10a3e3305c997: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1641e85d4c8a3cd8d40b26107c1f47b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d1bd0837eed11c75cf8557499e860b3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 039d3337a113898046c2798c5c7f58f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4ca29110ca211179e840b34ddd58e3d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c075dc1e00b227ec4c2686be52d64ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7f974e7d25da2fde1413c1c7464b7d61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5012a23aa043475d274b216b1b13bc70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35a0b01b94ca38191c7fab71bf215030: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e95271de4b1edf6c04ca42c5657f93ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21dc77604bbff287e9d2dd6ed891815c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20411f3b2578b92cc031025ad76ccbf8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dd3867f1c16e7d6d69f01dac2d916afb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68daf18df0a8c92e2f9eed4f128a05ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6140c940246d884fb1c6d33d939a5c7f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar caacc46133b3c50ca204eb4f5f69fa99: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 809f4fe2b2c1640260c2d44fb9e7de03: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6066b7f2416a9012025776b9e3619336: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar af4c35018a1bde4535887034b8066a2a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2ae75a42c11a46ef04529561640bdb1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7a234b1c85648a0df586ff069498978: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a93009cae76d69e8f0892b5c0c0a3ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20fa66f6924765245dad23a70d934da1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f0eb2c92f8fbb3ec1d7cd5d18fc56c00: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5d537e4f88c322941021a92df8922110: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc45453befa02d8e21ef7ada3a60979c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c5f92f5751b96f788b0331843e9b7e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 599e439788c5789fcaedddc437e3c184: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 248dee945cb2987c22610cd442c010bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9d859fb98f0b35a2487869154b4ed0bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d2a515c686e7924552ec0ccd6ebdb30: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8eeb46238b9e6d8319af7c1a4e7e06a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8dbc3d73be6696304b95729d3ea457b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6d278693db48a6c12f4c9e61a4cfa2b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81cc2f4b2f5c54f9d83e040288cffc87: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a857e69c6b63d478f5d2ff7249e8a5cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00da89fa57e12e1c18f42b02df6c1d98: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2750529e90fb0a7df41ad3994fbfa758: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48b8cc06587128e600f6402c1007d96d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eed939839602e512a8ea5ee5d5c676ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f713d237931fe0abf2a6d709e8e5f049: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar da172e32add4262127f5c356aade7c19: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9486c78e63bb4541cccf7e94fa55004a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0541bef1a33441d4081dd69373779664: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 22ea9e6ea29003e423b93cd03308f08d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ecb829556626b79b3f4281f837291ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f61bad79a26e6d94f0d9f20ea3c919d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 11da1f5f9532f0ca2eac21d7659bbb76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28dde0bf2ed55fd6c3dfaad61330e3d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c5122da8065d585faa31aec891f2ab3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 40a8a84b1482ac1bfa68164a7c98d5b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e5cdc975bfa6d92c84114f8b5159f25c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 728feb276562e98de9c73b81f6d3b2f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0bb8f4333c6b1efce279af97e8dfff36: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8b7f95fd2ed017332336e7ec627b480: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26bfee784cf90ace935ccd2f1074ee0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b10e37f4323b627e527e900737041d13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd66d26c0489f4297782b95a139c499a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 909679cb699d4ec8e99b6e0b654504b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b9a1fcdadb6e873efcbbac32887e7af8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e00b90ca7d0939e43efb33b9a632b8a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4572afaddabe8b0d8e50300d5540f284: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f08cafbc56b8896aad3a15107b61a61e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d1231c2cb63925da764c833eebd5885e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92e0d271b4b72a281078d6350c5452d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 504de2660c5b57a495469f0cdc76653b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eab58cf73f291cce8a1644ac820255b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b6ecb4bf184b4ee9d979df939bf8a692: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 093fe173558890045cd6ad9808d31f37: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77f12862a1e9343c6af1897f478501c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b8a7bcca818bbf7f4b2ea90aae45a7a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fc9616e70d3d5c9294eeb6a1288d9f01: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f28988747bda4b117889060d5bc56e38: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 34a5f893edfddf9c7ba7c85b35bb19d4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd689b31b2d1da205ac83a55f8122331: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b9373c5144f980ea4a07da3d99e10cc0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64d3891abeaf3d7d5f54c26550de0bc8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fa99068e32e73b2d2fea86ef2c81b4ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d0696ebc49f92afa863864652aec2797: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1eacc9b37ce8dc1333b001044762f8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5565b54ac9303b9880d76e7aaf4ef055: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76aff92deba49f1f83a754c6e6aadb18: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c1a70bd64ebc7e494f0ee073df6c799: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6902c1f6a994fb902e983dfab4f1d588: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 94bf322ca5b9313b1eae23056cc5ee4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5286c37a5ea2d1d95472443884597b32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dabb862813951d674c95243e7e586904: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 605ccee2ebf33eec4f495e3d885adb8b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 789ad4856fd04473d248ae269f4e430a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d396955dd3d60e98d1b108f59335bdfc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 187d8b9745d00f088774cc2ee47f1016: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 92a329f57c5e09a46ca6a9bb6847e142: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f344aa7f45c2ec90bbe991c565234da6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ea33294a07cfae1a3d660bd1932db0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a658a90404082e9d9cc1a33f08d2689d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ea801e693c9defcfa15c3db342ad4bda: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c978101409520fffe72b5036f6871d7a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bafc401981f4d9dc01b3972a1001e5a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eaf14f2a05806bbef234ea4c3a72b2ec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fe44722cf3bd8063596d6a3158a816d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbc47aef29cfada145a781b66addf48c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 330add6a820b630fb4f13fcd83f92297: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 280bbe62de980dd2d87d485b21ec6566: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fafb9b8b8e289b946deaf694eb0ef0d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c4be5cd48df705a31f5b8450ee2f829: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4a3ac60bd53b946d48c31e0cfcc6afc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7bbd4c5526e8214643084836a17fcd31: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5cacc0b193ae6dca17861ce7ff1255c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cea442b4d014eaa565023c6cf3cd67ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbc46d4bcd0d585aeec06d425c34e44b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39d9e537976e6ee88a2562044229dd4f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd72440cbce88beb8c12128451418d60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 288e0aead9eab9a1ac22bff90d46e6ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cc60f3466d916a9113295bab828baa6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef32d6be980ddf959f022c06ee8d2c0c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d86dab1e7393ebdf445bf0dcb982b0ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e688131e1e02b7c21e2e9687ceb7e58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 281e06e8844c956fd15201a0582288e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ade942ee800ad856cd1ee609402d6591: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 90096556471d925ba3375cadb74dd6a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 392187b4caeb6992670f4fc99dc5ef56: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c61cd8ccc22ba9eb3190a155d2abb05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4245e58b3acafe27f6df69bb774ca879: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a102476c061eed76eba6d5f00feb4468: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4be64265537861d4206394082b65abec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7ea889a2e27a7b4b713c67bd195f19f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd7d2c55a61ecc7cbdc31cef99d4a29f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f350679f767d5d736ff68c8deb26c005: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8d43d693ffa950eb3fd73ae9d74bd98: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3756dfbd992dd7e5630686765f6dfd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 136ee1b786b281dce7a829a7475e1a53: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 10b3ebf1daa45d23f7000787eddc80f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ebefb068a61340e790dcf1aa3bd176c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 626753e305db1bfec291ff86d2f042ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbafb8d147ad301ef31754a02ac0c0b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 515a203be97011eae28f719999e0dfb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 659f742a7188926c2a6feb79c93359fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 87e1dfd3e5435bebd3ae63e3d18c06d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a39c33f250b84b43180d4ce29c2653c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 63419f91ba3f7e31755ceeee4b294c8f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a61c95154def2ed05445c1f5cfeb9d7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 982c6bcc3574a90d183db0d402bc798e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15c48b6824e9587c3e686ad517ebb6ae: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 956420032bad02dc1cdff3131826179c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2336465f98aaf18670400745d6db329a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f4d3d5ff4850216954bce1566ef6ac67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fca695ec9d336755c6fdb94570dab235: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 930e2ffd950e61485da294b5be6f391c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9b24c39a76f9a8da9442e39fd864909: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 269a73bcb03c726630927ae68732fd52: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b296251e2337053f24ce2557e041b5e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b015f0a17e5e3e1b38bd70996556db5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07e28ed4e7b056ec13ef3491f5204d34: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cd0c975cb9d0284c5aedfc05d3ba272: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 16915900c760f1f79b18be5a33eaa0c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6610f199330e8e009476c71740504b5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8d9dff19fc552c2298804a9d46b4c46: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 61c4842f8823cda36e3946722bc40a5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a8e3397d3bcb2869f0f6e33d1ce2a855: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 451a92f4dab4ff78ac9e08697425e310: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d5c63de5027343269028ea2065469a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 37fbfc797a707afcde13f533aa16e1be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c27c1dc37260207300a56e8cb19a1eeb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f16a1e7b018056b8837d8c1fa3170e82: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 975af0d023aa504a00a3f2c6cd85f781: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb82014cef196745a50732c2d4c73901: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 95686252af3bf4deab0823b362937de6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ea0b6dfda6d1ccb5513be02a87c0bbe3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8012bee4bde2fd577ddad84bb0d89567: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6934fefb7e626af3be639bb6f00c9588: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 249b539a921efc53ba2ba636a9c85f9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 860b62df808156ba5f534df21e213bce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 611ab271df1ef22d6418ef6fcafa628c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17edc9a6453e79295e03dc6e4ac14e54: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9f2d10fdb6c61021bae9e6c22ecdf4a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77d34e772e23d66e2a98433403dfdd46: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac38d16468a8ce96c8f092876bf55ee5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1ee16dc0acaf23fdc382d228e3482fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c2cc7f7f7c4eca6f397a4bd12f5d42cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar afcf77516bee707bbdf053fd6f426dd7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c9c3abb60b84f6a6cc50b831ad897a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cea89d2ccb97a5555b107b7333cabe64: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 44f9c50085021502b391ae60d7b154b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21ea51bf0d5c67cbe7619408daf9b8c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ee3e0ace770584823e896f721fb73204: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58709eb347f5fabdfdf921b24ac0a2e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 14b899a528a4492a72399686c59303c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 00dfa637e6218a0107264b29bf70d3a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a11a2f1ff277e88a597a989689aadc67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f9178c364c011e98dc99ba6fbd2b29b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 11f990502a4295309cf3a3ebc4d293e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c8927809b3bbb6b786d3864014373327: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2c52b69536a432841aa8ae3bf007b99d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b6c97e0f5c51fe9d3d4cbeeb03a01c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac4ea7d32b1840fa955863a4689e5c32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f016831b7fe0e81e415b74ef14e75b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 305b93b7f0b23c591b353f23e8bc478f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5951575668618328461954584f9cafe7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d50ec5020c3cc5120d9d393780079e82: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 097740491ba2ae2faef8bc9237f2287b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9cd03f2b8dc828c8c0e7e3d52feba0a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8e0951961b55e032a35c2a379d46008c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9a7e8636cd550dfdc8b46b5838f31f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f50bc25196cbd7eb9469fca6caf30c5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 491b51440a30de22a81b3d46452d56df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c9109c37e5607f2ffd58ace1fc9a976: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21daf5dbeec4761623ad360816dcfc2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6216e64911a73b3067d25cc29dc5a532: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a6e25088a2695b3e7f1560552ca04d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf91248f5ef20bb7128760f667703ffe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 22cbc0a1aea22cb28c38ceab83f3853e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3d6954ddcab94b9c0058a8d4644071b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68a86bca877d923f6cd008247cc98d21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2d75a1e9eddf84caab3020d312204f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d7ce753e7422517062cc0aa110e0725: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 10a5b0984c32e8b595343ed1d44d7807: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dc81633ad320169330584943fa998def: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3658efc153640e129587e53748efdc1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36a5c8f8b3a9673e3994941ff9a2564c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb27021c48e664a4721810348f807775: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41441236cbe557971cf670850c5ec5b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d93dd9c833a0c61521388a4b910910bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ab2b59912bebb916abd4db471ce02659: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ec1bbbcaf4f725306cda2c33d1ef401: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e031b021f64beab4250b435779e9f522: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c058b64ae71f9aec8ed2a88dae2eca6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec8b80089ec3d39764625b6968a765a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 56de799d5e894a7e96b0ecd970fc8e24: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6acd3281ba58421850161212f330121: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dbad4b9581d0c9a50b7b7ea0aa8763c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5244f250497d71f0b2638eb2850113ca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4705f1a39fde7391bf63485fb6b509ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d121dfbd57fa81ed0948a4ff16b0b9c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e73e880104223fd25f837162884ad7cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dfdd603fb903d67c9f7ef33c383dd0da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 25da548051313dafcd6ff3bb681b31c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 019edc17eca1acae266dfae2b93a0f27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f84e4c070801e7f02c1c35646d35ce93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 97d2a4ea3d56db74f26bdad9c85879aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f67e4c89152f48433df204cd9b55b4fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb3e6218c6725f838532dc6ae69ac19d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b9dfca01d0179ba431d4e9d3ead2b567: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3dc9ed2903187b30692c094c14b19066: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6dd172b892bca5cbd0ded19c39702029: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f183a06e79b2b149125e01c12766d8ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 022a36326e2cfbc1768ca101cc35f63e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 60fbf01ed64cfecf34cefd1f3672225b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7558dd3251cab841a9f403f70c22dece: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7df6b3bec01a933a6b0cec7fb786ae64: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ada3e6cf443cb6e064334fc9108e6bb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e3e000b4e1a4d4cf2e85382c4735c65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 220c89f072813848689d0556d960f152: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 90286813b41e41b61c9b29a3ee05031b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5cce829eedfcfc3a652012efc059d978: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9303a2fc7529630ccf355b1154a43692: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ca74b897bbd11402af1c4be41b374490: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fae5051a22f48dda5410647a245c4d9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0319386600a4911f52611db147762b1c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77e63eca2f7719dfe436cd6da1be540d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fc4f3dc48f7b066af12a9b2e5f4c57c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bbcf9fd5754ba8f634f5379ce3762f84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2dff0d4483eb08d158d031d7fe0815c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d02ae85b443e36268ab3eee4a4d802cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b22bdc14f3492bf2ee1c270e857b40b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6558826b0f0944db1b68ce8ec66e3c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3015b4ae483c759ac1f27b7b9c10db43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9d24eed01c0917ecff8706643c167c6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fcce6514cd1109a0aaf1abe5af2d1f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0da0208f213ec202ad8a7ad7c6fc0efb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77f7387689922a930ac316da36e25c5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef46017de7e72734356c4b77c0a141bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7cb03d9de8ec1cb80d0c73b805af0423: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3833ceb51e3ab0041ef77aa1e47fff10: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar adb030856e48f33023958ba5e46eddf9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64e604d97d5621f69de9a99cfdbba365: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 172ea6f662827f42c5c0acb594dc3885: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 100a9e610151ce977c56bfd2f74ec73d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0e94176c5e504883bfcd41537a5e393: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b5cdaac3e5bb08dcab2038df5b04b0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 49a795f31d0fd3d2ac342e569e416d94: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 446e94c91b9f81628ee7e5452c53c6eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3602fc997b097c174ecef37c8eeb79da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07a9d84539d0eb47e2083b0c7533a554: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f58f6c22842ef60fd76aacd192c1e8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f576ec3eda96e5ba8489b74d0e4db75: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 80e2df247f6a8550246ae1cbab737af5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2690512b99d4d6a85945a436ca3f9107: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15c0cf81fb1d9cdf6dfb12e960ede3cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4c4a68aa5ec25c592110b0f440185cff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1dfeab81492d3a9698543b7f4129c10e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50a6a9041e1384cdb790cad0e718c957: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dfe300c32228d2727389b5283560e098: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f39093c3de801304356513a618d23a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed414ba0af2623f41c39952326aee79e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39c8ea123dc6ca52907020d0f3dd16a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41177d3ec382a71b02d5668417145b82: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d85334b5fe7ef5ac89e841b4ebb84fbb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 58f508cb734182fb64494a9ce14d2723: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 656adc233bfaa7ee88e324c9f50b36e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b4dbe10fb9989768ff2a22604999ad3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 22007b25b4b8a9a4a314501ade3f10ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0341937d7231cea5db36de339ba185b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ef2e47bdaf14330a8019b6c84259507: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d9e9e68266b59581da5f149e2135b15b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5679a46d48b37ff818dd835dcfc6c4c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4755515a6dc05f7e907c4c74152d03fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6c6f9d886e98132c8241a0827943e95: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0716b86e65ebb1ba4f9917923728399: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1cb89363d15968b84d24faa80b9778c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c6f86e355e84e991ee3378553a147307: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86d4b609c6cb3b2136ab32154bd13515: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 753ec98344d30b9b3f175d8ca1b422d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 517f900ca503f814fe0006236b20f372: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a87b37175f4612932f732099a3d49d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d672e3a14114567e2c9c9a64095ca05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f47e4393926e51d367a5def5883e515e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 619cb2459dc187691cd59c0ed5c55208: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 04cca1e9d5c704784c708924353315d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7f5866d65795ff5e0808d46ec914837: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 700ceb61c348ecbc9093fdefc9fab6c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70bae5a4e6ddb231f1e2fef58625aaf1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3e63ad929b4b37cba73fec70ab42cc86: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e66ce072f9a9f5c32c79316c0f6c033: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39d58ac66a54e8329bac6ddb96a0d56c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f80962080da772058776b9e6d19d7ff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18f645068dcee768d1ee2c5611792ced: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4551ba692363d20c76a3dfdf32419d6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 114dd85e733cb3134567650cf71d7a0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b8a136bc5a175112fadc7891658896a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b65e35007b92bbcba73d67bb6b36f02: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ca1ec1ae524dca908322228cf1a0ce7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0c7f6a2317ed2abf8eea61a90d0ad05: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ad65dcf2a9643cf7db99506a74d3c90: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 384cf05eb331be2626125538d871df83: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5d9c3927404ad66431a81ff9d50d740: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 37ddc16dfbf4f326d179486a78a0f034: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50b9496ef2c4367f7b35b7946b9084e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ac11148db8df2940615a251140a60f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d3f5722f1d686dbcea2f1f3482bba6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 870ded103e216f712800d7583812037a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39a2c8d5b21b5b0501fb169479865efe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6e02f2efcc877ba9d201707ec879967: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0f24565060eb8294b440eb0235fa233: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8493c5c521c510e626cdd80f94c05efa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d194c3ba1e0b4db91f3cbbcd0d5e377: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bb7e5019602f1dfbc514f328edc1f675: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 42e5f57894cd241b57fca2f5d948996c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f9a1898f177f3f2288c5629da1897da2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e67d4867e4f04f680093e0792194a8f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 958c15fdc1c78a268cdeba8be45d86eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b1898334e60c5f351752f724f6bd47f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e870f89441b14e5cbf52c1565fc887c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b31cb4491d3f8dfb1a8b3fba7ee648f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ec9520bd752c6b10e94b7da93bf01a2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d6f4d33f671aaaef363442f55bb14d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31a64ad8f9dae76d37b3f7c78cd907d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a5fb682d81ee5bf8bd5f650a50804a09: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 24bcd4b659ae2cc58ec9240e01bda54c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 669a1f426be244937ca8b8abd094d807: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b4e17826ec4395fa1e1e82f559a0ca5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4536e930affc58edab956eaba59f8432: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b67d25a59137cc59257785bd428c408: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb0975dee2acd4dc5b2f8b8d09687a76: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 331e382eab262c21a70cfe919da13638: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 66f3f1c4d39cec7a0306382544f39790: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5377696a4551244d7be2a9ae6895ca72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3010108da77c46759347cbf19fc574f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c46503bde4c66b23e06458026697d18: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2cc925e2e6ba068a4651cb38a3eeadb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c288319357166a537cc4438cec09ba6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5754754e774e8681ccc372b810858bad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 98d34818c27507f206830aee81bb060c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb830195dda4dc712bd0f6e4fb6e7d33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb9775df835852222ae8eafcb7444931: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77ee62727d53a70d9d9a33678285d1b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4b831a7475d5511340c97060fbb66b6f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1f1ca741fe9842641e5da182fcb9b32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f132ae4f9778390864bb6b9ff12b311f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c520f039675cbf210768af567c09249: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4df217a324692573e9563b5f2f49ffd5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7621bc9c9320c2da55907d2faab067b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e5219a68ed4abba1801ca150d3f86ce1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4590c573bc5b3a08801668d01bc7dacd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ad575ebbb93fa1e453b851e7fe824d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c40c4a56a257903f8f75d2226ed7aad8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d48627de3e80373638691d76a8ecde2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4558b61e67e092daf23258dcc9db950b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39f02e10e9501003ce9cf75cee36501d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8dd4f8aac005261af3f97f8a04176d9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a84ba79f17bd33f7aa8bc99f0f55b09a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa2f775e06c8afb6540fe8ffbee6eae0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d3002af704ff71011f8da90e51f0d37b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 889fc649f7ebd0cea601aff26ce8256a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 879e57e04fdbcb0b05bb41e7fa597060: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 035e4094095d94de88c1e751294ef80a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48953e0c96cf3bb3ce5cc39bcf956a4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a6d3bb9698ba48aae9ad44ad953c0a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fe24dc3a4b50eeb8571b9812c253f999: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 71a2e3cc3816a50c6aef3bcc4ca9e19a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 27793233d7767d8390b133cd517b2df1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c78f2ac9f5670c548ff69b8656ab4db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b8f510b9401cea1b0f156bbf79d0381: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ce3cd745242de58658d039f10fecb64d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c7bfc4301b3537bfb9e33fa7ab176d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a68156facb62d90acfa2bdc8649ae3e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a86db20eff653b1ae8841287e5c084b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77516a4a999b4cacb9f7a1e11e4a74d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4bca11b64d5afa66e78041d358e3ca93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 796fe9a7b9fd27f82aeedd995fafe105: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 743901edc04ae0384a3ac13f76c7a5bb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 92091235f389d3ff0837a39c24489d20: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1736b6814df2ca40779ae20b4ef81ce1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3286c4024539fe29aa6ec8754c903c7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 290552c73707c96cd97575092b725a8e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54037cb6a40d2f86fb845c2cd052d6ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 481ce4d1ff2c9b10396bd1736270fe1c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8e3e426cbfd24cb2a6521e9442d04751: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 31a74db6805b36ce9798f4385174e7b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b5935b058e7f4fe5cd92592b8250f67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c0a1557b92883d50314fb8d80fef295: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1a5e889ad061f16b0eb4fa9d09c40627: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5db2460035016903447f7bbdb8bb565: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 26b6b2478eb8444a911eb5ec20856187: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50a6c4779149501e60106e3e089d8a50: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 21c896324701e48a2ac79f0f08863012: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ecc5a5a297d905820c2d9bc3bff843d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7350bdd26e6fcdf3d7d3dab8ab3b5d10: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0fd9494da78e57c3aa39c31c43b4b60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b2ad368a9bfacba2c1e2d31ab2f203b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4850479b0cc2d5068ff3449e4ccb54fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a35f70841818dae5ba3a260412314cf8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bec49ded2d2450eda783a6112086c7a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f8c641c3e4ae37e8373ba4d4b2e6e5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0934fc0ffb983ac3c7c62733b871da48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 587ff1754b556c2eb7dbc239f97a58a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a5a86729cbc1a594269902acafb68ed7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed13f00a3520779718d94e9b21f6cae6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b8282e877fa7993df4cf34dbb25240c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 61abb2a53362b9f03c9de311bbac02cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 12204d6c5f7582310e04fb17f341b252: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 326f06ed740fe5dbdac1e494ebf46aac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8989355c95645067a42f7bfeb98f2678: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2c46351b6e1f15a9e8af9ba124d83577: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7494f3bd586179fc224be5cc47d39d6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 855567392a1d5567429c8ee1decccd63: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 45e0654eed02d9284aa005d32d1c7751: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f4af2dd478fb12fd32acec939d031e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1551e5328b894b037816a8935c9370a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6baf7c06747d1a1a4e839c9fc7890a23: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5e0debcb06831f6565309f524592102: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28df5ca246e033207718d8ff524d01c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5cc39b803bd43cb502d23334df8335ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82cca6e616135f4947dd176eca082456: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 839dd408a3022902c785ff89759813b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c45b57851d3491c8642b0f5821758c15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9616920d000fbdfec793f2f1b4ffb108: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 048c2a1e2a98aa840a78223cbfb37f51: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c950c5b164fd666a5552e89747efca9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2c285310c8c5602c6f754b892db2add: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1dd8ac41de345073e5cb5b395cc128d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdc10b4e4a71a8ac28c07ee5e75a071c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25cc225c834babe2655f13214f1cf269: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43f47d75cf4f2f2279c01528be7383aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b767c88c2604a94f2ce36dac46d08da6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 569b9585e10887ea96832f5c64ba4f0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f7d207e9780a052e02069fef65467f1b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93058fbf91a97be112ef710302f35c2d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1556b7b750476a7c237e725a1fbde82c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05953a9ed9457c2ae162751d45c61058: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bdf0a59a18ae0dbd4b8b3dcdc5c64a5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5fcf8e549b98fad1c0ca3267bc3ff173: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3cd03dc8db661288ebba7531656e93ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar de80928414e8041641f1cd232d56650c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0ee6e31b1af86c7c373941d2592ed78: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7375e81156fd026d1d52e4246ea0b115: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d4869d32e92c7f4884437981dde2648: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6fc4cb752269f2ef5572a832d467d12d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cbe7397646ce87fc061447e651c0279f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05d8531cbfecc24dbbeb1aec8fbd56d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96a2684b66d43702d97aa8c530a8edab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bf8b8420e65414fc890d2a31e1291b0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 28ca1517363738b68b3af668b0ccb453: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b085d57a7aaae7061a57d954b9db0ddd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5183e1d050b13ccd0f3c426d93a944d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58028ffd798704650b6b1ae33b55d845: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d97071004f888614052cd43e01b1ca85: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 069f86842613faaf75ce62517e2d4f94: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80acee329e8da718e0bc82605d8778be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9cf0b3f7e68574e85cc73385a782383: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2205a75a63325955c13d284d5061b48b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f87fc7b235263ff890009a089aa392fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e65d198c4188241e5d00050cd543dc21: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 18e57ece895856b91732544ff6f370ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f292a5ff8ca06f01859f6cf94646b7f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f67b380af0b5789d9be6d905c93139b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar acc01267fddde77efaa06156b3994c06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09852a35c8d2c25da2aaf14a0332598e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 09718f9a59636f6592de92e4acf8797c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7016ea89b498a688ac5ef3ccda10af40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 29ce96a8ae621e6faafff808b79755aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 821f980871759ece328028fddfd5700e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar de96c5a2e266efe87a9d9c5d2cfcf811: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc039940ab17aa918c2cc2a9445aad4c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f809e764df3097a6283a7447f2ad0bd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fcd5f73196fb211efa1ead0643b37a99: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 501b0bd3885bc4a4bf6a4f8d825e76db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 96ea821001b9e3907b56c2f8fc4f882f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1126bf5eb0faebf4194af41181b298c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39397d29d179acfd3642d89d5fe36d7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eaa6256a8d417703714a0aa63c829eaf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e59e68c3d1243cb9f354ad3587607fa4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c2053ceff06701f07b300577f7220c3d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0887d3746fa6fa9fc8e72e36b21843ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e7fc83d1ba735bfbc5ccf47c80f7ee1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ee6f11a2d5ca618cd9edb0d3d2d03a0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ccb16704bd62de84c9dbd70dfdc6bc5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 648319806e8ac94fae80550ea1b86ee2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a39e74d66a070658a3b6087a47f11d0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bec2c0495e3b7ff23f2bde3213eb5979: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 496174e012c881e1a8af54e086635768: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a26ea4e73121286a30c5a26621fb76cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 984d60a13b2ead4a77f5826e862e5a5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b44e21af4bf25de66e98835083d3247b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 87f0abcfbe76285c908598f6160728f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05d2317dce47f27f17c81cacf209b7a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a4c4adb55ca7d3cc20a2ee17107a108: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f8b4b7586edcfd4b5d5e618d6c6130cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ee327f5d43a46d8fce9bd44d3acc8247: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49957b24461991bda9ab119b0caaa366: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 553556bcd449aa2e01983bf4a2bb3836: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7169a4f0b5aa5e4949ffc8385a504f3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5fb2b8ea6ab84029c7cec5cdf16b7581: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 624a2a7ca4dc781dbee47e5cc9fab0a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aec4a065bd994018c2ae7cb4dfe4f8de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a32c41d29057c33571b24daa0a61f82b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ab55ca830d25066dab2701acfe1188f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 601862815cdb97e2074fb28ef6fe021e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f178697b6fc2f05d090b52e0685b8a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 605f1ccc9a7a9df1c191aa2c91e8f335: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67ff17501384a141428d3abf61bb50a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2d135e93842d46de603c12deb019db7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a6aa707fb26a9fe902832c360f71b5a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7b5821e50a00ef5f5caf85cef8db560: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1610f20b4a0621c8cabe3291df9aa6a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 471c2e019512205a456335bb3c761e8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e08e47b250b5778e097488e587bd177f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d084079122ce5dd4bf322d5438c4142: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 21adde9389154cf690b0693d902a35ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41947672a2e2dcd3c8c37c0593858420: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ab5253df60121c6d49bea605b4861ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c9a492e11deed091f0ae258f8b20e379: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a043f8ad74315cb5b2086dc5e2f84f7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar aa5d3d884ba8520faad519fa84dcccef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57930e3d2592c4d9ce6063e28f5f6448: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a954e800735b30d5ebbaf55cc42ec4ec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f3009104588206ba2e61ecf7337da75: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a8c54f43ada0be61675043ecfcc2051e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9db933363ab40bf7c6767f248beac916: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 40ecd68b1c5fc421ba1b4b4696176b11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 744cc4dd1bdb8a29bd671ff4ab94a18d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d16373ffc673563f7655b563240f3f33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e88a573bf750c278ea57f87cd9eb920d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 87bf205274a9fcd5138b0c7944c1723c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23d44895eff6e38b7e9acba3f6b8e361: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c5636d0f04b7213df039a6448746afd7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41ca5c07eb95b590effc7358264ea384: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1971bee3f8798eafb3803985f628f23e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 142bb44c4c9149a73c912ce4494462bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c4d39c861acb903c4d920f0edb721fb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0ef3e5f6e3b14a8f3d536dc77be187cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fd2650b1d922724aa0b16d3a4a97d548: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 185191c865e4482d0a8d9aadf819d655: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0fcbb739663c049f894949c2779a9a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0a0b2466d1107bfb51cfaefca0279be2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ba983e6c393282a624a1d79fdc2e7eaf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f6771f1db48a76a872ba95013619b4d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5458c6128c3ee0138407bb2cfd903275: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d9f0fd68873b06a6206df70b17edcef6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41f0d296a354c08fb3b545803ea2f0a7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f8efc5f2fa0ea38ba70690d62009bf1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5bad2f9bb8d2b12b2f2210214f613ed6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23984754fcec3a8daee6ae691f77d909: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0fbaa1e0d83700fd19e261b0777dede2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19955446a1f67facb95891d1a564ad56: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 97523a9428e5195828f6bde6155efca7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 457a2f686e759232dbe0de1f47570ec4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1831635fe5e792f2773871d9b8b08c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff0b4b1b35f8c250b85d7d2b89598c7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar eec8bd2358b5f3296bebe71abedfca0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2efc4036fb6967e924722efe6a811829: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78e10c191fb1ad33947bd934b86bddd9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 84f14a73dfcc3ed7f8df538311da84b5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23aaea89256a8a4e405f3a875205cfcc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 846dcbab8e931627e7ce0575bbce86ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4c05e38459cbc040e103c34bb0a1018e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 391e5c76118631d2ac0109f2f51b3015: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3eb584bb446cfa520dd122f6899c7b1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 019eafbf4caec28472b8f85539981191: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eac61e2292dc09704fb2545c2bcc7195: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f308eddfc04b028f11d70afa17c53a3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b70ddd9195b090c679c24bf2a56a9a11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2f42ce93bd1dcab5722c1aa0361419a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfc872305762ffc446e702fc18dfbba2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b7d1be00b4e20877e2cfd4d20b78f8cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e8b870a507dbc4ddb26eeab7cd6afa7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d2287bacab6d9fb2430484d4fd2c8d3f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ceefd5012b310e96561d91cbc22d3e7d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b84ada97e72ab0ff5eb2bfc9b6ce26a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc4bc63e66047dc9631eaecab34c4040: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ae1c7ed8d4db6aa7577d23a97ff45eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ca753fcd68e4c53cd4973eac6d14d28: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3ac43726836cdf3ffa49fe5949105407: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ef3283670e15fa072cfcc9cc4277e70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e2453f2fb836f564b333745c592afe6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb0a9df7f9faa05d63973bd0f78fe4df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 25b359da94c09738d98ac443e2b68d5d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a4b693e0d9a8a7b403088ab6b947f334: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 60d51faf56e91a17639f6a7e2bd6d533: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 36f3fcb6791174bf9b65138cf7990326: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 195851b1750ea1a1c03a6b6d7c25a3c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09b30ba411c2fcf237ecbc4fb4de160a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 669f389f6ffea71c40097055fa640b94: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 622698df629423ac331ed08de6c1acbc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 729e52cacb64c5b4a005d4ad77e57cf0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1abc4fb531be3acdeec8505fc0328d69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20d9af38e6073856b0dbabdd66f63479: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 479e6ad06fc57d7477266bb328577d31: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 73777c8e6cb3bc4a0281de9edc63ffa5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6b333a341f60f5fcd852967db9a38ddb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec60eeaf6645bf8cd9bc7722c1e28309: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6f20b112276c6f71bd487c6f59ce29e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae4638ac109f136b541b0e10fd232e30: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d551a28e6795bad4d8881f83dc778bf5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7206db1e167e9ead00e5ba61e806cfce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 487d62e93eee626ce514c825a3f2a7eb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2e2eca4fbd9fa03daad7eaad4b193e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 092e88dc33ec5d65cea5093df0b5ad8c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01ea26bce1e842b5d58e66b389611d5f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ebb889fd8bb3bb8018fcf5d8ae916ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3e1713c2d75aac572c134aa2ee0d47b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4e6a157b158390c23d8bffc1fc885d56: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c7d8ca37f3edac7b52c8a3f5f552eb1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b740f4801fbcdf8e8559708f48354d5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f2b7fd62942ac93bd94915dff8787d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0b8dc2e8652161c0a09f4474e52d73db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2054da332682f231d089115f10c4e6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f410b652aa862dff6017d0a84bb85bc6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17a4a4242e93d47bafcfe97c5daa45ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f5dc6e4d69a0c7fd45f3ffb024608a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da1579a82d5bf194351010a59989933d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5de563c2cfef607c2f5437489a18906: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e280024fec5bbad75aafccbd867c630: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e30d62d1f5bca80151a9dab04d76df17: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d80e95fa0c0aa3fb5813aa81b0443dee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d8f212c3850777cff92389c69f5e141: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 092fc76498ad3715cdedb06f0b9ae6a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc8b40584b41c9e352dd9250d2970cb2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 97c6b9c51af9d17711e765aeae1d7edc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01fe16166a24c3b774081a8390d155ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f905272fdf7ae795b41d9a8271a33400: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4211681127dc9ce2f533693b18f3a6d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39e2de26e03d7a5fc9df4d817eec1859: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b21856394a84e95078603eed8c3e91b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4714a894e4b349340d870d47e06d4ea1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f062f19344810c69cce3e38367247a11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar aedcae59c294b291d196381b8970cfb4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5631e124b77efbd6fdcd6162dba6db53: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d2cbd922c749aec18d0078bee210ee0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cc5bc12b010f1dadba87335f18a38794: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68048505a1c757dd3e300af15e5ba127: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9d404a7a7748a1b3469dfc91773b359: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a740991bf516d57e3865b189cb5c7e65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2fa692a035aff704d0ff1850d3e444e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c39521e5d617550c7bddd7cc76f445fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1db511e384f7ff19a4bd556fe6658235: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6b306d62c32fd40d6c65b02957c7eaa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fc7264acf80049b7335196886721272: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 753a00e422f1b049003b0d1eb352e6ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 35a7c5844e1bc79d0c5ab96c1c528329: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9c8bb9a6b7e80aaff1e0f5a9a74f3c79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01515f70aea8a3a71fb716b8272082bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 678e458c221a27964694ffd292acee73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cfb4c14faa9125860d43f44b2e4eb277: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f62e1b4542b05e5581ad916df6466dac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 59c5249fc384b40c43dd82c9c8ca3d28: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c613a62084f13f0ec01f39bba9553c40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff5338b8b0bbf8856175afb10ac09319: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 67d46669c088369bae5003a1bedcac74: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed16a79d6b88ec46386433456c30bcc7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 576b5708c7a5a22fbc3377246250bcf5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1b26c81b74140ea7e24168f8949cf859: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ccae64caede93fb4a2bd3949024ccd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbb32fcce78db3c0789027ad54e81830: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fd088e76625692aad1bac5ac2ff8ced: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0378889028f5c48e2c3e12029808dbca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f0256b5480398fd93c3c705e62a16da4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 87496886604400d5d3fd6ec1d83fedf2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65fa2cf832413396df128372f931fd39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 71abd0bac5963b7706ff6a91aeef16d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7370a7d7cb9eda6e0dab1ace4c813854: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e0d6daf16b67960d7fd01810f86f96b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06f2367abe05d1a203c1c4df6a37a5fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0c5541a41a2af654324f90e9b5ced03c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a17210de07b8f7ffab00bdfe01524eb3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3a1f1bf92af623a2316b4daf54dfab84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 42368d73012816eca30ea912e9b792f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a275ba0b3897290bd7ed71a268c322a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c6548ff3682e29b35103cc86f0450aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e632c9827c7982520885a335ca12986b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 185978dfaf3e22dd03e4bb0a5b3ff481: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb828a626b2602ad0a9b626da3d43451: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5c21fd0e513f4aa4b3331c9f69ff051: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0409343e82c43f6f1d75426b920adfb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ba2022e03fa5e130db5ae200307c0309: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 13c140c3346b04f496d324952b22f62a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c43b87ee59e0858bcadaae89fd4f8038: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9dda8bef0d83701325de927534032fcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06238dc84c10bdf709cf2dfb49260e33: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f0b0079c90436ea1dac5fa2d71284799: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1d0583b494d8c254c56621d97a223098: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 151e6e63630433ce1f39c1c75f37f058: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb9886ca5b6e6487c43ce5edd1a0dd26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 476307504cd52f777ab07c237edf357e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7bfe5616dc631bfe53b4c9685fcf591f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19f1d3193e1890dc5f0adb69cac474fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7ec98a6eef8c257c2e78d7df0720856e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 629cb8b06b5365d214bc8685761aead5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ba69f6792d346008d065e32efc34d2cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3999532ada513a3ebf013d2aec9e8292: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cbc588d610760df5a8e86507900d71c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c63c419aa02da317ae8fae392892f60f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6190d78c478f607d0ec7287d6b8353c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3838f34fe3371bc0de5bd101286f2908: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 805764102bfb6e54d93b263fa086e16d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfe994a19881324241d75ac9c399b1fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 326689256776cc0be7e353f146cd0e08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc26c5d2376d536ac83942ac199355dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e446dcf2a6accf1ae5211ae6998ca376: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ca134e5f267d4e77d62432c7d7248c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9b9b31b3c86705bdaa1ab8973fd6291: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1480952f4e81bf73a8db2033389a0b1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 210b5687e2ab84cf6efea7214f9a807d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1628f8d50ddce3b0e53bce182ab2294: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3ff8e9d11bdc956a29da76f0172e066e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50344637bf8a9abaa5c08922c5a1e5e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 583beb399fd3385ed26075652e68f2e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa64c3f03b12d130c4753a0d7079c438: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5cceb05825583ab9d6830ac320d39baf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7eb5b9b08ad81ac1b43817247c0b51da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 395a424ae29d2d2b0368b21d99def649: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f31cc2c2b8a02973ea4298f98e2d6950: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e399471c4e71a1c3cb14c8dc3b365ebd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5bbc7ad731add4e46cf4e85ad441d0ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f03bd88ba079102a563f7ed9b63afe9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e83d0f39c41f372222fcbe5eff54d8ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d36ced7be2fdfeeb47fc7285fa723aa6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 87154a8506ac1f9d48712fb562f4fc9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d25f44de2a256c1afd81d7b6239e2654: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f17fc39b5f0453fe28624e3503f34621: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f242f43c412b4cf645acc9911b441987: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af0ef6f2ec0fc5500966618377eae7fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 40f7cfa624eafe96f2d428d62eeffeb0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f7f2047202e9ae44482161890349000d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2a382fdbd1aec3cd219dc06a06eb7a55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f3c1e25e7b4b6d1a4058c45e3043362: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3525c04291c3b27c1c80d15a11c8cb9c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a0352c905f1a7b9d22a6832557758ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 539f43060bd122c102e31e4dceaf5d10: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5b4d0466cdd6560f8749249483e61b9a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7093c293f29b017af23a7dce45497e41: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b0762ede23a211b152fa2093618b7ba2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7efdd8ec7d9b8f8e2a72cdbc1806439e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 34b2db56a2b0bd7a36bba5ff7d913136: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a023177c4917019192e966d3bef0b88a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7ef612fdaa621a94035c65226a374b61: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 950fbc64d817f33d2d5959fe8db6a844: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e9abc643d3301e3d531a0b2aea932e19: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8962ebc13e5182ec93cb9d132c8c0075: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1c8e0349e68f3bd7a34cbfab239acf1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 91a4e05f3cd3ddcf34d81e5ca8d4217f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6e7bc8d574fa5dc9520d272ea43d6717: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 392ed334cff5cc9a0010877acf170d2b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 13702b344a697a356825233538d1cd6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e11aff2e411e51f003aa7640bc8982b7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 165392738e09c6c707f761e83bce72d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f101f9b7413531b93768f934f92ea09f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 547d28f681a16c7d87e71b336b1f999f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 038b3499d6cd5348d809f3a854f8a69a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ee9ff5572cdf741186657726c41209e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6c58f33e089d83788951867383b65389: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d47d051f71a22070d7077c113790bb22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 191507e7be0f06919484cf928338ccf1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1d15603d6d421746f3fdc877cc921684: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64209fe53afb539b9258457a292b588e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e2101eeed6d20e059c68152a1f285e60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4da0c7495b07c2f2e01fa353680c6e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a115181df8bf93080785ec4bb4506f0c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1b974ed9e511050a860ca01dbd857b5d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d10a8c58d17a16d9e0e1fa42fc49849d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2da7bf905d31e5595f6252e3172343a9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6bc44daf5e2215ac43a98d072923d8da: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 74e9f1e73d2e2cfb46f88b05561fe975: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2607c9809c671b64d2aee1778d92a66c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 59246e91dd6e7b6ca9e49ef098074884: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7059287db9f1d1296da8abef1ee2371e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a75d090556352b880ed9ce646fd3b56f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d28cbc03540f2f684c945253463e42c1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 45e7367e7f8fd641032ba776bb41875f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e6c64ad998084a1c1a8c7f2279bc716d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d4290ac3424ae03ba687a37c5e932408: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3317999f87276fd10a8d8f4f1d36b93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ec6044c4898df16db58264f624b5c65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dea00b63cee3cbfd71a7ef4f2932b708: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49940d51c092798966a46783c8477f06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fc01194949948348a0f003b25ef24c5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d361cd0420eb5971ff8420960692b668: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70565fcfcc9ad47e298e8f9e96298b5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c63846181aab87c65a837c8fe5dc5393: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 79d3fdd59efdaa50277aacb49ba32491: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e7334976c6fd76d9d0ec98442e2788e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd0a1e727d49cf463e378bdc0ea690fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 44eb71b3ed668cf8f298f1b0e74c8f74: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2e54c27905a5f45ffc02181b977b177f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 404ef9029cf8e922d253d7bcaa59e498: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar deba3476efcd13d8ffcaecf8e617ce84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e1e5d4ad2cc6903f631e966fbf85173: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59941d2f9331b51de44d17da61c62578: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 620a753965ea80f0ef3d2d9f02ff02ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c55f4f71e2b7ee38a99dc5de5aa828f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar dcb05e3a38314137a1c24b3d8a7b400a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 763bc89bd4ff9b98c71b21bc7641db0f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bfc8358cbe5c00df7967568239f46991: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e10bafa6054790723688eecc31ad473b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b1faf415a3fced8ae865bbd8f10d0dfa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0416126af9a1a3d11616cc2b09b5cd0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fc1d6d4b8a814473412bd683814fcca8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5437a41fdd920288d005631c94d8568b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e2e82f0d926b3a472969a0d75e28ef3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bff92a64c34641b9903ece829f77c071: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7de9df4f9e6fa6f214e18e55311c09f0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 776fd9e3881807ccfef03a57077854a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c56180fa53df868bf9942cf6e3636271: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 105183328067f7a68dbb0ba79bd61912: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3912d65fcd1f932c076e04c4f978116c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76cf553e24171f4d94ad9e02140063bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a8212f9e752f1547c8739b2c507dab50: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17d2065ae48c4e9d49b6ea0e8b000986: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c7d3b24a00655a080f1d2e28c96f2442: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8e68c664d524d974fc4ad519724d501c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 03cb4fd41603a4e4410da1b02cb692dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a40a530762ff7762578f9c38aa593e9c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 632d6eb2b32f6ac02b958627c77d3d0a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a389037f55ee8a249d4512dd5a998fce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 06e1c6a6873b4ac5d4eb7e8b490b589c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 63dae921753fb45dd4ea0d2556fefd17: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38a5afafa976a7b45ce38fe1b32179b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e24424ab6fd7fa338dbfaae88dc933b8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c6b36b646707c6121f018a74cd0d759: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2512b1d5587f8b23f3d814dc6a4bb656: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cb2ca7f64bc541b7ca5004ab668d09aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 59ddac6a1c78e98c8d04a9ab08dfeb40: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65f6d2a0ea159748026e0f5de802b567: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 910a719b2433a001a44f7e24d58ba000: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6baebda8333503e7a7ddf731d5905db7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 406bc2eb59286ed1fca8881cab3c13a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 79e081779db4d104bb9f076ba09406fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar db2c753b66768ac2d0fa5add1aad97fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26e18e3bf88f3f837a73bc8622780e32: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4990174e7314509d6890fae38eb95500: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cf0d082a824cb8376bf5555461cb6e48: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8888ea9ebebffe834e1488d660ea8ac0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54c84cd28452b32ad79beade57385e68: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed09e9e551203763a50dbe986e922d7d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dbf3792e1becb879f5af16291ed00934: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 39b79f8c2ca2854e644362f8ca24cb3e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e11ed2bb576c5f29a292672f3afdd87d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 572b280b0f35cb33a9cf5eaf97c75ae0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da40a65b0fef6f31556c97a88a056327: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac9e35f993d0869b92e4ddc2a98c9af2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a6be7e0a2de1e0b845a7f0295c8f67f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f63042e7f502160218d0f1676615915: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8b97c42baa463a069eada1924fe09616: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cc6953d8ae6c6161de772d9229801d41: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb745aee5bd601710d61a71f31b25fe5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 49ba2ef00e9028a05c9fb49a960a7c43: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3d5a3cd02925728825f762cecc356e3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43fe34e152d57a91ff176867e4d7019b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c60618c8d9eba9c0865e89f97f2ff5be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8bd3eb07b3c88054a5d3d551aa82450a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f830f1b6b3c1c7abdb6b797c5e9282f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed7a48ee4de2ab1f06ac20c7885865bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f28060c8f4ef006582e4d8626b3d5eb3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 97d680b7baac4007e54169af2cabf139: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d77f849191b807dac2d98d4abb6f50a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 96c65eeafb07e2525c2900cb4990887b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b7e192f6c014f311aca7c062cac3ccab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35fa6ecac8338d6d3cf04314fae48d1c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9248a939e2c2a2f75c1d4b9a1de1815e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e881792c9634f963473a345a614ea2ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 198eb65858d6dd95bf831368d0c93ea4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bff185481a9e247eec29db91b08c8f08: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6572ec901aabace28d2397072ef86843: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8cdf3a1ce84d5082ad75b64d0ed6e094: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b91e02894aa75627b50826fb5190b658: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3e0b4570175a2a6a38a963c143a981c3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 982e479e91a6a08020933fae965366e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 608a85fc3b4bbc147bae7e964b379ae5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 457239399ab93364886b89ac9da22394: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a347aa1e2dc92f8be9f0ae86c95cc72c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 124eec93e8f9edc41551e0c8d4e28b1e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9187fbf9c11485f048dcc040f9374689: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7e67b0638c25a579e82050959de7008: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a5618a42cc036351d2ab73aeed9a2434: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1ffef573d495a587bb15bd71b3f8df44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a73140ea7ab0bb465a0ab8ab83c09ed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 733f763f424deea208206bb79db4a4f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec64f8a8f7130a39ad458ab75abf207a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 04f76e4132ad5784ec695cd76c7bad52: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ca95ade9ba1fce75fa2bfb14a3968934: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a9f3d9b1c603fae47bb392193c944cc3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc17dc85e57b7338e12800b34f81b4b1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4847e6552495a695078be8a4488fd496: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80958a93e51f23f71272d19d4a336700: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d3de2f212e28315dacc4616a06f6746: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e590f57c301179e2c9a78418bee8dfe3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3bc1150eb8f4cd30096d51c7e33ea4ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d865808fdd93c1bf2f14d5376b07c3dd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 17e232f0b25070d9b077f1f495b2d3db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f66fdbc3e1115bbb51708376976dd78: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f325e7022434f0fd0ae43483444d038: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7701f3715c82f2da1c71a22496fbddec: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d640b2d3311603a591d056e8b7bbfbd4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3aaf5271588013f331d7d49a5d19cad5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa73f0f93515e11cae04344c8293fb07: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a38ffe4dd467ae2f80c3a83235651d93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e45b1e496ddccb360ae84077b27c6835: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ddb976d2af0b4c9da040984ffe8f50c8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7f901c8d37a0a3fb8e23b2fb86e8b1c0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 823590bd64b518d7c2fab77692000ec5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8472b2ae40cd07d6473cbb2adda6eb5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c7c79ddc1aa6587d5daa91c18c175732: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 627091d83f0c3b770856c266f82af4f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 216d34843fcd7c082b90058b826f3735: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c1b244a3ce2b0008382cb7ecfc101980: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b4b290f2e342969f901d6f43610fffb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7330b70ec808737b37feb36019110acc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5dc09c02c255f8c2f9f097ea085bd5bd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e3cb79122400efac8dfaf5baecbe7f2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01ce01b0a4e0a47c9a386cce84d338d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ea9ee0ad9cf1009cfa4c733fbf7e9495: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc0780569641f9e941da6b0f50ecf888: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac3eb1db9833678596408ca62e8bfbdd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d9a736d1594255e79ff68a58c28a994a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3812bc9bb185a745d6370b2c7289c158: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d8c28bbc5ba6fe27decec40543c3eb0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 2bcab59fdb33a5c533117ed8844bc439: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae17a29c20764ae27ef55122fca4b980: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3ca07bed32f8a85560234b9a664455f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 72d4b915797b74f9f04cb48a3bf2a7c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 26167b5396ab7bf62bed69dab0e9c85d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64eedc7389878330131c6067c3fe2788: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 08578235acc13215f236237c697de412: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9c4f00f7ac86d858f355d4f890eecc63: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 588e5a0f1cd2af17806ced7a5871d9c7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43367cd92cf19d3623a118374386acfd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8e4c570c7fea63c5a601a67a72fcada8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1cceb11d73ab08e971bf13f0c4813f0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3548b2419dc62823cf4f8da4993860e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65d2fc1e52b0a16680133c932c480311: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc4f80e534a5d391f33b64596303acd0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6669eb62d2278dddc9dcf57c1411985: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 45c9db25e55347c8914b6df4aa197e75: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0baf9e0912467c89f0fc5c4a669a3251: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2026ae40987315f0d6299453b23713ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fb94930702576f424c748130566e7a11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f05e0c7a5e966896ffbcdfdd1424314e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5348b256ec31daf6b849fc762553a60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 14a6a3c503316cf4c08e88a92dbf1e91: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6eb469916bcf93c89935a26abdd0da78: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb54384624ce5b2a579593af633bd163: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d769dacab7c32aa2af592284c6aa045: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2e8aa78c8d7bf5771d99f83e2cdf62cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar acd8e152e11111687d2f9e3f9c69a45a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ab89769eda54be7d8d2d1a7301e1365e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 24318fc91313a0e7327cba9cebd0889f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 689a1f4b83fb03db5b830a1f184eed4e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 16ca2627be67004073da82a2710fbc0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2eb0ccbc07b0884efb7fd322f461742e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6a396d0ef7d097cba08be1b37fb17529: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c541251c8f36168fc7079cf5011aa42a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 324832fffdb3df1fbece00294c8dda19: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff0c6abc67c42dbefc3b87a0ca4f67dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b75914173e7e3af2a4fa7867cb4c1f77: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 115832995582f2770850d654d4d3450a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eab7f5a5f4832c5047c441b6464c4fe4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c8e06e25b783c189fb7a94b87f8a8020: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f935f8f765064578040c30fd2557583: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b42041a1f683cb4fdb923b274df1289: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 687dcb3a0a2523cf23f68d2f27b0430b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 645a6bdf8103b126044c49ee6861a800: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd493011ddd10f585df1ceb15844bec5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 721421ef01363e0039f2b95c09e38916: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 66c46db283c3c07c43320cefaf910fd3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b35899bd2b4ecb4c4bc9c9755c0c634: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9b99cb970c333ac95c17c93b1f21306e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbd80c9a16f5770be76f20e1fa8b5e6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a5d8f31006077a43bd8ef291eca7b83: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a00b05b624c893f5807336bb2c2fb164: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2966354ea4f08091e89cca823cd6ca82: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32020cec42d76b26d6c43a88111a10ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ea78217cebe292cd5d317e739da5ae3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d79c4c2f9f63c90959dbc35ede0b92cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3978fe7d5741f67110ce7172b9a14656: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 09083d21931140d1366c13ba450ba58f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58f89b0477c96c5be23b188b0891b8bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ba67a23ac795077f164ecb47a7d95ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f98564996425e33c2574e3993331c232: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1d5e5393324438528145b5c7361d6db5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e46d483330f3896f923a7cf2635fd438: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3c2eba94f7c38f3843993899f46bf7fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 93cf1556128a44b5d936308fdf730757: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 458cd2c901cafa6135d3a8a1ba420b55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d35797c53b179e2446c7bca54fa0a49b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 152eaf079b80e2341ef58dcb39e45248: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c6c9f54a5bbe58e76f4b8a909b3d1013: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b324c594e2b8638ab2441e8b376ffb3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eaea8cc07f11b939f39248a1e44b095c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 35a622aa3d0148607ab7d7782e6ec2ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 22638d5747485d00f484931a3fecfeef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e864f292328ee78caf1be05ad0ced73e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f81e15b4c074282ba433a9ac057238f4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f83520e4d823bf6c1a02553293bf5399: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ac9e8ae48b95792329d6a9c488f4c6b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8fe3c4e294d1ee55be0510313cc0ff49: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ed1e30ef1c0c9a3bfbecc48b3af4835c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0d55c75588b4f36b5854bb8b948065c6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1cc35b7633724692734c91946c5ab4ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ed8e958b39f4e59e53b9c58d90dcb845: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a946d5c9ba49dc34ef2a6c4ea309bf5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c033047609c8d85283c24f066a7d4d9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cece4fc231a424a3880efe511e6f5951: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f407982f3682c5df09ef98e062c05aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 11227fdb46232aaf8b079dd03b02075e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7e80aa3f730297f39436eee539d8db11: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar be444784a392061650382bf29ced6d3f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02f4b50b0ecff6b97c4cc5adf26f29fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 363afc01c7125f3ab5d22e9c7e0c6ad0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7048d885af691f1a0d72affdb35f1f22: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fb0c09fe0603881060ceea293c3d4a26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d40e3394204f651cd4472331516dc03: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar adee9bd4f65d4a1bca8f1830a87b2092: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e82afa3a7e878ea3c7604e6a58516f87: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 74d6c542b04022bcf8a4ce97448ee0bf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4ce0602c467e017bd371a7dce34a5cba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7f6d0b665707c08600c8a7a0d3faa052: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d01cf6890e235c8a80d8764c28143d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff4706c03efa909ca068caf178d3e3d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f746b1891c17ae2c24119b871c69f727: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3294efb464bff3edb2cabc322f3c8071: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8d1acca3a915de8e813e77d03c201a58: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6dc2d5962ccb2b62876efb26fbbfad20: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a5c6d8a7390d4020b759f431ff0bb9a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 33d94a21603d2a276f9ace930f91e67f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a0806bccf5253ec790cd1023b4dccfc9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d29e13ad8f0c42c82057e71096a98cfd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5f92fd9b9ba088e88a4017a10078840: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82d8a7fae4473348874cd872c441bd42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50feeb3fa798f30d809b5f9fb9eafce1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81247cfe5c03e85a436808fe483b2d15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6f21ee1f8262912b57dc17b032bbcf44: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d06502c72987c214211d62b8e42db7f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54be8439a2d10ba64e3ef1d7f8b0e54f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 181d25b8ff43325fb7eebe35a8987e92: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a772e2ce8b83f62850ac9185ecb7d1a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 36903d88c48b5751b64033001a1ef57d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f30061031c3bc54dc0a95baaf2c1dafa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c5fa5f2919c55979cb0ad3ba37ce176: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d9fb46360b4b8dd243d8b8792e8d4cfb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc5a168b30f8132267c33bf60f3766af: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0ba81c9088692b8076b4c2ff3add1a4e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd9c625367897920191fea49dd8168bc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b34a2df2872c84fc9d559a691ee95e0a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 99c2344354926b16a2c20048d2081841: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa2e5d172b985f56d3a678d76498b302: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 79e5c94642a5e4c3ca7e96c47bcd6f16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4c16166dd2cd8aa1f1681740fd008fbf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6205c0af57f0901d47e6af8f2ef1cd6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7859bfd32edceb6b8ac3f4f6e305bbb6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ca8cfdb96ae7a1dccfec638877e1bce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0e6e9883afa5a39f5bcae9086800e5a1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a060e2d3e37c9b7535d900e68c8b44ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ae61272bfecafe8381e7864670d7995e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d7ca141d230e27855c5ee2b02aa8f1d2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 652f8281d350082f8b8f6ea0cebab4cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5e20af58168ecce59215c674fedb816d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e699e8b1c9222e3ff6842461b8a98756: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b025ec51d7f9f514441cdb0f525dba0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 27d9d0dea464ab2e39841b5869640e2b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 81f2cc237b8b4bfbe97eb05c034f56c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52665d578feb035e63e73b815be4aab5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89f20107b3c19c9d0df43ef6a703ae00: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d51e981538082fa83e9ed073db8229a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15610a43f4d64b0508b4fab06ef96706: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 43ffb2ff50b06af921d5b07ac248db66: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2e15245ad47d37b6464c5d672aa9f0f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38ce72db98f069af0d3b3eeb2bbf96cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a27600218eb2ffdc4512172d3b131fe1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78cc81f755966bec82e9095b6b7f6904: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0d221a873e088c2e368228ec66e1de6d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0e1ad75ef9d16a558bcf3964d9015a9f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar be8f0e4e0458474b2868ae6fea2e3f7a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8817845a1bc122e49d44d7eab3e1e65d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bb571e747bf2731d3507aa4a965d5c6a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 945e2e85bb9cf3bb5e9a172485c2d7c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ec3e3f589eed93d953b5eab5524c47f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 401263bc5d2b0270b36d8d8619026f86: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 74ecb2fe2028b98fa8392dd821459455: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d8858263e8756f5f53af0c82d040690: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae29b8736a3e88c9743b6d751da153cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c2d86641bf50d02796bfd387e5c7a7a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3dd447828701371a94d7ae1040b4a22d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d53dd1ee176cab7917d73b847b9f804f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02f06be6e3924c1fc916d6ef5226fa27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e26c90c34d8f5c26fdf2354951a45020: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9ada94d6da55fce6fd319814a5884a42: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b2dbc2432c8299eaabb45c4adfeaf0fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2ae51ea9d20dac988cbe32a6a07c3c97: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 75946a1c8271b6d3304d9c369ea5c02f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15bf22cd2b3880294ccf5e1f8326ac73: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fe648d2a43b615c8dc6abec4838365c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 15d2787af37263d38869643bf10526ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8834273b07e6b108db76e6e55aa2a7ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d12452b85ceddd70be965f03d912d935: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c5e98edfc44f1c251a31d0242b59b05a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c62ed8d121c5a65f1f6b29558d13c3a3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6d7cd41533f974edfffce905b69b3bdb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 91fb292bd6d8e0e159d6aa845a1f9030: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d5b6c3e563c04dcae07a05382d7bb8cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a7f8f0b88509168b9ba82603c5cd1438: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4d19fdfd3033c95e7a101ff065e526d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ebda6e885885e3be44ba2f6479fc6541: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 226e597e467c8a096d93e50c798e6828: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a205f1061a8aa0f8153734929bdc6b3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20467eec4cfe708e09f4a9379b3a75ef: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cec0d1a8b6650f5fa557ef336ddaa96: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d15178c3c2cbe4d5a052fca00a0bdba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 281eff0aa0026fefa8bb9d0817fad0ac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 728814698ba5569bbcd208e1712fabc5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar accb3cc17c3c9bf34c186c6b3eb09d17: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 268aef4def872ef7341710a04ee1d7f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e4b56474baf59a2471837644bca81ef3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a2f457f61781c8f11b844cf6bb12cc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6b704d8c52887bfba33ef1ac18cee4b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c908ad1d1f792d837adf95561040ff83: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 078f9ed087c59abef3745eeb09a98791: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 350c3e7384dc5bfe31e7315da22df179: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c01c7ddf22ab18bc58385925b01244d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ac6c2c239e17254b5050e1a57421ffa7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d0fbcd44da571ed86a8940089c52be45: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6b3725cb4887873410fee9671788a08d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 40240395315e301363d193d6b7d540fd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c465def70b02f73cbc599e9c65cc43a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d3138bce18e405a6d4523488f2e1b2b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a2195126046a345f38c5686b84a18ed2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43e46c31d7d5a4c3bf45deb8af9700de: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d515cb402b6728fb28b85b76a3e7fa39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e5a672e56920997a198db5a797d2f02: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 91fe7d4f1128d0e2580b3a53d8dd957f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c18c78dfb591adc0b94f3771e893df5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bc1d5081ff1b1ad832a8771ac3518fce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 510ab493e75853ef1cdb4cdea4a3f4f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 387e39ac33fe33e31510b39b370d4c2f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0c8fdf9127b3f290fe6ff72013072fdc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1ad6c6b262557a0d3891a1e5d8c4590a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f2aae7628056994ed7bbbf85722555e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e5f809ac8967359dad1bb4c7c026153: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3a8c835e53763389aaf856bd0fe83873: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e11af3b2de55fc853ca96561c2c4b249: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 532d55e1f108df10a140ba2059fd6aed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6dace504c78a137404d90ecc41b52d16: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b8f3fafaa68940c5f3b2ddee9b4d129: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ab38d9d51786265680b3c7f88cc0745: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7a2395fea4554880d991bbf3510a00d6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 153f9ea726ac1515540939e5c5c81db2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fc83f9bd0b6883f3fdb04db8e063a74f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5ae29307ef470e258055ce66cf6b2a3f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e523e8fb51362319e9223ce7dc647240: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e67eb7fb4e7d2cc1d39af2c42d799fa3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 86aef19eaf113bc6e9661d7ae06773ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar e37e4908f2d7d7921e904037817a2199: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 459f899575667bd1fc8965dad833e234: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a116d3cd8a18c2fc1def74b82b0ad8b6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a64083147bfd68525dba37b0cbe49fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cdcd8590cf54b704b4b9d21896820989: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1e976244fad37961cd151e73d90ed20: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ae0166ec3afe6d83c6d0392d659c48a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dc163ec87a75346357d65611d41e1a37: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32ac4d0cc46a6d13adbbde74ae02b3e3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a6c615e7b169c39247f93e328a6d6a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 69e2a872b6cb7f63d920da11e518ec27: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 27296f445f16a587d39f5cc6eaad5803: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar daa6d80a1ae9d638b3cdc058dc40aaf2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d821599b02f96cb21b86edc6b8170509: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c071ad2222c1e77e53fec1534e2b5314: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e42a63958689c550dd6dbce3f46cb890: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 541e1f108d573dec8a58328f9d1b081e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c33f07a75cd76a9aae5a5c9c4cd08277: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5251a22e475cf227cd0554df7dbb68ba: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 82b53869b2a805c548f9f030b2f95507: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb3c171b1eac2689cd982996fe66735a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2abb4d625ba0913703b9c65fcba0e95: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 76bcd2260c2cb73455c049f709bed843: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8f43a70965505cc67d13fd348de78dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 137175e2fca4081c9c8d4544adc67370: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 939327c0fdf307bfe4c97e002c8a2159: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d858554352d40501c4da5e5e5deb982d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7570ef19069778d5180a7b077d6d01dc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8217d1f0e9033afec5f6e4d32db3f5ab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2d8917794290cdd9bf945d6ecdb866cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6d461d85c6ec304636e0192c03ac12f1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a38b189f95eeb35f30e4a42f83a1e55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3f3c45c51f01e540aa7363bc3e51b18c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07e536e478658c376da089b5b70b2bfb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bee6a88dfb262db7e3d7ff9864d54e7b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a836b7abe2a8142a16632e78faac09d1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9d08585712ebadf6371e14556f08fe7b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e067c64251260978f551170d26a7f69d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e253978115c4c32d031008b6fb9d69cb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 64c8a8939dd948be471a0199082b1f3b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 188990c98d69bbaee45860595b82ba67: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19e80725aff34ff76aaf4b57f7bf199c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8e95a16561f39818a9f484b63a3f7472: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 727f44b1205b21b849c1b4e10ac65d4a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7c1a09d172d7f5dee821c33d77f3dd0a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3fafdc7bc2a4f769d94f12f35b89c832: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 05ba19e35045e0c187736e4042f4e502: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0012582f4add238f236107b1c813dd79: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c4f4ff303f3389de346f42780940cbc6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dbe2d4d6a93e3b661968b644d4c591fb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fbe55ec2fc85c9919399c7b6eee842a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8ef267919f4172b0578a6c7a476e6593: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 060c679e67e2043eda39bce8450770d3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d3b75ef2d78a24769676d5a901c672a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6e74e86fb2c94a8a70a61261dd880e92: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c2a635f6e5a642a2249cbe09fd6c3ce4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 494b0fb64633957e3bde2e4156b569c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d6c03b7d40521188ff2ce1c782f13cac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar fb8f11c0746cf38dd7985bd24ad9163a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80e443289fdb20e9a35b70749de82fd9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06a27471c09a79699d4acb15488f4b7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4dcb0cd9133fb01aee30d0d1e03df07b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a01aa07bba32df8d1fdeb496e5753294: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 89ea2f796326a26089aaeba84153531c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0207d3a5e5dcd26f515cb195356a883e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fd1c4264d9699dda8a240924315331e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar bd6c621837c2cf949a115534f92af91e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 77ea4a200d281afe0d2ae98ad3acf591: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar feb108af71e87de27375510dac88e560: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9315e76952c2cfeedec4aab96e8046ad: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 69c13afcc831cc09a945abf2526bedff: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cacaeb7e59ac5156bf0adf02feb3af72: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d21a9caf44d8c0912e7d876a6d3ad7e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 343e430645d5193819a0942938c3da8a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6bce254fce650c99aeb0f25cc8373866: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 534a290a46721e3cc365bc48ba7806f8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 428e373c6ee668744c5c176fb80df09a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5b37ed2c1adfb6ec1cb1dfaf15a8150c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a2f67870ab42d94cdc518e103ea51d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0ba2bef7a0a08efbbb43ad16789891d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9a808baa8145a21c42639161beb6cf2e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 409ce0723272bd32b1d3a655ea899e88: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7c0ea859bb60849793783d82180772b5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 514b2d9e60bff7cc2919c404f54db750: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 52fd48627b72af9d168a4a22efa2f36b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ef7f6f2afa8b9727160eeb41e7ba9393: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 211fcef5a28ccb3b14bf79d81bbf9a64: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 679eddb4350b93c7bd4596bc0bafef02: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9a0b39c96e0410bbb9e711346a27f0cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 48be5de5e2f5560a8ff05b40ccacbb39: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 34f775cb980ed1f3863027a7d4d6eb0d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e992d56536566a34053841363cf158e5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b95200ef183ceddbd22142f8d975f1df: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b337cf696f3462e0ff12d93bab499de8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 943568ea6e8923a52c6dc7b611b6aae1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5c7f5c579080eee1a40e355f90d21443: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 19b7bc3656d55aef2de4fe8906e33128: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 68c25daf73ce08a7beb3fc1d42ba9099: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d41ec4baa64ca93e2c3d571fd55398d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd7bbfcc42488ea0b4743b49fa64dcb2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar ed6c114c343c58db25e8e0ebb1ba0321: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b793da22c64448cca6b44dcc793f715d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 722ac5c5239b89394d4f469832a71d2d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9d7af59cf8fd157532bc29295ae29df8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 30c3fefdc0b9986e3fec1b14ccc2e459: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 592d477e7e95c9c8cd51a24b29ffdaed: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar cebb3428cf84c8a5b34ea85df588306d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1d81547ca7df7023ab55af117d6e09d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae6f777a090584bd14a8ad413e59ce84: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 78e67b63663ec84062c15aef679ffe13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c014b14ffd1a8d62e2a492512d076b9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6b516bf629850ab5a848e6f950044adc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d790a79d6b714d7115bd7861a369f2d4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d750cd968bc068fbb8ded4b5b42d1b2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4dbe1c8d01ff131d0b7fa809149b9f06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0f303f3ad642f0e53dd601dc218a74b9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e62636114eeb4745546cf944cc20eb30: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 10b5094677f3c5af307fc0b42af8474f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5af0809ab51dd1bd73bee04b66f195a8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b28d383c00e7bdd500c925c1070a062: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2893c9c6b4c8004f99df25adc012127f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a090e96518f73e0040f21003f4b7dadd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 47e07ce01e07227382cb7ca512134a24: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f3db0d135711505162879455d8c3733b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e6a5e0b99cd6d50623b144876ac49569: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cbfc666b9ced2633311e4895631bbbc2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar db47e63fae2ce6b8fda3f214d972ad26: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cdf86a9974ef7ac9a8fd3ada10f1d650: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b5e6ab7eff089a0aea2f238f467d893b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar eff7bb223524e61f47364f0c3e43002e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8326e60a80edebc7f70681506af72120: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 99a622064b14cbe81faefa9dbc639646: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0769cc4ef2b250ae4df43fabea2fb8f9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c50c1154002ed25ec2d91442c5b5c13d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f07961427642c820a7ea80172318c5e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar caa3f70f8d3103705d1138c5522783aa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e61005bf3c8c167b125f106daca2a12b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 265024e5a31aaf7b1001a6743cf4e2cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f227194c0304e54cde71f3e70f0c6203: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5810805dff2c57411a3ec8aa16327e55: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4635e678c573dc7f46a3c6512db4cf3a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 9e6c6fb596c04c537a271af6b8bba2a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d903d1f3e9b869f6d3240c4c85347837: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cbc0006e4865ef5cc24d7f1c508b214b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ae038037ff1b776a06dc6716645c582e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0cdffdb5f3fd011b2528ec3d522e5b7c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4791d4d75e4af326e045481d7c6c5f5a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 28a83c8d4a9adf4c279da3247eade36e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c899a1500d1aba859564b1dffa64eafa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a3c93e08cc8a0a320d43ec2f97efc6cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 01db2ebf7242dd39284c051641e2763a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5a2ee22462b52e60c3135f9bec8cb8e4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar dd69c4646e6c38a8e4cbb7d72ee230a0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar f8fd5d005dfe6b92b811c60394ed7f07: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2789d60b03a23f9e6d6e8b0e49c7bcb8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 026dbb06dfd9c1ff40bf416b05e3ac7d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ebbff8afb0f51661f349d40470454d0e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 176baf83aebdc09bd0bda9d105d5c874: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 79c5c327c32fbada83fca6cd55703c69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar b262fde02d232c132bf60e31d32846f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4f7fcadf37f799574bda8ed3baa58ebc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4d89082be885b704bcc0b0d7153523c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 358a3b1bd7d9899f461f7f0ca717eb65: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 980b0b0bb7d518cb920f333aa06eeafe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4b8be1afa003998f1a184d1d22355152: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar bb9e04c822ea99aa3dad043e38bc96e2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 54e40c03251d12aee95d9308ce9ca83f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eec93714c731f3a955eb4eec1b943d47: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e47e07bdcb3ccf8152eb3738bd4faeee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0982c9f65037d9f88d5393014f4893fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b7fdbeb6da1010573389be68242ae116: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7539ca7f36692879c2ec1f643ce73a06: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7d636d86e3fc80e3ff7cb752e449382e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar aa97415ee2623dcbe9f3aa05336cc2e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 07d5895d751324521197e625fa161fcb: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5f1e1009e76607bcfa21cb460e4cb9e9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a59c0593c6df4aa34179c292f4e23c5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5e7db97fe9ee0647fced550fd706e142: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 65b9342987889863326639e9626c56fc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 70e8c76386b1eeb18bfd9d5a9d748534: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a756e5412faef43c610761c37bf5c736: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8c96e71825197284b788465c5e662204: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 945ed76441826c156bb1bd8c886961d5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9fb8464739b6bd236a42049d458243b0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d5b3c15a5adc60f2460418f61f9935c9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2001dc0f8d908d14877decb481bbd835: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fded1c99aa5bee22a7b99ddee3d09bc5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d2b4caf5cbdb6132ae9c48dec883a9c2: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 53ae5001053a0e37ee580880249b102b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a85fdf523d27a77ad32bc8c80719d95b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d253e1b4100b01f838d235fd451e1ff1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b34e4096f32358c841a210d490dc9db3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0454dad3b49c2d727f64372ef13afa5e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar df255e66e86b8606701498dc7d95d28b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 50fc7c31c9db62cbf4d8cb91f5de3ce9: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8d5b66edeea03aaf03ba3a6e7190ed24: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a1e902d310ccda65ff80feef6df03d69: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6af4b431c0821b85b2c45f7ae1aaa7e6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b76dd4821f625c69f88e98d0b053f8c4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 495d2e6a0460320be3d8a293aecee772: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1841402de1cdd8381893e65fa885401c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 654aee73b97973d440eab2f07090ed1d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f0a46af71ade638314063bafeb21f0e1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f41d3dd9f17cbaca019744f9cc765333: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 41b623c5dd782b24ce6471b54d8bf7a5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4284d7a5620a966c188948e0af738081: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c84f56ddfbc7542b08687657dc6bd050: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 3bdcefaf775963cb01e2098ad9f95dab: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d873606adaf79bea0f6c4a79fb10ec15: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4eff560802ad54dadf70498bdb5469af: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38a51e8d1993312ea51aa3a90d4b21ea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 20ae45f00a9d00b65d3994e548060864: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e71a9bf245ad4e98b8bc63a00a24be9a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 0b01a22759d471eaf6c89d20bd7d35e8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 43d195860ee3329ead516bbb8e5d8c50: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 694c15e3c5af376b5d386d332fdc9972: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8f0811172c5d4f78c2a052faba857dd4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a0c279966c5347f371acff331ce31678: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5d6006e1d4c0fd442c01d0d12e69b456: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 8c59e4046cc86b5a7e7e969a3b632948: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f1d6a31fdcc7a22b9b52ee845d09b262: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a81a7a896a7811065e1b0f532c2f51ce: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c98c11d69ee5bf7262fad89e6d67b147: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c96511c6d61d602007be81fa4ed2dcea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a9bddb4850bfbf431081bcbcc40727bd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 6171b81fa4be13e0cdf5cb6599072daa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 57215631d2e3953ed7c091b01f473d9e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f65a65187830863aeaa5d79d57bc0f70: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 58ec213a907257ce69c188fff7c09937: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e3478c36123ba4df7020640cb242a05a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f125b9a4ca9a40c54bba7d902ee74ba6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d4c72f7dfecaf8cb7f0fac72c9728d17: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar db003055753c77fde2d231c8f414a53e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 170605e1f9bf6f1940e5ab964b3be2cc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8a7fb9e17793842758591c32feabce35: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6ad9ac004566df3aa2127cad2b6b914b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 063c60fe3276c07514e0ddbccd28c706: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 02a58ee7451779b349a72d223eb1e98f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 1523c02a3c3c60bab7394b8a9089ac93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f3f23f9a1244d12363c20b465bcc6747: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 618306b6e6f5716bbb029dca5b8a27be: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 056482ecb3c09a55cd78ee598e0b494e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4db2015ff1308d880e56584784a62879: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e16330dcb391b3eb7c976b8ea3fbd3db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7f64099b339b392f2477a8b9769ba68f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 23dca21559b71443c4d7de182eaec502: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar edc6f6372929cdf58955be58fa25c741: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 180a5ccaf3b20a836227f3c0ce7bcace: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9554402bf7df33ab849792316aeb7c5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 13774b57217aa0e9fedec7113901d2cf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 08626ca6ba78b520ab03b50414873ac1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 32887884358061632d158fc3f321bb6c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar af04a09707237a3e9a09d0bf9c50f7a6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b9de1a46acb34fa59b15fa9b3f8616f5: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c76e444ee5bbb69571f02cff073ceb5c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 2192c36ee06d7efba0ed611327de55ee: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5b6418dbdc74a5831f159052e13cf6db: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 5c2083fedb0189189eb5000cb844d949: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 5edac10f0b1ed058460ebae310379a0b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cd410350fe82d53242f75a1663cf056d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 9e195130b0e1624e96685c118b054533: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f5462fdb6407397cd6b2f7deccfeb008: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1c6567520fef5ba6e4378a3b7f81a689: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 521d9e3f29980f6ed8021a303a1429d7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar df30666f037c71541198e54e20af6fbc: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d9e7f42ce77ecdfd644ac103f5edcd60: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d748404769a6d429982b8fcac0f10077: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c573f02b4553b4ef98ef7bd5f5f4da31: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 746f0246b4769b4c3aeae1f9670fefcf: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1e2c08f0c3a1cadc62eca09f25464ca7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d84ee7ea4f21f7a84b44b5992c59cb0f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 7b9716710399bbda77f38d4bdc76886c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c1586681317e4ce000dbbc297ad35ef1: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar a2c3486970290169e60d2342dae702fe: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 844056ef90ebcc5800cd509bcc996464: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar a24b61cac1b6582f5feff1b74c1171a4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 74cbfa58b6b7c2385b05b454e2e34841: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 678c8b49a734b7f9b6a6f558f3e3b4b4: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar b7971b7d5fef94c6a4efb2002e7e9f1c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 31176b938306ed65ddc03dd0dcc9c131: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4807b0216b1831db4ac4c179dd3d1a9d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 6f859444df68a810159ed3486e8a6bca: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e8f0feac454eb6bb4611859efdeb2047: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 06f8cfc5cb382a26bb858a2e57c09880: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 048ad56f8b5cdacd7fe3772ae10fff93: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 7bbc47cdec0bc2471e3ee500c9f02f62: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar c973336457bd51a05cdf4d2ca304e313: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4715b1addc9a8ffc59ed19449812f942: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar eb080709678e7845db7aebdf74e4f9d8: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3fb5574772856cc43eaf6ac8bf3d1010: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 1f7096a896a3b0c6a52edbe6c50e055c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 45bf749db5df66fd858c8924bb6761f6: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4a3b5b4245b79f3f2f5eb37037a9d6cd: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e619f692549f8569d422bdd0fcdcbd5b: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 0bb98b82cafb0f7319dfb1cd3de3253d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4e70733da89a4f1886d518ff3c2dd6fa: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ecbb93adce490adc6beb46d1669d3224: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar acee21e527cc1c1cfe2f17c1f18a7f13: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fd07ea7dee50c8701031be3bbf7f6524: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar fda2e733e8919ea6844487a7d07e5325: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 38cb63939b5e4ba6cd53434b5fd5a43f: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cfcec5ecd844cb11e860e05abb297e46: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 607e05820ad58952755d506e9a839890: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar da9cf96ccc4867e3c7b6c92c587351e7: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar c713738988c4ee9a336b47979a85c864: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 000710b9a4e596f935c9fb966d17684c: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar d8cc499f3c5b156b7d6acb9f3a399441: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar ff14e24ee40290b6abfba709d225d21e: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar e63c96e4362cbf13e56f238ca1e1d0f3: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 4da793fc8d4860b08809b2723b20ff0a: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar 4e153b4c754afb0761c1ce614f584276: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 8bd635b0aa67c9a5c8fcfd9c0548f75d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f6a536c9ceb992f099104bdc91c1be74: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar f893242c54ad24ad71a3358ebf3fd417: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar cb36f2d3adb9c31a89488461efc2ffb0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 80f3bfa980b5a13186381c549c03031d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

  ❌ Erro ao atualizar d3011a4ab25f9471012def0dd85aeaea: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 3cfbe83e167ec63cb7087806eb74710d: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 771bbd55240d03d9b99c5abb012ecfac: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 206cae5a3274f7ca5144e5fa22557846: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}
  ❌ Erro ao atualizar 174f7620624194901389568dfe7e15d0: {'message': "Could not find the 'consultor_grupo_atendimento_raw' column of 'tab_vinculos_sq' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}

=== RESUMO DO ETL DE VÍNCULOS ===
📄 Arquivos processados: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION\BD_BI_VINCULOS_COMPLETO.xlsx
📊 Total de registros: 6142
🆕 Registros novos: 1
🔄 Registros atualizados: 3693
✅ Registros processados com sucesso: 0
❌ Registros com erro: 3694
⏱️ Tempo de inserção: 146.43 segundos
⏱️ Tempo total do ETL: 153.57 segundos
📅 Data/hora de conclusão: 2026-08-18 16:02:12
✅ Teste de ETL de vínculos concluído com sucesso!

# 5. Visitas dos Projetos

In [8]:
def processar_relatorios_visitas(diretorio_dados=None):
    """
    Processa os relatórios individuais de visitas e cria um DataFrame consolidado

    Args:
        diretorio_dados: Diretório onde estão os arquivos de relatórios

    Returns:
        DataFrame consolidado com os dados de visitas
    """
    try:
        print("=== PROCESSAMENTO DE RELATÓRIOS DE VISITAS ===")
        inicio = datetime.now()

        # Mudar para o diretório especificado se fornecido
        if diretorio_dados:
            # os.chdir gerido no setup
            print(f"Diretório alterado para: {diretorio_dados}")
        
        # Definir nomes dos arquivos
        regenera_arquivo = config_yaml['smartquestion']['arquivos']['visita_regenera']
        alvoar_arquivo = config_yaml['smartquestion']['arquivos']['visita_alvoar']
        semear_arquivo = config_yaml['smartquestion']['arquivos']['visita_semear']
        ccpr_arquivo = config_yaml['smartquestion']['arquivos']['visita_ccpr']
        lpa_arquivo = config_yaml['smartquestion']['arquivos']['visita_lpa']
        
        # Definir configurações de importação
        # Alvoar
        alvoar_columns = [0,1,2,3,4,5,8,9,10,11,12,13,14,17,18,19,20,21,22,23,24,31,32]
        alvoar_aba = 'INF_GERAIS'
        alvoar_inicio = 2

        # Regenera
        regenera_columns = [1,2,3,4,5,6,9,11,12,13,14,15,16,17,18,19,20,21,28,30,32,33]
        regenera_aba = 'DADOS_COLETADOS'
        regenera_inicio = 3
        
        # Semear
        semear_columns = [1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,25,27,29,30]
        semear_aba = 'DADOS_COLETADOS'
        semear_inicio = 3
        
        # CCPR
        ccpr_columns = [1,2,3,4,5,7,8,9,10,11,12,13,14,15,22,24,26,27]
        ccpr_aba = 'DADOS_COLETADOS'
        ccpr_inicio = 3
        
        # LPA
        lpa_columns = [0,1,2,3,4,6,8,9,10,11,12,13,14,17,18,19,20,21,22,23,24]
        lpa_aba = 'INF_GERAIS'
        lpa_inicio = 2
        
        # Dicionário de mapeamento de colunas
        col_mapping = {
            'alvoar':{
                'Produtor(a):':'nome_produtor',
                'Código do produtor(a)':'codigo_lr',
                'Propriedade:':'nome_propriedade',
                'Consultor(a):':'nome_consultor',
                'Número de atendimento:':'id_atendimento',
                'Data fim no sistema:':'data_visita',
                'Área utilizada para pecuária (hectares): ':'area_pecuaria_ha',
                'Quantidade de dias-homem (média diária): ':'mdo_dias_homem',
                'Produção (litros/dia): ':'producao_l_dia',
                'CCS mensal (x 1.000 cél./ml): ':'ccs_mensal',
                'CPP mensal (x 1.000 UFC/ml): ':'cpp_mensal',
                'Gordura mensal (%): ':'gordura_mensal',
                'Proteína mensal (%): ':'proteina_mensal',
                'Vacas em lactação (cabeças): ':'vacas_lactacao',
                'Vacas secas (cabeças): ':'vacas_secas',
                'Bezerras em aleitamento (cabeças): ':'bezerras_aleitamento',
                'Bezerros em aleitamento (cabeças): ':'bezerros_aleitamento',
                'Novilhas (cabeças): ':'novilhas',
                'Reprodutores (cabeças): ':'reprodutores',
                'Receptoras (cabeças): ':'receptoras',
                'Total de rebanho (cabeças): ':'rebanho_total',
                'Valor pago pelo produtor (R$):':'valor_pago_produtor',
                'Valor subsidiado pela Alvoar (R$):':'valor_pago_agroindustria'
            },
            'semear':{
                'Número do atendimento':'id_atendimento',
                'Consultor(a)':'nome_consultor',
                'Código do produtor(a)':'codigo_lr',
                'Nome do produtor(a)':'nome_produtor',
                'Propriedade':'nome_propriedade',
                'Data da realização da visita:':'data_visita',
                'Área utilizada para pecuária (hectares):':'area_pecuaria_ha',
                'Quantidade de dias-homem (média diária):':'mdo_dias_homem',
                'Produção (litros/dia):':'producao_l_dia',
                'Vacas em lactação (cabeças):':'vacas_lactacao',
                'Vacas secas (cabeças):':'vacas_secas',
                'Bezerras em aleitamento (cabeças):':'bezerras_aleitamento',
                'Bezerros em aleitamento (cabeças):':'bezerros_aleitamento',
                'Novilhas (cabeças):':'novilhas',
                'Reprodutores (cabeças):':'reprodutores',
                'Receptoras (cabeças):':'receptoras',
                'Total de rebanho (cabeças):':'rebanho_total',
                'CCS mensal (x1.000 cél./ml):':'ccs_mensal',
                'CPP mensal (x1.000 UFC/ml):':'cpp_mensal',
                'Gordura mensal (%):':'gordura_mensal',
                'Proteína mensal (%):':'proteina_mensal'
            },
            'regenera':{
                'Número do atendimento':'id_atendimento',
                'Consultor(a)':'nome_consultor',
                'Código do produtor(a)':'codigo_lr',
                'ID Farm':'id_farm',
                'Nome do produtor(a)':'nome_produtor',
                'Propriedade':'nome_propriedade',
                'Data da realização da visita:':'data_visita',
                'Área utilizada para pecuária (hectares):':'area_pecuaria_ha',
                'Quantidade de dias-homem (média diária):':'mdo_dias_homem',
                'Produção (litros/dia):':'producao_l_dia',
                'Vacas em lactação (cabeças):':'vacas_lactacao',
                'Vacas secas (cabeças):':'vacas_secas',
                'Bezerras em aleitamento (cabeças):':'bezerras_aleitamento',
                'Bezerros em aleitamento (cabeças):':'bezerros_aleitamento',
                'Novilhas (cabeças):':'novilhas',
                'Reprodutores (cabeças):':'reprodutores',
                'Receptoras (cabeças):':'receptoras',
                'Total de rebanho (cabeças):':'rebanho_total',
                'CCS mensal (x1.000 cél./ml):':'ccs_mensal',
                'CPP mensal (x1.000 UFC/ml):':'cpp_mensal',
                'Gordura mensal (%):':'gordura_mensal',
                'Proteína mensal (%):':'proteina_mensal'
            },
            'ccpr':{
                'Número do atendimento':'id_atendimento',
                'Consultor(a)':'nome_consultor',
                'Código do produtor(a)':'codigo_lr',
                'Nome do produtor(a)':'nome_produtor',
                'Propriedade':'nome_propriedade',
                'Data da realização da visita:.1':'data_visita',
                'Área utilizada para pecuária (hectares):':'area_pecuaria_ha',
                'Quantidade de dias-homem (média diária):':'mdo_dias_homem',
                'Produção (litros/dia):':'producao_l_dia',
                'Vacas em lactação (cabeças):':'vacas_lactacao',
                'Vacas secas (cabeças):':'vacas_secas',
                'Bezerros em aleitamento (cabeças):':'bezerros_aleitamento',
                'Novilhas (cabeças):':'novilhas',
                'Reprodutores (cabeças):':'reprodutores',
                'Receptoras (cabeças):':'receptoras',
                'Total de rebanho (cabeças):':'rebanho_total',
                'CCS mensal (x1.000 cél./ml):':'ccs_mensal',
                'CPP mensal (x1.000 UFC/ml):':'cpp_mensal',
                'Gordura mensal (%):':'gordura_mensal',
                'Proteína mensal (%):':'proteina_mensal'
            },
            'lpa':{
                'Produtor(a):':'nome_produtor',
                'Código do produtor(a)':'codigo_lr',
                'Propriedade:':'nome_propriedade',
                'Consultor(a):':'nome_consultor',
                'Número de atendimento:':'id_atendimento',
                'Data da realização da visita:':'data_visita',
                'Área utilizada para pecuária (hectares): ':'area_pecuaria_ha',
                'Quantidade de dias-homem (média diária): ':'mdo_dias_homem',
                'Produção (litros/dia): ':'producao_l_dia',
                'CCS mensal (x 1.000 cél./ml): ':'ccs_mensal',
                'CPP mensal (x 1.000 UFC/ml): ':'cpp_mensal',
                'Gordura mensal (%): ':'gordura_mensal',
                'Proteína mensal (%): ':'proteina_mensal',
                'Vacas em lactação (cabeças): ':'vacas_lactacao',
                'Vacas secas (cabeças): ':'vacas_secas',
                'Bezerras em aleitamento (cabeças): ':'bezerras_aleitamento',
                'Bezerros em aleitamento (cabeças): ':'bezerros_aleitamento',
                'Novilhas (cabeças): ':'novilhas',
                'Reprodutores (cabeças): ':'reprodutores',
                'Receptoras (cabeças): ':'receptoras',
                'Total de rebanho (cabeças): ':'rebanho_total'
            }
        }
        
        # Lista para armazenar os DataFrames
        list_df = []
        
        # Importar cada um dos relatórios de visitas
        print("\n🔍 ETAPA 1: IMPORTANDO RELATÓRIOS DE VISITAS")
        
        # Regenera
        try:
            df_regenera = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / regenera_arquivo, sheet_name=regenera_aba, header=regenera_inicio, usecols=regenera_columns)
            df_regenera.rename(columns=col_mapping['regenera'], inplace=True)
            df_regenera['origem_dados'] = 'REGENERA'
            df_regenera['valor_pago_produtor'] = np.nan
            df_regenera['valor_pago_agroindustria'] = np.nan
            list_df.append(df_regenera)
            print(f"✅ Relatório de visitas do Regenera lido com sucesso!! ({len(df_regenera)} registros)")
        except Exception as e:
            print(f"⚠️ Erro ao importar relatório Regenera: {str(e)}")
        
        # Alvoar
        try:
            df_alvoar = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / alvoar_arquivo, sheet_name=alvoar_aba, header=alvoar_inicio, usecols=alvoar_columns)
            df_alvoar.rename(columns=col_mapping['alvoar'], inplace=True)
            df_alvoar['origem_dados'] = 'ALVOAR'
            df_alvoar['data_visita'] = df_alvoar['data_visita'].dt.normalize()
            df_alvoar['id_farm'] = np.nan
            list_df.append(df_alvoar)
            print(f"✅ Relatório de visitas do Alvoar lido com sucesso!! ({len(df_alvoar)} registros)")
        except Exception as e:
            print(f"⚠️ Erro ao importar relatório Alvoar: {str(e)}")
        
        # Semear
        try:
            df_semear = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / semear_arquivo, sheet_name=semear_aba, header=semear_inicio, usecols=semear_columns)
            df_semear.rename(columns=col_mapping['semear'], inplace=True)
            df_semear['origem_dados'] = 'SEMEAR'
            df_semear['id_farm'] = np.nan
            df_semear['valor_pago_produtor'] = np.nan
            df_semear['valor_pago_agroindustria'] = np.nan            
            list_df.append(df_semear)
            print(f"✅ Relatório de visitas do Semear lido com sucesso!! ({len(df_semear)} registros)")
        except Exception as e:
            print(f"⚠️ Erro ao importar relatório Semear: {str(e)}")
        
        
        # CCPR
        try:
            df_ccpr = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / ccpr_arquivo, sheet_name=ccpr_aba, header=ccpr_inicio, usecols=ccpr_columns)
            df_visita_ccpr = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / ccpr_arquivo, sheet_name='DADOS_DA_VISITA', header=4, usecols=['Número do atendimento', 'Data da realização da visita:.1'])
            df_ccpr = pd.merge(df_ccpr, df_visita_ccpr, how='left', on=['Número do atendimento'])
            df_ccpr.rename(columns=col_mapping['ccpr'], inplace=True)
            df_ccpr['bezerras_aleitamento'] = np.nan
            df_ccpr['origem_dados'] = 'CCPR'
            df_ccpr['id_farm'] = np.nan
            df_ccpr['valor_pago_produtor'] = np.nan
            df_ccpr['valor_pago_agroindustria'] = np.nan 
            list_df.append(df_ccpr)
            print(f"✅ Relatório de visitas do CCPR lido com sucesso!! ({len(df_ccpr)} registros)")
        except Exception as e:
            print(f"⚠️ Erro ao importar relatório CCPR: {str(e)}")
        
        # LPA
        try:
            df_lpa = pd.read_excel(Path(diretorio_dados or DIR_BD_SQ) / lpa_arquivo, sheet_name=lpa_aba, header=lpa_inicio, usecols=lpa_columns)
            df_lpa.rename(columns=col_mapping['lpa'], inplace=True)
            df_lpa['origem_dados'] = 'LPA'
            df_lpa['id_farm'] = np.nan
            df_lpa['valor_pago_produtor'] = np.nan
            df_lpa['valor_pago_agroindustria'] = np.nan
            list_df.append(df_lpa)
            print(f"✅ Relatório de visitas do LPA lido com sucesso!! ({len(df_lpa)} registros)")
        except Exception as e:
            print(f"⚠️ Erro ao importar relatório LPA: {str(e)}")

        # Verificar se há DataFrames para processar
        if not list_df:
            print("❌ Nenhum relatório de visitas foi importado com sucesso.")
            # os.chdir gerido no setup
            return None

        print(f"✅ Total de relatórios importados: {len(list_df)}")

        # ETAPA 2: CONSOLIDAR E TRATAR OS DADOS
        print("\n🔄 ETAPA 2: CONSOLIDANDO E TRATANDO OS DADOS")

        # Obter todas as colunas únicas de todos os dataframes
        all_columns = set()
        for df in list_df:
            all_columns.update(df.columns)

        print(f"Total de colunas únicas: {len(all_columns)}")

        # Adicionar colunas faltantes em cada dataframe
        for df in list_df:
            for col in all_columns:
                if col not in df.columns:
                    df[col] = None

        # Concatenar todos os dataframes
        df_visitas = pd.concat(list_df, ignore_index=True)

        print(f"DataFrame consolidado criado com sucesso!")
        print(f"Total de registros: {len(df_visitas)}")
        print(f"Total de colunas: {len(df_visitas.columns)}")

        # Converter a coluna de data para o tipo datetime
        if 'data_visita' in df_visitas.columns:
            df_visitas['data_visita'] = pd.to_datetime(df_visitas['data_visita'], errors='coerce')

        # Converter colunas numéricas para o tipo float
        numeric_columns = [
            'area_pecuaria_ha', 'mdo_dias_homem', 'producao_l_dia', 
            'ccs_mensal', 'cpp_mensal', 'gordura_mensal', 'proteina_mensal',
            'vacas_lactacao', 'vacas_secas', 'bezerras_aleitamento', 
            'bezerros_aleitamento', 'novilhas', 'reprodutores', 
            'receptoras', 'rebanho_total','valor_pago_produtor','valor_pago_agroindustria'
        ]

        for col in numeric_columns:
            if col in df_visitas.columns:
                df_visitas[col] = pd.to_numeric(df_visitas[col], errors='coerce')

        # Verificar se há registros duplicados
        duplicated_count = df_visitas.duplicated(subset=['id_atendimento']).sum()
        print(f"Registros duplicados por id_atendimento: {duplicated_count}")

        # Remover duplicados
        df_visitas.drop_duplicates(subset=['id_atendimento'], keep='first', inplace=True)

        duplicated_count = df_visitas.duplicated(subset=['id_atendimento']).sum()
        print(f"Registros duplicados pós-tratamento: {duplicated_count}")

        # Corrigir tipos de dados
        df_visitas = corrigir_tipos_dataframe(df_visitas)

        # Voltar ao diretório original
        # os.chdir gerido no setup

        # Calcular tempo de processamento
        fim = datetime.now()
        duracao = (fim - inicio).total_seconds()

        print(f"\n✅ Processamento concluído em {duracao:.2f} segundos")
        print(f"✅ Total de registros no DataFrame final: {len(df_visitas)}")

        return df_visitas

    except Exception as e:
        print(f"❌ Erro durante o processamento dos relatórios: {str(e)}")
        traceback.print_exc()

        # Voltar ao diretório original
        # os.chdir gerido no setup

        return None

def corrigir_tipos_dataframe(df):
    """
    Corrige os tipos de dados do DataFrame para compatibilidade com o Supabase

    Args:
        df: DataFrame a ser corrigido

    Returns:
        DataFrame com tipos corrigidos
    """
    # Cópia para não modificar o original
    df_corrigido = df.copy()

    # Colunas que devem ser inteiros
    colunas_inteiras = [
        'vacas_lactacao', 
        'vacas_secas', 
        'bezerras_aleitamento', 
        'bezerros_aleitamento', 
        'novilhas', 
        'reprodutores', 
        'receptoras', 
        'rebanho_total'
    ]

    # Converter colunas para inteiro
    for col in colunas_inteiras:
        if col in df_corrigido.columns:
            # Converter para float primeiro para lidar com NaN, depois para int
            df_corrigido[col] = pd.to_numeric(df_corrigido[col], errors='coerce')
            df_corrigido[col] = df_corrigido[col].fillna(0)
            df_corrigido[col] = df_corrigido[col].astype(int)

    # Colunas que devem ser float
    colunas_float = [
        'area_pecuaria_ha', 
        'mdo_dias_homem', 
        'producao_l_dia', 
        'ccs_mensal', 
        'cpp_mensal', 
        'gordura_mensal', 
        'proteina_mensal',
        'valor_pago_produtor',
        'valor_pago_agroindustria'
    ]

    # Converter colunas para float
    for col in colunas_float:
        if col in df_corrigido.columns:
            df_corrigido[col] = pd.to_numeric(df_corrigido[col], errors='coerce')
            df_corrigido[col] = df_corrigido[col].fillna(0)

    # Garantir que a coluna data_visita seja datetime
    if 'data_visita' in df_corrigido.columns:
        df_corrigido['data_visita'] = pd.to_datetime(df_corrigido['data_visita'], errors='coerce')

    # Garantir que id_atendimento seja string
    if 'id_atendimento' in df_corrigido.columns:
        df_corrigido['id_atendimento'] = df_corrigido['id_atendimento'].astype(str)

    return df_corrigido

def criar_id_composto(row):
    """
    Cria um ID composto usando MD5 hash de campos-chave

    Args:
        row: Linha do DataFrame

    Returns:
        String com o hash MD5
    """
    # Lista de colunas para compor o ID
    colunas_id = [
        'id_atendimento', 'nome_consultor', 'codigo_lr', 'id_farm', 'nome_produtor', 
        'nome_propriedade', 'data_visita', 'area_pecuaria_ha', 'mdo_dias_homem',
        'producao_l_dia', 'vacas_lactacao', 'vacas_secas', 'bezerras_aleitamento',
        'bezerros_aleitamento', 'novilhas', 'reprodutores', 'receptoras',
        'rebanho_total', 'ccs_mensal', 'cpp_mensal', 'gordura_mensal',
        'proteina_mensal', 'origem_dados','valor_pago_produtor','valor_pago_agroindustria'
    ]

    # Concatenar valores das colunas
    valores = []
    for col in colunas_id:
        if col in row.index:
            valor = row[col]
            # Converter para string e tratar valores nulos
            if pd.isna(valor):
                if col in ['area_pecuaria_ha', 'mdo_dias_homem', 'producao_l_dia', 
                          'vacas_lactacao', 'vacas_secas', 'bezerras_aleitamento',
                          'bezerros_aleitamento', 'novilhas', 'reprodutores', 
                          'receptoras', 'rebanho_total', 'ccs_mensal', 'cpp_mensal', 
                          'gordura_mensal', 'proteina_mensal','valor_pago_produtor','valor_pago_agroindutria']:
                    valores.append('0')
                else:
                    valores.append('')
            else:
                valores.append(str(valor).lower().strip())
        else:
            valores.append('')

    # Juntar valores e criar hash MD5
    texto_composto = '|'.join(valores)
    return hashlib.md5(texto_composto.encode('utf-8')).hexdigest()

def etl_visitas(df_visitas=None, diretorio_dados=None, DIRETORIO_ENV=DIRETORIO_ENV):
    """
    Função ETL para atualizar a tabela de visitas no Supabase

    Args:
        df_visitas: DataFrame já tratado com os dados de visitas (opcional)
        diretorio_dados: Diretório onde estão os arquivos de relatórios (opcional)
        DIRETORIO_ENV: Diretório onde está o arquivo .env
    
    Returns:
        bool: True se o processo foi concluído com sucesso, False caso contrário
    """
    try:
        print("=== ETL DE VISITAS ===")
        inicio_total = datetime.now()

        # Se o DataFrame não foi fornecido, processar os relatórios
        if df_visitas is None:
            if diretorio_dados is None:
                print("❌ É necessário fornecer o DataFrame ou o diretório dos dados.")
                return False

            print("🔍 DataFrame não fornecido. Processando relatórios...")
            df_visitas = processar_relatorios_visitas(diretorio_dados)

            if df_visitas is None:
                print("❌ Falha ao processar os relatórios de visitas.")
                return False

        # Mudar para o diretório onde está o arquivo .env
        # os.chdir gerido no setup
        print(f"Diretório alterado para: {DIRETORIO_ENV}")

        # ETAPA 1: CRIAR ID COMPOSTO E PREPARAR DADOS
        print("\n🔄 ETAPA 1: CRIANDO ID COMPOSTO E PREPARANDO DADOS")

        # Converter data_visita para datetime se ainda não for
        if 'data_visita' in df_visitas.columns and not pd.api.types.is_datetime64_any_dtype(df_visitas['data_visita']):
            df_visitas['data_visita'] = pd.to_datetime(df_visitas['data_visita'], errors='coerce')

        # Adicionar data_processamento atual
        df_visitas['data_processamento'] = datetime.now()

        # Criar coluna de ID composto após ajustar os tipos de dados
        print("🔄 Gerando ID composto para cada registro...")
        df_visitas['id_composto'] = df_visitas.apply(criar_id_composto, axis=1)
        print(f"✅ ID composto gerado para {len(df_visitas)} registros")

        # ETAPA 2: BUSCAR REGISTROS EXISTENTES NO SUPABASE
        print("\n🔍 ETAPA 2: BUSCANDO REGISTROS EXISTENTES NO SUPABASE")

        # Carregar credenciais do Supabase
        key = os.getenv('SUPABASE_SERVICE_KEY')
        url = os.getenv('SUPABASE_URL')

        if not key or not url:
            print("❌ Credenciais não encontradas!")
            # os.chdir gerido no setup
            return False

        # Inicializar cliente Supabase
        supabase = create_client(url, key)

        # Buscar dados existentes para comparação
        print("🔍 Buscando registros existentes...")
        
        try:
            # Buscar apenas os id_composto existentes
            resultado = supabase.table(TAB_VISITAS_STAGING).select("id_composto,data_processamento").execute()

            if resultado.data:
                # Obter conjunto de IDs existentes
                ids_existentes = set(item['id_composto'] for item in resultado.data if 'id_composto' in item)
                
                # Obter a data de processamento mais recente
                datas_processamento = [pd.to_datetime(item['data_processamento']) 
                                      for item in resultado.data 
                                      if 'data_processamento' in item and item['data_processamento'] is not None]

                if datas_processamento:
                    ultima_data_processamento = max(datas_processamento).normalize()
                    print(f"✅ Data de processamento mais recente: {ultima_data_processamento}")
                else:
                    ultima_data_processamento = pd.to_datetime(PERIODO_CHECAGEM_INICIO)
                    print("⚠️ Nenhuma data de processamento encontrada. Usando data padrão.")

                print(f"✅ Encontrados {len(ids_existentes)} registros existentes no Supabase")
            else:
                ids_existentes = set()
                ultima_data_processamento = pd.to_datetime(PERIODO_CHECAGEM_INICIO)
                print("⚠️ Nenhum registro encontrado no Supabase.")
        except Exception as e:
            print(f"⚠️ Erro ao buscar registros existentes: {str(e)}")
            # Em caso de erro, assumir que não há registros
            ids_existentes = set()
            ultima_data_processamento = pd.to_datetime(PERIODO_CHECAGEM_INICIO)

        # ETAPA 3: IDENTIFICAR REGISTROS NOVOS OU ALTERADOS
        print("\n🔍 ETAPA 3: IDENTIFICANDO REGISTROS NOVOS OU ALTERADOS")

        # Identificar registros novos ou alterados usando ID composto
        ids_atuais = set(df_visitas['id_composto'])

        # Registros novos (não existem no Supabase)
        ids_novos = ids_atuais - ids_existentes
        df_novos = df_visitas[df_visitas['id_composto'].isin(ids_novos)]

        # Registros a atualizar (existem no Supabase)
        ids_atualizar = ids_atuais.intersection(ids_existentes)
        df_atualizar = df_visitas[df_visitas['id_composto'].isin(ids_atualizar)]

        print(f"✅ Registros novos por ID composto: {len(df_novos)}")
        print(f"✅ Registros a atualizar: {len(df_atualizar)}")

        # ETAPA 4: INSERIR NO SUPABASE
        print("\n🔄 ETAPA 4: INSERINDO REGISTROS NO SUPABASE")

        # Preparar para inserção
        df_prep = df_novos.copy()  # Apenas registros novos, já que id_composto é a chave primária

        # Converter datas para formato ISO
        for col in ['data_visita', 'data_processamento']:
            if col in df_prep.columns and pd.api.types.is_datetime64_any_dtype(df_prep[col]):
                df_prep[col] = df_prep[col].dt.strftime('%Y-%m-%dT%H:%M:%S')

        # Converter NaN para None
        df_prep = df_prep.replace({np.nan: None})

        # Converter para lista de dicionários
        registros = df_prep.to_dict(orient='records')

        # Definir tamanho do lote
        lote = 100
        total = len(registros)

        # Se não houver registros para inserir, mostrar mensagem e encerrar
        if total == 0:
            print("✅ Nenhum registro novo para inserir.")

            # Mostrar resumo
            fim = datetime.now()
            duracao_total = (fim - inicio_total).total_seconds()

            print("\n=== RESUMO DO ETL DE VISITAS ===")
            print(f"📊 Total de registros no DataFrame: {len(df_visitas)}")
            print(f"🆕 Registros novos: {len(df_novos)}")
            print(f"🔄 Registros já existentes: {len(df_atualizar)}")
            print(f"✅ Nenhum registro novo para inserir.")
            print(f"⏱️ Tempo total do ETL: {duracao_total:.2f} segundos")
            print(f"📅 Data/hora de conclusão: {fim.strftime('%Y-%m-%d %H:%M:%S')}")

            # Voltar ao diretório original
            # os.chdir gerido no setup

            return True

        total_lotes = (total + lote - 1) // lote

        # Contadores
        sucesso = 0
        erro = 0

        inicio = datetime.now()

        # Processar em lotes
        for i in range(0, total, lote):
            lote_atual = registros[i:i+lote]
            num_lote = i // lote + 1

            try:
                print(f"Processando lote {num_lote}/{total_lotes} ({len(lote_atual)} registros)...")

                # Realizar insert simples (não precisamos de upsert já que id_composto é a chave primária)
                resultado = supabase.table(TAB_VISITAS_STAGING).insert(lote_atual).execute()
                
                # Verificar resultado
                if hasattr(resultado, 'error') and resultado.error:
                    print(f"❌ Erro no lote {num_lote}: {resultado.error}")
                    erro += len(lote_atual)
                else:
                    sucesso += len(lote_atual)
                    print(f"✅ Lote {num_lote} processado com sucesso.")

                # Pausa para não sobrecarregar a API
                if num_lote < total_lotes:
                    time.sleep(0.5)

            except Exception as e:
                print(f"❌ Erro no lote {num_lote}: {str(e)}")
                erro += len(lote_atual)

        # Mostrar resumo
        fim = datetime.now()
        duracao = (fim - inicio).total_seconds()
        duracao_total = (fim - inicio_total).total_seconds()

        print("\n=== RESUMO DO ETL DE VISITAS ===")
        print(f"📊 Total de registros no DataFrame: {len(df_visitas)}")
        print(f"🆕 Registros novos: {len(df_novos)}")
        print(f"🔄 Registros já existentes: {len(df_atualizar)}")
        print(f"✅ Registros processados com sucesso: {sucesso}")
        print(f"❌ Registros com erro: {erro}")
        print(f"⏱️ Tempo de inserção: {duracao:.2f} segundos")
        print(f"⏱️ Tempo total do ETL: {duracao_total:.2f} segundos")
        print(f"📅 Data/hora de conclusão: {fim.strftime('%Y-%m-%d %H:%M:%S')}")

        # Voltar ao diretório original
        # os.chdir gerido no setup

        return True

    except Exception as e:
        print(f"❌ Erro durante a execução: {str(e)}")
        traceback.print_exc()

        # Voltar ao diretório original
        # os.chdir gerido no setup

        return False

## Execução: Consolidação e Atualização da Tabela de Visitas (tab_visitas_sq)

In [9]:
# 1. Consolidar as visitas dos 5 relatórios Excel
df_visitas_consolidado = processar_relatorios_visitas(DIR_BD_SQ)

# 2. Atualizar a tabela de staging de visitas no Supabase
if df_visitas_consolidado is not None and not df_visitas_consolidado.empty:
    resultado_tab_visitas = etl_visitas(df_visitas_consolidado)
    if resultado_tab_visitas:
        print('✅ ETL de visitas concluído com sucesso no Supabase!')
    else:
        print('❌ Falha ao atualizar a tabela de visitas no Supabase!')
else:
    print('❌ Falha ao consolidar relatórios de visitas!')

=== PROCESSAMENTO DE RELATÓRIOS DE VISITAS ===
Diretório alterado para: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\BD_SMARTQUESTION

🔍 ETAPA 1: IMPORTANDO RELATÓRIOS DE VISITAS

✅ Relatório de visitas do Regenera lido com sucesso!! (4376 registros)

✅ Relatório de visitas do Alvoar lido com sucesso!! (3680 registros)

✅ Relatório de visitas do Semear lido com sucesso!! (1323 registros)

✅ Relatório de visitas do CCPR lido com sucesso!! (317 registros)
✅ Relatório de visitas do LPA lido com sucesso!! (100 registros)
✅ Total de relatórios importados: 5

🔄 ETAPA 2: CONSOLIDANDO E TRATANDO OS DADOS
Total de colunas únicas: 25
DataFrame consolidado criado com sucesso!
Total de registros: 9796
Total de colunas: 25
Registros duplicados por id_atendimento: 5
Registros duplicados pós-tratamento: 0

✅ Processamento concluído em 3.36 segundos
✅ Total de registros no DataFrame final: 9791
=== ETL DE VISITAS ===
Diretório alterado para: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\PY_SCRIPT\SCRIPTS

🔄 ETAPA 1: CRIANDO ID COMPOSTO E PREPARANDO DADOS
🔄 Gerando ID composto para cada registro...

✅ ID composto gerado para 9791 registros

🔍 ETAPA 2: BUSCANDO REGISTROS EXISTENTES NO SUPABASE
🔍 Buscando registros existentes...

✅ Data de processamento mais recente: 2026-08-18 00:00:00
✅ Encontrados 10260 registros existentes no Supabase

🔍 ETAPA 3: IDENTIFICANDO REGISTROS NOVOS OU ALTERADOS
✅ Registros novos por ID composto: 0
✅ Registros a atualizar: 9791

🔄 ETAPA 4: INSERINDO REGISTROS NO SUPABASE
✅ Nenhum registro novo para inserir.

=== RESUMO DO ETL DE VISITAS ===
📊 Total de registros no DataFrame: 9791
🆕 Registros novos: 0
🔄 Registros já existentes: 9791
✅ Nenhum registro novo para inserir.
⏱️ Tempo total do ETL: 5.17 segundos
📅 Data/hora de conclusão: 2026-08-18 16:02:21
✅ ETL de visitas concluído com sucesso no Supabase!

# 6. Análise de Indicadores de Visitas

In [10]:

# Diretório onde está o arquivo .env
DIRETORIO_ENV = DIR_BD_SQ
# os.chdir gerido no setup

# Carregar variáveis de ambiente

# Configurar conexão com o Supabase
supabase_url = os.getenv('SUPABASE_URL')
supabase_key = os.getenv('SUPABASE_SERVICE_KEY')
supabase = create_client(supabase_url, supabase_key)

print("=== CRIANDO TABELA FATO DE VISITAS ===")

# 1. Obter dados de visitas
print("\n🔍 ETAPA 1: IMPORTANDO DADOS DE VISITAS")

# Definir período de consulta
data_inicial = DATA_INICIAL_ELABORE
data_final = datetime.now().strftime('%Y-%m-%d')

# Definir colunas a serem importadas
colunas_visitas = 'id_atendimento,nome_consultor,codigo_lr,id_farm,nome_produtor,data_visita,origem_dados'

try:
    # Executar a consulta com filtros de data
    resultado_visitas = supabase.table(TAB_VISITAS_STAGING) \
        .select(colunas_visitas) \
        .gte('data_visita', data_inicial) \
        .lte('data_visita', data_final) \
        .execute()
    
    if resultado_visitas.data:
        df_visitas = pd.DataFrame(resultado_visitas.data)

        # Converter a coluna de data para o tipo datetime
        df_visitas['data_visita'] = pd.to_datetime(df_visitas['data_visita'])
        # Mostrar a data mais recente
        print(f"Data mais recente no relatório de visitas: {df_visitas.data_visita.max()}")

        # Adicionar coluna mes_ano para facilitar o merge
        df_visitas['mes_ano'] = df_visitas['data_visita'].dt.strftime('%Y-%m')
        # Mostrar a data mais recente
        print(f"Mes-Ano mais recente no relatório de visitas: {df_visitas.mes_ano.max()}")
        print(f"✅ Importação de visitas concluída: {len(df_visitas)} registros")
    else:
        print("⚠️ Nenhum registro de visita encontrado para o período especificado.")
        df_visitas = pd.DataFrame()

except Exception as e:
    print(f"❌ Erro ao importar dados de visitas: {str(e)}")
    df_visitas = pd.DataFrame()

# 2. Obter dados de produtores ativos
print("\n🔍 ETAPA 2: IMPORTANDO DADOS DE PRODUTORES ATIVOS")

projetos = ['REGENERA', 'ALVOAR ECO', 'ALVOAR ASSIST', 'SEMEAR', 'ATEG_CCPR', 'Alvoar', 'LPA']  # Lista de projetos a filtrar

try:
    # Executar a consulta sem filtro em coluna inexistente (data_referencia)
    resultado_vinculos = supabase.table(TAB_VINCULOS_STAGING) \
        .select('*') \
        .in_('projeto', projetos) \
        .execute()

    if resultado_vinculos.data:
        df_vinculos_mes = pd.DataFrame(resultado_vinculos.data)
        if 'consultor_grupo_atendimento' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
            df_vinculos_mes.rename(columns={'consultor_grupo_atendimento': 'nome_consultor'}, inplace=True)
        elif 'consultor' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
            df_vinculos_mes.rename(columns={'consultor': 'nome_consultor'}, inplace=True)

        if 'data_referencia' not in df_vinculos_mes.columns:
            df_vinculos_mes['data_referencia'] = pd.to_datetime(
                df_vinculos_mes.get('data_processamento', df_vinculos_mes.get('data_associacao', pd.Timestamp.now()))
            )
        else:
            df_vinculos_mes['data_referencia'] = pd.to_datetime(df_vinculos_mes['data_referencia'])

        # Retirar os grupos de atendimento do CFT
        grupo_cft = [
            'DAYANNE UCHOA VEIGA / DEBORA LIMA DE OLIVEIRA / MARIO BARBOSA ROSA FILHO / MATEUS CARNIELLI / TALITA FONTES / THAYNAN FERREIRA DE ARAUJO',
            'HUGO LOPES / MATEUS CARNIELLI / ROMARCIO PAULO DE OLIVEIRA / THAYNAN FERREIRA DE ARAUJO',
            'BRUNO ANTONIO FERRONI RODRIGUES / HUGO LOPES / MATEUS CARNIELLI / THAYNAN FERREIRA DE ARAUJO',
            'MATHEUS GOMIDES GONCALVES', 'TALITA FONTES'
        ]
        if 'nome_consultor' in df_vinculos_mes.columns:
            df_vinculos_mes = df_vinculos_mes[~df_vinculos_mes['nome_consultor'].isin(grupo_cft)]

        # Adicionar coluna mes_ano para facilitar o merge
        df_vinculos_mes['mes_ano'] = df_vinculos_mes['data_referencia'].dt.strftime('%Y-%m')

        print(f"Data mais recente no relatório de vínculos: {df_vinculos_mes.data_referencia.max() if not df_vinculos_mes.empty else 'N/A'}")
        print(f"Mes-Ano mais recente no relatório de vínculos: {df_vinculos_mes.mes_ano.max() if not df_vinculos_mes.empty else 'N/A'}")
        print(f"✅ Importação de produtores ativos concluída: {len(df_vinculos_mes)} registros")
    else:
        print("⚠️ Nenhum registro de produtor ativo encontrado para o período especificado.")
        df_vinculos_mes = pd.DataFrame()

except Exception as e:
    print(f"❌ Erro ao importar dados de produtores ativos: {str(e)}")
    df_vinculos_mes = pd.DataFrame()

# 3. Preparar os dados para o merge
print("\n🔄 ETAPA 3: PREPARANDO DADOS PARA INTEGRAÇÃO")

# Normalizar nomes de colunas para o merge
df_vinculos_mes = df_vinculos_mes.rename(columns={
    'consultor': 'nome_consultor',
    'projeto': 'origem_dados'
})

# Verificar se as colunas necessárias existem
colunas_necessarias_visitas = ['codigo_lr', 'nome_consultor', 'mes_ano']
colunas_necessarias_vinculos = ['codigo_lr', 'nome_consultor', 'mes_ano']

for coluna in colunas_necessarias_visitas:
    if coluna not in df_visitas.columns:
        print(f"❌ Coluna {coluna} não encontrada em df_visitas")
        exit()

for coluna in colunas_necessarias_vinculos:
    if coluna not in df_vinculos_mes.columns:
        print(f"❌ Coluna {coluna} não encontrada em df_vinculos_mes")
        exit()

# 4. Criar a tabela fato PRINCIPAL (AGREGADA)
print("\n🔄 ETAPA 4: CRIANDO TABELA FATO PRINCIPAL (AGREGADA)")

# Agrupar visitas por produtor, consultor e mês para contar o número de visitas
# Esta é a contagem CORRETA de visitas para cada combinação (produtor, consultor, mês)
visitas_agrupadas = df_visitas.groupby(['codigo_lr', 'nome_consultor', 'mes_ano']).size().reset_index(name='qtd_visitas')

# Criar uma tabela base com todas as combinações de produtor-consultor-mês dos vínculos
# Esta será a granularidade da nossa tabela fato principal
df_fato_base = df_vinculos_mes[['codigo_lr', 'nome_consultor', 'nome_produtor', 'nome_propriedade',
                                 'origem_dados', 'unidade_atendimento', 'cidade_produtor',
                                 'estado_produtor', 'mes_ano']].copy()

# Fazer o merge com as visitas agrupadas (left join para manter todos os produtores ativos)
# O resultado df_fato_principal terá uma linha por (codigo_lr, nome_consultor, mes_ano)
df_fato_principal = pd.merge(
    df_fato_base,
    visitas_agrupadas,
    on=['codigo_lr', 'nome_consultor', 'mes_ano'],
    how='left'
)

# Preencher valores nulos na coluna de quantidade de visitas com 0 (para produtores sem visita)
df_fato_principal['qtd_visitas'] = df_fato_principal['qtd_visitas'].fillna(0)

# Adicionar coluna binária para indicar se houve visita
df_fato_principal['visitado'] = np.where(df_fato_principal['qtd_visitas'] > 0, 1, 0)

# A df_fato_principal agora é a sua df_fato_final para os cálculos de métricas
df_fato_final = df_fato_principal.copy() # Renomeando para manter a consistência com o restante do seu código

#  NOVO: Criar a tabela de detalhes de visitas (para o drill-down)
print("\n🔄 ETAPA 5: CRIANDO TABELA DE DETALHES DE VISITAS")

# Selecionar as colunas relevantes do df_visitas original
df_visitas_detalhe = df_visitas[['id_atendimento', 'data_visita', 'codigo_lr', 'id_farm', 'nome_consultor', 'mes_ano', 'nome_produtor']].copy()

# Opcional: Adicionar informações do vínculo para enriquecer a tabela de detalhes
# Isso pode ser útil se você quiser exibir mais detalhes do produtor/propriedade
df_visitas_detalhe = pd.merge(
    df_visitas_detalhe,
    df_vinculos_mes[['codigo_lr', 'nome_produtor', 'nome_propriedade', 'unidade_atendimento', 'cidade_produtor', 'estado_produtor', 'origem_dados', 'mes_ano']],
    on=['codigo_lr', 'nome_produtor', 'mes_ano'], # Use nome_produtor para garantir que o merge seja correto se houver múltiplos consultores para o mesmo produtor
    how='left',
    suffixes=('_visita', '_vinculo')
)

# Tratar colunas duplicadas após o merge, se necessário
# Por exemplo, se 'nome_produtor_visita' e 'nome_produtor_vinculo' são iguais, manter apenas um
for col in ['nome_produtor', 'origem_dados']:
    if f'{col}_visita' in df_visitas_detalhe.columns and f'{col}_vinculo' in df_visitas_detalhe.columns:
        df_visitas_detalhe[col] = df_visitas_detalhe[f'{col}_visita'].fillna(df_visitas_detalhe[f'{col}_vinculo'])
        df_visitas_detalhe.drop(columns=[f'{col}_visita', f'{col}_vinculo'], inplace=True)
    elif f'{col}_vinculo' in df_visitas_detalhe.columns:
        df_visitas_detalhe[col] = df_visitas_detalhe[f'{col}_vinculo']
        df_visitas_detalhe.drop(columns=[f'{col}_vinculo'], inplace=True)
    elif f'{col}_visita' in df_visitas_detalhe.columns:
        df_visitas_detalhe[col] = df_visitas_detalhe[f'{col}_visita']
        df_visitas_detalhe.drop(columns=[f'{col}_visita'], inplace=True)


print(f"✅ Tabela de detalhes de visitas criada: {len(df_visitas_detalhe)} registros")


# 6. Finalizar e salvar os resultados
print("\n✅ ETAPA 6: FINALIZANDO E SALVANDO RESULTADOS")

# Ordenar o DataFrame principal
df_fato_final = df_fato_final.loc[:, ~df_fato_final.columns.duplicated()].copy()
df_fato_final = df_fato_final.sort_values(by=['mes_ano', 'origem_dados', 'nome_consultor', 'codigo_lr'])
df_fato_final = df_fato_final.loc[(df_fato_final['unidade_atendimento']!='UNIDADE GENERICA') & (df_fato_final['nome_consultor']!='TALITA FONTES')]

# Adicionar coluna de data de processamento
df_fato_final['data_processamento'] = datetime.now()

# Mostrar a data mais recente
print(f"Mes-Ano mais recente da df_fato_final: {df_fato_final.mes_ano.max()}")

# Exibir informações sobre a tabela fato
print(f"\n✅ Tabela fato principal criada com sucesso!")
print(f"Total de registros: {len(df_fato_final)}")

# Exibir informações sobre a tabela de detalhes
print(f"\n✅ Tabela de detalhes de visitas criada com sucesso!")
print(f"Total de registros: {len(df_visitas_detalhe)}")

=== CRIANDO TABELA FATO DE VISITAS ===

🔍 ETAPA 1: IMPORTANDO DADOS DE VISITAS

Data mais recente no relatório de visitas: 2026-08-17 00:00:00
Mes-Ano mais recente no relatório de visitas: 2026-08
✅ Importação de visitas concluída: 7428 registros

🔍 ETAPA 2: IMPORTANDO DADOS DE PRODUTORES ATIVOS

Data mais recente no relatório de vínculos: 2026-08-18 09:45:49
Mes-Ano mais recente no relatório de vínculos: 2026-08
✅ Importação de produtores ativos concluída: 1410 registros

🔄 ETAPA 3: PREPARANDO DADOS PARA INTEGRAÇÃO

🔄 ETAPA 4: CRIANDO TABELA FATO PRINCIPAL (AGREGADA)

🔄 ETAPA 5: CRIANDO TABELA DE DETALHES DE VISITAS
✅ Tabela de detalhes de visitas criada: 7668 registros

✅ ETAPA 6: FINALIZANDO E SALVANDO RESULTADOS
Mes-Ano mais recente da df_fato_final: 2026-08

✅ Tabela fato principal criada com sucesso!
Total de registros: 1407

✅ Tabela de detalhes de visitas criada com sucesso!
Total de registros: 7668

# 7. Tabela Fato: Visitas (f_Visitas)

In [11]:

# Diretório onde está o arquivo .env
DIRETORIO_ENV = DIR_BD_SQ
# os.chdir gerido no setup

# Carregar variáveis de ambiente

# Configurar conexão com o Supabase
supabase_url = os.getenv('SUPABASE_URL')
supabase_key = os.getenv('SUPABASE_SERVICE_KEY')
supabase = create_client(supabase_url, supabase_key)

# Nome da tabela no Supabase
SUPABASE_TABLE_NAME = TAB_VISITAS_FATO

def run_etl_and_upsert_f_visitas(data_inicial: str, data_final: str) -> pd.DataFrame:
    """
    Executa o processo ETL para construir a tabela f_visitas e realiza um upsert
    (delete/insert granular) no Supabase para o período especificado,
    sem depender da coluna 'id_composto' no Supabase.

    Args:
        data_inicial (str): Data de início do período de consulta (YYYY-MM-DD).
        data_final (str): Data de fim do período de consulta (YYYY-MM-DD).

    Returns:
        pd.DataFrame: O DataFrame f_visitas final após o tratamento e antes do upsert.
    """
    print("=== INICIANDO ROTINA ETL E UPSERT GRANULAR PARA F_VISITAS ===")

    # 1. Obter dados de visitas
    print("\n🔍 ETAPA 1: IMPORTANDO DADOS DE VISITAS")
    colunas_visitas = 'id_atendimento,nome_consultor,codigo_lr,id_farm,nome_produtor,data_visita,origem_dados,valor_pago_produtor,valor_pago_agroindustria'
    try:
        resultado_visitas = supabase.table(TAB_VISITAS_STAGING) \
            .select(colunas_visitas) \
            .gte('data_visita', data_inicial) \
            .lte('data_visita', data_final) \
            .execute()
        if resultado_visitas.data:
            df_visitas = pd.DataFrame(resultado_visitas.data)
            df_visitas['data_visita'] = pd.to_datetime(df_visitas['data_visita'])
            df_visitas['mes_ano'] = df_visitas['data_visita'].dt.strftime('%Y-%m')
            df_visitas['mes_referencia'] = df_visitas['data_visita'].dt.to_period('M').dt.to_timestamp()
            df_visitas['valor_pago_produtor'] = pd.to_numeric(df_visitas['valor_pago_produtor'], errors='coerce').astype('Float64')
            df_visitas['valor_pago_agroindustria'] = pd.to_numeric(df_visitas['valor_pago_agroindustria'], errors='coerce').astype('Float64')
            print(f"✅ Importação de visitas concluída: {len(df_visitas)} registros")
        else:
            print("⚠️ Nenhum registro de visita encontrado para o período especificado.")
            df_visitas = pd.DataFrame()
    except Exception as e:
        print(f"❌ Erro ao importar dados de visitas: {str(e)}")
        df_visitas = pd.DataFrame()

        # 2. Obter dados de produtores ativos
    print("🔍 ETAPA 2: IMPORTANDO DADOS DE PRODUTORES ATIVOS")
    projetos = ['REGENERA', 'ALVOAR ECO', 'ALVOAR ASSIST', 'SEMEAR', 'ATEG_CCPR', 'Alvoar', 'LPA']
    try:
        resultado_vinculos = supabase.table(TAB_VINCULOS_STAGING).select('*').in_('projeto', projetos).execute()
        if resultado_vinculos.data:
            df_vinculos_mes = pd.DataFrame(resultado_vinculos.data)
            if 'consultor_grupo_atendimento' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
                df_vinculos_mes.rename(columns={'consultor_grupo_atendimento': 'nome_consultor'}, inplace=True)
            elif 'consultor' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
                df_vinculos_mes.rename(columns={'consultor': 'nome_consultor'}, inplace=True)

            if 'data_referencia' not in df_vinculos_mes.columns:
                df_vinculos_mes['data_referencia'] = pd.to_datetime(df_vinculos_mes.get('data_processamento', df_vinculos_mes.get('data_associacao', pd.Timestamp.now())))
            else:
                df_vinculos_mes['data_referencia'] = pd.to_datetime(df_vinculos_mes['data_referencia'])
                
            df_vinculos_mes['mes_ano'] = df_vinculos_mes['data_referencia'].dt.strftime('%Y-%m')
            df_vinculos_mes['mes_referencia'] = df_vinculos_mes['data_referencia'].dt.to_period('M').dt.to_timestamp()
            
            if 'meses_ativos_vinculo' not in df_vinculos_mes.columns:
                df_vinculos_mes['meses_ativos_vinculo'] = 1
            else:
                df_vinculos_mes['meses_ativos_vinculo'] = pd.to_numeric(df_vinculos_mes['meses_ativos_vinculo'], errors='coerce').fillna(1).astype('Int64')

            if 'codigo_fazenda' not in df_vinculos_mes.columns:
                df_vinculos_mes['codigo_fazenda'] = None

            grupo_cft = [
                'DAYANNE UCHOA VEIGA / DEBORA LIMA DE OLIVEIRA / MARIO BARBOSA ROSA FILHO / MATEUS CARNIELLI / TALITA FONTES / THAYNAN FERREIRA DE ARAUJO',
                'HUGO LOPES / MATEUS CARNIELLI / ROMARCIO PAULO DE OLIVEIRA / THAYNAN FERREIRA DE ARAUJO',
                'BRUNO ANTONIO FERRONI RODRIGUES / HUGO LOPES / MATEUS CARNIELLI / THAYNAN FERREIRA DE ARAUJO',
                'MATHEUS GOMIDES GONCALVES'
            ]
            if 'nome_consultor' in df_vinculos_mes.columns:
                df_vinculos_mes = df_vinculos_mes[~df_vinculos_mes['nome_consultor'].isin(grupo_cft)]

            print(f"✅ Importação de vínculos concluída: {len(df_vinculos_mes)} registros")
        else:
            print("⚠️ Nenhum registro de vínculo encontrado para o período especificado.")
            df_vinculos_mes = pd.DataFrame()
    except Exception as e:
        print(f"❌ Erro ao importar dados de vínculos: {str(e)}")
        df_vinculos_mes = pd.DataFrame()

    # 3. Validação e Preparação dos DataFrames
    print("\n🔍 ETAPA 3: VALIDANDO E PREPARANDO DATAFRAMES")
    if df_visitas.empty or df_vinculos_mes.empty:
        print("❌ Não foi possível criar a tabela fato devido a DataFrames vazios.")
        return pd.DataFrame()

    colunas_necessarias_visitas = ['id_atendimento', 'nome_consultor', 'codigo_lr', 'nome_produtor', 'data_visita', 'mes_ano', 'mes_referencia', 'origem_dados','valor_pago_produtor','valor_pago_agroindustria']
    colunas_necessarias_vinculos = ['codigo_lr', 'nome_consultor', 'mes_ano', 'mes_referencia', 'nome_produtor', 'nome_propriedade', 'projeto', 'unidade_atendimento', 'cidade_produtor', 'estado_produtor', 'codigo_agroindustria','codigo_fazenda','meses_ativos_vinculo']

    for coluna in colunas_necessarias_visitas:
        if coluna not in df_visitas.columns:
            print(f"❌ Coluna {coluna} não encontrada em df_visitas")
            return pd.DataFrame()
    for coluna in colunas_necessarias_vinculos:
        if coluna not in df_vinculos_mes.columns:
            print(f"❌ Coluna {coluna} não encontrada em df_vinculos_mes")
            return pd.DataFrame()

    # 4. Construindo a Tabela Fato F_VISITAS
    print("\n🔄 ETAPA 4: CONSTRUINDO A TABELA FATO F_VISITAS")
    df_base_vinculos = df_vinculos_mes[[
        'codigo_lr', 'nome_consultor', 'mes_ano', 'mes_referencia','meses_ativos_vinculo', 'unidade_atendimento', 'nome_produtor', 'nome_propriedade',
        'projeto', 'codigo_agroindustria', 'codigo_fazenda', 'cidade_produtor', 'estado_produtor'
    ]].drop_duplicates(subset=['codigo_lr', 'nome_consultor', 'mes_ano']).copy()

    df_visitas_para_merge = df_visitas[[
        'id_atendimento', 'data_visita', 'codigo_lr','nome_consultor', 'mes_ano','valor_pago_produtor','valor_pago_agroindustria'
    ]].copy()
    
    # Normalizar chaves de junção para garantir casamento perfeito
    # Normalizar chaves e remover caracteres invisiveis (\xa0)
    df_base_vinculos['codigo_lr'] = df_base_vinculos['codigo_lr'].astype(str).str.strip().str.replace('\xa0', '').str.upper()
    df_visitas_para_merge['codigo_lr'] = df_visitas_para_merge['codigo_lr'].astype(str).str.strip().str.replace('\xa0', '').str.upper()
    df_visitas_para_merge = df_visitas_para_merge.drop(columns=['nome_consultor'], errors='ignore')

    f_visitas = pd.merge(
        df_base_vinculos,
        df_visitas_para_merge,
        on=['codigo_lr', 'mes_ano'],
        how='left'
    )

    # Antes: o id_farm vinha da tab-visitas. Agora, vem da tab_vinculos Renomear para não mudar estrutura
    # Garantir que f_visitas armazene APENAS eventos de visitas efetivamente realizadas (com data_visita válida)
    f_visitas = f_visitas[f_visitas['data_visita'].notna()].copy()

    f_visitas.rename(columns={'codigo_fazenda':'id_farm'},inplace=True)
    
    # 5. Finalizar e preparar para o Supabase
    print("\n✅ ETAPA 5: FINALIZANDO E PREPARANDO PARA SUPABASE")
    f_visitas = f_visitas.loc[(f_visitas['unidade_atendimento'] != 'UNIDADE GENERICA') & (f_visitas['nome_consultor'] != 'TALITA FONTES')]
    f_visitas.drop(columns=['mes_ano', 'unidade_atendimento', 'cidade_produtor', 'estado_produtor'], inplace=True)

    # Converter id_atendimento para o tipo Int64 (inteiro que aceita NaN/None)
    f_visitas['id_atendimento'] = f_visitas['id_atendimento'].astype('Int64')

    # Adicionar coluna de data de processamento (datetime)
    # Esta coluna NÃO fará parte do hash para garantir estabilidade
    f_visitas['data_processamento'] = datetime.now()

    # Formatar colunas de data/datetime para o Supabase (ISO 8601 strings com 'Z' para UTC)
    # ESTAS SÃO AS STRINGS QUE SERÃO ENVIADAS PARA O SUPABASE E USADAS NO HASH (se aplicável)
    f_visitas['data_visita_str'] = f_visitas['data_visita'].apply(
        lambda x: x.isoformat(timespec='milliseconds') + 'Z' if pd.notna(x) else None
    )
    f_visitas['mes_referencia_str'] = f_visitas['mes_referencia'].apply(
        lambda x: x.isoformat(timespec='milliseconds') + 'Z' if pd.notna(x) else None
    )
    # data_processamento_str é formatada para envio, mas NÃO para o hash
    f_visitas['data_processamento_str'] = f_visitas['data_processamento'].apply(
        lambda x: x.isoformat(timespec='milliseconds') + 'Z' if pd.notna(x) else None
    )

    # Reordenar o DataFrame final
    f_visitas = f_visitas.sort_values(by=['mes_referencia', 'projeto', 'nome_consultor', 'codigo_lr', 'data_visita'])

    print(f"✅ Tabela f_visitas tratada e pronta para upsert: {len(f_visitas)} registros")
    print("\nExemplo de f_visitas (primeiras 5 linhas com id_composto):")
    print(f_visitas.head())

    #  Geração do id_composto LOCALMENTE para f_visitas
    # Colunas que formam a chave composta para o hash
    hash_cols = ['codigo_lr', 'nome_consultor', 'mes_referencia_str', 'id_atendimento']
    
    f_visitas_temp_for_hash = f_visitas[hash_cols].copy()
    
    # Tratar None/NaN para string 'NULL_VAL' para o hash
    # IMPORTANTE: id_atendimento deve ser tratado como string para o hash
    f_visitas_temp_for_hash['id_atendimento'] = f_visitas_temp_for_hash['id_atendimento'].astype(str).replace({'<NA>': 'NULL_VAL'})
    f_visitas_temp_for_hash['mes_referencia_str'] = f_visitas_temp_for_hash['mes_referencia_str'].astype(str).replace({'None': 'NULL_VAL'})
    # Adicione tratamento para outras colunas em hash_cols se elas puderem ser None/NaN
    f_visitas_temp_for_hash['codigo_lr'] = f_visitas_temp_for_hash['codigo_lr'].astype(str).replace({'None': 'NULL_VAL', 'nan': 'NULL_VAL'})
    f_visitas_temp_for_hash['nome_consultor'] = f_visitas_temp_for_hash['nome_consultor'].astype(str).replace({'None': 'NULL_VAL', 'nan': 'NULL_VAL'})
    
    
    f_visitas_hash_input = f_visitas_temp_for_hash.agg(''.join, axis=1)
    f_visitas['id_composto'] = f_visitas_hash_input.apply(lambda x: hashlib.sha256(x.encode()).hexdigest())
    #  FIM da Geração do id_composto LOCALMENTE


    # 6. Rotina de UPSERT no Supabase
    print("\n🚀 ETAPA 6: REALIZANDO UPSERT NO SUPABASE")

    # Adicionar a coluna 'id_composto' ao DataFrame que será enviado para o Supabase
    # Isso é crucial para que o upsert saiba qual registro usar para o conflito
    f_visitas_to_upsert = f_visitas.copy()
    
    #  REMOVER DUPLICATAS DE id_composto DO DATAFRAME ANTES DO UPSERT
    initial_rows_upsert = len(f_visitas_to_upsert)
    f_visitas_to_upsert.drop_duplicates(subset=['id_composto'], keep='first', inplace=True)
    if len(f_visitas_to_upsert) < initial_rows_upsert:
        print(f"   - Removidas {initial_rows_upsert - len(f_visitas_to_upsert)} linhas duplicadas com base em 'id_composto' antes do UPSERT.")
    
    # Preparar o DataFrame para inserção/upsert, usando as colunas de string de data
    # e removendo as colunas temporárias ou as originais de data/datetime
    f_visitas_to_upsert = f_visitas_to_upsert.drop(columns=['data_visita', 'mes_referencia', 'data_processamento'], errors='ignore')
    f_visitas_to_upsert.rename(columns={
        'data_visita_str': 'data_visita',
        'mes_referencia_str': 'mes_referencia',
        'data_processamento_str': 'data_processamento'
    }, inplace=True)

    # ✅ TRATAMENTO FINAL DE np.nan PARA None EM TODAS AS COLUNAS ANTES DO UPSERT
    print("\n🔄 Tratando np.nan para None em todas as colunas antes do upsert...")
    for col in f_visitas_to_upsert.columns:
        # Para colunas numéricas (Float64, Int64)
        if pd.api.types.is_numeric_dtype(f_visitas_to_upsert[col]):
            if f_visitas_to_upsert[col].isnull().any():
                f_visitas_to_upsert.loc[f_visitas_to_upsert[col].isnull(), col] = None
                # print(f"  ✅ Coluna '{col}': np.nan/NaT transformados para None.") # Opcional: remover para menos logs
        # Para colunas de objeto (string) que podem ter a string 'NaN' ou np.nan
        elif pd.api.types.is_object_dtype(f_visitas_to_upsert[col]):
            if (f_visitas_to_upsert[col] == 'NaN').any():
                f_visitas_to_upsert.loc[f_visitas_to_upsert[col] == 'NaN', col] = None
                # print(f"  ✅ Coluna '{col}': string 'NaN' transformadas para None.") # Opcional: remover para menos logs
            if f_visitas_to_upsert[col].isnull().any():
                f_visitas_to_upsert.loc[f_visitas_to_upsert[col].isnull(), col] = None
                # print(f"  ✅ Coluna '{col}': np.nan em objeto transformados para None.") # Opcional: remover para menos logs
    print("✅ Tratamento de NaN para None concluído.")

    records_to_upsert = f_visitas_to_upsert.to_dict(orient='records')

    print(f"   - Realizando UPSERT de {len(records_to_upsert)} registros no Supabase...")

    chunk_size = 1000
    for i in range(0, len(records_to_upsert), chunk_size):
        chunk = records_to_upsert[i:i + chunk_size]
        try:
            # Usar a função upsert do Supabase, especificando 'id_composto' como a coluna de conflito
            response = supabase.table(SUPABASE_TABLE_NAME) \
                .upsert(chunk, on_conflict='id_composto') \
                .execute()
            if response.data:
                print(f"     - UPSERT de {len(response.data)} registros em chunk {i//chunk_size + 1}.")
            else:
                print(f"     - ATENÇÃO: Nenhum registro UPSERTED para chunk {i//chunk_size + 1} ou erro na resposta. Resposta: {response.status_code} - {response.data}")
        except Exception as e:
            print(f"❌ Erro ao realizar UPSERT no Supabase (chunk {i//chunk_size + 1}): {str(e)}")
            # Opcional: Logar o chunk que falhou para depuração
            # print(f"   Chunk que falhou: {chunk}")

    print(f"   - UPSERT concluído. Total de registros processados: {len(records_to_upsert)}")

    print("\n✅ Rotina ETL e UPSERT concluída com sucesso!")
    return f_visitas 

#  Exemplo de como chamar a função

## Execução: Tabela Fato Visitas (f_Visitas)

In [12]:
data_inicial_etl = '2026-01-01'
# Trazer o dia atual
hoje = date.today()
# Separa primeiro e último dia
_, ultimo_dia = calendar.monthrange(hoje.year, hoje.month)
# Criar a data do último dia do mês atual
data_ultimo_dia = date(hoje.year, hoje.month, ultimo_dia)
# Define a data final do ETL
data_final_etl = data_ultimo_dia

final_f_visitas_df = run_etl_and_upsert_f_visitas(data_inicial_etl, data_final_etl)

if not final_f_visitas_df.empty:
    print(f"\nDataFrame final retornado pela função (primeiras 5 linhas):\n{final_f_visitas_df.head()}")
    data_export = datetime.now().strftime("%Y_%m_%d_%H%M%S")
    pasta_saida = raiz_projeto / "DB" / "OUTPUT" / "PROCESSED"
    pasta_saida.mkdir(parents=True, exist_ok=True)
    caminho_export = pasta_saida / f"{data_export}_f_visitas_final_pos_upsert.xlsx"
    exportar_xlsx_formatado(df=final_f_visitas_df, caminho_saida=caminho_export)
    aplicar_estilo_listrado_xlsx(caminho_arquivo=caminho_export, cor_cabecalho="#247B72", cor_texto_cabecalho="#FFFFFF", cor_linha_alternada="#F2F2F2", cor_linha_base="#FFFFFF", primeira_linha_cinza=True)
    print(f"✅ Excel formatado exportado com sucesso em: {caminho_export}")

=== INICIANDO ROTINA ETL E UPSERT GRANULAR PARA F_VISITAS ===

🔍 ETAPA 1: IMPORTANDO DADOS DE VISITAS

✅ Importação de visitas concluída: 6434 registros
🔍 ETAPA 2: IMPORTANDO DADOS DE PRODUTORES ATIVOS

✅ Importação de vínculos concluída: 1410 registros

🔍 ETAPA 3: VALIDANDO E PREPARANDO DATAFRAMES

🔄 ETAPA 4: CONSTRUINDO A TABELA FATO F_VISITAS

✅ ETAPA 5: FINALIZANDO E PREPARANDO PARA SUPABASE
✅ Tabela f_visitas tratada e pronta para upsert: 994 registros

Exemplo de f_visitas (primeiras 5 linhas com id_composto):
  codigo_lr                    nome_consultor mes_referencia  \
0   LR09606  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
1   LR09652  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
2   LR09660  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
4   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
5   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01

   meses_ativos_vinculo                     nome_produtor  \
0                     1          ANTERO FERREIRA DA CUNHA
1                     1                   JOAO MARRA NETO
2                     1  JULIANO AURELIO PEREIRA SOBRINHO
4                     1         MARTA CASSIANA DOS SANTOS
5                     1         MARTA CASSIANA DOS SANTOS

                                 nome_propriedade        projeto  \
0              FAZENDA SANTO ANTONIO-QUEBRA ANZOL  ALVOAR ASSIST
1              FAZENDA SANTO ANTONIO LUGAR ESTIVA  ALVOAR ASSIST
2  FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE  ALVOAR ASSIST
4                                  FAZENDA ANGICO  ALVOAR ASSIST
5                                  FAZENDA ANGICO  ALVOAR ASSIST

  codigo_agroindustria id_farm  id_atendimento data_visita  \
0              1012313    None       401000108  2026-05-27
1              1012857    None       401000107  2026-05-27
2              1012353    None       401000102  2026-05-20
4              1012046    None       401000106  2026-05-26
5              1012046    None       401000109  2026-05-27

   valor_pago_produtor  valor_pago_agroindustria         data_processamento  \
0                375.0                     500.0 2026-08-18 16:02:24.467312
1                650.0                     500.0 2026-08-18 16:02:24.467312
2                375.0                     500.0 2026-08-18 16:02:24.467312
4                375.0                     500.0 2026-08-18 16:02:24.467312
5                850.0                     500.0 2026-08-18 16:02:24.467312

            data_visita_str        mes_referencia_str  \
0  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z
1  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z
2  2026-05-20T00:00:00.000Z  2026-05-01T00:00:00.000Z
4  2026-05-26T00:00:00.000Z  2026-05-01T00:00:00.000Z
5  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z

     data_processamento_str
0  2026-08-18T16:02:24.467Z
1  2026-08-18T16:02:24.467Z
2  2026-08-18T16:02:24.467Z
4  2026-08-18T16:02:24.467Z
5  2026-08-18T16:02:24.467Z

🚀 ETAPA 6: REALIZANDO UPSERT NO SUPABASE
   - Removidas 4 linhas duplicadas com base em 'id_composto' antes do UPSERT.

🔄 Tratando np.nan para None em todas as colunas antes do upsert...
✅ Tratamento de NaN para None concluído.
   - Realizando UPSERT de 990 registros no Supabase...

     - UPSERT de 990 registros em chunk 1.
   - UPSERT concluído. Total de registros processados: 990

✅ Rotina ETL e UPSERT concluída com sucesso!

DataFrame final retornado pela função (primeiras 5 linhas):
  codigo_lr                    nome_consultor mes_referencia  \
0   LR09606  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
1   LR09652  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
2   LR09660  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
4   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01
5   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ     2026-05-01

   meses_ativos_vinculo                     nome_produtor  \
0                     1          ANTERO FERREIRA DA CUNHA
1                     1                   JOAO MARRA NETO
2                     1  JULIANO AURELIO PEREIRA SOBRINHO
4                     1         MARTA CASSIANA DOS SANTOS
5                     1         MARTA CASSIANA DOS SANTOS

                                 nome_propriedade        projeto  \
0              FAZENDA SANTO ANTONIO-QUEBRA ANZOL  ALVOAR ASSIST
1              FAZENDA SANTO ANTONIO LUGAR ESTIVA  ALVOAR ASSIST
2  FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE  ALVOAR ASSIST
4                                  FAZENDA ANGICO  ALVOAR ASSIST
5                                  FAZENDA ANGICO  ALVOAR ASSIST

  codigo_agroindustria id_farm  id_atendimento data_visita  \
0              1012313    None       401000108  2026-05-27
1              1012857    None       401000107  2026-05-27
2              1012353    None       401000102  2026-05-20
4              1012046    None       401000106  2026-05-26
5              1012046    None       401000109  2026-05-27

   valor_pago_produtor  valor_pago_agroindustria         data_processamento  \
0                375.0                     500.0 2026-08-18 16:02:24.467312
1                650.0                     500.0 2026-08-18 16:02:24.467312
2                375.0                     500.0 2026-08-18 16:02:24.467312
4                375.0                     500.0 2026-08-18 16:02:24.467312
5                850.0                     500.0 2026-08-18 16:02:24.467312

            data_visita_str        mes_referencia_str  \
0  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z
1  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z
2  2026-05-20T00:00:00.000Z  2026-05-01T00:00:00.000Z
4  2026-05-26T00:00:00.000Z  2026-05-01T00:00:00.000Z
5  2026-05-27T00:00:00.000Z  2026-05-01T00:00:00.000Z

     data_processamento_str                                        id_composto
0  2026-08-18T16:02:24.467Z  a15c4a16f76a7a22499609e480df6aaf8ad1c2a95ea429...
1  2026-08-18T16:02:24.467Z  0fc58e3c5a932d86ccafbc7cfe3489c15af33347138e8e...
2  2026-08-18T16:02:24.467Z  e5c6067f280ddead481dc62521d2f012f9b915b49d2a04...
4  2026-08-18T16:02:24.467Z  38178e637e196b45459b4297b0156c1a024b5b6d7ebb54...
5  2026-08-18T16:02:24.467Z  eca10ae9dfa20d9f94bd731834b811decc6b9130ec4414...

✅ Excel formatado exportado com sucesso em: C:\Users\Guilherme\LABOR RURAL\Analytics - Departamento Analytics\POWER_BI\PROJETOS\BI_LABOR_RURAL\PY_SCRIPT\DB\OUTPUT\PROCESSED\2026_08_18_160224_f_visitas_final_pos_upsert.xlsx

In [13]:
final_f_visitas_df

,codigo_lr,nome_consultor,mes_referencia,meses_ativos_vinculo,nome_produtor,nome_propriedade,projeto,codigo_agroindustria,id_farm,id_atendimento,data_visita,valor_pago_produtor,valor_pago_agroindustria,data_processamento,data_visita_str,mes_referencia_str,data_processamento_str,id_composto
0,LR09606,ANDRE VICTOR DE OLIVEIRA QUEIROZ,2026-05-01,1,ANTERO FERREIRA DA CUNHA,FAZENDA SANTO ANTONIO-QUEBRA ANZOL,ALVOAR ASSIST,1012313,None,401000108,2026-05-27,375.0,500.0,2026-08-18 16:02:24.467312,2026-05-27T00:00:00.000Z,2026-05-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,a15c4a16f76a7a22499609e480df6aaf8ad1c2a95ea429...
1,LR09652,ANDRE VICTOR DE OLIVEIRA QUEIROZ,2026-05-01,1,JOAO MARRA NETO,FAZENDA SANTO ANTONIO LUGAR ESTIVA,ALVOAR ASSIST,1012857,None,401000107,2026-05-27,650.0,500.0,2026-08-18 16:02:24.467312,2026-05-27T00:00:00.000Z,2026-05-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,0fc58e3c5a932d86ccafbc7cfe3489c15af33347138e8e...
2,LR09660,ANDRE VICTOR DE OLIVEIRA QUEIROZ,2026-05-01,1,JULIANO AURELIO PEREIRA SOBRINHO,FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE,ALVOAR ASSIST,1012353,None,401000102,2026-05-20,375.0,500.0,2026-08-18 16:02:24.467312,2026-05-20T00:00:00.000Z,2026-05-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,e5c6067f280ddead481dc62521d2f012f9b915b49d2a04...
4,LR09674,ANDRE VICTOR DE OLIVEIRA QUEIROZ,2026-05-01,1,MARTA CASSIANA DOS SANTOS,FAZENDA ANGICO,ALVOAR ASSIST,1012046,None,401000106,2026-05-26,375.0,500.0,2026-08-18 16:02:24.467312,2026-05-26T00:00:00.000Z,2026-05-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,38178e637e196b45459b4297b0156c1a024b5b6d7ebb54...
5,LR09674,ANDRE VICTOR DE OLIVEIRA QUEIROZ,2026-05-01,1,MARTA CASSIANA DOS SANTOS,FAZENDA ANGICO,ALVOAR ASSIST,1012046,None,401000109,2026-05-27,850.0,500.0,2026-08-18 16:02:24.467312,2026-05-27T00:00:00.000Z,2026-05-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,eca10ae9dfa20d9f94bd731834b811decc6b9130ec4414...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,LR05215,RAFAEL RODRIGUES CAMPOS,2026-08-01,1,JOSE MARIA BRAGA,FAZENDA LAGOA FORMOSA,REGENERA,101339420,1975,406000165,2026-08-14,0.0,0.0,2026-08-18 16:02:24.467312,2026-08-14T00:00:00.000Z,2026-08-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,15881cfd271fe18c06b0f6a27f3e5ab85cda2383ec99c6...
1243,LR05259,RODRIGO MAGALHAES VIANA,2026-08-01,1,JOSE LOURENCO DOS REIS,FAZENDA PONTE ALTA,REGENERA,100657866,364,413000150,2026-08-17,0.0,0.0,2026-08-18 16:02:24.467312,2026-08-17T00:00:00.000Z,2026-08-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,9e3ff2d5b4664706f269b7dfd678e31e77b305d4e8fb0a...
1313,LR05198,THUANY LANCA PEREIRA SILVA,2026-08-01,1,VINICIUS DE SOUZA BORGES CRUVINEL,AGROPECUARIA GGV,REGENERA,101344171,1855,171000425,2026-08-06,0.0,0.0,2026-08-18 16:02:24.467312,2026-08-06T00:00:00.000Z,2026-08-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,b38a62237bd97af1fcb0dbd7abc55f288b4b0a9d1448f3...
1457,LR05994,WILSON VAGNER VILAS BOAS FROTA,2026-08-01,1,JOSE ALVES BARBOSA NETO,FAZENDA JAO,REGENERA,100312837,763,392000228,2026-08-14,0.0,0.0,2026-08-18 16:02:24.467312,2026-08-14T00:00:00.000Z,2026-08-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,71e72bd1eef0a45712dffb2b565b3f8d830d4d57cf5424...
1458,LR05994,WILSON VAGNER VILAS BOAS FROTA,2026-08-01,1,JOSE ALVES BARBOSA NETO,FAZENDA JAO,REGENERA,100312837,763,282000483,2026-08-14,0.0,0.0,2026-08-18 16:02:24.467312,2026-08-14T00:00:00.000Z,2026-08-01T00:00:00.000Z,2026-08-18T16:02:24.467Z,3a87004a125911d866030ebfd5fe8dcad6ee2bde074c76...

# 8. Tabela Fato: Consistência (f_Consistencia)

In [14]:
# Diretório onde está o arquivo .env
DIRETORIO_ENV = DIR_BD_SQ
# os.chdir gerido no setup

# Carregar variáveis de ambiente

# Configurar conexão com o Supabase
supabase_url = os.getenv('SUPABASE_URL')
supabase_key = os.getenv('SUPABASE_SERVICE_KEY')
supabase = create_client(supabase_url, supabase_key)

# Definir datas de importação
data_inicial = DATA_INICIAL_ANALISE
data_inicial_elabore = DATA_INICIAL_ELABORE

# Trazer o dia atual
hoje = date.today()
# Separa primeiro e último dia
_, ultimo_dia = calendar.monthrange(hoje.year, hoje.month)
# Criar a data do último dia do mês atual
data_ultimo_dia = date(hoje.year, hoje.month, ultimo_dia)
# Define a data final do ETL
data_final =  data_ultimo_dia

# 2. Obter dados de produtores ativos
print("\n🔍 ETAPA 1: IMPORTANDO DADOS DE PRODUTORES ATIVOS")
projetos = ['REGENERA', 'ALVOAR ECO', 'ALVOAR ASSIST', 'SEMEAR', 'ATEG_CCPR', 'Alvoar', 'LPA']
colunas_produtores_ativos = '*'
try:
    resultado_vinculos = supabase.table(TAB_VINCULOS_STAGING) \
        .select(colunas_produtores_ativos) \
        .in_('projeto', projetos) \
        .execute()
    if resultado_vinculos.data:
        df_vinculos_mes = pd.DataFrame(resultado_vinculos.data)
        if 'consultor_grupo_atendimento' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
            df_vinculos_mes.rename(columns={'consultor_grupo_atendimento': 'nome_consultor'}, inplace=True)
        elif 'consultor' in df_vinculos_mes.columns and 'nome_consultor' not in df_vinculos_mes.columns:
            df_vinculos_mes.rename(columns={'consultor': 'nome_consultor'}, inplace=True)

        if 'data_referencia' not in df_vinculos_mes.columns:
            df_vinculos_mes['data_referencia'] = pd.to_datetime(df_vinculos_mes.get('data_processamento', df_vinculos_mes.get('data_associacao', pd.Timestamp.now())))
        else:
            df_vinculos_mes['data_referencia'] = pd.to_datetime(df_vinculos_mes['data_referencia'])

        grupo_cft = [
            'DAYANNE UCHOA VEIGA / DEBORA LIMA DE OLIVEIRA / MARIO BARBOSA ROSA FILHO / MATEUS CARNIELLI / TALITA FONTES / THAYNAN FERREIRA DE ARAUJO',
            'HUGO LOPES / MATEUS CARNIELLI / ROMARCIO PAULO DE OLIVEIRA / THAYNAN FERREIRA DE ARAUJO',
            'BRUNO ANTONIO FERRONI RODRIGUES / HUGO LOPES / MATEUS CARNIELLI / THAYNAN FERREIRA DE ARAUJO',
            'MATHEUS GOMIDES GONCALVES', 'TALITA FONTES'
        ]
        df_vinculos_mes = df_vinculos_mes[~df_vinculos_mes['nome_consultor'].isin(grupo_cft)]
        df_vinculos_mes['mes_referencia'] = df_vinculos_mes['data_referencia'].dt.to_period('M').dt.to_timestamp()
        print(f"✅ Importação de vínculos concluída: {len(df_vinculos_mes)} registros")
    else:
        print("⚠️ Nenhum registro de vínculo encontrado para o período especificado.")
        df_vinculos_mes = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de vínculos: {str(e)}")
    df_vinculos_mes = pd.DataFrame()

#  NOVA ETAPA 1.5: Importar dados de solicitação de vínculo (tab_vinculos_sq)
print("\n🔍 ETAPA 1.5: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq)")
colunas_vinculos_sq = '*'
try:
    # Importar todos os registros, sem filtro de data, para garantir que todas as datas de solicitação sejam capturadas
    df_vinculos_solicitacao_supabase = (
        supabase
        .table(TAB_VINCULOS_STAGING)
        .select(colunas_vinculos_sq)
        .in_('projeto', projetos)
        .execute()
    )
    
    if df_vinculos_solicitacao_supabase.data:
        df_vinculos_solicitacao = pd.DataFrame(df_vinculos_solicitacao_supabase.data)
        df_vinculos_solicitacao.rename(columns={'consultor_grupo_atendimento': 'nome_consultor'}, inplace=True)
        df_vinculos_solicitacao = df_vinculos_solicitacao.loc[~df_vinculos_solicitacao['nome_consultor'].isin(grupo_cft)]
        df_vinculos_solicitacao['data_associacao'] = pd.to_datetime(df_vinculos_solicitacao['data_associacao']).dt.to_period('M').dt.to_timestamp()

        # Agrupar para pegar a data de solicitação mais antiga por vínculo único
        df_min_solicitacao = df_vinculos_solicitacao.groupby(['codigo_lr', 'nome_consultor'])['data_associacao'].min().reset_index()
        df_min_solicitacao.rename(columns={'data_associacao': 'data_solicitacao_min'}, inplace=True)

        print(f"✅ Importação de datas de solicitação concluída: {len(df_min_solicitacao)} vínculos únicos.")
        print("\nDataFrame df_min_solicitacao (head):")
        print(df_min_solicitacao.head())
    else:
        print("⚠️ Nenhum registro de solicitação de vínculo encontrado.")
        df_min_solicitacao = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de solicitação de vínculo: {str(e)}")
    df_min_solicitacao = pd.DataFrame()
    

# 2. Importar tabela de consistencia mensal
print("\n🔍 ETAPA 2: IMPORTANDO DADOS DE CONSISTENCIA MENSAL")

try:
    resultado_consistencia = supabase.table('tab_consistencia_mensal') \
        .select('*') \
        .gte('mes_referencia', data_inicial) \
        .lte('mes_referencia', data_final) \
        .execute()
    if resultado_consistencia.data:
        df_consistencia_mes = pd.DataFrame(resultado_consistencia.data)
        df_consistencia_mes['mes_referencia'] = pd.to_datetime(df_consistencia_mes['mes_referencia']).dt.to_period('M').dt.to_timestamp()
        df_consistencia_mes['mes_elabore'] = pd.to_datetime(df_consistencia_mes['mes_elabore']).dt.to_period('M').dt.to_timestamp()
        print(f"✅ Importação de consistência mensal concluída: {len(df_consistencia_mes)} registros")
    else:
        print("⚠️ Nenhum registro de consistência mensal encontrado para o período especificado.")
        df_consistencia_mes = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de consistência mensal: {str(e)}")
    df_consistencia_mes = pd.DataFrame()

codigos_invalidos = ['Teste', 'Teste Gestor', 'Labor Rural']
if not df_consistencia_mes.empty:
    df_consistencia_mes = df_consistencia_mes[
        df_consistencia_mes['codigo_lr'].notna() &
        ~df_consistencia_mes['codigo_lr'].isin(codigos_invalidos) &
        ~df_consistencia_mes['codigo_lr'].str.lower().str.contains('teste', na=False) &
        ~df_consistencia_mes['codigo_lr'].str.lower().str.contains('labor', na=False)
    ]
    print(f"✅ Registros inválidos removidos. Restam: {len(df_consistencia_mes)}")

# 3. Importar tabela de consistencia mensal
print("\n🔍 ETAPA 3: IMPORTANDO DADOS DE CONSISTENCIA ANUAL")

try:
    resultado_consistencia = supabase.table('tab_consistencia_anual') \
        .select('*') \
        .gte('mes_referencia', data_inicial) \
        .lte('mes_referencia', data_final) \
        .execute()
    if resultado_consistencia.data:
        df_consistencia_anual = pd.DataFrame(resultado_consistencia.data)
        df_consistencia_anual['mes_referencia'] = pd.to_datetime(df_consistencia_anual['mes_referencia']).dt.to_period('M').dt.to_timestamp()
        df_consistencia_anual['mes_elabore'] = pd.to_datetime(df_consistencia_anual['mes_elabore']).dt.to_period('M').dt.to_timestamp()
        print(f"✅ Importação de consistência anual concluída: {len(df_consistencia_anual)} registros")
    else:
        print("⚠️ Nenhum registro de consistência anual encontrado para o período especificado.")
        df_consistencia_anual = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de consistência anual: {str(e)}")
    df_consistencia_anual = pd.DataFrame()

# Fazer o mesmo para df_consistencia_anual (ETAPA 3)
df_consistencia_anual = df_consistencia_anual[
    df_consistencia_anual['codigo_lr'].notna() &
    ~df_consistencia_anual['codigo_lr'].isin(codigos_invalidos) &
    ~df_consistencia_anual['codigo_lr'].str.lower().str.contains('teste', na=False) &
    ~df_consistencia_anual['codigo_lr'].str.lower().str.contains('labor', na=False)
]
print(f"✅ Registros inválidos removidos da anual. Restam: {len(df_consistencia_anual)}")

#  NOVA ETAPA: Aplicar regra de carência de 3 meses aos VÍNCULOS
print("\n⚙️ ETAPA 4: APLICANDO REGRA DE CARÊNCIA DE 3 MESES AOS VÍNCULOS")

df_vinculos_com_carencia = pd.DataFrame() # Inicializa para garantir que existe

if not df_vinculos_mes.empty:
    # 1. Agrupar por 'codigo_lr' e 'nome_consultor' para encontrar a data mínima de vínculo
    # Esta é a data de referência mais antiga do produtor ativo
    df_min_vinculo_ativo = df_vinculos_mes.groupby(['codigo_lr', 'nome_consultor'])['data_referencia'].min().reset_index()
    df_min_vinculo_ativo.rename(columns={'data_referencia': 'data_referencia_min_ativo'}, inplace=True)

    # 2. Mesclar com df_min_solicitacao para obter a data de solicitação mínima
    if not df_min_solicitacao.empty:
        df_min_vinculo_completo = df_min_vinculo_ativo.merge(
            df_min_solicitacao,
            on=['codigo_lr', 'nome_consultor'],
            how='left'
        )
        # Escolher a data de início do vínculo: a menor entre data_referencia_min_ativo e data_solicitacao_min
        # Se data_solicitacao_min for NaN (não encontrado), usar data_referencia_min_ativo
        df_min_vinculo_completo['data_inicio_vinculo'] = df_min_vinculo_completo.apply(
            lambda row: min(row['data_referencia_min_ativo'], row['data_solicitacao_min'])
                        if pd.notna(row['data_solicitacao_min'])
                        else row['data_referencia_min_ativo'],
            axis=1
        )
    else:
        # Se não houver dados de solicitação, usar apenas a data mínima de atividade
        df_min_vinculo_completo = df_min_vinculo_ativo.copy()
        df_min_vinculo_completo['data_inicio_vinculo'] = df_min_vinculo_completo['data_referencia_min_ativo']

    # 3. Calcular a data de carência (data_inicio_vinculo + 3 meses)
    df_min_vinculo_completo['data_carencia_fim'] = df_min_vinculo_completo['data_inicio_vinculo'] + pd.DateOffset(months=2)

    print(f"✅ Datas de carência calculadas para {len(df_min_vinculo_completo)} vínculos únicos usando data de solicitação.")
    print("\nDataFrame df_min_vinculo_completo (head):")
    print(df_min_vinculo_completo.head())

    print("\n🤝 ETAPA DE CARÊNCIA: MESCLANDO E FILTRANDO VÍNCULOS")

    df_vinculos_com_carencia = df_vinculos_mes.merge(
        df_min_vinculo_completo[['codigo_lr', 'nome_consultor', 'data_carencia_fim', 'data_inicio_vinculo']],
        on=['codigo_lr', 'nome_consultor'],
        how='left'
    )
    print(f"✅ Vínculos mesclados com datas de carência: {len(df_vinculos_com_carencia)} registros.")
    print("\nDataFrame df_vinculos_com_carencia (head):")
    print(df_vinculos_com_carencia.head())
else:
    print("⚠️ DataFrame de produtores ativos está vazio, não é possível aplicar a lógica de carência.")
    df_vinculos_com_carencia = pd.DataFrame() # Garante que o DF existe mesmo vazio

#  NOVA ETAPA 5: Integrar Dados de Consistência Mensal e Anual
    print("\n📊 ETAPA 5: INTEGRANDO DADOS DE CONSISTÊNCIA MENSAL E ANUAL")

    if df_vinculos_com_carencia.empty:
        print("⚠️ DataFrame de vínculos com carência está vazio, não é possível integrar dados de consistência.")
        df_vinculos_com_carencia = pd.DataFrame()

# Merge com consistência mensal
# Selecionar apenas as colunas necessárias de df_consistencia_mes para evitar conflitos
cols_consist = [c for c in ['codigo_lr', 'mes_referencia', 'mes_elabore', 'consistencia_mensal', 'status_code', 'detalhamento_inconsistencia'] if c in df_consistencia_mes.columns]
df_consistencia_mes_merge = df_consistencia_mes[cols_consist].copy()

df_final = df_vinculos_com_carencia.merge(
    df_consistencia_mes_merge,
    on=['codigo_lr', 'mes_referencia'],
    how='left'
)
# Preencher False onde não houve match (ou seja, não tem consistência mensal)
print(f"✅ Consistência mensal integrada. Total de registros: {len(df_final)}")

# Merge com consistência anual
# Selecionar apenas as colunas necessárias de df_consistencia_anual
df_consistencia_anual_merge = df_consistencia_anual[['codigo_lr', 'mes_referencia','consistencia_anual']].copy()

df_final = df_final.merge(
    df_consistencia_anual_merge,
    on=['codigo_lr', 'mes_referencia'],
    how='left'
)

# Retirar produtor teste
df_final = df_final.loc[df_final['codigo_lr']!='PRODUTOR_TESTE']
# Preencher False onde não houve match (ou seja, não tem consistência anual)
print(f"✅ Consistência anual integrada. Total de registros: {len(df_final)}")

#  ETAPA 6: Retirar lista de produtores exceção
print("⬆️ ETAPA 6: IMPORTAR TABELA DE PRODUTORES EXCEÇÃO")
try:
    caminho_excecao = buscar_arquivo_mais_recente(DIR_BD_SQ, "*EXCECAO*.xlsx")
    if caminho_excecao and Path(caminho_excecao).exists():
        df_excecao = pd.read_excel(caminho_excecao)
        df_excecao.columns = ['codigo_lr', 'nome_produtor', 'status']
        df_excecao = df_excecao.loc[df_excecao['status']=='ATIVO']
        df_excecao['excecao'] = 1
        df_final = df_final.merge(df_excecao[['codigo_lr','excecao']], on='codigo_lr', how='left')
    else:
        df_final['excecao'] = 0
except Exception as e:
    print(f"⚠️ Tabela de exceção não encontrada ou não processada: {e}")
    df_final['excecao'] = 0

# Preencher NaN com 0 e converter para tipo inteiro.
if 'excecao' in df_final.columns:
    df_final['excecao'] = df_final['excecao'].fillna(0).astype(int)
    print("✅ Coluna 'excecao' tratada (NaN preenchido com 0 e convertida para int).")

#  ETAPA 7: Inserindo tabela de PRODUTORES 12 MESES
print("\n⬆️ ETAPA 7: IMPORTANTO E MESCLANDO PRODUTORES COM 12 MESES")

# Importar do supabase
try:
    produtores_12meses = supabase.table('tab_lancamentos_produtores') \
        .select('idFazenda,mesReferencia,meses_sequenciais') \
        .gte('mesReferencia', data_inicial_elabore) \
        .lte('mesReferencia', data_final) \
        .execute()
    if produtores_12meses.data:
        df_produtores_12meses = pd.DataFrame(produtores_12meses.data)
        df_produtores_12meses['mesReferencia'] = pd.to_datetime(df_produtores_12meses['mesReferencia']).dt.to_period('M').dt.to_timestamp()
        print(df_produtores_12meses.dtypes)
    else:
        print("⚠️ Nenhum registro de produtores com dados encontrado para o período especificado.")
        df_produtores_12meses = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de produtores com dados: {str(e)}")
    df_produtores_12meses = pd.DataFrame()

# Importar tab_fazenda para identificar codigo_lr por idFazenda
try:
    tab_fazenda = supabase.table('tab_fazenda') \
        .select('id,codAgroindustria,idProdutor,idConsultor') \
        .eq('aprovacao','Aprovado') \
        .eq('Excluido', 0) \
        .execute()
    if tab_fazenda.data:
        d_fazenda = pd.DataFrame(tab_fazenda.data)
        d_fazenda = d_fazenda.loc[d_fazenda['codAgroindustria'].notna()]
        d_fazenda = d_fazenda[['id','codAgroindustria','idProdutor','idConsultor']]
        d_fazenda.columns = ['idFazenda', 'codigo_lr','idProdutor','idConsultor'] # Renomear para padrão utilizado nas outras tabelas
        d_fazenda['idFazenda'] = pd.to_numeric(d_fazenda['idFazenda'])
        # Dividir a string por ';' e expandir em novas linhas
        d_fazenda = d_fazenda.assign(
            idConsultor=d_fazenda['idConsultor'].str.split(';')
        ).explode('idConsultor')
        
        # Remover linhas onde idConsultor ficou vazio após a divisão (ex: se tinha '2;;30')
        # ou se a coluna original era NaN e virou ''
        d_fazenda = d_fazenda[d_fazenda['idConsultor'] != '']
        
        # Opcional: Converter idConsultor para tipo numérico (int) se for o caso
        d_fazenda['idConsultor'] = pd.to_numeric(d_fazenda['idConsultor'])
        print(d_fazenda.dtypes)
    else:
        print("⚠️ Nenhum registro de d_fazenda encontrado para o período especificado.")
        d_fazenda = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de d_fazenda: {str(e)}")
    d_fazenda = pd.DataFrame()       

try:
    df_produtores_12meses = (
        df_produtores_12meses
        .merge(
            d_fazenda,
            on = 'idFazenda',
            how='left'
        )
    )
    # df_produtores_12meses = df_produtores_12meses.loc[df_produtores_12meses['codigo_lr'].notna()] # Retirar os que não tem código LR
    df_produtores_12meses.drop('idFazenda', axis='columns', inplace=True) # Retirar idFazenda para não poluir a tabela
    df_produtores_12meses.rename(columns={'mesReferencia':'mes_elabore'},inplace=True)
except Exception as e:
    print(f"❌ Erro ao mesclar produtores com dados: {str(e)}")
    df_produtores_12meses = pd.DataFrame()   

# ✅ Remover ANTES do merge com df_final
df_produtores_12meses = df_produtores_12meses.drop_duplicates(
    subset=['codigo_lr', 'mes_elabore'],
    keep='first'
)
print(f"✅ Duplicatas removidas de df_produtores_12meses. Restam: {len(df_produtores_12meses)}")

# Aí sim realizar o merge
df_final = df_final.merge(
    df_produtores_12meses[['codigo_lr', 'mes_elabore', 'meses_sequenciais', 'idConsultor']],
    on=['codigo_lr', 'mes_elabore'],
    how='left'
)
display(df_final.head())

#  ETAPA 8: Inserindo tabela de PRODUTORES 12 MESES
print("\n⬆️ ETAPA 8: INSERINDO A PROFISSÃO DO CONSULTOR")


def padronizar_nome_consultor(df, coluna_nome='nome_consultor'):
    """
    Aplica padronização (maiúsculas, sem acentos, sem espaços extras)
    na coluna nome_consultor de um DataFrame.
    """
    if coluna_nome in df.columns:
        print(f"🔄 Padronizando coluna '{coluna_nome}'...")
        df[coluna_nome] = df[coluna_nome].astype(str).apply(
            lambda x: unidecode(x).upper().strip() if pd.notna(x) else x
        )
        print(f"✅ Coluna '{coluna_nome}' padronizada.")
    else:
        print(f"⚠️ Coluna '{coluna_nome}' não encontrada no DataFrame.")
    return df

# Importar tab_fazenda para identificar codigo_lr por idFazenda
try:
    tab_consultor = supabase.table('tab_consultor') \
        .select('formacaoConsultor,nomeConsultor') \
        .eq('Excluido', 0) \
        .execute()
    if tab_consultor.data:
        d_consultor = pd.DataFrame(tab_consultor.data)
        # PRIMEIRO renomear
        d_consultor.columns = ['profissao_consultor', 'nome_consultor']
        # DEPOIS criar o merge
        d_consultor_merge = d_consultor[['nome_consultor', 'profissao_consultor']].copy()
        # Aplicar a mesma lógica de LAC CONSULTORIA e padronização
        consultores_lac = ['CELIO ROBERTO OLIVEIRA', 'SUELY DE JESUS OLIVEIRA']
        d_consultor['nome_consultor'] = d_consultor['nome_consultor'].apply(
            lambda nome: 'LAC CONSULTORIA' if nome in consultores_lac else nome
        )
        d_consultor = padronizar_nome_consultor(d_consultor, 'nome_consultor')
        # Remover duplicatas se houver, para garantir um merge 1:1 ou N:1
        d_consultor = d_consultor.drop_duplicates(subset=['nome_consultor'], keep='first')
        print(d_consultor_merge.dtypes)
        print(d_consultor_merge.head())

    else:
        print("⚠️ Nenhum registro de consultor encontrado para o período especificado.")
        d_consultor = pd.DataFrame()
except Exception as e:
    print(f"❌ Erro ao importar dados de consultores: {str(e)}")
    d_consultor = pd.DataFrame()
    
df_final = padronizar_nome_consultor(df_final, 'nome_consultor')
df_final = df_final.drop_duplicates(
    subset=['codigo_lr', 'mes_elabore'],
    keep='first'
)
# Adicionar profissao_consultor no df_final.
try:
    # Remover a coluna idConsultor de df_final antes do merge, pois ela é a problemática
    if 'idConsultor' in df_final.columns:
        df_final.drop(columns=['idConsultor'], inplace=True)
        print("✅ Coluna 'idConsultor' removida de df_final antes do merge de profissão.")

    df_final = (
        df_final
        .merge(
            d_consultor[['nome_consultor', 'profissao_consultor']], # Selecionar apenas as colunas necessárias
            on=['nome_consultor'],
            how='left'
        )
    )
    print(f"✅ Profissão do consultor mesclada com sucesso. Total de registros: {len(df_final)}")
    display(df_final.head())
    
except Exception as e:
    print(f"❌ Erro ao mesclar dados de consultores: {str(e)}")

#  NOVA ETAPA 9: Preparar df_final para UPSERT no Supabase
print("\n⬆️ ETAPA 9: PREPARANDO E REALIZANDO UPSERT NO SUPABASE")

# Adicionar a coluna data_processamento
df_final['data_processamento'] = datetime.now(timezone.utc)

# Data limite
data_limite = datetime(hoje.year, hoje.month, 1,0,0,0)

# Limitar o número de linhas
df_final = df_final.loc[df_final['mes_referencia']<=data_limite]

#  CORREÇÃO AQUI: Converter todas as colunas de data/hora para string ISO 8601
# Identificar colunas que são de data/hora
date_cols = ['mes_referencia', 'data_carencia_fim', 'mes_elabore', 'data_processamento', 'data_inicio_vinculo', 'data_referencia']

for col in date_cols:
    if col in df_final.columns:
        df_final[col] = pd.to_datetime(df_final[col], errors='coerce')

        if df_final[col].dt.tz is not None:
            df_final[col] = df_final[col].dt.tz_convert('UTC').dt.strftime('%Y-%m-%dT%H:%M:%S.%fZ')
        else:
            if col in ['mes_referencia', 'data_carencia_fim', 'mes_elabore', 'data_inicio_vinculo', 'data_referencia']:
                df_final[col] = df_final[col].dt.strftime('%Y-%m-%d')
            else:
                df_final[col] = df_final[col].dt.strftime('%Y-%m-%dT%H:%M:%S')

        df_final[col] = df_final[col].replace({pd.NaT: None}) # Já trata NaT para None

# ✅ NOVO BLOCO: TRATAMENTO FINAL DE np.nan PARA None E CONVERSÃO DE TIPOS
print("\n🔄 Tratando np.nan para None e ajustando tipos de colunas numéricas...")

# Colunas que devem ser inteiros, mas podem ter nulos
int_nullable_cols = ['excecao', 'meses_sequenciais']
for col in int_nullable_cols:
    if col in df_final.columns:
        # Primeiro, garantir que np.nan seja tratado para None
        df_final.loc[df_final[col].isna(), col] = None
        # Em seguida, converter para o tipo inteiro que aceita nulos (Int64)
        # Isso também converterá None para o valor nulo do Int64
        try:
            df_final[col] = df_final[col].astype('Int64')
            print(f"  ✅ Coluna '{col}': np.nan transformados para None e tipo ajustado para Int64.")
        except Exception as e:
            print(f"  ❌ Erro ao converter coluna '{col}' para Int64: {e}. Mantendo tipo original.")

# Para outras colunas que podem ter np.nan e não são datas (já tratadas) ou Int64
for col in df_final.columns:
    # Se a coluna não é uma das datas ou Int64 já tratadas, e não é string
    if col not in date_cols and col not in int_nullable_cols and not pd.api.types.is_object_dtype(df_final[col]):
        if df_final[col].isnull().any():
            df_final.loc[df_final[col].isnull(), col] = None
            print(f"  ✅ Coluna '{col}': np.nan transformados para None.")
    # Para colunas de objeto (string) que podem ter a string 'NaN' ou np.nan
    elif pd.api.types.is_object_dtype(df_final[col]):
        if (df_final[col] == 'NaN').any():
            df_final.loc[df_final[col] == 'NaN', col] = None
            print(f"  ✅ Coluna '{col}': string 'NaN' transformadas para None.")
        if df_final[col].isnull().any():
            df_final.loc[df_final[col].isnull(), col] = None
            print(f"  ✅ Coluna '{col}': np.nan em objeto transformados para None.")


# Separar apenas as colunas necessárias
tab_supabase_cols = [
    'codigo_lr', 'nome_consultor', 'profissao_consultor', 'projeto',
    'mes_referencia', 'data_carencia_fim', 'mes_elabore',
    'consistencia_mensal', 'consistencia_anual', 'status_code', 'excecao', 'meses_sequenciais',
    'detalhamento_inconsistencia',
    'data_processamento'
]
# Garantir que só seleciona colunas que existem no df_final
tab_supabase_cols = [c for c in tab_supabase_cols if c in df_final.columns]
# Slice dataframe
df_final = df_final[tab_supabase_cols]

# ❌ REMOVER ESTA LINHA: df_final.loc[df_final['meses_sequenciais']=='NaN','meses_sequenciais'] = None
# O novo bloco acima já trata isso de forma mais robusta.

# Exibir o head novamente para verificar os tipos após a conversão
print("\nDataFrame df_final (head após conversão de datas para string e tratamento de NaN):")
print(df_final.head())
print("\nTipos de dados de df_final após conversão de datas e tratamento de NaN:")
print(df_final.dtypes)


# Exemplo de como seria o upsert no seu script Python
SUPABASE_TABLE_CONSISTENCIA = TAB_CONSISTENCIA_FATO

records_to_upsert = df_final.to_dict(orient='records')

chunk_size = 1000
for i in range(0, len(records_to_upsert), chunk_size):
    chunk = records_to_upsert[i:i + chunk_size]
    try:
        response = supabase.table(SUPABASE_TABLE_CONSISTENCIA).upsert(
            chunk,
            on_conflict="codigo_lr,nome_consultor,mes_referencia" # Chave composta para o UPSERT
        ).execute()
        if response.data:
            print(f"     - Upsert de {len(response.data)} registros em chunk {i//chunk_size + 1}.")
        else:
            print(f"     - Nenhum registro upserted para chunk {i//chunk_size + 1} ou erro na resposta.")
    except Exception as e:
        print(f"❌ Erro ao realizar upsert no Supabase (chunk {i//chunk_size + 1}): {str(e)}")


print("\nDataFrame df_final (head após merges de consistência):")
print(df_final.head())

🔍 ETAPA 1: IMPORTANDO DADOS DE PRODUTORES ATIVOS

✅ Importação de vínculos concluída: 1410 registros

🔍 ETAPA 1.5: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq)
✅ Importação de datas de solicitação concluída: 1307 vínculos únicos.

DataFrame df_min_solicitacao (head):
  codigo_lr            nome_consultor data_solicitacao_min
0   LR01964    LORENA VIRGINIA ARAUJO           2025-05-01
1   LR02474  MARIO BARBOSA ROSA FILHO           2024-04-01
2   LR02475  MARIO BARBOSA ROSA FILHO           2024-04-01
3   LR02480  MARIO BARBOSA ROSA FILHO           1970-01-01
4   LR02481  MARIO BARBOSA ROSA FILHO           2024-04-01

🔍 ETAPA 2: IMPORTANDO DADOS DE CONSISTENCIA MENSAL

C:\Users\Guilherme\AppData\Local\Temp\ipykernel_14736\980147798.py:107: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_consistencia_mes['mes_referencia'] = pd.to_datetime(df_consistencia_mes['mes_referencia']).dt.to_period('M').dt.to_timestamp()
C:\Users\Guilherme\AppData\Local\Temp\ipykernel_14736\980147798.py:108: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_consistencia_mes['mes_elabore'] = pd.to_datetime(df_consistencia_mes['mes_elabore']).dt.to_period('M').dt.to_timestamp()

✅ Importação de consistência mensal concluída: 11801 registros
✅ Registros inválidos removidos. Restam: 11075

🔍 ETAPA 3: IMPORTANDO DADOS DE CONSISTENCIA ANUAL

C:\Users\Guilherme\AppData\Local\Temp\ipykernel_14736\980147798.py:138: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_consistencia_anual['mes_referencia'] = pd.to_datetime(df_consistencia_anual['mes_referencia']).dt.to_period('M').dt.to_timestamp()
C:\Users\Guilherme\AppData\Local\Temp\ipykernel_14736\980147798.py:139: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_consistencia_anual['mes_elabore'] = pd.to_datetime(df_consistencia_anual['mes_elabore']).dt.to_period('M').dt.to_timestamp()
C:\Users\Guilherme\AppData\Local\Temp\ipykernel_14736\980147798.py:277: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df_produtores_12meses['mesReferencia'] = pd.to_datetime(df_produtores_12meses['mesReferencia']).dt.to_period('M').dt.to_timestamp()

✅ Importação de consistência anual concluída: 9451 registros
✅ Registros inválidos removidos da anual. Restam: 8543

⚙️ ETAPA 4: APLICANDO REGRA DE CARÊNCIA DE 3 MESES AOS VÍNCULOS
✅ Datas de carência calculadas para 1307 vínculos únicos usando data de solicitação.

DataFrame df_min_vinculo_completo (head):
  codigo_lr            nome_consultor data_referencia_min_ativo  \
0   LR01964    LORENA VIRGINIA ARAUJO       2026-05-06 11:29:10
1   LR02474  MARIO BARBOSA ROSA FILHO       2026-07-02 08:36:00
2   LR02475  MARIO BARBOSA ROSA FILHO       2026-05-06 11:29:10
3   LR02480  MARIO BARBOSA ROSA FILHO       2026-05-06 17:30:41
4   LR02481  MARIO BARBOSA ROSA FILHO       2026-07-02 08:36:00

  data_solicitacao_min data_inicio_vinculo data_carencia_fim
0           2025-05-01          2025-05-01        2025-07-01
1           2024-04-01          2024-04-01        2024-06-01
2           2024-04-01          2024-04-01        2024-06-01
3           1970-01-01          1970-01-01        1970-03-01
4           2024-04-01          2024-04-01        2024-06-01

🤝 ETAPA DE CARÊNCIA: MESCLANDO E FILTRANDO VÍNCULOS
✅ Vínculos mesclados com datas de carência: 1410 registros.

DataFrame df_vinculos_com_carencia (head):
  codigo_lr codigo_agroindustria                     nome_produtor  \
0   LR09606              1012313          ANTERO FERREIRA DA CUNHA
1   LR09652              1012857                   JOAO MARRA NETO
2   LR09660              1012353  JULIANO AURELIO PEREIRA SOBRINHO
3   LR09673              1011060    MARISA DINIZ GONCALVES MACHADO
4   LR09674              1012046         MARTA CASSIANA DOS SANTOS

                                 nome_propriedade unidade_atendimento  \
0              FAZENDA SANTO ANTONIO-QUEBRA ANZOL         LABOR RURAL
1              FAZENDA SANTO ANTONIO LUGAR ESTIVA         LABOR RURAL
2  FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE         LABOR RURAL
3               FAZENDA CAMPO LIMPO E PIRAPETINGA         LABOR RURAL
4                                  FAZENDA ANGICO         LABOR RURAL

  tipo_ponto_atendimento cidade_produtor estado_produtor  vinculo_ativo  \
0                  LEITE      Patrocínio              MG           True
1                  LEITE      Patrocínio              MG           True
2                  LEITE      Patrocínio              MG           True
3                  LEITE      Patrocínio              MG           True
4                  LEITE      Patrocínio              MG           True

       data_associacao  ...                    nome_consultor        projeto  \
0  2025-08-27T10:38:10  ...  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST
1  2025-08-27T10:38:10  ...  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST
2  2025-08-27T10:38:10  ...  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST
3  2025-08-27T10:38:10  ...  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST
4  2025-08-27T10:38:10  ...  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST

    data_processamento     id                       id_composto  \
0  2026-05-06T11:29:10  56336  f51d943f378816332ccac73b8e3c1fe7
1  2026-05-06T11:29:10  56337  9534c5eeab51865b4f0f2afa6e5a1ed9
2  2026-05-06T11:29:10  56338  57fb853940bd804eb0b7c6fabef8c0bb
3  2026-05-06T11:29:10  56339  2a65cacb3e067b316672c6912e9f2140
4  2026-05-06T11:29:10  56340  6f50e601ca23e484342a244e25618b13

  codigo_fazenda     data_referencia mes_referencia data_carencia_fim  \
0           None 2026-05-06 11:29:10     2026-05-01        2025-10-01
1           None 2026-05-06 11:29:10     2026-05-01        2025-10-01
2           None 2026-05-06 11:29:10     2026-05-01        2025-10-01
3           None 2026-05-06 11:29:10     2026-05-01        2025-10-01
4           None 2026-05-06 11:29:10     2026-05-01        2025-10-01

  data_inicio_vinculo
0          2025-08-01
1          2025-08-01
2          2025-08-01
3          2025-08-01
4          2025-08-01

[5 rows x 21 columns]
✅ Consistência mensal integrada. Total de registros: 1410
✅ Consistência anual integrada. Total de registros: 1645
⬆️ ETAPA 6: IMPORTAR TABELA DE PRODUTORES EXCEÇÃO
⚠️ Tabela de exceção não encontrada ou não processada: nothing to repeat at position 0
✅ Coluna 'excecao' tratada (NaN preenchido com 0 e convertida para int).

⬆️ ETAPA 7: IMPORTANTO E MESCLANDO PRODUTORES COM 12 MESES
idFazenda                     int64
mesReferencia        datetime64[ns]
meses_sequenciais             int64
dtype: object

idFazenda        int64
codigo_lr       object
idProdutor       int64
idConsultor    float64
dtype: object
✅ Duplicatas removidas de df_produtores_12meses. Restam: 2756

,codigo_lr,codigo_agroindustria,nome_produtor,nome_propriedade,unidade_atendimento,tipo_ponto_atendimento,cidade_produtor,estado_produtor,vinculo_ativo,data_associacao,...,data_carencia_fim,data_inicio_vinculo,mes_elabore,consistencia_mensal,status_code,detalhamento_inconsistencia,consistencia_anual,excecao,meses_sequenciais,idConsultor
0,LR09606,1012313,ANTERO FERREIRA DA CUNHA,FAZENDA SANTO ANTONIO-QUEBRA ANZOL,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,9.0,112.0
1,LR09652,1012857,JOAO MARRA NETO,FAZENDA SANTO ANTONIO LUGAR ESTIVA,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Inconsistente,active_approved,None,NaN,0,9.0,112.0
2,LR09660,1012353,JULIANO AURELIO PEREIRA SOBRINHO,FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,9.0,112.0
3,LR09673,1011060,MARISA DINIZ GONCALVES MACHADO,FAZENDA CAMPO LIMPO E PIRAPETINGA,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,5.0,112.0
4,LR09674,1012046,MARTA CASSIANA DOS SANTOS,FAZENDA ANGICO,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,NaT,NaN,NaN,NaN,NaN,0,NaN,NaN

⬆️ ETAPA 8: INSERINDO A PROFISSÃO DO CONSULTOR
🔄 Padronizando coluna 'nome_consultor'...
✅ Coluna 'nome_consultor' padronizada.
nome_consultor         object
profissao_consultor    object
dtype: object
                     nome_consultor        profissao_consultor
0  Caio Cezar de Oliveira Brasilino   Médico(a) Veterinário(a)
1         João Victor Cândido Silva  Engenheiro(a) Agrônomo(a)
2               Dayanne Uchoa Veiga  Engenheiro(a) Agrônomo(a)
3            Lorena Virgínia Araújo  Engenheiro(a) Agrônomo(a)
4           Débora Lima de Oliveira  Engenheiro(a) Agrônomo(a)
🔄 Padronizando coluna 'nome_consultor'...
✅ Coluna 'nome_consultor' padronizada.
✅ Coluna 'idConsultor' removida de df_final antes do merge de profissão.
✅ Profissão do consultor mesclada com sucesso. Total de registros: 1058

,codigo_lr,codigo_agroindustria,nome_produtor,nome_propriedade,unidade_atendimento,tipo_ponto_atendimento,cidade_produtor,estado_produtor,vinculo_ativo,data_associacao,...,data_carencia_fim,data_inicio_vinculo,mes_elabore,consistencia_mensal,status_code,detalhamento_inconsistencia,consistencia_anual,excecao,meses_sequenciais,profissao_consultor
0,LR09606,1012313,ANTERO FERREIRA DA CUNHA,FAZENDA SANTO ANTONIO-QUEBRA ANZOL,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,9.0,Médico(a) Veterinário(a)
1,LR09652,1012857,JOAO MARRA NETO,FAZENDA SANTO ANTONIO LUGAR ESTIVA,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Inconsistente,active_approved,None,NaN,0,9.0,Médico(a) Veterinário(a)
2,LR09660,1012353,JULIANO AURELIO PEREIRA SOBRINHO,FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,9.0,Médico(a) Veterinário(a)
3,LR09673,1011060,MARISA DINIZ GONCALVES MACHADO,FAZENDA CAMPO LIMPO E PIRAPETINGA,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,2026-04-01,Consistente,active_approved,None,NaN,0,5.0,Médico(a) Veterinário(a)
4,LR09674,1012046,MARTA CASSIANA DOS SANTOS,FAZENDA ANGICO,LABOR RURAL,LEITE,Patrocínio,MG,True,2025-08-27T10:38:10,...,2025-10-01,2025-08-01,NaT,NaN,NaN,NaN,NaN,0,NaN,Médico(a) Veterinário(a)

⬆️ ETAPA 9: PREPARANDO E REALIZANDO UPSERT NO SUPABASE

🔄 Tratando np.nan para None e ajustando tipos de colunas numéricas...
  ✅ Coluna 'excecao': np.nan transformados para None e tipo ajustado para Int64.
  ✅ Coluna 'meses_sequenciais': np.nan transformados para None e tipo ajustado para Int64.
  ✅ Coluna 'codigo_agroindustria': np.nan em objeto transformados para None.
  ✅ Coluna 'nome_produtor': np.nan em objeto transformados para None.
  ✅ Coluna 'nome_propriedade': np.nan em objeto transformados para None.
  ✅ Coluna 'tipo_ponto_atendimento': np.nan em objeto transformados para None.
  ✅ Coluna 'cidade_produtor': np.nan em objeto transformados para None.
  ✅ Coluna 'estado_produtor': np.nan em objeto transformados para None.
  ✅ Coluna 'data_associacao': np.nan em objeto transformados para None.
  ✅ Coluna 'codigo_fazenda': np.nan em objeto transformados para None.
  ✅ Coluna 'mes_elabore': np.nan em objeto transformados para None.
  ✅ Coluna 'consistencia_mensal': np.nan em objeto transformados para None.
  ✅ Coluna 'status_code': np.nan em objeto transformados para None.
  ✅ Coluna 'detalhamento_inconsistencia': np.nan em objeto transformados para None.
  ✅ Coluna 'consistencia_anual': np.nan em objeto transformados para None.
  ✅ Coluna 'profissao_consultor': np.nan em objeto transformados para None.

DataFrame df_final (head após conversão de datas para string e tratamento de NaN):
  codigo_lr                    nome_consultor       profissao_consultor  \
0   LR09606  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
1   LR09652  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
2   LR09660  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
3   LR09673  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
4   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)

         projeto mes_referencia data_carencia_fim mes_elabore  \
0  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
1  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
2  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
3  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
4  ALVOAR ASSIST     2026-05-01        2025-10-01        None

  consistencia_mensal consistencia_anual      status_code  excecao  \
0         Consistente               None  active_approved        0
1       Inconsistente               None  active_approved        0
2         Consistente               None  active_approved        0
3         Consistente               None  active_approved        0
4                None               None             None        0

   meses_sequenciais detalhamento_inconsistencia           data_processamento
0                  9                        None  2026-08-18T19:02:32.267811Z
1                  9                        None  2026-08-18T19:02:32.267811Z
2                  9                        None  2026-08-18T19:02:32.267811Z
3                  5                        None  2026-08-18T19:02:32.267811Z
4               <NA>                        None  2026-08-18T19:02:32.267811Z

Tipos de dados de df_final após conversão de datas e tratamento de NaN:
codigo_lr                      object
nome_consultor                 object
profissao_consultor            object
projeto                        object
mes_referencia                 object
data_carencia_fim              object
mes_elabore                    object
consistencia_mensal            object
consistencia_anual             object
status_code                    object
excecao                         Int64
meses_sequenciais               Int64
detalhamento_inconsistencia    object
data_processamento             object
dtype: object

     - Upsert de 1000 registros em chunk 1.
     - Upsert de 58 registros em chunk 2.

DataFrame df_final (head após merges de consistência):
  codigo_lr                    nome_consultor       profissao_consultor  \
0   LR09606  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
1   LR09652  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
2   LR09660  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
3   LR09673  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)
4   LR09674  ANDRE VICTOR DE OLIVEIRA QUEIROZ  Médico(a) Veterinário(a)

         projeto mes_referencia data_carencia_fim mes_elabore  \
0  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
1  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
2  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
3  ALVOAR ASSIST     2026-05-01        2025-10-01  2026-04-01
4  ALVOAR ASSIST     2026-05-01        2025-10-01        None

  consistencia_mensal consistencia_anual      status_code  excecao  \
0         Consistente               None  active_approved        0
1       Inconsistente               None  active_approved        0
2         Consistente               None  active_approved        0
3         Consistente               None  active_approved        0
4                None               None             None        0

   meses_sequenciais detalhamento_inconsistencia           data_processamento
0                  9                        None  2026-08-18T19:02:32.267811Z
1                  9                        None  2026-08-18T19:02:32.267811Z
2                  9                        None  2026-08-18T19:02:32.267811Z
3                  5                        None  2026-08-18T19:02:32.267811Z
4               <NA>                        None  2026-08-18T19:02:32.267811Z

# 9. Tabela Fato: Movimentação de Produtores (f_mov_produtores)

In [15]:
#  NOVA ETAPA 1.5: Importar dados de solicitação de vínculo (tab_vinculos_sq_backup)
print("\n🔍 ETAPA 1: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq_backup)")
colunas_vinculos_sq = '*'

# Projetos alvo
projetos = ['REGENERA', 'ALVOAR ECO', 'ALVOAR ASSIST', 'SEMEAR', 'ATEG_CCPR', 'Alvoar', 'LPA']

# Consultores CFT (Sair)
grupo_cft = [
    'DAYANNE UCHOA VEIGA / DEBORA LIMA DE OLIVEIRA / MARIO BARBOSA ROSA FILHO / MATEUS CARNIELLI / TALITA FONTES / THAYNAN FERREIRA DE ARAUJO',
    'HUGO LOPES / MATEUS CARNIELLI / ROMARCIO PAULO DE OLIVEIRA / THAYNAN FERREIRA DE ARAUJO',
    'BRUNO ANTONIO FERRONI RODRIGUES / HUGO LOPES / MATEUS CARNIELLI / THAYNAN FERREIRA DE ARAUJO',
    'MATHEUS GOMIDES GONCALVES', 'TALITA FONTES'
]

try:
    # Importar todos os registros, sem filtro de data, para garantir que todas as datas de solicitação sejam capturadas
    df_vinculos_solicitacao_supabase = (
        supabase
        .table(TAB_VINCULOS_STAGING)
        .select(colunas_vinculos_sq)
        .in_('projeto', projetos)
        .execute()
    )
    
    if df_vinculos_solicitacao_supabase.data:
        df_vinculos = pd.DataFrame(df_vinculos_solicitacao_supabase.data)
        df_vinculos.rename(columns={'consultor_grupo_atendimento': 'nome_consultor', 'data_associacao':'data_movimentacao'}, inplace=True)
        df_vinculos = df_vinculos.loc[~df_vinculos['nome_consultor'].isin(grupo_cft)]
        # Após essa linha em AMBAS as etapas (df_vinculos e df_inativacao):
        df_vinculos['data_movimentacao'] = pd.to_datetime(df_vinculos['data_movimentacao']).dt.to_period('M').dt.to_timestamp()
        # Adicione imediatamente abaixo:
        nulos_data = df_vinculos['data_movimentacao'].isna().sum()
        if nulos_data > 0:
            print(f"⚠️ {nulos_data} registros com data_movimentacao nula — serão removidos")
            df_vinculos = df_vinculos.dropna(subset=['data_movimentacao'])
        # Faça o mesmo para df_inativacao
        df_vinculos['movimentacao'] = 'Entrada'
        df_vinculos['motivo_inativacao'] = None
        df_vinculos['outro_motivo'] = None

        print("⚠️ Nenhum registro de solicitação de vínculo encontrado.")

except Exception as e:
    print(f"❌ Erro ao importar dados de solicitação de vínculo: {str(e)}")

#  NOVA ETAPA 2: Importar dados de solicitação de inativação (tab_inativacao_sq)
print("\n🔍 ETAPA 2: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq_backup)")
colunas_vinculos_sq = 'codigo_lr,nome_consultor,data_solicitacao,motivo_inativacao,outro_motivo'
try:
    # Importar todos os registros, sem filtro de data, para garantir que todas as datas de solicitação sejam capturadas
    df_inativacao_supabase = (
        supabase
        .table(TAB_INATIVACAO_PRODUTORES)
        .select(colunas_vinculos_sq)
        .in_('projeto', projetos)
        .execute()
    )
    
    if df_inativacao_supabase.data:
        df_inativacao = pd.DataFrame(df_inativacao_supabase.data)
        df_inativacao.rename(columns={'consultor_grupo_atendimento': 'nome_consultor', 'data_solicitacao':'data_movimentacao'}, inplace=True)
        df_inativacao = df_inativacao.loc[~df_inativacao['nome_consultor'].isin(grupo_cft)]
        df_inativacao['data_movimentacao'] = pd.to_datetime(df_inativacao['data_movimentacao']).dt.to_period('M').dt.to_timestamp()
        nulos = df_inativacao['data_movimentacao'].isna().sum()
        if nulos > 0:
            print(f"⚠️ {nulos} registros removidos por data_movimentacao nula (df_inativacao)")
            df_inativacao = df_inativacao.dropna(subset=['data_movimentacao'])
        df_inativacao['movimentacao'] = 'Saída'

        print("⚠️ Nenhum registro de solicitação de vínculo encontrado.")
        
except Exception as e:
    print(f"❌ Erro ao importar dados de solicitação de vínculo: {str(e)}")


#  NOVA ETAPA 3: CRIAR ID_COMPOSTO
print("\n🔍 ETAPA 3: CRIAR ID_COMPOSTO")
df_movimentacao = pd.concat([df_vinculos, df_inativacao])

# Usamos .dt.strftime('%Y-%m-%d') para a data para um formato consistente.
df_movimentacao['id_composto'] = (
    df_movimentacao['codigo_lr'].astype(str) + '_' +
    df_movimentacao['nome_consultor'].astype(str) + '_' +
    df_movimentacao['data_movimentacao'].dt.strftime('%Y-%m-%d').astype(str) + '_' +
    df_movimentacao['movimentacao'].astype(str)
)
print(f"✅ Coluna 'id_composto' criada. Exemplo: {df_movimentacao['id_composto'].iloc[0]}")
print("\nDataFrame df_movimentacao (head com id_composto):")
print(df_movimentacao.head())


#  ETAPA 4: Obter id_composto existentes do Supabase
print("\n🔍 ETAPA 4: IMPORTANDO ID COMPOSTO EXISTENTES DO SUPABASE")
SUPABASE_TABLE_MOVIMENTACAO = TAB_MOVIMENTACAO_FATO

try:
    # Selecionar apenas a coluna id_composto do Supabase
    response_supabase_ids = supabase.table(SUPABASE_TABLE_MOVIMENTACAO).select('id_composto').execute()
    if response_supabase_ids.data:
        df_ids_supabase = pd.DataFrame(response_supabase_ids.data)
        # Converter a coluna para um set para buscas mais rápidas
        existing_ids_supabase = set(df_ids_supabase['id_composto'].tolist())
        print(f"✅ {len(existing_ids_supabase)} IDs compostos existentes importados do Supabase.")
        print("⚠️ Nenhuma ID composta encontrada no Supabase. Todos os registros serão considerados novos.")
        existing_ids_supabase = set()
except Exception as e:
    print(f"❌ Erro ao importar IDs compostos do Supabase: {str(e)}")
    existing_ids_supabase = set() # Em caso de erro, assume que não há IDs existentes

#  ETAPA 5: Filtrar o DataFrame local para manter apenas as linhas novas
print("\n⚙️ ETAPA 5: FILTRANDO NOVOS REGISTROS")

# Filtrar df_movimentacao para manter apenas os IDs que não estão no Supabase
df_novos_registros = df_movimentacao[~df_movimentacao['id_composto'].isin(existing_ids_supabase)].copy()

# Remover duplicados
if not df_novos_registros.empty:
    num_duplicatas = df_novos_registros.duplicated(subset=['id_composto']).sum()
    if num_duplicatas > 0:
        print(f"⚠️ {num_duplicatas} duplicatas de 'id_composto' encontradas no DataFrame de novos registros. Removendo...")
        df_novos_registros.drop_duplicates(subset=['id_composto'], keep='first', inplace=True)
        print(f"✅ Duplicatas removidas. Restam {len(df_novos_registros)} registros únicos.")
        print("✅ Nenhuma duplicata de 'id_composto' encontrada no DataFrame de novos registros.")

if not df_novos_registros.empty:
    print(f"✅ {len(df_novos_registros)} novos registros identificados para inserção.")
    print("\nDataFrame df_novos_registros (head):")
    print(df_novos_registros.head())
    print("⚠️ Nenhum novo registro encontrado. O Supabase já está atualizado.")

#  ETAPA 6: Realizar o upsert/insert no Supabase
print("\n⬆️ ETAPA 6: REALIZANDO UPSERT DE NOVOS REGISTROS NO SUPABASE")

if not df_novos_registros.empty:
    # Preparar os dados para upsert
    # Garantir que colunas de data/hora sejam strings ISO 8601 e NaN/NaT sejam None
    # (Adapte este bloco de tratamento de datas/NaN conforme as colunas do seu df_movimentacao)

    # Exemplo de tratamento para 'data_movimentacao' e outras colunas que podem ter NaN
    df_novos_registros['data_movimentacao'] = df_novos_registros['data_movimentacao'].dt.strftime('%Y-%m-%d').replace({pd.NaT: None})

    # Tratar outras colunas que podem ter NaN (como 'motivo_inativacao', 'outro_motivo')
    for col in ['motivo_inativacao', 'outro_motivo']:
        if col in df_novos_registros.columns:
            df_novos_registros.loc[df_novos_registros[col].isna(), col] = None

    # Selecionar apenas as colunas que existem na tabela do Supabase
    cols_movimentacao_validas = ['id_composto', 'codigo_lr', 'nome_consultor', 'data_movimentacao', 'movimentacao', 'motivo_inativacao', 'outro_motivo', 'data_processamento']
    cols_presentes = [c for c in cols_movimentacao_validas if c in df_novos_registros.columns]
    df_para_upsert = df_novos_registros[cols_presentes].copy()

    # Converter todos os NaN/NaT float para None (evita JSON serialization error)
    import numpy as np
    for col in df_para_upsert.columns:
        if df_para_upsert[col].dtype == object:
            df_para_upsert[col] = df_para_upsert[col].where(df_para_upsert[col].notna(), None)
        elif df_para_upsert[col].dtype in [float, 'float64']:
            df_para_upsert[col] = df_para_upsert[col].apply(lambda x: None if (pd.isna(x) or (isinstance(x, float) and (x != x))) else x)

    records_to_upsert = df_para_upsert.to_dict(orient='records')

    chunk_size = 1000
    for i in range(0, len(records_to_upsert), chunk_size):
        chunk = records_to_upsert[i:i + chunk_size]
        try:
            # Para novos registros, um 'insert' simples pode ser suficiente se a chave composta
            # for garantidamente única e você não quiser atualizar registros existentes.
            # Se você quiser que ele atualize se encontrar a chave composta, use 'upsert'.
            # A chave 'on_conflict' deve ser a coluna 'id_composto' no Supabase.
            
            # Descomente para gravação oficial:
            response = supabase.table(SUPABASE_TABLE_MOVIMENTACAO).upsert(chunk, on_conflict="id_composto").execute()
            if response and hasattr(response, 'data') and response.data:
                print(f"     - Upsert de {len(response.data)} registros em chunk {i//chunk_size + 1}.")
                print(f"     - Chunk {i//chunk_size + 1} enviado com sucesso.")

        except Exception as e:
            print(f"❌ Erro ao realizar upsert no Supabase (chunk {i//chunk_size + 1}): {str(e)}")
    print("✅ Nenhuma inserção necessária.")

print("\nProcesso de atualização de movimentação concluído.")

🔍 ETAPA 1: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq_backup)

⚠️ 26 registros com data_movimentacao nula — serão removidos
⚠️ Nenhum registro de solicitação de vínculo encontrado.

🔍 ETAPA 2: IMPORTANDO DATAS DE SOLICITAÇÃO DE VÍNCULO (tab_vinculos_sq_backup)

⚠️ Nenhum registro de solicitação de vínculo encontrado.

🔍 ETAPA 3: CRIAR ID_COMPOSTO
✅ Coluna 'id_composto' criada. Exemplo: LR09606_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-08-01_Entrada

DataFrame df_movimentacao (head com id_composto):
  codigo_lr codigo_agroindustria                     nome_produtor  \
0   LR09606              1012313          ANTERO FERREIRA DA CUNHA
1   LR09652              1012857                   JOAO MARRA NETO
2   LR09660              1012353  JULIANO AURELIO PEREIRA SOBRINHO
3   LR09673              1011060    MARISA DINIZ GONCALVES MACHADO
4   LR09674              1012046         MARTA CASSIANA DOS SANTOS

                                 nome_propriedade unidade_atendimento  \
0              FAZENDA SANTO ANTONIO-QUEBRA ANZOL         LABOR RURAL
1              FAZENDA SANTO ANTONIO LUGAR ESTIVA         LABOR RURAL
2  FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE         LABOR RURAL
3               FAZENDA CAMPO LIMPO E PIRAPETINGA         LABOR RURAL
4                                  FAZENDA ANGICO         LABOR RURAL

  tipo_ponto_atendimento cidade_produtor estado_produtor vinculo_ativo  \
0                  LEITE      Patrocínio              MG          True
1                  LEITE      Patrocínio              MG          True
2                  LEITE      Patrocínio              MG          True
3                  LEITE      Patrocínio              MG          True
4                  LEITE      Patrocínio              MG          True

  data_movimentacao                                 grupo_atendimento  \
0        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
1        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
2        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
3        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
4        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)

                     nome_consultor        projeto   data_processamento  \
0  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
1  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
2  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
3  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
4  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10

        id                                        id_composto codigo_fazenda  \
0  56336.0  LR09606_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
1  56337.0  LR09652_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
2  56338.0  LR09660_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
3  56339.0  LR09673_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
4  56340.0  LR09674_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None

  movimentacao motivo_inativacao outro_motivo
0      Entrada              None         None
1      Entrada              None         None
2      Entrada              None         None
3      Entrada              None         None
4      Entrada              None         None

🔍 ETAPA 4: IMPORTANDO ID COMPOSTO EXISTENTES DO SUPABASE

✅ 10419 IDs compostos existentes importados do Supabase.
⚠️ Nenhuma ID composta encontrada no Supabase. Todos os registros serão considerados novos.

⚙️ ETAPA 5: FILTRANDO NOVOS REGISTROS
⚠️ 54 duplicatas de 'id_composto' encontradas no DataFrame de novos registros. Removendo...
✅ Duplicatas removidas. Restam 2065 registros únicos.
✅ Nenhuma duplicata de 'id_composto' encontrada no DataFrame de novos registros.
✅ 2065 novos registros identificados para inserção.

DataFrame df_novos_registros (head):
  codigo_lr codigo_agroindustria                     nome_produtor  \
0   LR09606              1012313          ANTERO FERREIRA DA CUNHA
1   LR09652              1012857                   JOAO MARRA NETO
2   LR09660              1012353  JULIANO AURELIO PEREIRA SOBRINHO
3   LR09673              1011060    MARISA DINIZ GONCALVES MACHADO
4   LR09674              1012046         MARTA CASSIANA DOS SANTOS

                                 nome_propriedade unidade_atendimento  \
0              FAZENDA SANTO ANTONIO-QUEBRA ANZOL         LABOR RURAL
1              FAZENDA SANTO ANTONIO LUGAR ESTIVA         LABOR RURAL
2  FAZENDA SANTO ANTONIO - LUGAR ESPIGAO DA PONTE         LABOR RURAL
3               FAZENDA CAMPO LIMPO E PIRAPETINGA         LABOR RURAL
4                                  FAZENDA ANGICO         LABOR RURAL

  tipo_ponto_atendimento cidade_produtor estado_produtor vinculo_ativo  \
0                  LEITE      Patrocínio              MG          True
1                  LEITE      Patrocínio              MG          True
2                  LEITE      Patrocínio              MG          True
3                  LEITE      Patrocínio              MG          True
4                  LEITE      Patrocínio              MG          True

  data_movimentacao                                 grupo_atendimento  \
0        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
1        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
2        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
3        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)
4        2025-08-01  ANDRE VICTOR DE OLIVEIRA QUEIROZ (ALVOAR ASSIST)

                     nome_consultor        projeto   data_processamento  \
0  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
1  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
2  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
3  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10
4  ANDRE VICTOR DE OLIVEIRA QUEIROZ  ALVOAR ASSIST  2026-05-06T11:29:10

        id                                        id_composto codigo_fazenda  \
0  56336.0  LR09606_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
1  56337.0  LR09652_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
2  56338.0  LR09660_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
3  56339.0  LR09673_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None
4  56340.0  LR09674_ANDRE VICTOR DE OLIVEIRA QUEIROZ_2025-...           None

  movimentacao motivo_inativacao outro_motivo
0      Entrada              None         None
1      Entrada              None         None
2      Entrada              None         None
3      Entrada              None         None
4      Entrada              None         None
⚠️ Nenhum novo registro encontrado. O Supabase já está atualizado.

⬆️ ETAPA 6: REALIZANDO UPSERT DE NOVOS REGISTROS NO SUPABASE

     - Upsert de 1000 registros em chunk 1.
     - Chunk 1 enviado com sucesso.

     - Upsert de 1000 registros em chunk 2.

     - Chunk 2 enviado com sucesso.
     - Upsert de 65 registros em chunk 3.
     - Chunk 3 enviado com sucesso.
✅ Nenhuma inserção necessária.

Processo de atualização de movimentação concluído.

In [16]:
# ùltinmo